### ISSUE TITLE
polymer build does not create service-worker.js when generating polymer-2-starter-kit-2.0

### ISSUE THREAD

**Issue by rogozinds** [PolymerElements/polymer-starter-kit#1005]
### Description
polymer build does not create service-worker.js when generating polymer-2-starter-kit

### Expected outcome

When running `polymer build` create a service-worker.js and working in offline mode.

### Actual outcome
No service-worker.js, when starting application exception in console.
`A bad HTTP response code (404) was received when fetching the script.`

### Steps to reproduce

1. install polymer-cli and bower
2. polymer init (choose polymer-2-starter-kit-2.0)
3. go to generated folder run `polymer build`
3. run `polymer serve build/default`
4. Try app in offline mode it doesn't work and there is an exception in browser console.

### Browsers Affected
- [x] Chrome
- [x] Firefox

**Comment by abdonrd** [comment]
Did you use the `--add-service-worker` flag?

**Comment by legowerewolf** [comment]
This is a workaround, but is there a more permanent option? Perhaps something in the polymer.json file?

**Comment by stramel** [comment]
Probably good to add a preset?

```
"builds": [{ "preset": "es5-bundled" }]
```

**Comment by GaetanoHerman** [comment]
So I got the service-worker.js file but it still doesn't work, do I need to import the `platinum-sw` folder in my project?

**Comment by stramel** [comment]
@GaetanoHerman You should not need to do anything. Are you serving the built directory?

**Comment by GaetanoHerman** [comment]
@stramel Yes, I'm serving the build folder. The service worker panel in DevTools doesn't show any service workers thought and doesn't show any errors.

**Comment by MUCHZER** [comment]
May have something to do with https://github.com/Polymer/polymer-cli/commit/6077dbe82eb337f91104dc80b6e41280b7e20ca7 ?

**Comment by abdonrd** [comment]
Explained in https://github.com/PolymerElements/polymer-starter-kit/issues/1005#issuecomment-294774060. Let me know if the problem persists!

**Comment by zhen1991** [comment]
Hi guys!
I am facing this problem right now in polymer 2 in all of my project when i run them so the page load undefined and it says polymer build does not create service-worker.js when generating polymer-2-starter-kit-2.0 ??
my projects all of them in polymer used to work before but now i dont know what happens suddenly i get this error!
will be glad if someone kan help me with that !!
thnx guys :)
