### ISSUE TITLE
icon doesnt render

### ISSUE THREAD

**Issue by toobstar** [PolymerElements/polymer-starter-kit#1013]
### Description

Do a fresh install of starter kit.
Start app.

### Expected outcome

The page loads and given the code I expect to see a paper-icon-button next to the "My App" title:
```
<paper-icon-button icon="my-icons:menu" drawer-toggle></paper-icon-button>
<div main-title>My App</div>
```

### Actual outcome

There is no icon visible and I  presume there should be.  If I try and replace this line with a standard icon it also doesn't work:

```
<paper-icon-button icon="star"></paper-icon-button>
```
### Steps to reproduce

npm install -g polymer-cli@next
mkdir my-app
cd my-app
polymer init
select polymer 2 starter kit
polymer serve --open

### Browsers Affected
- [X] Firefox
- [X] Safari 10.1

**Comment by rom1504** [comment]
I'm also getting this issue. Do you know how to fix it ?

**Comment by toobstar** [comment]
Either it was my error or it's fixed in version 2.  Couple of things to note:

- drawer-toggle class means icon only visible on narrow screen width
- if you want to show the star paper icon you need to install the iron-icons lib  e.g. (iron-icons/iron-icons.html)
