### ISSUE TITLE
Update Project description 

### ISSUE THREAD

**Issue by atishpatel** [PolymerElements/polymer-starter-kit#1033]
The project description is still "A starting point for Polymer 1.0 apps https://www.polymer-project.org/1.0/s". 
Just thought I'd bring it to your attention since PSK should work with polymer 2 hybrid mode, and it is easy to miss when upgrading to polymer 2.

**Comment by abdonrd** [comment]
Right! Thanks @atishpatel!

@robdodson probably has the power to do that.

**Comment by robdodson** [comment]
I think maybe @arthurevans would be able to do this?

**Comment by arthurevans** [comment]
OK, did this (although I probably jumped the gun in pointing to the 2.0 docs, because  I think ATM master only works with 1.x, and you need the 2.0-preview branch for 2.0?)

**Comment by abdonrd** [comment]
Yes, right now the PSK has two active versions:

Polymer v1 - `#master`
Polymer v2 - `#2.0-preview`

I has created an issue to bring it all together: https://github.com/PolymerElements/polymer-starter-kit/issues/1035

**Comment by abdonrd** [comment]
Done!
