### ISSUE TITLE
Update the build section in the README

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/polymer-starter-kit#1034]
After added the support for differential serving, we need to update the build section in the README.

https://github.com/PolymerElements/polymer-starter-kit#build

We also need to update the Polymer Docs sections:

https://www.polymer-project.org/2.0/start/toolbox/deploy
https://github.com/Polymer/docs/blob/master/app/2.0/start/toolbox/deploy.md

Also, we should take care of https://github.com/PolymerElements/polymer-starter-kit/issues/1036.

<hr>

* `PolymerElements/polymer-starter-kit` pull request: https://github.com/PolymerElements/polymer-starter-kit/pull/1044
* `Polymer/docs` pull request: https://github.com/Polymer/docs/pull/2240

**Comment by abdonrd** [comment]
@graynorton @arthurevans we should talk about the differential serving in the build section? Or only about the new builds?

Previously was there the `bundled` and `unbundled`, and now `es5-bundled`, `es6-bundled` & `es6-unbundled`.

**Comment by lp177** [comment]
HI, I don't know if it's an new update because I start just to use polymer-cli but in my case I have nor bundled, nor unbundled but just default when I do polymer-cli build on the last starter kit v2 project

**Comment by abdonrd** [comment]
@lp177 when the Polymer CLI releases v1.0.0, the build command returns a different default result.

And now in the PSK we customize the build with the `builds` property from the `polymer.json`.

**Comment by lp177** [comment]
Thanks I see that now right here ! When I do a polymer init polymer-2-starter-kit I'm not up to date on this sources and I don't have this property, but ok I understand now.

That seem ambiguous in the documentation because I'm up to date on polymer cli 1.2.0 and the documentation describe a normal procedure with this field already set as bundled unbundled and don't say to set him.

**Comment by abdonrd** [comment]
@lp177 exactly! 😞

I propose https://github.com/PolymerElements/polymer-starter-kit/issues/1035 to solve it.

**Comment by abdonrd** [comment]
Friendly ping to @arthurevans & @graynorton: https://github.com/PolymerElements/polymer-starter-kit/issues/1034#issuecomment-307722363

**Comment by abdonrd** [comment]
Or maybe @katejeffreys can help us with the docs?

**Comment by katejeffreys** [comment]
Yes! On it :)

**Comment by katejeffreys** [comment]
https://github.com/PolymerElements/polymer-starter-kit/pull/1044

**Comment by katejeffreys** [comment]
https://github.com/Polymer/docs/pull/2240

**Comment by abdonrd** [comment]
Thanks @katejeffreys! 👏

We should mention the differential serving in the docs?

**Comment by abdonrd** [comment]
Closed by #1044.
