### ISSUE TITLE
basePath: true is needed for using prpl-server

### ISSUE THREAD

**Issue by kenchris** [PolymerElements/polymer-starter-kit#1036]
It was not obviously that that was the case and it was hidden within the documentation for prpl-server, even Alex had issues finding that out (https://github.com/Polymer/prpl-server-node/issues/24) and I also spend considerable time.

I know we cannot add comments to JSON files, but it would be nice if we could make this more clear - if it cannot be added by default.

**Comment by katejeffreys** [comment]
@arthurevans @aomarks I am not sure about this one. Is the basePath option referenced here a new thing in polymer.json?

**Comment by aomarks** [comment]
@katejeffreys Yeah, it was added specifically for the differential serving behavior that prpl-server supports: https://github.com/Polymer/polymer-project-config/blob/master/src/builds.ts#L140

**Comment by katejeffreys** [comment]
Thanks all. l will handle this by documenting `basePath` in https://www.polymer-project.org/2.0/docs/tools/polymer-json. An issue to track it in the Docs repo is here: https://github.com/Polymer/docs/issues/2255

**Comment by abdonrd** [comment]
@katejeffreys Work done, right? We close the issue?

**Comment by katejeffreys** [comment]
Yes, this can be closed. Thanks @abdonrd
