### ISSUE TITLE
Request for more flexible JS concat/minification

### ISSUE THREAD

**Issue by ValueBC** [PolymerElements/polymer-starter-kit#104]
Just tested the new 1.0.1 by adding a simple JS file to the "scripts" folder. Then run GULP. The JS file does not show up in the "dist" folder. What is the process for Javascript concatenation and minification?

**Comment by addyosmani** [comment]
Thanks for the bug report. We've been testing JS concatenation/handling as part of imports (which get handled by the Vulcanization pipeline) so it's entirely possible this slipped through the cracks. 

Are you looking for minification any more complex than what we do in https://github.com/google/web-starter-kit/blob/master/gulpfile.js#L112? If not, it shouldn't be too difficult for us to bring that in.

**Comment by ValueBC** [comment]
Thanks for the quick reply. I am interested in simple js concat/minification, similar to the github link you provided. I noticed that the firebase.js is accessed via firebase.html. I assume this is so that Vulcanize will process it? Would this be a better pattern for custom js files? ie reference them in an html file?

**Comment by addyosmani** [comment]
@ValueBC Btw, we do support a form of concat/minification out of the box already. Any script you reference in https://github.com/PolymerElements/polymer-starter-kit/blob/master/app/index.html#L164 will automatically be minified and concatenated. So, let's say you have a foo.js file you want to include in your index/final JS file. You can do:

```js
  <!-- build:js scripts/app.js -->
  <script src="scripts/app.js"></script>
 <script src="scripts/foo.js"></script>
  <!-- endbuild-->
```

**Comment by robdodson** [comment]
I'm going to close this if that's ok.

The two ways to include your js for minification are...

1.

Add a script tag to the build block at the bottom of the page.

```js
<!-- build:js scripts/app.js -->
<script src="scripts/my-awesome-library.js"></script>
<script src="scripts/some-other-library.js"></script>
<script src="scripts/app.js"></script>
<!-- endbuild-->
```

OR

2.

Create an HTML import that contains your script and add the import to `elements.html` or (if it's used by a specific element) import it in that element's `.html` file.
