### ISSUE TITLE
Date Picker

### ISSUE THREAD

**Issue by lobosan** [PolymerElements/polymer-starter-kit#1043]
Hi, I just started following the polymer documentation and I want to build and app based on the starter kit app. However I cannot find a material design date picker compatible with polymer 2. Can you please suggest one that works? Ideally it should be part of PolymerElements.

**Comment by moderndeveloperllc** [comment]
@lobosan The best place to look for components is https://www.webcomponents.org/. The best place to ask questions like this is really [StackOverflow](https://stackoverflow.com/questions/tagged/polymer). To answer the question, I really like [Vaadin's implementation](https://www.webcomponents.org/element/vaadin/vaadin-date-picker).

**Comment by lobosan** [comment]
I see thanks @moderndeveloperllc.

I had a look at vaadin's date picker but it looks really different to the other PolymerElements. 

Is there any roadmap to implement all of the material design components as PolymerElements?

**Comment by arjunyel** [comment]
They said they are relying on the community for a date-picker https://youtu.be/945pO9Yn1ns?t=2m41s

**Comment by lobosan** [comment]
After trying for a couple of days to get something done with polymer, I've decided to go with [VuetifyJS](https://vuetifyjs.com) since it has a more cohesive implementation of Material Design

**Comment by arjunyel** [comment]
There are multiple Polymer/Web Component based material design date pickers available: https://www.webcomponents.org/search/date%20picker

Either way please close this issue, thanks!
