### ISSUE TITLE
Clicking links in es5-bundled on Internet Explorer 11 causes entire application to refresh

### ISSUE THREAD

**Issue by shawnd** [PolymerElements/polymer-starter-kit#1051]
### Description

PSK reloads with every route change when using Internet Explorer 11.

### Expected outcome

Click link in PSK, using Internet Explorer 11, and route changes without reloading app.

### Actual outcome

Click link in PSK, using Internet Explorer 11, and app reloads prior to route change.

### Live Demo

http://psk.shdh.ca

### Steps to reproduce

1. `polymer init`
2. Select Polymer Starter Kit
3. `polymer build`
4. Deploy `build/es5-bundled`
5. Access using Internet Explorer 11
6. Click link and witness app reload prior to route change

### Browsers Affected
- [ ] Chrome
- [ ] Edge
- [ ] Firefox
- [x] IE 11
- [ ] Safari 8
- [ ] Safari 9

**Comment by abdonrd** [comment]
Could you try the latest version? I can't reproduce.

Demo: https://psk-demo-6e320.firebaseapp.com

**Comment by web-padawan** [comment]
Does this mean the global onclick handler in `iron-location` might be broken in IE?

**Comment by shawnd** [comment]
@abdonrd It also works for me when served locally by `polymer serve` but not when deployed. Also, the error exists in your Firebase deployment for me as well.

**Comment by motss** [comment]
The issue is hard to reproduce sometimes. I face this on and off. This actually happens on every browser I have tested. The only way to resolve is to remove your entire project and rerun `polymer init` and build it again then if `polymer serve` works it works. Something odd happening under the hood.

**Comment by shawnd** [comment]
I've only experienced the problem with Internet Explorer 11, no other browser I've tested has this issue. I've been able to consistently reproduce this error with fresh installs of polymer-cli.

>The only way to resolve is to remove your entire project and rerun polymer init and build it again then if polymer serve works it works.

Really not sure what you mean by _"if polymer serve works it works"_ 

Furthermore, me and @abdonrd were able to reproduce the error with the es5-bundle output from `polymer build` but we could not reproduce the error with `polymer serve`

**Comment by shawnd** [comment]
I can confirm that version 2.x of PSK doesn't have the error, however version 3.x of PSK does.

**Comment by shawnd** [comment]
I've mitigated this issue by running `bower install -S webcomponents/URL#^0.5.7` and adding `<script src="../bower_components/url/url.js"></script>` prior to the app-location import.
