### ISSUE TITLE
Not working in IE on a remote IIS 

### ISSUE THREAD

**Issue by ignlopezperez** [PolymerElements/polymer-starter-kit#1053]
### Description
I have a Blank page in Internet Explorer when I deploy ES5 transpiled code polymer starter kit in IIS. I am using Polymer 2, and the latest version of Polymer Starter Kit (v3.1.0): https://github.com/polymerelements/polymer-starter-kit/releases

It works with Chrome.

I have transpiled my polymer code with different presets with polymer build (like es5-bundled, with the js compiled) , but I can´t get the page rendered.

It works when I deploy on my local full IIS, but not when I deploy on a remote server (but it works when I request the page with Chrome).

I don't know what else I can try. Thanks!

### Expected outcome
Working in IE

### Actual outcome

Blank Page in IE

### Browsers Affected

- [ ] Chrome
- [ ] Edge
- [ ] Firefox
- [ X ] IE 11
- [ ] Safari 8
- [ ] Safari 9

**Comment by TimvdLippe** [comment]
Closing this in favor of https://github.com/Polymer/polymer/issues/4787 Please report any IE issues over there, such that we can consolidate feedback.
