### ISSUE TITLE
on-tap in <a> tag doesnt work

### ISSUE THREAD

**Issue by johnlim** [PolymerElements/polymer-starter-kit#1056]
### Description
on-tap in <a> tag inside PSK doesn't work.

### Expected outcome
on-tap to be triggered

### Actual outcome
on-tap isnt triggered

### Live Demo
https://github.com/johnlim/polymer-starter-kit/tree/onTapFails

### Steps to reproduce
Clicking the <a> tag `View 4` in the drawer menu doesn't trigger on-tap.

### Browsers Affected

- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] IE 11
- [ ] Safari 8
- [ ] Safari 9

**Comment by jsilvermist** [comment]
You should change `on-tap` to `on-click` unless you have a specific reason to use `on-tap`.

If you do decide to use `on-tap` you will also need to import the mixin:
```html
<link rel="import" href="../bower_components/polymer/lib/mixins/gesture-event-listeners.html">
```
and also apply/extend from the mixin in your `MyApp` class declaration, eg.
```js
    class MyApp extends Polymer.Element {
```
to:
```js
    class MyApp extends Polymer.GestureEventListeners(Polymer.Element) {
```

For more info, see https://www.polymer-project.org/2.0/docs/devguide/gesture-events

**Comment by johnlim** [comment]
Hi Jason,

Thanks. I wasn't aware of the differences between 1.0 ( https://www.polymer-project.org/1.0/docs/devguide/gesture-events) and 2.0 (https://www.polymer-project.org/2.0/docs/devguide/gesture-events). But having said that, doesn't the recommendation to use polymer's gesture events still hold true to ensure interoperability with both touch and mouse devices?  Therefore, should we by default, use on-tap?

Thanks,
John

**Comment by abdonrd** [comment]
You can use `on-click`. Some references about this:

- https://github.com/Polymer/docs/pull/2227
- https://github.com/PolymerElements/app-layout/issues/465#issuecomment-298401945

**Comment by johnlim** [comment]
Hi @abdonrd , awesome! Thanks for the info. So if I understand correctly, we should now go with on-click by default? Under what circumstances do we use on-tap then?

**Comment by abdonrd** [comment]
@johnlim I'm not sure. 😕 

Friendly ping to @keanulee @arthurevans!

**Comment by moderndeveloperllc** [comment]
> Under what circumstances do we use on-tap then?

I had always seen to use on-tap for items that won't give you a pointer when hovered (i.e. `<a>` links) So if you want them to tap just a plain `<div>` and not have an `<a>` link around it. Perhaps that is old 0.x or 1.x logic I'm seeing though.

**Comment by keanulee** [comment]
Should definitely use `click` going forward https://github.com/PolymerElements/app-layout/issues/465#issuecomment-298401945
