### ISSUE TITLE
Caching with platinum-sw-register

### ISSUE THREAD

**Issue by Alienuser** [PolymerElements/polymer-starter-kit#106]
In the **"polymer-starter-kit-dependencies-checked-in-1.0.1.zip"** should be an working cache example with **"platinum-sw-register"**. But this is not working for me.

If I'm changing this:
```
<platinum-sw-register auto-register
                          clients-claim
                          skip-waiting
                          on-service-worker-installed="displayInstalledToast">
        <platinum-sw-cache default-cache-strategy="networkFirst"
                           precache-file="precache.json">
        </platinum-sw-cache>
    </platinum-sw-register>
```
to this: *(adding on-service-worker-error)*
```
<platinum-sw-register auto-register
                          clients-claim
                          skip-waiting
                          on-service-worker-error="displayInstalledToastError"
                          on-service-worker-installed="displayInstalledToast">
        <platinum-sw-cache default-cache-strategy="networkFirst"
                           precache-file="precache.json">
        </platinum-sw-cache>
    </platinum-sw-register>
```
and in the app.js something like:
```
app.displayInstalledToastError= function() {
    console.log("Error!");
  };
```

this error function is triggert.

**Comment by robdodson** [comment]
@Alienuser can you tell us the browser and OS you're using?

**Comment by Alienuser** [comment]
Hello @robdodson 
It's chrome in version 43.0.2357.124 and my os is windows 8.
The os from the server ist linux ubuntu.

It seems that I can work with the service on xampp but not on an 'real' apache installed on linux.

**Comment by jeffposnick** [comment]
The `on-service-worker-error` handler is passed an error string as its first parameter. Could you log that and see what information is provided about the error?

(If I had to guess, I'd say that if you're doing local development over HTTP and not HTTPS, you're running into issues due to accessing your page via something other than `http://localhost` or `http://127.0.0.1`. Those are the only HTTP URLs that are whitelisted to use service workers.)

**Comment by samccone** [comment]
Closing this due to it going stale, we can reopen if we get a response cc @Alienuser

**Comment by dman777** [comment]
> (If I had to guess, I'd say that if you're doing local development over HTTP and not HTTPS, you're running into issues due to accessing your page via something other than http://localhost or http://127.0.0.1. Those are the only HTTP URLs that are whitelisted to use service workers.)

I hit this issue also. This was very frustrating. You really need to place in the docs https://elements.polymer-project.org/elements/platinum-sw that this will only work on https.

**Comment by robdodson** [comment]
@dman777 would you mind submitting a pull request for this?

**Comment by dman777** [comment]
@robdodson Sure, I would be more than happy to.

**Comment by robdodson** [comment]
@dman777 awesome thank you 😸

**Comment by dman777** [comment]
@robdodson No problem :smile:  [PR #012 has been submitted](https://github.com/PolymerElements/platinum-sw/pull/102)
