### ISSUE TITLE
Lazy-import not actually used?

### ISSUE THREAD

**Issue by pkaske** [PolymerElements/polymer-starter-kit#1064]
Here in [my-app](https://github.com/PolymerElements/polymer-starter-kit/blob/dc9cfa72866e69be736982c7ba502cabcc3d259a/src/my-app.html#L25) are link elements with `rel="lazy-import"` defined. I first thought that the start kit actually uses them for lazy loading the views. But turns out that those links are not used at all. Instead `importHref` is used [here](https://github.com/PolymerElements/polymer-starter-kit/blob/master/src/my-app.html#L157).

Maybe I'm just missing the use of those link elements, or they are in fact useless here?

**Comment by abdonrd** [comment]
There are a work in progress pull request about that: https://github.com/PolymerElements/polymer-starter-kit/pull/998.

**Comment by pkaske** [comment]
Ah, thanks. I only searched the issues not the pr section for that. So I missed this.

**Comment by stramel** [comment]
Currently, the `rel=lazy-import`s that you see are just there to make the linter aware that the elements exist. My PR actually uses those imports.
