### ISSUE TITLE
Polymer support with VS2017 and ASP.NET CORE 2.0

### ISSUE THREAD

**Issue by touseefbsb** [PolymerElements/polymer-starter-kit#1070]
Suggestion : 
Please add support for creating Polymer based web applications with ASP.NET CORE 2.x and add templates for Visual Studio 2017 as well.
Angular and React and some other popular frameworks like aurelia, vue have also made SPA templates with asp.net core.

I really love polymer and whole web component concept which allows us to develop top quality pwa apps without complicated frameworks like angular, react e.t.c, that is why developers like me who love polymer and also are asp.net core developers would have a better developer experience if we can have polymer integration with visual studio 2017 and specially with asp.net core 2.x

**Comment by TimvdLippe** [comment]
Closing this in favor of https://github.com/Polymer/polymer/issues/4868 so that we can track this in 1 place.
