### ISSUE TITLE
Image subfolders not loaded in offline mode

### ISSUE THREAD

**Issue by AliMd** [PolymerElements/polymer-starter-kit#1073]
### Description

When i make folder in image or use manifest/* in my project, images not load in offline mode
Because in `sw-precache-config.js` just images/* cached!
### Browsers Affected

- [ ] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] IE 11
- [ ] Safari 8
- [ ] Safari 9

**Comment by keanulee** [comment]
It's really up to your use case to determine which images to precache - you have to balance having important images available offline with not hogging users' storage with images that are never used. Pre-caching the entire images directory seems excessive, so I'm actually going to remove that line from `sw-precache-config.js` and leave it up to the developer to add images here.

**Comment by AliMd** [comment]
Many people don't know this and usually have issue on this, i'm have many confusing to finding issue!
Could you please change default to all subdirectory.
Developers can optimize and change it for himself
