### ISSUE TITLE
Yarn support

### ISSUE THREAD

**Issue by ma499** [PolymerElements/polymer-starter-kit#1076]
Are there any plans to migrate the starter kit to use yarn instead of bower?

**Comment by moderndeveloperllc** [comment]
I imagine they will transition when Polymer 3 comes out as the idea is to move away from bower and to npm -> https://www.polymer-project.org/blog/2017-08-22-npm-modules.html

**Comment by TimvdLippe** [comment]
@moderndeveloperllc is correct. We are moving away from Bower, as explained in the blog post. For more updates, you can follow https://github.com/Polymer/polymer/issues/326 and https://github.com/Polymer/polymer-modulizer/blob/master/docs/polymer-3-element-status.md for our progress on making elements compatible with the NPM-ecosystem.
