### ISSUE TITLE
NGINX + backend API + Polymer routes all to Polymer

### ISSUE THREAD

**Issue by exp0nge** [PolymerElements/polymer-starter-kit#1077]
### Description

The setup includes polymer on `/` and an API on `/api/`. This is maybe a nginx issue but I think it's related to Polymer.

### Expected outcome

/ routes to Polymer views, /api/ calls the backend API

### Actual outcome

All routes are captured by Polymer regardless of nginx setting. The /api/ route loads properly when cache/hard reload is cleared.

### Browsers Affected

- [x] Chrome
- [x] Edge
- [x] Firefox
- [x] IE 11
- [x] Safari 8
- [x] Safari 9

**Comment by keanulee** [comment]
Do you have a live demo you can share? It could be related to the generated service worker - what happens if you don't include it (remove `navigator.serviceWorker.register`)?

**Comment by exp0nge** [comment]
@keanulee That would do it. I had to unregister it for the nginx routing to properly work.
