### ISSUE TITLE
 reusable components: http://127.0.0.1:8081/components/polymer-starter-kit url not working

### ISSUE THREAD

**Issue by tanmaypatil** [PolymerElements/polymer-starter-kit#1079]
### Description

application url is loading up correctly  http://127.0.0.1:8081
However reusable component url is not working .

### Expected outcome
http://127.0.0.1:8081/components/polymer-starter-kit  should work fine.

### Actual outcome
After installing polymer starter kit , reusable component url is not working .
Below url : http://127.0.0.1:8081/components/polymer-starter-kit  gives 404.
![404](https://user-images.githubusercontent.com/5380383/32404804-21aae480-c17e-11e7-8bcf-f71976e1bdac.png)

### Live Demo
NA

### Steps to reproduce

Just run polymer serve --open

### Browsers Affected
Checked in chrome
- [ ] Chrome

**Comment by abdonrd** [comment]
You should the application URL: http://127.0.0.1:8081

**Comment by tanmaypatil** [comment]
![404_1](https://user-images.githubusercontent.com/5380383/32405199-9b301cc8-c186-11e7-99a1-7b9e9f25ff28.png)

Getting this explicit message on command line with url details .

**Comment by abdonrd** [comment]
In the third line you can read `applications: http://127.0.0.1:8081`.

**Comment by keanulee** [comment]
+1 what @abdonrd said; more details on the difference between the 2 types of projects that `polymer serve` works on https://www.polymer-project.org/2.0/docs/tools/polymer-cli#project-types
