### ISSUE TITLE
elements.html should be sorted alphabetically

### ISSUE THREAD

**Issue by ValueBC** [PolymerElements/polymer-starter-kit#109]
Hi, one of the first things I do is sort my HTML imports alphabetically like so:

```javascript
<link rel="import" href="../bower_components/iron-flex-layout/classes/iron-flex-layout.html">
<link rel="import" href="../bower_components/iron-icons/iron-icons.html">
<link rel="import" href="../bower_components/iron-pages/iron-pages.html">
<link rel="import" href="../bower_components/iron-selector/iron-selector.html">
<link rel="import" href="../bower_components/paper-drawer-panel/paper-drawer-panel.html">
<link rel="import" href="../bower_components/paper-header-panel/paper-header-panel.html">
<link rel="import" href="../bower_components/paper-icon-button/paper-icon-button.html">
<link rel="import" href="../bower_components/paper-item/paper-item.html">
<link rel="import" href="../bower_components/paper-material/paper-material.html">
<link rel="import" href="../bower_components/paper-menu/paper-menu.html">
<link rel="import" href="../bower_components/paper-styles/paper-styles-classes.html">
<link rel="import" href="../bower_components/paper-toast/paper-toast.html">
<link rel="import" href="../bower_components/paper-toolbar/paper-toolbar.html">
<link rel="import" href="../bower_components/platinum-sw/platinum-sw-cache.html">
<link rel="import" href="../bower_components/platinum-sw/platinum-sw-register.html">
```
This make it easy to add new imports without scanning for duplicates. 

Currently, I do this manually. Is there an easy way to do this with Gulp. Yes, I recognize this may be the worlds smallest enhancement request ;)

**Comment by arthurvr** [comment]
I guess I'm alright with ordering them all alphabetically. Will submit a PR if everybody agrees.

Don't know if I would personally care to add them in order, I'd rather just use search to find duplicates, though, in a boilerplate/starter kit I like things to be pixel perfect so I agree.

**Comment by addyosmani** [comment]
I'm fine with them being ordered alphabetically as long as we test the dep order switch doesn't cause unexpected  runtime issues. PR welcome :)

**Comment by SilverPaladin** [comment]
Why would the order of import be important?

**Comment by devAtPolydeals** [comment]
I think ordering is more of a personal preference. I order mine as all Irons first, then paper with input then text area then validation etc, then 3rd party elements, then my own

**Comment by addyosmani** [comment]
That ordering seems pretty reasonable to me. In this case perhaps we should do..

Iron
Paper
Platinum
Any others
User

**Comment by devAtPolydeals** [comment]
:+1:

**Comment by SilverPaladin** [comment]
This is how I arranged my elements file:

<link rel="import" href="../../bower_components/iron-icons/iron-icons.html">
<link rel="import"
href="../../bower_components/iron-flex-layout/classes/iron-flex-layout.html">
<link rel="import"
href="../../bower_components/iron-selector/iron-selector.html">
<link rel="import" href="../../bower_components/iron-pages/iron-pages.html">
<link rel="import"
href="../../bower_components/iron-media-query/iron-media-query.html">
<link rel="import" href="../../bower_components/iron-ajax/iron-ajax.html">
<link rel="import" href="../../bower_components/iron-image/iron-image.html">


<link rel="import"
href="../../bower_components/paper-toolbar/paper-toolbar.html">
<link rel="import"
href="../../bower_components/paper-icon-button/paper-icon-button.html">
<link rel="import" href="../../bower_components/paper-menu/paper-menu.html">
<link rel="import"
href="../../bower_components/paper-material/paper-material.html">
<link rel="import"
href="../../bower_components/paper-styles/paper-styles-classes.html">
<link rel="import"
href="../../bower_components/paper-drawer-panel/paper-drawer-panel.html">
<link rel="import"
href="../../bower_components/paper-header-panel/paper-header-panel.html">
<link rel="import" href="../../bower_components/paper-item/paper-item.html">
<link rel="import"
href="../../bower_components/paper-toast/paper-toast.html">


<link rel="import"
href="../../bower_components/platinum-sw/platinum-sw-register.html">
<link rel="import"
href="../../bower_components/platinum-sw/platinum-sw-cache.html">


<link rel="import" href="app-layout/app-layout.html">
<link rel="import" href="app-products/app-products.html">
<link rel="import" href="app-ingredients/app-ingredients.html">
<link rel="import" href="app-categories/app-categories.html">
<link rel="import" href="element-table.html">

**Comment by arthurvr** [comment]
This looked like okay to me: https://github.com/PolymerElements/polymer-starter-kit/pull/124. Suggestions welcome :)
