### ISSUE TITLE
package-lock.json contain old dependency to polymer lib

### ISSUE THREAD

**Issue by JosefJezek** [PolymerElements/polymer-starter-kit#1121]
```
"wct-browser-legacy": {
      "version": "1.0.0",
      "resolved": "https://registry.npmjs.org/wct-browser-legacy/-/wct-browser-legacy-1.0.0.tgz",
      "integrity": "sha512-eWbVuY0OdLOPZMXAQMEjhbs1xn7WR6IgKfueMWE8CKdTAoXAfquQ+7rQRuXVSBN2l21YG8MP+U36XqLaTvkRHg==",
      "dev": true,
      "requires": {
        "@polymer/polymer": "^3.0.0-pre.1",
```

https://github.com/Polymer/polymer-starter-kit/blob/master/package-lock.json#L13133

Affected issue https://github.com/PolymerElements/paper-input/issues/652

Solution is `rm -rf node_modules/ package-lock.json; npm i`

**Comment by grayox** [comment]
This solution does not work for me. I still get these errors. https://jpst.it/1kyao

**Comment by emersonbottero** [comment]
Delete the node_modules folder manually and it should work.

**Comment by keanulee** [comment]
I updated package/-lock.json since this issue was filed and it should be working now. Please open a new issue if it's not.
