### ISSUE TITLE
npm run build or polymer build error 

### ISSUE THREAD

**Issue by AnkitMaheshwariIn** [PolymerElements/polymer-starter-kit#1126]
**FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory**

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x1ea8214a57c1 <JSObject>
    1: create(this=0x1ea821484739 <JSFunction Object (sfi = 0x1ea801889cf9)>)
    2: _setStartLocation [/usr/local/lib/node_modules/polymer-cli/node_modules/parse5/lib/extensions/location_info/parser_mixin.js:30] [bytecode=0x1ea804a5c7f9 offset=30](this=0x1ea8053f61c9 <JSObject>,element=0x1ea8517886d1 <Object map = 0x1ea892ff8131>)
    3: _attachElementToTree [/usr/local/lib/node_modules/polymer...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::Factory::NewMap(v8::internal::InstanceType, int, v8::internal::ElementsKind) [/usr/local/bin/node]
 5: v8::internal::Map::RawCopy(v8::internal::Handle<v8::internal::Map>, int) [/usr/local/bin/node]
 6: v8::internal::Map::CopyInitialMap(v8::internal::Handle<v8::internal::Map>, int, int, int) [/usr/local/bin/node]
 7: v8::internal::Map::GetObjectCreateMap(v8::internal::Handle<v8::internal::HeapObject>) [/usr/local/bin/node]
 8: v8::internal::Runtime_ObjectCreate(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]

![screen shot 2018-07-25 at 7 21 46 pm](https://user-images.githubusercontent.com/7944017/43205075-28517376-9040-11e8-9b0b-366010b56ace.png)

**Comment by keanulee** [comment]
Couldn't reproduce on my machine (Node 10). Can also take a look at this similar issue: https://github.com/Polymer/pwa-starter-kit/issues/292

**Comment by Anid4u2c** [comment]
Here's a solution that worked for me:  [http://disq.us/p/299niel](http://disq.us/p/299niel)
