### ISSUE TITLE
Listening for template-bound event is obsolete

### ISSUE THREAD

**Issue by jagare** [PolymerElements/polymer-starter-kit#113]
In app.js an event listener is added for template-bound event. This doesn't make sense for Polymer 1.0 since this event is no longer sent (but it was in v. 0.5). So better remove this confusing code and replace something relevant.

**Comment by addyosmani** [comment]
This is fixed in master https://github.com/PolymerElements/polymer-starter-kit/blob/master/app/scripts/app.js - the event was renamed.

**Comment by jagare** [comment]
Yes, you are right! Sorry I didn't notice.
