### ISSUE TITLE
Feature Request : Add CCA (Chrome App Mobile) packaging gulp tasks

### ISSUE THREAD

**Issue by jmorille** [PolymerElements/polymer-starter-kit#114]
Add the gulp tasks for packaging cca (https://github.com/MobileChromeApps/mobile-chrome-apps).

The buildings step need to be modify to add crisper tasks.

**Comment by addyosmani** [comment]
Thanks for the feature request, @jmorille. After talking it over, we're going to try keeping PSK as trim as possible by default. There's already a lot in our build process at present and we're aiming to solve the most commonly used tasks for the majority of our users as part of our core focus. Atm, we're not going to include crisper and other tasks for CCA at this time. We are happy to link to a setup if someone else ends up putting this together.
