### ISSUE TITLE
Unable to get property 'baseURI' of undefined or null reference in IE11

### ISSUE THREAD

**Issue by peterpde** [PolymerElements/polymer-starter-kit#115]
Error:
Unable to get property 'baseURI' of undefined or null reference

on the line:
var baseURI = document.currentScript.baseURI 
in <platinum-sw-register> element js file.

The only symptom I have seen from this error thus far is that the toast letting me know the application can be used offline does not come up in IE.

The currentScript is the property that is undefined in the above line of code.

Thanks,
Peter

**Comment by addyosmani** [comment]
To confirm: you're seeing this issue when firing up a newly cloned/installed Polymer Starter Kit in IE11 using `gulp serve` without any modifications made to the codebase. Is that correct?

If so, I'll try to verify. I haven't seen any exceptions in my IE testing but that's not to say a recent change hasn't introduced one.

**Comment by peterpde** [comment]
That is correct.  I downloaded the polymer-starter-kit-1.0.1.zip version.  Thanks again.

**Comment by jeffposnick** [comment]
This was fixed in `<platinum-sw-register>` by https://github.com/PolymerElements/platinum-sw/pull/38
