### ISSUE TITLE
Appname overlaps mainContainer

### ISSUE THREAD

**Issue by steinhoff1989** [PolymerElements/polymer-starter-kit#116]
Hi,

the title of my App overlaps the mainContainer as seen in the following picture:
http://abload.de/img/unbenannt22u6v.png

I am not able to click on "item1" at the area, where the appname is overlapping "item1". 

This just happens if the Toolbar is expanded, and only at screen sizes > 660px.

By the way. I saw, that you declared the css declaration of "#mainToolbar .bottom" inside the "app-theme.html" twice.

**Comment by addyosmani** [comment]
Could you verify if this is still an issue with 1.0.1? We'll get the duplicate declaration cleared up. Thanks for the heads up.

**Comment by steinhoff1989** [comment]
Yes. I'm on 1.0.1

**Comment by hazourano** [comment]
![screenshot from 2015-06-08 17 34 31](https://cloud.githubusercontent.com/assets/2435891/8031905/b5a87312-0e04-11e5-9306-2c057f3a424d.png)

got this issue when header resize

**Comment by robdodson** [comment]
@hazourano I think you'll need to remove the bottom padding from `#mainToolbar .bottom` in `app-theme.html` and you'd want to move the element so your `paper-toolbar` looks like this:

```
         <button tabindex="1" id="paperToggle" paper-drawer-toggle>
            <iron-icon icon="menu" paper-drawer-toggle></iron-icon>
          </button>
         <!-- Application name -->
          <div class="middle paper-font-display1 app-name">Polymer Starter Kit</div>
          <span class="flex"></span>

          <!-- Toolbar icons -->
          <paper-icon-button icon="refresh"></paper-icon-button>
          <paper-icon-button icon="search"></paper-icon-button>
```

I also changed the `paper-font-display` class to 1. I *think* that will fix it

**Comment by addyosmani** [comment]
We have some in-flight changes that should fix this. In the mean time, the changes Rob suggests above should help.

**Comment by chuckh** [comment]
I believe version 1.0.2 fixes this issue.

**Comment by addyosmani** [comment]
1.0.2 does indeed fix this issue. If anyone continues to run into this with the version in master, let us know and we'll reopen this.
