### ISSUE TITLE
Wrong indentation for hamburger menu

### ISSUE THREAD

**Issue by kenchris** [PolymerElements/polymer-starter-kit#117]
The indentation from the left to the hamburger menu should be around 16px, but as the button containing the icon (of size 24x24) is itself 45x45 meaning that is has approx 10px too much padding.

Compare with https://voice-memos.appspot.com/ or any Android app with material design such as Google Keep and Play Newsstand

**Comment by addyosmani** [comment]
![screen shot 2015-06-04 at 12 16 38](https://cloud.githubusercontent.com/assets/110953/7982954/a61e8976-0ab3-11e5-9ed9-23743eeaae48.png)

We currently appear to have a combined margin of ~29px from the edge to the hamburger menu. The Material Design spec site (which I'm told by our designers is the canonical version to go by) uses 27px.

![screen shot 2015-06-04 at 12 19 12](https://cloud.githubusercontent.com/assets/110953/7982992/043d43f8-0ab4-11e5-9534-6d943f595d2f.png)

Google Play Music uses 19px:

![screen shot 2015-06-04 at 12 20 47](https://cloud.githubusercontent.com/assets/110953/7983015/2e979f36-0ab4-11e5-8033-ddd56136764a.png)

Inbox uses ~27px:

![screen shot 2015-06-04 at 12 22 18](https://cloud.githubusercontent.com/assets/110953/7983031/604d7ae6-0ab4-11e5-8bb9-290ef61e3b00.png)

I'll check with the MD team to find out what the correct margins/padding here should be. We definitely want to make sure we're using the correct values.

**Comment by kenchris** [comment]
I forgot telling you that I changed to seamed mode, which is even closer. 

https://voice-memos.appspot.com/ also has two different identation depending on size (seamed or waterfall).

You are right that Inbox (on the web, not on Android) uses 27px. I remember using core-narrow for the toolbar when the width is below 640px. I believe that this also makes up the difference.

**Comment by kenchris** [comment]
It is either 16 or 24 to the icon according to the guide and it depends on it being mobile or desktop (media queries)

http://www.google.com/design/spec/layout/structure.html#structure-app-bar

**Comment by addyosmani** [comment]
@kenchris Put together https://github.com/PolymerElements/polymer-starter-kit/pull/118. PTAL if you get a chance.

**Comment by devAtPolydeals** [comment]
@addyosmani  does that also mean changing app-layouts? Are they as per spec?

https://github.com/PolymerElements/app-layout-templates
