### ISSUE TITLE
Could not find WCT plugin named "local"

### ISSUE THREAD

**Issue by mangibu** [PolymerElements/polymer-starter-kit#119]
When I run "gulp test:local" I get

$ gulp test:local
[17:10:39] Using gulpfile c:\Users\Michael\Documents\Projects\polymer-starter-kit\gulpfile.js
[17:10:39] Starting 'wct:local'...
[17:10:39] 'wct:local' errored after 23 ms
[17:10:39] Error: Could not find WCT plugin named "local"

Any help is welcome.
Thank you.

Michael

**Comment by addyosmani** [comment]
Could you share: version of Starter Kit you're using, version of Node, OS (assuming Windows).

**Comment by mattbogado** [comment]
Hi Addy, I getting the same error:

0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install' ]
2 info using npm@2.5.1
3 info using node@v0.10.33
4 error install Couldn't read dependencies
5 verbose stack Error: ENOENT, open '/Users/mb0337/Documents/playground/polymer-starter-kit-light-1.0.1/package.json'
6 verbose cwd /Users/mb0337/Documents/playground/polymer-starter-kit-light-1.0.1
7 error Darwin 14.3.0
8 error argv "node" "/usr/local/bin/npm" "install"
9 error node v0.10.33
10 error npm  v2.5.1
11 error path /Users/mb0337/Documents/playground/polymer-starter-kit-light-1.0.1/package.json
12 error code ENOPACKAGEJSON
13 error errno 34
14 error package.json ENOENT, open '/Users/mb0337/Documents/playground/polymer-starter-kit-light-1.0.1/package.json'
14 error package.json This is most likely not a problem with npm itself.
14 error package.json npm can't find a package.json file in your current directory.
15 verbose exit [ 34, true ]

**Comment by addyosmani** [comment]
@mattbogado for the `gulp` commands to work, you'll need to use the full version of Polymer Starter Kit (see the intermediate version in https://github.com/PolymerElements/polymer-starter-kit/releases).

Light is for a quick start without any of the tools included.

**Comment by mattbogado** [comment]
Using the full version, when trying to run `gulp serve` I get this error:
```
Error: Cannot find module 'concat-map'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/mb0337/Documents/playground/polymer-starter-kit-

1.0.1/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/minimatch/node_modules/brace-expansion/index.js:1:79)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)'

**Comment by mangibu** [comment]
I am running Windows 8.1 and Node v0.12.4.

Ok, I thougth I am using the full version. I was able to run "gulp serve" succesfully.
To verify I downloaded the full version again and this time it is working (sorry for the trouble...).

This is the test result:

$ gulp test:local
[18:47:51] Using gulpfile c:\Users\Michael\Documents\Projects\polymer-starter-kit-1.0.1\gulpfile.js
[18:47:51] Starting 'wct:local'...
Starting Selenium server for local browsers
Selenium server running on port 49546
Web server running on port 2000 and serving from c:\Users\Michael\Documents\Projects\polymer-starter-kit-1.0.1\app
firefox 38               Beginning tests via http://localhost:2000/components/app/generated-index.html?cli_browser_id=1
404 GET /bower_components/webcomponentsjs/webcomponents.min.js
404 GET /components/app/my-greeting-basic.html?
ie 11.0.9600.17416       Beginning tests via http://localhost:2000/components/app/generated-index.html?cli_browser_id=2
ie 11.0.9600.17416       Tests passed
chrome 43                Beginning tests via http://localhost:2000/components/app/generated-index.html?cli_browser_id=0
chrome 43                Tests passed
firefox 38               ? my-greeting-basic.html

  Timed out loading http://localhost:2000/components/app/my-greeting-basic.html?
    <unknown> at                          done at /components/mocha/mocha.js:1846:0
    <unknown> at        Runner.prototype.run/< at /components/mocha/mocha.js:5213:0
    <unknown> at   EventEmitter.prototype.emit at /components/mocha/mocha.js:616:0
    <unknown> at                       start/< at /components/mocha/mocha.js:5203:0
    <unknown> at     Runner.prototype.runSuite at /components/mocha/mocha.js:5103:0
    <unknown> at                         start at /components/mocha/mocha.js:5201:0
    <unknown> at          Runner.prototype.run at /components/mocha/mocha.js:5226:0
    <unknown> at           Mocha.prototype.run at /components/mocha/mocha.js:1849:0

404 GET /components/app/my-list-basic.html?
firefox 38               ? my-list-basic.html

  Timed out loading http://localhost:2000/components/app/my-list-basic.html?

firefox 38               Tests failed: 2 failed tests
Test run ended in failure: 2 failed tests

chrome 43 (2/0/0)                       firefox 38 (0/0/2)                      ie 11.0.9600.17416 (2/0/0)
[18:49:12] 'wct:local' errored after 1.33 min
[18:49:12] Error: 2 failed tests

Thanks.
Michael

**Comment by addyosmani** [comment]
@mattbogado is this after running `npm install && bower install` inside your downloaded Starter Kit directory before running `gulp serve`?

**Comment by mattbogado** [comment]
@addyosmani yeah

**Comment by mattbogado** [comment]
@addyosmani I downloaded a fresh copy of 1.0.1 and run the `npm install && bower install` commands and I'm getting this:
```
npm ERR! install Couldn't read dependencies
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.33
npm ERR! npm  v2.5.1
npm ERR! path /Users/MAB15PRO/Documents/playground/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno 34

npm ERR! package.json ENOENT, open '/Users/MAB15PRO/Documents/playground/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/MAB15PRO/Documents/playground/npm-debug.log

**Comment by addyosmani** [comment]
@mangibu I'm glad to hear you were able to get a little further with the local testing setup. It seems like we'll need to work around timing issues as Node 0.12.x+ on *nix systems appears to work fine at the moment. 

I was able to get the tests passing on Windows 8 with Chrome (see below) but will try to verify with FF too in case we're seeing issues there.

![screen shot 2015-06-06 at 12 00 20](https://cloud.githubusercontent.com/assets/110953/8019394/be241e46-0c43-11e5-8c42-c7facfafd2eb.png)

(There is a known issue with tests running slow on Windows per https://github.com/Polymer/web-component-tester/issues/169)

**Comment by fuzzdota** [comment]
@addy I'm running into this issue with missing "local" plugin. 

Windows 7, Node: 0.12.3, wct: ^3.1.3. I'm not using the polymer-starter-kit. I have wct installed globally and start the test from root directory using 
```
wct --verbose
```

**Comment by fuzzdota** [comment]
Just an update. It was my mistake in updating PATH variable.

My PATH contains both directories to WCT 
```
Users/Sam/AppData/Roaming/npm
```
```
Users/Sam/AppData/Roaming/node_modules/web-component-tester/bin
```

Removing the 2nd path solves this problem for me.

**Comment by addyosmani** [comment]
Looked into this further. Please make sure to double-check your PATH config for issues as @fuzzdota did and you shouldn't run into problems with WCT failing on local. I've verified on a new Windows box that with a correct PATH setup, WCT runs fine :star:

**Comment by diregraph** [comment]
This problem also occurs if you have 'wct' installed globally and 'wct-local' plugin installed locally.
