### ISSUE TITLE
[Wiki] Instruction to use the Polymer Starter Kit with CDE

### ISSUE THREAD

**Issue by SmokyBob** [PolymerElements/polymer-starter-kit#121]
While Chrome Dev Editor is not developed by Google anymore [[ref](https://plus.google.com/u/0/+SriramSaroop/posts/6EwgknwKpeS)] a lot of people are still using it, especially on ChromeOS.

Following the steps required to use the starter kit from CDE:
- Download the Polymer Starter Kit zip file
- Unpack in a folder
- move the bower.json file from the main folder to /app
- Open CDE
- Load the project folder
- CDE should start downloading the packages from bower... it will take a bit of time (64 packages)
- meanwhile... Open the app/element/routing.html file and remove a ../ from the import of page.js
- rename manifest.json to ... _manifest.json ... or something that is not manifest.json, otherwise CDE will try to start your project as a Chrome app and fail.
- go to app/index.html, run the project

Would like to create the wiki page myself and push PR, but I'm not sure how to do it for wiki pages (is it possible? Sorry for my ignorance)

**Comment by arthurvr** [comment]
I honestly don't really think this is much of a topic for us to cover. Because it would be more showing how to use a specific editor than how to use the tooling/starter-kit.

**Comment by addyosmani** [comment]
@arthurvr I suggested @SmokyBob open an issue about this here, mostly so we can gauge interest in how many people would want this before we commit to adding it to docs via the wiki.

**Comment by arthurvr** [comment]
I like the idea of having docs, though I don't think we should do them over at the wiki. It limits contributions in a significant way. I'd rather see us doing 'recipes' such as [generator-gulp-webapp](https://github.com/yeoman/generator-gulp-webapp/tree/master/docs/recipes) does that.

On this idea in specific, although it all sounds like really handy documentation, I don't see how it's topic for us to cover. It's teaching how to use a specific editor, not documenting how to use the PSK tooling. 

The steps @SmokyBob covered in his comment are perfectly valid, but it's the editor's responsibility to document such things IMHO. Also this at all isn't specific to PSK. I can imagine that everybody using some kind of tooling and that editor runs into such problems.

> but I'm not sure how to do it for wiki pages (is it possible?

It isn't. That's one of the main reasons I wouldn't like us to start building documentation in the wiki.

**Comment by Nevraeka** [comment]
:+1: It would be great to add the 'preferred' way of building production apps into the polymer hackademics & codelabs we are upgrading to 1.0.x . Great idea @SmokyBob

**Comment by arthurvr** [comment]
@addyosmani Has been a while, what were your plans with this issue? I still don't think it's topic for us to cover.

**Comment by addyosmani** [comment]
I've decided that adding this to the wiki wouldn't make sense. We are interested in adding a `docs` or `recipes` directory to PSK and a guide like this could live there, but we would probably need commitment from someone to write that guide and initially help maintain it.

**Comment by SmokyBob** [comment]
Count me in to write the `docs` or `recipes` if nobody else come forward

**Comment by addyosmani** [comment]
@SmokyBob If you're interested, more than happy to review a PR. It would be great to get the ball rolling on this. I could see it being quite similar to how Gulp tackle their in-repo docs and recipes: https://github.com/gulpjs/gulp/tree/4.0/docs/recipes

**Comment by SmokyBob** [comment]
@addyosmani cool, so a PR adding a `docs/recipes` + README.md + the recipe for CDE should suffice for now?
Going to start working on it soon (and checking other possibilities after the latest update to CDE with templates using 1.0)

**Comment by chuckh** [comment]
@SmokyBob lets use `docs/recipes` + README.md for index of recipes and  `docs/recipes` +  +chrome-dev-editor.md for the specific recipe.

**Comment by SmokyBob** [comment]
@chuckh :+1:

**Comment by addyosmani** [comment]
Closed via https://github.com/PolymerElements/polymer-starter-kit/blob/master/docs/chrome-dev-editor.md
