### ISSUE TITLE
Source Path Too Long

### ISSUE THREAD

**Issue by Werner-Swart-83** [PolymerElements/polymer-starter-kit#123]
So, anyone else having a problems with Source Path Too Long on Windows when you try to remove or move the polymer-starter-kit-dependencies-checked-in-1.0.1 folder?

**Comment by addyosmani** [comment]
Hey @Werner-Swart-83. Unfortunately this is a limitation of NTFS. Read here for a workaround in case you're trying to delete/move the folder: https://coderwall.com/p/alhoww/solving-the-source-path-too-long-ntfs-issue

**Comment by devAtPolydeals** [comment]
Yes i would get this issue. See http://superuser.com/questions/45697/how-to-delete-a-file-in-windows-with-a-too-long-filename on how to fix it. robocopy works like a charm.

**Comment by hs71122** [comment]
@devAtPolydeals Thanks. I have created a simple bat file for deleting the "Source Path Too Long " folder. It is simple to delete this kind of annoying folders. https://github.com/hs71122/Delete-Too-Long-File-Name

**Comment by karin9** [comment]
for deletion or handling of long name i check that "Long Path Tool" software should be try, many articles refer this for such solutions.

**Comment by gamicklisafisher** [comment]
You should check out ‘Long Path Tool’ it will help you fix the issues.
I had faced similar issue and this tool helped me to resolve this issue.
