### ISSUE TITLE
Browser Sync Binding Breaks in Firefox

### ISSUE THREAD

**Issue by zmoshansky** [PolymerElements/polymer-starter-kit#126]
If paper-dialog is included, and thus iron-overlay-behaviour, Browser Sync tries to bind to the `<body>` tag in [iron-overlay's](https://github.com/PolymerElements/iron-overlay-behavior/blob/master/iron-overlay-behavior.html#L41]) documentation. This causes the rest of the file to get fubar'd and lots of weird application errors.

#127 "Fixes it on my machine"

**Comment by addyosmani** [comment]
Fixed now
