### ISSUE TITLE
Recommended update procedure?

### ISSUE THREAD

**Issue by flaiker** [PolymerElements/polymer-starter-kit#131]
If I use PSK in a project and want to update it (let's say from 1.0.0 to 1.0.1), is there a recommended way how to do so? I came up with the following ideas:
  - Work with PSK from source, have two remotes and rebase from PolymerElements/polymer-starter-kit@vX.X.X when I want to update. This however fills my log with commits from changes unrelated to my project but to the kit (and also changes history of my commits).
  - [Compare](https://github.com/PolymerElements/polymer-starter-kit/compare/v1.0.0...v1.0.1) the version I used and the latest one and apply the changes manually (which is a lot of work)

Both ways are of course not ideal, which is why I am asking. This is not specifically related to PSK but to every boilerplate I guess (I wondered about this in WSK also).

I assume there might be some git patch or submodule magic I could be using but I am not all to familiar with the deeper functions of git, so it would be nice to have your take on this.

**Comment by arthurvr** [comment]
Well, this is a *starter* kit. You start with the contents of this repo, and develop upon that base. Though I can imagine you want to update the build process to the latest and greatest, I think the only way you're going to be able to do this is manually.

Keep in mind that the amount of people that will use PSK without doing any modifications to its initial tooling is pretty small.

**Comment by flaiker** [comment]
Fair enough. Though I suppose I'll wait until changes slow down a little to use it in production.

**Comment by flaiker** [comment]
Just for reference: @addyosmani added some instructions on a possible git workflow to update in [v1.0.2 release comments](https://github.com/PolymerElements/polymer-starter-kit/releases/tag/v1.0.2).
