### ISSUE TITLE
Move app-theme.html to styles dir

### ISSUE THREAD

**Issue by robdodson** [PolymerElements/polymer-starter-kit#139]
This file is essentially a stylesheet being shimmed with custom props by `custom-style`. It feels like it should live in `styles`, I keep reflexively looking for it in there. Maybe it's just me, but it feels weird to have it in the `elements` dir

**Comment by chuckh** [comment]
​I agree. I keep looking for it in styles too. ​

On Mon, Jun 8, 2015 at 9:18 PM, Rob Dodson <notifications@github.com> wrote:

> stylesheet





-- 
Chuck Horton
actionplanr.com
www.hware.com
chuck@hware.com
www.twitter.com/chuckhorton
530.268.5840

Let us create a world that works for all.

**Comment by addyosmani** [comment]
I agree too. Let's move it to the styles directory.

**Comment by arthurvr** [comment]
I think this can be closed, as https://github.com/PolymerElements/polymer-starter-kit/pull/140 landed?

**Comment by addyosmani** [comment]
:+1:
