### ISSUE TITLE
navigation requires 2 clicks

### ISSUE THREAD

**Issue by atdotslashdot** [PolymerElements/polymer-starter-kit#141]
I just downloaded and tried the light version of the starter kit.
I have to click twice on the navigation to get it to work (home ,user, contact)
The first click highlights the link with a grey background.

**Comment by atdotslashdot** [comment]
Update, seems to work correctly in chrome but not firefox

**Comment by arthurvr** [comment]
Yes, I seem to be able to reproduce that. Is this a bug in `<paper-menu>` or our use of it?

**Comment by addyosmani** [comment]
It may be our use of it. For a11y reasons we opted/were recommended to just use anchors rather than <paper-item>. We're possibly losing some styling there.

**Comment by addyosmani** [comment]
This is basically the same issue as https://github.com/PolymerElements/polymer-starter-kit/issues/166. As it includes some more information, let's chase it up there.
