### ISSUE TITLE
links not relative

### ISSUE THREAD

**Issue by atdotslashdot** [PolymerElements/polymer-starter-kit#142]
the starter kit links aren't relative to install location
I installed at
http://mydomain/polymer/light/app/
but users (for example)
take me here
http://mydomain/#!/users
the app appears to work but a refresh will,of course, break it

**Comment by EvgenyKarataev** [comment]
According to Page.js documentation (https://visionmedia.github.io/page.js/)
you can set base path with page.base([path]).

In your case you could try to set page.base('/polymer/light/app/') in
routing.html.

P.S.: I have not tried the solution myself.


Best Regards,
Evgeny Karataev

**Comment by addyosmani** [comment]
I haven't confirmed the `page.base` solution works for the above, but once we've verified it I think it makes sense to at minimum add a comment to the routing import to make it more clear for folks.

**Comment by atdotslashdot** [comment]
Thanks Evgeny, where in routing.html would you include the call? I'm not having success here. i tried inside the anonymous function..

```javascript   
window.addEventListener('WebComponentsReady', function() {
   
    console.log("setting page base...");
    page.base('/polymer/light/app/');
...
```
console reports the message but the problem remains

Cheers
James Driscoll

**Comment by EvgenyKarataev** [comment]
James (@atdotslashdot),

The place where you put `page.base('/polymer/light/app/');` is correct. 

I just did some tests locally and also looked at the examples in the page.js codebase and it seems that the problem boils down to how href attributes are set in the index.html file. 

The values in href attributes should be prefixed with "." (dot). For example, `<a data-route="home" href="/">` should be `<a data-route="home" href="./">`, `<a data-route="users" href="/users">` should be `<a data-route="users" href="./users">`, etc.

Note that nothing need to be changed in the routing.html file (except adding the `page.base(...)`).

I tried to serve PSK locally at `localhost:8081/dist`

In routing.html file, I added `page.base('/dist');`:
```javascript
...
window.addEventListener('WebComponentsReady', function() {

     page.base('/dist');

    // We use Page.js for routing. This is a Micro
    // client-side router inspired by the Express router
    // More info: https://visionmedia.github.io/page.js/
    page('/', function () {
      app.route = 'home';
    });
...
```

As example screen shots (note the url)

![image](https://cloud.githubusercontent.com/assets/442457/8090502/e882b0b6-0f73-11e5-9811-9569e3b204da.png)

Here is the users page (note the url):

![image](https://cloud.githubusercontent.com/assets/442457/8090307/c85f91c4-0f72-11e5-83ed-5d264d591b79.png)


Hope that helps.

**Comment by atdotslashdot** [comment]
Hi Evgeny, still no joy here but it has changed a little....
I prefixed the hrefs in index.html with a .
e.g.
```javascript
<a data-route="users" href="./users">
```
if I go to
http://mydomain/polymer/light/app/
and click users it takes me to
http://mydomain/polymer/light/app/users
which results in a not found error
(NOTE the lack of #! in the url even the  hashbang is set to true  in routing.html)

Thanks for investigating. 
James Driscoll

**Comment by EvgenyKarataev** [comment]
@atdotslashdot,

That's weird. The example that I showed earlier was working on the full PSK (not lite version). I just tried that approach on the light version (light-1.0.2) and it didn't work.

However, I believe I was finally able to make it work after playing with different things. Here is the demo: http://evgenykarataev.github.io/pskWithBaseRoute/polymer/light/app

So, try this:
* Add `<base href="/polymer/light/app/">`  tag in the `index.html` file inside the `<head>` attribute. NOTE the trailing "/" at the end. Example from my demo is [here](https://github.com/EvgenyKarataev/pskWithBaseRoute/blob/gh-pages/polymer/light/app/index.html#L53).
* In `routing.html` file, set `page.base('/polymer/light/app')`. NOTE no trailing "/" at the end. Example from my demo is [here](https://github.com/EvgenyKarataev/pskWithBaseRoute/blob/gh-pages/polymer/light/app/elements/routing.html#L15). 

Let me know if that helped or not.

**Comment by atdotslashdot** [comment]
Thanks Evgeny, that appear to have got it running.
so the summary is....

* Add ```<base href="/polymer/light/app/">``` tag in the ```index.html file``` inside the ```<head>``` attribute. NOTE the trailing "/" at the end
* prefix hrefs in ```index.html``` with a ```.``` e.g ```<a data-route="users" href="./users">```
* in routing.html file, set page.base('/polymer/light/app'). NOTE no trailing "/" at the end. 

hopefully someone will take this information and make the 'light' version a little simpler :-)

Thanks for the help

**Comment by blahblahartyfarty** [comment]
thing is why do they need to be relative don't change a working horse

**Comment by himalikiran** [comment]
I made little adjustment to data-route section of index.html to work with hasbang (#!):
```Replace "./" to "#!/" in href of users and contacts.```

**Comment by victoriaSh** [comment]
If anyone else have the problem after this trick that page beginning infinitely reloading when you open url in browser to path that doesn't exists?
For example, I have app:
http://localhost/app/#!/
And have page like this
http://localhost/app/#!/users
But when I accidentally typed this url in a new tab the page began infinitely reloading:
http://localhost/app/#!/user

**Comment by robdodson** [comment]
Yeah the page.js router is a little flakey when it comes to hashbang urls :(

**Comment by robdodson** [comment]
There's now [a recipe for deploying to a subdirectory](https://github.com/PolymerElements/polymer-starter-kit/blob/master/docs/deploy-to-github-pages.md) (example used is GitHub pages but this should work for any subdir). Closing this but happy to reopen if folks are still having issue.

**Comment by raynstudios** [comment]
I am unable to get it working in Laravel. Please see my question at [Stackoverflow](https://stackoverflow.com/questions/34741888/polymer-routing-in-laravel)

**Comment by robdodson** [comment]
@raynstudios answered on stackoverflow
