### ISSUE TITLE
Weird behaviour when holding a mouse button down

### ISSUE THREAD

**Issue by hugo-agbonon** [PolymerElements/polymer-starter-kit#146]
Hello,

On an unmodified Starter Kit,

* On Firefox, holding down a mouse button anywhere (to select text for example) and moving the mouse cursor darkens the page then brings out the menu
* On Chrome, no menu appears, but (sometimes only after activating the menu and changing pages first) I am unable to select text correctly

**Comment by addyosmani** [comment]
Thanks @hugo-agbonon. Could you share:

- What version you're using (Light? Full? 1.0.0? 1.0.1?)
- Is this happening only when you're close to the left edge? (the menu is meant to appear when dragging lightly from the edge, but not when near the middle/right side)

**Comment by hugo-agbonon** [comment]
I'm using the full version 1.0.1. 

After further testing, I can see how the dragging works in Chrome, but the menu appears on Firefox  even if I start dragging on the far right side of my window (tested on FF 38 & 40)

**Comment by addyosmani** [comment]
After reviewing this issue, the drawer behaviour from `paper-drawer-panel` is causing it. Would you mind filing the issue upstream at https://github.com/PolymerElements/paper-drawer-panel? We can take a look at it there after.

Demo for verification (shrink the window/viewport down): https://elements.polymer-project.org/bower_components/paper-drawer-panel/demo/index.html.
