### ISSUE TITLE
Avoid sending iron-ajax request if page is not active

### ISSUE THREAD

**Issue by teckays** [PolymerElements/polymer-starter-kit#149]
I have multiple pages and one of them uses `iron-ajax` to grab some data from a database, however the request is sent no matter what page I'm currently on, how to avoid this?

**Comment by albertolobrano** [comment]
I have the same issue.  I was thinking to load the ajax request in the route but not sure if it is the best option.  Very interested to know an opinion on this.

**Comment by albertolobrano** [comment]
Polymer element catalog show how to use the iron-ajax to load data on demand and gives some useful patterns.  It is using app-router instead of page.js

**Comment by devAtPolydeals** [comment]
removing the attribute 'auto' may help. 

auto Boolean
default: false
If true, automatically performs an Ajax request when either url or params changes

**Comment by teckays** [comment]
@devAtPolydeals tried, no change. Thing here is that `iron-pages` renders all its sections no matter which one is active which leads the code to be executed and so ajax requests performed. I thought of a more "intelligent" way of managing it. As somebody pointed out on slack, the `core-pages` attached an `active` attribute to the current section and so inside it you know either the view is active or not. No I have to think of a clean and easy-to-implement solution.

**Comment by robdodson** [comment]
This issue doesn't seem specific to PSK but more about how you're architecting your app. Would you all be ok if we closed this?

**Comment by teckays** [comment]
Hi @robdodson, sorry for late reply. I'm OK with closing it, however I still think there should be a little talk here, but that's not related to PSK (you're right) but how `iron-pages` stamps the content for non active sections. I did find a workaround, looks more like a hack but it's OK for now. Thanks.

**Comment by albertolobrano** [comment]
In case someone has the same issue this is how i solved:

1) i added the attribute selected-attribute="activated" to the component iron-pages
2) added an activated properties in the component that reders my page : activated: {
        type: Boolean,
        value:false,
        observer: '_activatedChanged'
      }

every time my page becomes active i am notified.

**Comment by dman777** [comment]
Just wanted to add.... I haven't tested this, but lazyRegister could possibly be alternative solution:

```javascript
  // Setup Polymer options
  window.Polymer = {
    dom: 'shadow',
    lazyRegister: 'max'
  };
```

**Comment by dman777** [comment]
I'm having this issue design issue also. PSK is not the right place for it, but since the discussion is here it would be nice if `iron-ajax` had a attribute setting for this kind of use case.

**Comment by dman777** [comment]
[created feature request](https://github.com/PolymerElements/iron-ajax/issues/253)
