### ISSUE TITLE
poymer-starter-kit-light for the creation of custom elements 

### ISSUE THREAD

**Issue by mangibu** [PolymerElements/polymer-starter-kit#150]
To better understand: Can I use the starter-kit-light to create and test new elements?

If I add a new element to the elements-folder and add it to the elements.html and to the index.html file it is shown up in the browser. But if I change the new element it is not refreshed. The element is not changing. I tested this with the Firefox browser.

I read about "Register a custom element" but I can't find this in the starter-kit-light for the elements my-greeting and my-list.

Thanks.
Michael

**Comment by arthurvr** [comment]
> If I add a new element to the elements-folder and add it to the elements.html and to the index.html file it is shown up in the browser. But if I change the new element it is not refreshed.

Well, if you explicitely choose for a version without tooling, you can't benefit from the set of tooling PSK comes with :)

**Comment by mangibu** [comment]
OK, I got it.

Thanks. 
Michael

**Comment by addyosmani** [comment]
Arthur's comment above is correct. You'll need to use the version with tooling for the above to work.
