### ISSUE TITLE
Docs: enumeration of steps does not make sense if there is only one

### ISSUE THREAD

**Issue by flaiker** [PolymerElements/polymer-starter-kit#153]
In [my-greeting-basic.html](https://github.com/PolymerElements/polymer-starter-kit/blob/master/app/test/my-greeting-basic.html#L23) and [my-list-basic.html](https://github.com/PolymerElements/polymer-starter-kit/blob/master/app/test/my-list-basic.html#L23) there is a comment each telling the user:
```
<!-- Step 1: import the element to test -->
```

There are however no comments with step 2, 3 and so forth (just specific comments on the tests) so I would suggest to either leave out `Step 1:` or replace it by `First` or something similar. I assume this might be a remainder of a template for tests.

(If you want me to stop nitpicking on these extremely minor things tell me...)

**Comment by addyosmani** [comment]
Please nitpick :) I'd far rather that we got all of these items right. I think wrt to the above we should leave out `Step 1:`.
