### ISSUE TITLE
Moved <script> tags inside <dom-module> according to latest recommendations

### ISSUE THREAD

**Issue by chuckh** [PolymerElements/polymer-starter-kit#155]
Per latest Polymer release notes move `<script> tags` inside` <dom-module>`.

See release notes at https://www.polymer-project.org/1.0/docs/release-notes.html#documentation-updates-10-june-2015 

See @sjmiles example of this at http://jsbin.com/kobuvu/1/edit?html,output.

**Comment by cnbuff410** [comment]
the "is: xxxx" property is not required officially?

**Comment by addyosmani** [comment]
@chuckh good catch. We should be able to land a change for this to coincide with the 1.0.3 PSK release.

**Comment by arthurvr** [comment]
Fixed in https://github.com/PolymerElements/polymer-starter-kit/commit/d7a146c8cb42cff3d7f4712eb381183fa827e79e?

**Comment by chuckh** [comment]
Yes this now fixed with d7a146c and 5e682fa.
