### ISSUE TITLE
[FEATURE REQUEST] CLI tool for initing starter kit

### ISSUE THREAD

**Issue by QuantumInformation** [PolymerElements/polymer-starter-kit#157]
Can we create a CLI tool like (EMBER-CLI) [http://www.ember-cli.com/] that can download and init a project for us from terminal?

**Comment by addyosmani** [comment]
That would be https://github.com/yeoman/generator-polymer :) Specifically, the latest releases include support for Starter Kit out of the box https://github.com/yeoman/generator-polymer/releases
