### ISSUE TITLE
Application sub title does not work with waterfall-tall

### ISSUE THREAD

**Issue by flaiker** [PolymerElements/polymer-starter-kit#158]
In index.html there is a place to set an application sub title (not set by default) ([link](https://github.com/PolymerElements/polymer-starter-kit/blob/master/app/index.html#L102-L103)):
```
<!-- Application sub title -->
<div class="bottom title"></div>
```

As you can see in the following animation application title and subtitle overlap when `paper-header-panel.mode="waterfall-tall"`takes effect (scrolling).
![subtitle](https://cloud.githubusercontent.com/assets/5270359/8104754/82d22696-1033-11e5-824a-22b11110eaa9.gif)

Might want to not chose waterfall-tall, cut the subtitle from the template or refactor it to not be displayed if page-header-panel is collapsed.

**Comment by addyosmani** [comment]
My personal take is we should hide the subtitle from the template when `paper-header-panel` is collapsed. cc @chuckh in case he has thoughts here too.

I'll check with the Material Design team here too in case they have specific suggestions for what we should be doing here.

**Comment by SilverPaladin** [comment]
Until a fix is available you could add
```paper-toolbar.has-shadow #bottomBar {
    display: none;
}```
to styles/main.css

**Comment by chuckh** [comment]
I agree we should hide this condition. We should put it in styles/app-theme.html.
```
paper-toolbar.has-shadow #bottomBar { display: none; }
```

**Comment by SilverPaladin** [comment]
It would be better to hide it with script before the waterfall collapses, and unhide it when the waterfall expands. As it is with the css I suggested it's pretty janky looking.

Perhaps a scroll observer on the <paper-header-panel> and some script?

**Comment by robdodson** [comment]
You could try something like this:

```css
#mainToolbar .bottom {
  transition: 0.18s opacity 0.18s ease-in;
  opacity: 1;
}
  
#mainToolbar:not(.tall) .bottom {
  transition: 0.18s opacity ease-in;
  opacity: 0;
}
```

This is just personal opinion, but I don't like styling off of `.has-shadow` because I feel like `:not(.tall)` is more evocative of the state that we're in. I realize this style exists as precedent `#mainToolbar.has-shadow .middle` but I'm curious if we might consider changing over to `:not(.tall)` for these?

**Comment by chuckh** [comment]
I agree with @robdodson approach to use :not(.tall) across the board.

**Comment by addyosmani** [comment]
I agree with `:not(.tall)` being more evocative for the state this represents. Would anyone like to PR this change in?

**Comment by chuckh** [comment]
Pull request #185 makes @robdodson suggested changes and fixes this issue, see below for demo.

![sub-title-fix](https://cloud.githubusercontent.com/assets/19915/8212292/bb711c50-14cf-11e5-924e-9110b1f8a1d1.gif)

**Comment by howking** [comment]
same issue on IE11?
I fix it to set [tall] class on paper-toolbar like demo page.

polymer-starter-kit/app/index.html
```html
<paper-toolbar id="mainToolbar" class="tall">
```

**Comment by Adesfire** [comment]
On the WebStarterKit for Polymer, i can see this line in the main example index.html 

`<!-- Application sub title -->`
`<div class="bottom title"></div>`

If we put a sentence in this, we have the same problem as describe in the first post of this page.
I think it's an error in the example but i don't know how to avoid it.

**Comment by SayChunKim** [comment]
@Adesfire please refer previous comment of @robdodson 

Cheers
