### ISSUE TITLE
How does the paper-menu work with on-iron-select?

### ISSUE THREAD

**Issue by Cammisuli** [PolymerElements/polymer-starter-kit#159]
In the starter kit the paper-menu has an attribute called "on-iron-select". Where is documentation on this attribute?

I tried looking through Polyerm.IronSelectableBehavior, and all behaviors that are similar and I cannot find out where this is implemented.

Is this hidden somewhere?

**Comment by hourliert** [comment]
Same question here. I cannot find any documentation about this.

**Comment by Cammisuli** [comment]
Where would that event be in the docs here?
https://elements.polymer-project.org/elements/iron-selector?active=Polymer.IronSelectableBehavior

Even in the source I can't find anything related to 'on-iron-select'
https://github.com/PolymerElements/iron-selector/blob/master/iron-selectable.html

I just want to know how it works.

In the mean time I changed it to 'on-click' based on generic Polymer events, just so I understand how it's working.

**Comment by hourliert** [comment]
[Here](https://github.com/PolymerElements/iron-selector/blob/master/iron-selectable.html#L250) is the line when the event is fired.

The doc of IronSelectableBehavior seems to be incomplete and doesn't detail the events iron-select or iron-deselect :(.

**Comment by Cammisuli** [comment]
Thank you! That's exactly what I needed.
