### ISSUE TITLE
gulp does not copy non html files from new folders

### ISSUE THREAD

**Issue by devAtPolydeals** [PolymerElements/polymer-starter-kit#160]
Hi,

I created a new folder on the root i.e. app/pages and inside this folder I have some HTML, CSS and php pages. When i gulped it did not copy the non html files to the dist folder.

Thanks!

**Comment by chuckh** [comment]
The `gulpfile.js` needs to be change from  `'app/*',` to `'app/**',` to copy all files from app/ to dist/app. Note two stars instead of one.. 

### Revises code snippet.
```
// Copy All Files At The Root Level (app)
gulp.task('copy', function () {
  var app = gulp.src([
    'app/**',
    '!app/test',
    '!app/precache.json'
  ], {
    dot: true
  }).pipe(gulp.dest('dist'));
```

**Comment by devAtPolydeals** [comment]
Thanks @chuckh  that worked!
