### ISSUE TITLE
How should we handle google fonts api roboto error ?

### ISSUE THREAD

**Issue by akhr** [PolymerElements/polymer-starter-kit#162]
Hi,

I am not importing roboto font in my page or component. But the paper and iron components that I use do. The app/page suffers because randomly I get this following error.

![robot-error](https://cloud.githubusercontent.com/assets/695965/8116680/525e514c-1038-11e5-8615-6da793f287e3.png)

How do want us to handle this issue? Go in check every single component that we use and remove roboto font import or usage? 

Note: I have no network issues. But in general, wouldn't this be an issue when apps are designed to work offline? Is there a fix for this?

Thanks

**Comment by blasten** [comment]
are you using the elements from a chrome-extension? I think this is the issue:
https://github.com/PolymerElements/paper-styles/blob/master/typography.html#L11

**Comment by addyosmani** [comment]
Would it be possible to try this in a [clean](https://developer.chrome.com/devtools/docs/clean-testing-environment) testing environment (i.e a new profile without extensions on) to see if you're still running into the same issue?

**Comment by arthurvr** [comment]
> Would it be possible to try this in a clean testing environment (i.e a new profile without extensions on) to see if you're still running into the same issue?

Friendly ping @akhr.

**Comment by samccone** [comment]
Yeah this is totally due to one of the components using (the now anti-pattern) schema-less `fonts.googleapis`

@akhr if you can list your components and find the one grabbing those files it should be quite simple to fix upstream.

Thanks for the issue reporting :clap:

**Comment by arthurvr** [comment]
Can you check that you use the latest version of font-roboto? https://github.com/PolymerElements/font-roboto/commit/fcda0585729e698716a89b262c583ed5a24f16ec should have fixed this issue.

**Comment by samccone** [comment]
this is now all working on latest master

Thanks a bunch @arthurvr and @akhr :)
