### ISSUE TITLE
Can we minify vulcanized file in the gulp sequence?

### ISSUE THREAD

**Issue by devAtPolydeals** [PolymerElements/polymer-starter-kit#164]
I don't know if this is even possible. But it would be nice to minify the contents of elemets.vulcanized.html if possible after the vulcanize step

**Comment by jannakha** [comment]
it was possible in 0.5.* (--strip option) for new version check out bottom most note in https://github.com/Polymer/vulcanize ReadMe:
--csp mode has been moved into crisper
--strip mode was removed, use something like html-minifier or minimize
