### ISSUE TITLE
Preprocessors support

### ISSUE THREAD

**Issue by pmros** [PolymerElements/polymer-starter-kit#165]
It would be nice if polymer-starter-kit gulpfile.js support preprocessing files to JS/HTML/CSS, for example I usually use LiveScript/Jade/Stylus. Make polymer-starter-kit polyglot out of the box!
Thank you.

**Comment by robdodson** [comment]
I think it would be cool if other folks forked the starter kit to add their own tooling but IMO it's best if the starter kit sticks to plain HTML and CSS. Plain CSS in particular because we're using custom properties which may not be supported in CSS preprocessors.

**Comment by arthurvr** [comment]
You should feel free to use any preprocessor you like but I'd prefer PSK to be *vanilla*. If there are any really really popular options we could *maybe* think about options in generator-polymer.

>  Plain CSS in particular because we're using custom properties which may not be supported in CSS preprocessors.

:+1: 

Also consider that most preprocessors pick up whole files to compile while using Polymer (and web components in general) many code gets written inside of `<script>`/`<style>` tags.

**Comment by addyosmani** [comment]
> I think it would be cool if other folks forked the starter kit to add their own tooling but IMO it's best if the starter kit sticks to plain HTML and CSS. Plain CSS in particular because we're using custom properties which may not be supported in CSS preprocessors.

I fully agree with Rob here. We originally supported a baked in preprocessor (Sass) but since getting support for CSS custom properties, we prefer to include good defaults for those. It trims down the dependency tree for everyone too. I think documenting how to get this added to PSK elsewhere would be useful to folks though.
