### ISSUE TITLE
Global Variables getting trashed near end of load in PSK 1.0.2

### ISSUE THREAD

**Issue by ValueBC** [PolymerElements/polymer-starter-kit#167]
Seems to be an intermittent issue that has come up since the new PSK 1.0.2. Steps:
1) add new global object “var lm = {}”; (tried window.lm as well)
```
var lm = {};
console.log('Line 34 lm loaded');
```
2) gulp serve
3) works fine
```
Line 34 lm loaded
app.js:17 Our app is ready to rock!
lm
Object {map: Object, nav: Object, storage: Object, bcJuri: Object, place: Object…}
```
4) refresh browser
5) global loads, notice the "Line 34 statement", then “ls is not definded”
 ```
Line 34 lm loaded
(index):55 Resource interpreted as Document but transferred with MIME type text/css: "http://localhost:3000/bower_components/paper-dialog-behavior/paper-dialog-common.css".
(index):55 Resource interpreted as Document but transferred with MIME type text/css: "http://localhost:3000/bower_components/paper-drawer-panel/paper-drawer-panel.css".
(index):55 Resource interpreted as Document but transferred with MIME type text/css: "http://localhost:3000/bower_components/paper-item/paper-item-shared.css".
app.js:17 Our app is ready to rock!
lm
VM137:2 Uncaught ReferenceError: lm is not defined
    at <anonymous>:2:1
    at Object.InjectedScript._evaluateOn (<anonymous>:895:140)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:828:34)
    at Object.InjectedScript.evaluate (<anonymous>:694:21)

The MIME errors also show up on browser reload. I have seen these before, but they did not cause an issue. I had no issues with global variables before the upgrade to 1.0.2 (that I noticed).

```

**Comment by ValueBC** [comment]
Disabling "Service Worker" as per the PSK Instructions seems to have solved the issue for now.

**Comment by addyosmani** [comment]
Thanks for providing us more information. Would it be possible to test if (with Service Worker enabled) this is happening at build time too? As part of #151, we're thinking about whether this should just be disabled for users during `gulp serve` vs disabled outright by default to help avoid issues like this.

**Comment by addyosmani** [comment]
friendly ping

**Comment by ValueBC** [comment]
Sorry, I got busy with other issues. The "global varible trashing" may have
been caused by a mis-spelled custom element. That was one of the many
changes I made, then the problem went away, or it was something else. It
was a bit inconsistent, and there were too many changes to know for sure
what the issue was. The irony was that the issue only occured after a
brower reload, not on the intial "gulp serve".

Thanks for your diligence!

**Comment by addyosmani** [comment]
@ValueBC Thanks for the update. Totally understand. If you think that there's a sufficient enough chance this may have been a misspelled element name, are you okay with us closing this issue? I do want to double check the `gulp serve` step separately as my expectation is that it works for catching issues like this.

**Comment by ValueBC** [comment]
Hi Addy, yes please close the issue, thanks again.

**Comment by ValueBC** [comment]
Hi Addy, the issue of global variables disappearing after page inialization
came up again. I started a new PSK to try a demo. With almost no code,
except adding the global var, the problem re-appeared. The workaround is to
remove all "Service Worker" stuff, specifically the 'precache' from the
default gulp.task.

Not sure since this issue was closed if you get this email still.

**Comment by addyosmani** [comment]
Thanks for the update. We've since decided to comment out the SW implementation by default as it requires folks to be a little more familiar with how to debug SW, including issues like this as a portion of your codebase will get cached during serve too. 

I'm hopeful that as we see more people use our SW elements we'll be able to improve docs on how to ensure you're not accidentally precaching files that will raise issues like this.
