### ISSUE TITLE
Not loading webcomponents on browsers that have native WC support

### ISSUE THREAD

**Issue by devAtPolydeals** [PolymerElements/polymer-starter-kit#168]
In one of the Polycasts @robdodson  presented an idea that it is not required to load webcomponents polyfill for browsers that natively support WC, hence he had below piece of code, which i like:
```	
if ('registerElement' in document
		  && 'createShadowRoot' in HTMLElement.prototype
		  && 'import' in document.createElement('link')
		  && 'content' in document.createElement('template')) {
		  // We're using a browser with native WC support!
		} else {
		  document.write('<script src="bower_components/webcomponentsjs/webcomponents.min.js"><\/script>');
		}
```

This ensures that the js is not loaded on chrome, may be we can do the same on app-starter-kit?

however, this means WebComponentsReady event won't fire.

**Comment by addyosmani** [comment]
Thanks for bringing this up @devAtPolydeals. I'm familiar with this pattern, but would prefer for us to be able to continue offering the `WebComponentsReady` event. 

Looking at the polyfills, we fire a CustomEvent for this over in the booter https://github.com/webcomponents/webcomponentsjs/blob/ff1ba94f92efa3b882cc51668d4cfec0acac0e92/src/CustomElements/boot.js#L61.  One option is to put together a minimalist equivalent for the conditions leading to this being fired so the polyfills load + no-polyfills-load scenarios both offer the same compatibility with this event.

@sjmiles interested in your thoughts around whether this is worth exploring, in particular in the context of the Starter project. My gut tells me this is a pattern better left to more experienced devs, but will await your two cents :)

**Comment by kenchris** [comment]
I just ran into this as well, (ie starter kit not working properly) because I started following Paul Lewis latest lazy loading ideas :-)

**Comment by addyosmani** [comment]
Let's continue the conversation around performance patterns as part of #178. There's going to be some discussion that needs to be done about pros/cons, how much of this type of behaviour we delegate to tools like Vulcanize and so on.
