### ISSUE TITLE
a rule for #drawerToolbar in application theme overrides default rule for element height

### ISSUE THREAD

**Issue by peterblazejewicz** [PolymerElements/polymer-starter-kit#170]
PSK 1.0.2

I had a problem when applying `tall` class to `paper-toolbar` in the drawer when adapting default template to other project. Just adding documented classes seemed to not change element dimensions.

It appears that application theme declares property for element height that simply overrides defaults:
- PSK:
https://github.com/PolymerElements/polymer-starter-kit/blob/master/app/styles/app-theme.html#L54
- `polymer-toolbar`:
https://github.com/PolymerElements/paper-toolbar/blob/master/paper-toolbar.html#L84

To use element classes as documented I had to remove that declaration from application theme rule. After this element uses the default height (the same 64px) but can be easily customized.

If that is OK, I could do PR,
Thanks!

**Comment by chuckh** [comment]
@peterblazejewicz makes sense to me to remove. The height: 64px is redundant. 

Current CSS:
```
  #drawerToolbar {
    color: var(--secondary-text-color);
    background-color: var(--drawer-menu-color);
    border-bottom: var(--drawer-toolbar-border-color);
    height: 64px;
  }
```

**Comment by peterblazejewicz** [comment]
@chuckh 
Thanks, I'll make a PR.
