### ISSUE TITLE
Can I have push access to this repo? Thanks.

### ISSUE THREAD

**Issue by blahblahartyfarty** [PolymerElements/polymer-starter-kit#173]
I would like to contribute with push access. Thanks @addyosmani.

**Comment by robdodson** [comment]
Hi @blahblahartyfarty, if you'd like to contribute the best way to do so is by opening pull requests. That way everyone can review the work before it gets merged in. We are only able to give push access to members of the Polymer team.

**Comment by blahblahartyfarty** [comment]
@robdodson I just asked because arthurvr was asked to in https://github.com/PolymerElements/polymer-starter-kit/commit/a87c51aa285847a0ab59f57fbf887950bc276982 so I thought I could contribute as well.

**Comment by addyosmani** [comment]
Commented on that committee but otherwise what Rob said :) PRs are the best way forward for contributing to the project.

**Comment by arthurvr** [comment]
> I thought I could contribute as well.

You really don't need push access to contribute to a project. Also it's pretty unusual that people explicitly ask for this and open an issue for such things :)
