### ISSUE TITLE
Improve Performance

### ISSUE THREAD

**Issue by JosefJezek** [PolymerElements/polymer-starter-kit#178]
- [ ] Use inline styles to reserve app “regions”.
- [ ] Vulcanize and crush the element bundles (excluding Polymer itself).
- [ ] Conditionally and async load the Web Components lite polyfill.
- [ ] Async load the element bundles. (This will also set up a race for Polymer itself).

https://aerotwist.com/blog/polymer-for-the-performance-obsessed/

**Comment by moderndeveloperllc** [comment]
Aren't one and two already being done with gulp? I for one _like_ to have all my elements loaded in one vulcanized page. Maybe I'm in the minority on that though.

**Comment by kenchris** [comment]
I think that #1 is interesting because it might not be so obvious for people how to do that in a nice way

**Comment by addyosmani** [comment]
Today, @ebidel showed us a different take on the lazy loading pattern from @paullewis that was based on ES6 promises. I'd be up for us getting behind a single solid pattern we can bake into PSK as a default.

**Comment by addyosmani** [comment]
> Async load the element bundles. (This will also set up a race for Polymer itself).

@wibblymat has been doing research into the state of `async` friendliness of Polymer elements this past week. I don't think we're quite at the point where we can include opinion on it here, but this should be possible for it in the not too distant future.

>  Conditionally and async load the Web Components lite polyfill.

See above.

> Vulcanize and crush the element bundles

We're exploring what better support for element bundles would look like in Vulcanize. I'm told this is WIP.

> Use inline styles to reserve app “regions”.

It would be trivial for us to set this up for the default paper-* based layout, but I'm wondering how useful baking this in will practically be. Every app is going to be different. Some folks will prefer to implement their own splash screens, others will prefer rendering an application scaffold. Let's keep thinking about the best way to integrate support for this.

**Comment by paullewis** [comment]
I have a tweak to my pattern that may bring it in-line with @ebidel's, but without some of its quirks. I reckon next week will get us there. We are close.

**Comment by addyosmani** [comment]
> I have a tweak to my pattern that may bring it in-line with @ebidel's, but without some of its quirks. I reckon next week will get us there.

:rocket:

**Comment by bppffnn** [comment]
JSperf is broken at the moment because @mathiasbynens so you can't test performance!!

**Comment by addyosmani** [comment]
We're going to start work on integrating performance patterns from 1.0.4 onwards, starting with async loading the Web Component polyfills. We may look at async loading the element bundles after that.

This is how Eric tackled this problems in his PolyMail app: https://github.com/ebidel/polymer-gmail/blob/master/scripts/app.js#L50

**Comment by moderndeveloperllc** [comment]
@addyosmani The only issue I would have with async polyfill loading is that it makes it very difficult to do any sort of versioning (gulp-rev - #230) or concatenation of the webcomponents.js file with other scripts (using gulp-useref) during the gulp build process. Just something to keep in mind.

**Comment by dandv** [comment]
I'm new to PSK but have installed all the popular PWAs (e.g. those in @addyosmani's blog post) on my corp Nexus 5X.

Zuperkulblog's time to paint (above the fold) is a lot slower (~2X - [video](https://youtu.be/Sn_tIelm7g0)) than Jake's Offline Wikipedia, or the Pokedex app. Is this intended (as a price to pay for the far simpler development), or part of the perf improvement?

**Comment by samccone** [comment]
Hi @dandv, there is 0 reason why a polymer app can not be as fast or faster than the examples you have listed. There is just a bit of work required to abstract the build process to make it approachable to developers using PSK.

The thing to consider with this project is the complexity cost to adding in the perf patterns. Right now the tools do not exist to do this in an approachable manner and it is very manual. (https://github.com/PolymerElements/polymer-starter-kit/blob/master/docs/polymer-perf.md)


Given that we know this is the state of the world; this is something that we are working towards improving and providing users with a direct path to building performant progressive webapps by default.

Checkout https://github.com/PolymerElements/polymer-starter-kit/issues/653 -- and thanks for asking :+1:

**Comment by robdodson** [comment]
@dandv zuperkulblog-progressive relies on h2 server push which is only available on app engine if you disable the `experimental quic` flag in Chrome. That's one of the ways I was getting improved paint times.

Check out codelabs.developers.google.com which is also built with Polymer and paints suuuuuper fast. It's using a new experimental feature called `body-bind` which doesn't hold up painting at all (though does require you to manually control FOUC). You can see a demo here: https://github.com/PolymerLabs/polymer-experiments/tree/master/body-bind  Body-bind is not in any way ready for prime time use but I wanted to share it to illustrate that we're actively working to improve this area.

**Comment by robdodson** [comment]
Going to close this as it relates mostly to PSK1 and we're now lazy loading polyfills and elements using the PRPL approach
