### ISSUE TITLE
small issues with the Apple touch icon

### ISSUE THREAD

**Issue by arthurvr** [PolymerElements/polymer-starter-kit#182]
Found two things regarding the touch icon:

* [We recommend to put `apple-touch-icon.png` in the root directory](https://github.com/PolymerElements/polymer-starter-kit/blob/master/app/index.html#L20) while it actually lives in `images/touch`. The [`<link>`](https://github.com/PolymerElements/polymer-starter-kit/blob/master/app/index.html#L40) is correct though.

* I always thought the logo was meant for a white background, while the icon is transparent and thus, looks like this on IOS:

![screenshot_17_06_15_14_09](https://cloud.githubusercontent.com/assets/6025224/8206604/5e23071c-14fb-11e5-83b0-ed5c74700d2a.png)

**Comment by arthurvr** [comment]
One more thing, we have:

```html
<meta name="apple-mobile-web-app-title" content="Polymer Starter Kit">
```

but that's actually pretty long. As seen on the screenshot above most iPhone's don't even display that fully.

**Comment by chuckh** [comment]
How about calling it `Polymer Start` or `Polymer SK` for  apple-mobile-web-app-title.

**Comment by arthurvr** [comment]
It's a placeholder anyways so PSK seems fine.

**Comment by chuckh** [comment]
PSK makes sense.

**Comment by arthurvr** [comment]
By the way, forgot to mention, I'll submit a PR to fix all of this :) (hopefully this evening)

**Comment by arthurvr** [comment]
Opened PRs to fix most of this. @addyosmani How would you like the icon? Simply on a white background?

**Comment by addyosmani** [comment]
On a white background makes sense to me. I've shared the PSK assets directory with you via GDrive.

**Comment by chuckh** [comment]
@arthurvr did you get a chance to create a PR to fix this?

**Comment by arthurvr** [comment]
@chuckh I fixed most of it except the image's background. Gonna give it another try this evening.

**Comment by arthurvr** [comment]
Finally! :wink:  #268

**Comment by chuckh** [comment]
LGTM!
