### ISSUE TITLE
responsiveWidth on paper-drawer-panel doesn't seem to work

### ISSUE THREAD

**Issue by mattbogado** [PolymerElements/polymer-starter-kit#189]
@addyosmani I'm trying to hide the drawer in tablets and up to 1600px, and the property `responsiveWidth` isn't working. Do you have any suggestions?

**Comment by notwaldorf** [comment]
If you're using it as an HTML attribute, it should be `responsive-width`. Does that help?

**Comment by mattbogado** [comment]
@notwaldorf  I tried that as well (forgot to add it to this issue), and it didn't work. I also tried `forceNarrow` and got nothing.

**Comment by addyosmani** [comment]
@mattbogado thanks for reporting. Just to check: what version of PSK are you using?

**Comment by mattbogado** [comment]
@addyosmani I'm using `polymer-starter-kit-light-1.0.2.zip`

**Comment by addyosmani** [comment]
Testing against latest this works fine for me:

![](http://i.imgur.com/M4ML8cL.png)

code:

```html
    <paper-drawer-panel id="paperDrawerPanel" responsive-width="1280px">
```

Closing this issue as works for me. If you're still running into this issue after testing against master, let us know and we'll reopen.
