### ISSUE TITLE
1.0 Starterkit (modest changed) works better in FF than in Chrome (menu missing) (W7)

### ISSUE THREAD

**Issue by tjsavage** [PolymerElements/polymer-starter-kit#192]
_From @EckhardSchoenknecht on June 6, 2015 3:32_

Hello World,
... from germany, new to github, sorry for all mistakes.

See screenshot below or try demo hier: sbiz.schoenknecht.biz
Changing some colors and menu points (routing) and the drawer on the right: Everthing works well under Ubuntu (Chrome & FF) but under W7 (64B) with latest Chrome the Hamburger menu on the right is missing. Really nice (in my case):

If you take the mouse and fumble on the right side of screen, you can acess the menu and pull it on screen. Sometimes you have to try more than once.

OK, same demo, second problem (or feature). This works well in Chrome, but in FF it`s strange:

Klicking once to a menu Point doesnt work. You have to cklick double (like Windows 3.11:-) to see some content matching the menu Point. That`s nice, but i fear not all customers will appreciate this feature.

Best regards
Eckhard
![sbizwithpolymer](https://cloud.githubusercontent.com/assets/12674973/8018161/4f1adf0c-0c0d-11e5-99d5-9f740c7b0191.jpg)

_Copied from original issue: Polymer/polymer#1763_

**Comment by tjsavage** [comment]
_From @kevinpschaaf on June 8, 2015 17:22_

Thanks for the issue!  This issue tracker is for the Polymer core library, not the starter kit or elements built with it. We'll get this moved to an appropriate spot.

**Comment by addyosmani** [comment]
@EckhardSchoenknecht could you verify if this is still an issue when using the version in Master?

**Comment by EckhardSchoenknecht** [comment]
Hello Addy Osmani,
please give me 24 hours and i will test this and send you reply and  
maybee a link to the new version online. Sorry for my bad english.
Regards
Eckhard


Zitat von Addy Osmani <notifications@github.com>:

**Comment by addyosmani** [comment]
No worries. 24 hours sounds great :) Thanks!

**Comment by EckhardSchoenknecht** [comment]
Zitat von Addy Osmani <notifications@github.com>:
> No worries. 24 hours sounds great :) Thanks!
allways worrying:
- Germany
- 55 years old
- no Programmer
- new to polymer


OK:

+ Hamburger Menu Problem is solved with master.

+ FF Problem with "double Click" in Drawer Menu on the right still  
exists, but:
   I found a behavior that you can reproduce.

If thats of Interest for you:

+ New Demo is here:
   http://2014.schoenknecht.biz/

+ All Infos are in an "Apache indexd Dir" here:
   http://2014.schoenknecht.biz/INFO/

   - one jpg with OS and "three evergreen Browser Infos" from today under W7
   - .txt with Problem description
   - if you like: 9 MB with the whole Projekt for download.

Many thanks and best regards from "Huzenbach/Germany": thats the  
blackwood forrest, yeah.

Eckhard

**Comment by robdodson** [comment]
Having to double click menu items was fixed in https://github.com/PolymerElements/polymer-starter-kit/pull/525 so I think we're all good here. Going to close.
