### ISSUE TITLE
Move license after `<!doctype html>`

### ISSUE THREAD

**Issue by alrra** [PolymerElements/polymer-starter-kit#193]
Usually it's bad practice to [have anything before `<!doctype html>`](https://github.com/PolymerElements/polymer-starter-kit/blob/ab15f6ed6e8228bf2feb06e684c9c9f345011785/app/index.html#L1-L10),  as:

> For IE 6, 7 and 8, the Doctype declaration should be the very first line of the HTML document, otherwise it defaults to quirks mode (An XML declaration before an XHTML Doctype or even having a HTML comment above the Doctype declaration will trigger quirks mode). In IE 7 and 8, having an XML declaration as the first line of the HTML document will no longer trigger quirks mode.

From: http://nimbupani.com/the-truth-about-doctypes.html

**Comment by arthurvr** [comment]
I think we should do that :+1: Don't think it was a real issue though, we don't support any of those browsers.

**Comment by arthurvr** [comment]
=> https://github.com/PolymerElements/polymer-starter-kit/pull/197
