### ISSUE TITLE
Header font changes on wrong class trigger

### ISSUE THREAD

**Issue by Inrego** [PolymerElements/polymer-starter-kit#194]
I noticed on the users / contact pages that when I scroll down, the header font gets smaller, but the header is still tall (1920x1080 resolution).
Before scrolling:
![](http://i.imgur.com/FbVuRxF.png)

After scrolling:
![](http://i.imgur.com/Fdj2yYh.png)

One could argue, that it may be a bug in the paper-header-panel, because it applies the class .has-shadow while it's still tall (or it might be intented behavior).

I am going to remove that explicit height of 900px, but I still wanted to fix this bug first.

Anyway - to the fix:
in app-theme.html line 101

Change

      #mainToolbar.has-shadow .middle {

to:

      #mainToolbar:not(.tall) .middle {

**Comment by chuckh** [comment]
This has been fixed in the master with 9e084cf86655a16646c2c5a15b76c5003cc3e255.

**Comment by addyosmani** [comment]
Fixed as of https://github.com/PolymerElements/polymer-starter-kit/commit/9e084cf86655a16646c2c5a15b76c5003cc3e255
