### ISSUE TITLE
Should this repo be moved to /Polymer?

### ISSUE THREAD

**Issue by ebidel** [PolymerElements/polymer-starter-kit#195]
Feels a bit weird it's in the element org. Thoughts? @addyosmani

**Comment by addyosmani** [comment]
Good question. This is a call for @tjsavage. He initially thought the elements org would be better but I'm fine with it living under here or /Polymer depending on what he thinks makes sense.

**Comment by SilverPaladin** [comment]
Since the PSK requires elements doesnt it make more sense to keep it with the elements?

**Comment by arthurvr** [comment]
I personally would expect all elements to live in /PolymerElements and all the rest in /Polymer but that's just my opinion.

> Since the PSK requires elements doesnt it make more sense to keep it with the elements?

Well, basically every Polymer related things will in some way be related to elements, you know :p

**Comment by SilverPaladin** [comment]
You dont need to use any of the pre built elements to use polymer...

**Comment by samccone** [comment]
We could move it, we could not, not sure there is a big win / loss here

cc @tjsavage for final call

-----

Going to close this as it is not really an "issue" but rather just a general question :)
