### ISSUE TITLE
Polymer and data binding in Safari with auto binding templates

### ISSUE THREAD

**Issue by alexkolson** [PolymerElements/polymer-starter-kit#199]
I'm developing an application inspired by the polymer-starter-kit layout, and everything's working except my data bound values, `{{route}}` and `{{user}}` are empty when stamped into the DOM in Safari. 

`routing.html`:

```html
<script src="page/page.js"></script>

<script>
    window.addEventListener('WebComponentsReady', function() {
        page('/', function() {
            app.route = 'home';
            app.user = 'Alex';
        });

        // Initialize router.
        page();
    });
</script>
```

`elements.html`:
```html
<link rel="import" href="iron-flex-layout/iron-flex-layout.html">
<!-- <link rel="import" href="iron-ajax/iron-ajax.html"> -->
<link rel="import" href="iron-pages/iron-pages.html">
<link rel="import" href="paper-material/paper-material.html">
<link rel="import" href="paper-header-panel/paper-header-panel.html">
<link rel="import" href="paper-toolbar/paper-toolbar.html">
<link rel="import" href="paper-styles/paper-styles-classes.html">
<link rel="import" href="routing.html">
<link rel="import" href="app-theme.html">
```

`index.html`:
```html
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="generator" content="BYU MFA Enrollment" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>BYU MFA Enrollment</title>

    <link rel="stylesheet" href="main.css">
    <script src="webcomponentsjs/webcomponents.min.js"></script>
    <link rel="import" href="elements.html">
</head>

<body unresolved class="fullbleed layout vertical">
    <template is="dom-bind" id="app">
        <paper-header-panel mode="waterfall-tall">
            <paper-toolbar id="mainToolbar">
                <div class="middle paper-font-display2">BYU MFA Enrollment</div>
            </paper-toolbar>
            <iron-pages attr-for-selected="data-route" selected="{{route}}">
                <section data-route="home">
                    <paper-material elevation="1">
                        <h3>Welcome to BYU MFA Enrollment! Lets get going <span>{{user}}</span>!</h3>
                    </paper-material>
                </section>
            </iron-pages>
        </paper-header-panel>
    </template>
</body>

</html>
```

Again, everything works just fine in Chrome but in Safari `{{route}}` and `{{user}}` are stamped into the DOM with empty values. 

I've noticed that the vanilla polymer starter kit data bindings work just fine in Safari so there must be something simple I am missing. What's going on in the different browsers and how to I craft my Polymer application to work in both?

Forgive me if this is not the correct place to ask this, if it is just let me know.

Thanks!

**Comment by alexkolson** [comment]
I tried replacing:
```html
<script src="webcomponentsjs/webcomponents.min.js"></script>
```

with:

```javascript
<script src="webcomponentsjs/webcomponents-lite.min.js"></script>
```
Voila! My data bindings started working in Safari! Which is strange to me, because if I understand correctly webcomponents-lite is just supposed to be a lightweight version of webcomponents.

Anyway, if anyone has a more in-depth explanation/answer, please post it as I really have no idea ***why*** this worked just that it ***worked***, and I'd much prefer to know why as well.

**Comment by addyosmani** [comment]
Hmm. We're currently referencing the lite version of the polyfills in https://github.com/PolymerElements/polymer-starter-kit/blob/master/app/index.html#L50. By default, you should get what eventually worked here. I think we would need to do some further debugging to understand why the full version of the polyfills (which include Shadow DOM) were failing here.

**Comment by addyosmani** [comment]
After getting the code supplied setup locally with the current version of PSK, I tried reproducing the issue you experienced. It looks like (at some point) if there was a discrepancy in how this was working with the wc.min.js build it's working fine now. Feel free to shoot us over a comment if you still find this to be an issue :)
