### ISSUE TITLE
What happened to paper-dropdown and paper-dropdown-menu ?

### ISSUE THREAD

**Issue by akhr** [PolymerElements/polymer-starter-kit#200]
https://www.polymer-project.org/0.5/components/paper-elements/demo.html#paper-dropdown 

I would like to create an dropdown menu on my page. The paper-dropdown was perfect for this purpose of creating a overflow menu button and a pop-up of menus show up onClick in the section of the screen where the overflow menu button is located. 

But in Polymer1.0, I could no longer find the dropdown menu. Any help will be appreciated.

**Comment by devAtPolydeals** [comment]
It's in progress see https://github.com/polymerelements/paper-elements

**Comment by addyosmani** [comment]
Closing as not specific to this project and @devAtPolydeals is correct per above.
