### ISSUE TITLE
Content not scrolling back after navigating

### ISSUE THREAD

**Issue by Felizardo** [PolymerElements/polymer-starter-kit#202]
Hello,

I have noticed that the content div does not scroll back after navigating to other sections of the example. See image below.

![polymer_starter_kit_not_scrolling_back](https://cloud.githubusercontent.com/assets/1034631/8274621/82950f14-186b-11e5-89b7-65e6fdb3de3c.gif)

I could reproduce that on my Mac using Chrome, Safari and Firefox, and also on Chrome in my Android Lollipop device.

**Comment by Felizardo** [comment]
FYI, a workaround is to comment the height attribute of .content on app-theme.html

**Comment by addyosmani** [comment]
@Felizardo Thanks for the bug report. Could you verify if this is still an issue on Master?

**Comment by Felizardo** [comment]
Hello @addyosmani, yes, I just made a clone right now and the problem persists.

**Comment by DannieBGoode** [comment]
Work around until it gets fixed:

setting manually document.getElementById("mainContainer").scrollTop = 0 will scroll back up.

**Comment by chuckh** [comment]
Pull Request #316 fixed this issue. See details of change at https://github.com/PolymerElements/polymer-starter-kit/pull/316/files.  It is in master branch now, it will be included in the next release 1.1.0 of Polymer Starter Kit.
