### ISSUE TITLE
Migrate from `paper-header-panel` to `paper-scroll-header-panel`

### ISSUE THREAD

**Issue by addyosmani** [PolymerElements/polymer-starter-kit#206]
From @blasten:
 
Starter kit currently uses `paper-header-panel`. The Polymer team is thinking about deprecating it and using `paper-scroll-header-panel` for the same use cases of `paper-header-panel`. We should switch over to it for PSK.

On the perf side, Paul Lewis (https://github.com/PolymerElements/paper-scroll-header-panel/issues/19) pointed out a performance issue that we currently have in `paper-header-panel`. However, scroll-header-panel is tested and proved to be fast and cover almost the same use cases as the header-panel.

I'm fine with us moving over.

**Comment by addyosmani** [comment]
I'll probably get to this one later in the week. cc'ing in @chuckh and @arthurevans in case either of you might be interested/have time to do this before I do.

**Comment by blasten** [comment]
great to know!

**Comment by chuckh** [comment]
@addyosmani I have done some experimenting with `paper-scroll-header-panel`. For migrating from `paper-header-panel` to `paper-scroll-header-panel` I believe we should keep same functionality we have now. So we would use the `keep-condensed-header` on `paper-scroll-header-panel`. Below is example of that. One issue I am running into when using a middle title it is not being condensed correctly.  It uses whatever's in  `<div class="bottom">Bottom Sub title</div>` instead of using title in `<div class="middle title">Middle Title</div>`.

![paper-scroll-header-panel-example](https://cloud.githubusercontent.com/assets/19915/8335346/f32eafea-1a51-11e5-8122-6386a0b8b41c.gif)

### Code excerpt for above example.
```
<paper-scroll-header-panel keep-condensed-header>
    <paper-toolbar class="tall">
      <paper-icon-button icon="arrow-back"></paper-icon-button>
      <div class="flex"></div>
      <paper-icon-button icon="search"></paper-icon-button>
      <paper-icon-button icon="more-vert"></paper-icon-button>
      <div class="middle title">Middle Title</div>
      <div class="bottom">Bottom Sub title</div>
    </paper-toolbar>

    <div class="content">
      <sample-content size="100"></sample-content>
    </div>
  </paper-scroll-header-panel>
```

Gist of entire code for example above.
https://gist.github.com/chuckh/9ec69609ae180c55ec8f

@addyosmani any thoughts?

**Comment by blasten** [comment]
@chuckh I will look into it.

**Comment by addyosmani** [comment]
> For migrating from paper-header-panel to paper-scroll-header-panel I believe we should keep same functionality we have now. So we would use the keep-condensed-header on paper-scroll-header-panel. 

This sounds reasonable to me. I appreciate you looking into it.

> One issue I am running into when using a middle title it is not being condensed correctly. It uses whatever's in <div class="bottom">Bottom Sub title</div> instead of using title in <div class="middle title">Middle Title</div>.

I was going to ping @blasten regarding this, but it would appear he's on top of it. Let's see what happens in https://github.com/PolymerElements/paper-scroll-header-panel/issues/25 :)

**Comment by chuckh** [comment]
Currently `paper-scroll-header-panel` does not support middle title. @blasten is looking into a enhancement for it.  So our choices are either use bottom title for now and migrate to `paper-scroll-header-panel` or wait for the enhancement.

When we migrate drawer `paper-scroll-header-panel` will need to be fixed.
```
<paper-drawer-panel id="paperDrawerPanel">
      <!-- <div drawer> -->
      <paper-scroll-header-panel drawer fixed>
```

And main will need to be this.

```
<paper-scroll-header-panel main condenses keep-condensed-header>
        <!-- Main Toolbar -->
        <paper-toolbar id="mainToolbar" class="tall">
```

Per @blasten from https://github.com/PolymerElements/paper-scroll-header-panel/issues/25
> In the examples, condensed headers seem to only work if the title is at the bottom. That's because scroll-header-panel only zooms in/out the title; in other words, it doesn't translate the title yet. 
I've been playing with some ideas to fix this. I guess we will also need to fade in/out the elements that aren't a title or the navigation items.

**Comment by chuckh** [comment]
@addyosmani @arthurvr  @blasten I created a working demo based on code @frankiefu provided.  This method has both the middle and bottom titles areas working. I plan to create a pull request for PSK using this method.  Take a look and let know what you all thing.

#### This is a gist of the code:
https://gist.github.com/chuckh/9729813fbfe0484da1ca

#### Example of how it works
![paper-scroll-header-panel-titles-transform](https://cloud.githubusercontent.com/assets/19915/8462863/6e3f1d52-1feb-11e5-91ae-8f5b4c1c4de3.gif)

**Comment by chuckh** [comment]
@addyosmani can't we close this now that #233 landed?

**Comment by addyosmani** [comment]
Yep!
