### ISSUE TITLE
Example of settings dialog

### ISSUE THREAD

**Issue by kenchris** [PolymerElements/polymer-starter-kit#207]
A lot of Android apps, have a separate settings dialog/pane - meaning a fullscreen dialog/pane which is on top of the whole app.

I emulate this in Polymer 0.5 using the dialog element and some /deep/ magic. As this is pretty common and not so obvious how to accomplish, I think that adding such a pane to the PSK would be useful

**Comment by addyosmani** [comment]
Thanks for the suggestion, @kenchris. One of the goals of the starter kit is to try delivering an opinionated, but minimal set of defaults that folks can use. The Android settings UX you describe sounds like something a few folks would use, but I don't expect every app, site or beginner project to use this. 

That said, we're considering adding some way to share PSK recipes for adding more functionality in the future and this type of thing would fit better there imo.

**Comment by kenchris** [comment]
Cool, that sounds great.

A lot of advanced apps usually have some settings or at least a place to send feedback or find more help. On web pages, this is often separate pages (or sometimes separate sites - like for some google services) but in a mobile app world these things are often done with overlay panes, which you exit by clicking back (keep people in the app).

I think it is quite useful to make this easy as well, as it is a good UX on mobile devices and something people will want with time.

I agree though, that it fits better as a PSK recipe.
