### ISSUE TITLE
Add example of how to use babel or other transpilers

### ISSUE THREAD

**Issue by kenchris** [PolymerElements/polymer-starter-kit#208]
As many are using transpilers today, it would be nice with a some easy integration. Especially with a watch that transpiles on change, such that the web server is actually using the transpiled files.

**Comment by Klathmon** [comment]
More than direct integration with one transpiler, i'd love a hook (or even a note in the documentation) where we can put a .pipe() and toss in whatever we want (babel, typescript, coffeescript, etc...)

**Comment by cnbuff410** [comment]
Babel would be a decent starting point though.

**Comment by addyosmani** [comment]
Imo, until Polymer has an official story around ES6, transpilation is something best covered in documentation or linking up to a repo demonstrating how to use Babel with Polymer Starter Kit.

**Comment by arthurvr** [comment]
Ref https://github.com/yeoman/generator-polymer/issues/181.

> mostly team meetings/internal discussions. Let me try to pull up a summary of notes for you this week.

@addyosmani still interested :)

**Comment by arthurvr** [comment]
> Imo, until Polymer has an official story around ES6, transpilation is something best covered in documentation or linking up to a repo demonstrating how to use Babel with Polymer Starter Kit.

Sounds good.

**Comment by samccone** [comment]
https://github.com/PolymerElements/polymer-starter-kit/blob/master/docs/add-es2015-support-babel.md

documented! Thanks all for the interest!
