### ISSUE TITLE
Start using GitHub Changelog Generator

### ISSUE THREAD

**Issue by chuckh** [PolymerElements/polymer-starter-kit#211]
@addyosmani we should consider using GitHub Changelog Generator to generate a change log for new releases. It is now being used for Polymer (see https://github.com/Polymer/polymer/commit/9a630e6a59bdcc313c74acf8842724c3eeb1956f).

https://github.com/skywinder/github-changelog-generator

### Example Change log created by GitHub Changelog Generator for Polymer Starter kit:

# Change Log

## [Unreleased](https://github.com/PolymerElements/polymer-starter-kit/tree/HEAD)

[Full Changelog](https://github.com/PolymerElements/polymer-starter-kit/compare/v1.0.2...HEAD)

**Implemented enhancements:**

- Moved \<script\> tags inside \<dom-module\> according to latest recommendations [\#155](https://github.com/PolymerElements/polymer-starter-kit/issues/155)

**Fixed bugs:**

- Application sub title does not work with waterfall-tall [\#158](https://github.com/PolymerElements/polymer-starter-kit/issues/158)

- Appname overlaps mainContainer [\#116](https://github.com/PolymerElements/polymer-starter-kit/issues/116)

**Closed issues:**

- What happened to paper-dropdown and paper-dropdown-menu ? [\#200](https://github.com/PolymerElements/polymer-starter-kit/issues/200)

- Header font changes on wrong class trigger [\#194](https://github.com/PolymerElements/polymer-starter-kit/issues/194)

- Move license after `\<!doctype html\>` [\#193](https://github.com/PolymerElements/polymer-starter-kit/issues/193)

- responsiveWidth on paper-drawer-panel doesn't seem to work [\#189](https://github.com/PolymerElements/polymer-starter-kit/issues/189)

- a rule for \#drawerToolbar in application theme overrides default rule for element height [\#170](https://github.com/PolymerElements/polymer-starter-kit/issues/170)

- Preprocessors support [\#165](https://github.com/PolymerElements/polymer-starter-kit/issues/165)

- Can we minify vulcanized file in the gulp sequence? [\#164](https://github.com/PolymerElements/polymer-starter-kit/issues/164)

- Peculiar problem with gulp [\#163](https://github.com/PolymerElements/polymer-starter-kit/issues/163)

- gulp does not copy non html files from new folders [\#160](https://github.com/PolymerElements/polymer-starter-kit/issues/160)

- How does the paper-menu work with on-iron-select? [\#159](https://github.com/PolymerElements/polymer-starter-kit/issues/159)

- \[FEATURE REQUEST\] CLI tool for initing starter kit [\#157](https://github.com/PolymerElements/polymer-starter-kit/issues/157)

- Layout fixed to forceNarrow [\#156](https://github.com/PolymerElements/polymer-starter-kit/issues/156)

- Docs: enumeration of steps does not make sense if there is only one [\#153](https://github.com/PolymerElements/polymer-starter-kit/issues/153)

- poymer-starter-kit-light for the creation of custom elements  [\#150](https://github.com/PolymerElements/polymer-starter-kit/issues/150)

- Avoid sending iron-ajax request if page is not active [\#149](https://github.com/PolymerElements/polymer-starter-kit/issues/149)

- navigation requires 2 clicks [\#141](https://github.com/PolymerElements/polymer-starter-kit/issues/141)

- Browser Sync Binding Breaks in Firefox [\#126](https://github.com/PolymerElements/polymer-starter-kit/issues/126)

- Issue running Polymer Started Kit 1.0.0 [\#110](https://github.com/PolymerElements/polymer-starter-kit/issues/110)

## [v1.0.2](https://github.com/PolymerElements/polymer-starter-kit/tree/v1.0.2) (2015-06-10)

[Full Changelog](https://github.com/PolymerElements/polymer-starter-kit/compare/v1.0.1...v1.0.2)

**Implemented enhancements:**

- Question about menu button [\#147](https://github.com/PolymerElements/polymer-starter-kit/issues/147)

- elements.html should be sorted alphabetically [\#109](https://github.com/PolymerElements/polymer-starter-kit/issues/109)

**Fixed bugs:**

- forceNarrow should be force-narrow [\#132](https://github.com/PolymerElements/polymer-starter-kit/issues/132)

- Wrong indentation for hamburger menu [\#117](https://github.com/PolymerElements/polymer-starter-kit/issues/117)

- Gulp serve doesn't properly watch changes to .css files [\#92](https://github.com/PolymerElements/polymer-starter-kit/issues/92)

**Closed issues:**

- gulp builds with webcomponents.min.js instead of webcomponents-lite.min.js [\#143](https://github.com/PolymerElements/polymer-starter-kit/issues/143)

- Move app-theme.html to styles dir [\#139](https://github.com/PolymerElements/polymer-starter-kit/issues/139)

- app directory missing in .bowerrc [\#133](https://github.com/PolymerElements/polymer-starter-kit/issues/133)

- Recommended update procedure? [\#131](https://github.com/PolymerElements/polymer-starter-kit/issues/131)

- Remove .bowerrc [\#125](https://github.com/PolymerElements/polymer-starter-kit/issues/125)

- Error: spawn ENOENT after running gulp [\#122](https://github.com/PolymerElements/polymer-starter-kit/issues/122)

- Listening for template-bound event is obsolete [\#113](https://github.com/PolymerElements/polymer-starter-kit/issues/113)

- 1.0.1 failing to load resources [\#112](https://github.com/PolymerElements/polymer-starter-kit/issues/112)

- Issue when running gulp serve on polymer-starter-kit 1.0.1 [\#105](https://github.com/PolymerElements/polymer-starter-kit/issues/105)

- Remove unneeded removal of `unresolved` [\#103](https://github.com/PolymerElements/polymer-starter-kit/issues/103)

## [v1.0.1](https://github.com/PolymerElements/polymer-starter-kit/tree/v1.0.1) (2015-06-02)

[Full Changelog](https://github.com/PolymerElements/polymer-starter-kit/compare/v1.0.0...v1.0.1)

**Fixed bugs:**

- \#mainToolbar text placement prevents hamburger menu from working on scroll [\#75](https://github.com/PolymerElements/polymer-starter-kit/issues/75)

**Closed issues:**

- Failed at the polymer-starter-kit@0.0.0 deps script 'npm install -g gulp && npm install -g bower && npm install && bower install'. [\#99](https://github.com/PolymerElements/polymer-starter-kit/issues/99)

- Where's "Web App Install Banner"? [\#95](https://github.com/PolymerElements/polymer-starter-kit/issues/95)

- Duplicated lower bound for desktop x-large media query in the application theme [\#85](https://github.com/PolymerElements/polymer-starter-kit/issues/85)

- Polymer starter kit with cca  [\#83](https://github.com/PolymerElements/polymer-starter-kit/issues/83)

- Script src to page.js in routing fails in windows [\#82](https://github.com/PolymerElements/polymer-starter-kit/issues/82)

- Problem with example template autobinding snippets [\#74](https://github.com/PolymerElements/polymer-starter-kit/issues/74)

- Router [\#73](https://github.com/PolymerElements/polymer-starter-kit/issues/73)

- Incorrect GitHub link on homepage [\#70](https://github.com/PolymerElements/polymer-starter-kit/issues/70)

- Windows not supported? [\#69](https://github.com/PolymerElements/polymer-starter-kit/issues/69)

- errors installing dependencies, debug log below [\#68](https://github.com/PolymerElements/polymer-starter-kit/issues/68)

## [v1.0.0](https://github.com/PolymerElements/polymer-starter-kit/tree/v1.0.0) (2015-05-29)

[Full Changelog](https://github.com/PolymerElements/polymer-starter-kit/compare/v0.1.1...v1.0.0)

## [v0.1.1](https://github.com/PolymerElements/polymer-starter-kit/tree/v0.1.1) (2015-05-13)

[Full Changelog](https://github.com/PolymerElements/polymer-starter-kit/compare/v0.1.0...v0.1.1)

## [v0.1.0](https://github.com/PolymerElements/polymer-starter-kit/tree/v0.1.0) (2015-05-12)

\* *This Change Log was automatically generated by [github_changelog_generator](https://github.com/skywinder/Github-Changelog-Generator)*

**Comment by arthurvr** [comment]
Nah. No thanks. It complicates the workflow for both contributors and for us, and there's no clear need for this here atm.

Also, as with a boilerplate/starter kit you don't have to worry about breaking changes like in frameworks the changelogs make way less sense.

There are advantages to actually writing it yourself (like emphasising specific things and leaving away unimportant things).

**Comment by chuckh** [comment]
@arthurvr I can see your points. My thought this would be used in addition to the release notes not replace them. It is pretty simple to use. Contributors would not need to do anything. The github_changelog_generator command would just need to be done before creating a new release by us.

**Comment by arthurvr** [comment]
Leaving the decision up to @addyosmani but I don't think they add any value for us, honestly.

**Comment by addyosmani** [comment]
I had no idea this was a thing. I appreciate the ping about it. I'll review the solution to see if it offers value, but we may end up sticking with the light-weight process we have atm for release notes. Assigning self.

**Comment by chuckh** [comment]
Sounds good. Thought it was worth consideration. I could go either way.
