### ISSUE TITLE
use npm start do start gulp serve

### ISSUE THREAD

**Issue by ukkieanna** [PolymerElements/polymer-starter-kit#212]
as npm test

**Comment by arthurvr** [comment]
I personally don't use `npm start` much but why not. I'm opening a PR.

**Comment by ukkieanna** [comment]
yes that will be good

**Comment by addyosmani** [comment]
Thanks for the PR, @arthurvr. I'm going to keep this one open to see if there's broader interest in npm script tasks like this landing.

**Comment by jorin-vogel** [comment]
I just added `"start": "gulp"` to my `package.json`.
This way I don't need gulp installed globally and to run a gulp task like _serve_ I just run `npm start serve`.
I don't know if this is too confusing. I would also be happy with the more specific version of the npm scripts.

**Comment by arthurvr** [comment]
> It's nice if I don't need gulp installed globally. 

Yep.

> To run a gulp task like serve I just run npm start serve.

That looks a little strange imho. Most apps just boot at `npm start`. 

> However, it requires to have bower in devDependencies (npm install --save-dev bower).

I'm not sure about this one. Do consider that bower is quite a big dependency.
