### ISSUE TITLE
You cannot package apps made with PSK with manifoldjs.com due to missing image sizes

### ISSUE THREAD

**Issue by kenchris** [PolymerElements/polymer-starter-kit#218]
WARNING: Manifest validation  (Android) - Launcher icons of the following sizes are required: 48x48, 72x72, 96x96, 144x144, 192x192, 512x512[icons]

Whether these should be required is of course up to discussion. If you believe that some of these sizes are not needed, please file an issue at https://github.com/manifoldjs/ManifoldJS/issues

**Comment by robdodson** [comment]
Hm so we're missing:

- 72x72
- 96x96
- 512x512

It's easy enough for us to add these I guess but it's also not hard for the dev to make them themselves. I'm curious what the rest of the team thinks? @kenchris do you know if these need any special filenames or can we just call them icon-72x72?

**Comment by kenchris** [comment]
cc'ing @boyofgreen (from Manifoldjs).

The filename should not matter - what matters are the entries in the manifest file.

**Comment by boyofgreen** [comment]
yea @kenchris is right. It's not that they can't get all the image sizes, it's just that they don't.  If you think we are requiring too many let me know, we just want to make sure it looks good on all phones.  We should do a blog post on building with the polymer starter kit then deploying with manifoldjs.  Let me know if our interested.

**Comment by addyosmani** [comment]
Quick notes from me if this helps:

* In most of my apps I end up using realfavicongenerator.net. We can either commit static files or try to generate our icons with realfavicongenerator so it's easy enough to copy/paste replacements. 
* There's a Node module we could use to generate the icons (https://github.com/haydenbleasel/favicons) but in other projects (like Web Starter Kit), we've decided to just opt for static files being committed as this encourages folks to spend more time manually crafting the best looking icons for their projects. In practice, this doesn't really happen though. 
* Perhaps just manually commit for now? Adding things to the build process is something we're trying to avoid atm.

**Comment by robdodson** [comment]
Addressed here https://github.com/PolymerElements/polymer-starter-kit/pull/623
