### ISSUE TITLE
paper-drawer-panel narrow layout question

### ISSUE THREAD

**Issue by Stefdv** [PolymerElements/polymer-starter-kit#220]
If i just use 

< paper-drawer-panel  force-narrow>

        <div drawer>
          <paper-toolbar>
           <span>Drawer</span>
          </paper-toolbar>
        </div>
        <div main>
          <paper-toolbar>
            <paper-icon-button icon="menu" paper-drawer-toggle></paper-icon-button>
          </paper-toolbar>
        </div>
    </paper-drawer-panel>

then when i open the drawer, the main div is shining tru. ( everything has a background-color )
Only when i use a paper-header-panel it works...but i don't need that

**Comment by addyosmani** [comment]
Do you have a screenshot or demo you can link us to that could help visualise the problem you're running into a little better?

**Comment by Stefdv** [comment]
I don't have a place to host a demo, i use polymer in nw.js ( former node-webkit) applications.  I do not use webcomponentsjs.js.
My index.html is like i stated above, every element is loaded. Polymer is ready..
I hope these screenshots show my problem.
![01](https://cloud.githubusercontent.com/assets/890650/8396666/9a990f72-1daf-11e5-8189-1b48d3492a7a.jpg)
![02](https://cloud.githubusercontent.com/assets/890650/8396667/9da0b2ba-1daf-11e5-9e14-825c898456b9.jpg)
![03](https://cloud.githubusercontent.com/assets/890650/8396668/a038e81c-1daf-11e5-8437-7be03e9aed81.jpg)

**Comment by Stefdv** [comment]
Don't know why i closed it...

**Comment by robdodson** [comment]
I'm not seeing this issue with the current release when I replace `paper-scroll-header-panel` with divs for `drawer` and `main`.

<img width="694" alt="screen shot 2015-12-19 at 7 28 58 am" src="https://cloud.githubusercontent.com/assets/1066253/11913706/3fb2725a-a622-11e5-8ffd-f459a45eb99a.png">

However, if you're going to replace the header panels you do need to update your javascript in two places. 

In `app.js`, comment out this block:

```js
// Scroll page to top and expand header
  app.scrollPageToTop = function() {
     app.$.headerPanelMain.scrollToTop(true);
   };
```

And in `elements/routing.html` comment out the `scrollToTop` middleware

```js
// Middleware
    function scrollToTop(ctx, next) {
      app.scrollPageToTop();
      next();
    }
```

and remove it from the `*` route

```js
// Routes
    page('*', scrollToTop, closeDrawer, function(ctx, next) {
      next();
    });
```
