### ISSUE TITLE
Include project's name in the local dev URL

### ISSUE THREAD

**Issue by jeffposnick** [PolymerElements/polymer-starter-kit#221]
As a bit of a hacky approach to ensuring that multiple local projects don't inadvertently share a service worker, we can consider configuring the local dev web server so that it included the project's (directory) name in the URL path. Since that path is used when constructing the service worker scope, it would mean that service worker scoping would work as intended.

This has the drawback of the path prefixes used during the development phase not matching the likely path prefixes that will be used during the production deployments.

This may or may not be sufficient to work around some of the concerns raised in https://github.com/PolymerElements/polymer-starter-kit/issues/80

CC: @wibblymat @addyosmani

**Comment by addybd** [comment]
:+1:

**Comment by addyosmani** [comment]
> This has the drawback of the path prefixes used during the development phase not matching the likely path prefixes that will be used during the production deployments.

I have concerns folks are going to trip over this step often when switching to deployment, but it may be something we can work around with good documentation.

It may be worth us implementing the proposal in a branch and testing out whether  the user-effort for deployment is negligible enough to land it as a default.

**Comment by jeffposnick** [comment]
Trying to get browserSync, the middleware, and the routing library happy with a fake top-level path led to a dead end when I looked into this.

I'm thinking of an alternative approach in which a different port is used for dev/dist and the cache name is read from a config file. See https://github.com/PolymerElements/platinum-sw/pull/52 for the first steps.
