### ISSUE TITLE
Licensing projects made with PSK

### ISSUE THREAD

**Issue by flaiker** [PolymerElements/polymer-starter-kit#227]
As of now most files in the starter kit contain a license header and there is also a [LICENSE.md](https://github.com/PolymerElements/polymer-starter-kit/blob/master/LICENSE.md) in the repository's root. I am wondering how I should act in the following scenario:
- I want to make a web application based on PSK as a starting point (as intented)
- I want to publish that work
- I want to license it
  - With either no license (Copyright by ...) or
  - With a specified license

How can one distinguish between the code authored "by the Polymer authors" and the adjustments I made? Do I need to remove or modify the file headers / am I even allowed to? How do I go about new files? Do I need to think about license compatibility?

Poke @addyosmani

**Comment by arthurvr** [comment]
I always thought getting rid of the license headers in your projects is fine. Might be wrong though. 

Let's hope we can just get rid of some license headers (ref https://github.com/yeoman/generator-polymer/issues/202) If we can't, those are all really valid questions and we might want to document these points.

**Comment by addyosmani** [comment]
I spoke to the open-source team about this today. I'm waiting on some clarifications but will update this thread and add a note to the README as soon as I've got the final word from them. Sorry for the delay! Lawyercats to blame :)

**Comment by bppffnn** [comment]
My company told me I can't use polymer start kit because of this issue

**Comment by flaiker** [comment]
Any update on this?

**Comment by Frikki** [comment]
I raised a similar question to Rob Dodsen, Design Technologist and Writer at Google, regarding Polymer.

> Under which copyright and license am I allowed to publish a Polymer app; what do I have to pay attention to? Also, when I use the Starter Kit as my project structure, am I allowed to delete the license banners or do they have to stay?

And Rob’s answer:

>  You'll need to leave the license headers in the source files. But you may add your own extensions to license code you've written.
>
> You can remove the big license text that's inside the paper-material element on the first page,

**Comment by Download** [comment]
Actually, I think BSD license allows redistibution under different license as well?

Asking people to keep the license headers of the Starter Kit intact forever sounds unreasonable to me...

**Comment by arthurvr** [comment]
@addyosmani Any update on this?

> Asking people to keep the license headers of the Starter Kit intact forever sounds unreasonable to me...

Yes, I agree. Though it's up to the Lawyercats.

**Comment by arthurvr** [comment]
@addyosmani Do you have any updates on this one? I can imagine this being a big problem for some users.

**Comment by addyosmani** [comment]
Thanks for the reminder @arthurvr. 

The update I got from the Google open-sourcing team was that the license headers currently in the project need to stay in tact as is, but that (as relayed to Rob) your own custom licensing information can be appended to this. 

I'm a little disappointed by this and can completely sympathise with any frustration folks would have with this. Lawyercats have the final say I'm afraid :/
It's probably worth us documenting this in the project README so we're super clear about it. I would have had similar questions if it was another project.

**Comment by arthurvr** [comment]
Wow, that's pretty stupid. But thanks for the update, Addy!

**Comment by Download** [comment]
This makes using Polymer Starting Kit impossible for a lot of users. A lot of licenses are just not compatible with BSD license.

> Lawyercats have the final say I'm afraid

The owners of the copyright (authors or companies they work for) can choose whatever they want. Blaming this on 'the lawyercats' is just not fair. This is a decision that the original authors make.

**Comment by timblack1** [comment]
Does Google's copyright notice make it impossible for me to legally 1) distinguish and 2) copyright my own work in the same file?

**Comment by robdodson** [comment]
My understanding is that you can add your own licenses after the Google licenses to copyright the work you've added. But I am unfortunately not a legal expert :\ @addyosmani any thoughts on this?

**Comment by addyosmani** [comment]
I'll update the FAQ now to include the latest OSS team answer on this.
