### ISSUE TITLE
Loading Route Directly

### ISSUE THREAD

**Issue by PaulHMason** [PolymerElements/polymer-starter-kit#229]
I'm playing around with the starter kit (lite version) and can't get the navigation to work properly (using page,js). The back/forward buttons work correctly but if I try to navigate directly to a route, e.g. 

http://localhost/myapp/#!/mypage

It just loads the default page/route.

How should I set up the default route (./) and alternative navigate directly to a route if specified in the url.

Thanks

**Comment by arthurvr** [comment]
Thanks for the bug report. What browser and OS were you using? I doubt it matters but just in case.

> The back/forward buttons work correctly but if I try to navigate directly to a route, e.g.
> 
> http://localhost/myapp/#!/mypage
> 
> It just loads the default page/route.

Hmm, that's weird. Mind telling us how you setup the route? Some code for us to look at would be handy. 



> How should I set up the default route (./)

Here: https://github.com/PolymerElements/polymer-starter-kit/blob/master/app/elements/routing.html#L18 ;)

**Comment by arthurvr** [comment]
> Mind telling us how you setup the route? Some code for us to look at would be handy.

Friendly ping @PaulHMason.

**Comment by chuckh** [comment]
@PaulHMason have you tried the latest Polymer Starter Kit version 1.1.1 (https://github.com/PolymerElements/polymer-starter-kit/releases)? I just tested and it worked ok for me. I was able to go directly to routes like `http://localhost:8080/#!/users/Rob`.

Also did you change to the app folder before running `python -m SimpleHTTPServer 8080`?

**Comment by chuckh** [comment]
@PaulHMason I am going to close for now since it looks like it is working. If you have any more questions or problems with this issue please reopen.
