### ISSUE TITLE
[Enhancement] Use gulp-rev and gulp-rev-replace for versioning

### ISSUE THREAD

**Issue by moderndeveloperllc** [PolymerElements/polymer-starter-kit#230]
To take best advantage of client caching, servers should set their Expires headers to something pretty far out (1 month+) for CSS and JS files. With a full front-end build process, this means that you can do that with *.html files too. Especially helpful for something like the vulcanized elements. The easiest way to do this is with [gulp-rev](https://www.npmjs.com/package/gulp-rev) and [gulp-rev-replace](https://www.npmjs.com/package/gulp-rev-replace). This will create md5 hash based file names like `styles-666bae72.css` that will bust cache when the content changes.

I did this by breaking up the vulcanize task, but I'm sure others could do it better than I. index.html would need to be a special case, unless an `.htaccess` file were added to the `dist/` folder to rewrite requests for `index.html` to something like `index-23452abc.html`

**Comment by arthurvr** [comment]
> I did this by breaking up the vulcanize task, but I'm sure others could do it better than I. index.html would need to be a special case, unless an .htaccess file were added to the dist/ folder to rewrite requests for index.html to something like index-23452abc.html

IMHO, it's better for PSK to stay unopinionated about server-side tooling.

**Comment by moderndeveloperllc** [comment]
@arthurvr True, so either *.html would not be versioned, or index.html would be an exception to that.

**Comment by addyosmani** [comment]
Imo @arthurvr is right here. I think we should stay focused and trim where possible and keeping unopinionated about SS tooling helps us with that. 

cc @jeffposnick as an FYI about this as we had discussed revving briefly as part of one of many possible strategies for improving our Service Worker setup, but all of that is very much in the design phase atm.

**Comment by moderndeveloperllc** [comment]
@addyosmani Do you have a preference as to whether elements.vulcunized.html should be versioned or not? If it's not versioned, then you are depending on server software to not be caching it.

**Comment by moderndeveloperllc** [comment]
@addyosmani I'll hold off on doing any of this till after y'all decide on polybuild or not. I'm guessing this can either be an additional command like `default:versioned`, or just a comment like `precache` is now.

**Comment by moderndeveloperllc** [comment]
Perhaps it would be best if this were a recipie like implementing ES2015. That way reccomendations can be made regarding how to integrate asset revisioning without poluting the code.

**Comment by robdodson** [comment]
I think creating a recipe for this is a good call. Any volunteers? :grinning:

**Comment by robdodson** [comment]
Closing this as a PSK issue now that we're using Polymer CLI.

There's discussion on how to tackle this in CLI going on here: https://github.com/Polymer/polymer-cli/issues/283

If the decision comes down to needing to add your own gulp task then folks should be able to add gulp-rev to https://github.com/PolymerElements/generator-polymer-init-custom-build
