### ISSUE TITLE
question on deploying kit

### ISSUE THREAD

**Issue by hazourano** [PolymerElements/polymer-starter-kit#234]
how do i deploy as a node app in heroku?

**Comment by addyosmani** [comment]
It's quite similar to the deployment process for apps built using other modern Node/Gulp tooling. See https://github.com/yeoman/generator-gulp-webapp/blob/master/docs/recipes/gh-pages.md for deployment instructions to gh-pages and http://stackoverflow.com/questions/24504476/how-to-deploy-node-that-uses-gulp-to-heroku. We'll do our best to document deployment best practices in the not too distant future.
