### ISSUE TITLE
IE11 Menu item alignment issue.

### ISSUE THREAD

**Issue by PaulHMason** [PolymerElements/polymer-starter-kit#235]
Just a minor styling issue - the children (iron-icon and span) of the menu anchor tags aren't centered in IE11 (fine in Chrome and Firefox).

![polymer_menu](https://cloud.githubusercontent.com/assets/1944711/8501407/5d2cb13a-21a5-11e5-9a3d-bf51df3f89bc.png)

**Comment by addyosmani** [comment]
Last I tested in Edge this was rendering as expected against master. Closing. Thanks.
