### ISSUE TITLE
routing.html page callbacks not called in iOS

### ISSUE THREAD

**Issue by kenjitayama** [PolymerElements/polymer-starter-kit#237]
How to reproduce

1. Download Starter Kit 1.0.2 or git clone the latest.

1. Edit routing.html and add these two cosole.log

		window.addEventListener('WebComponentsReady', function() {

		console.log('WebComponentsReady!');

		// We use Page.js for routing. This is a Micro
		// client-side router inspired by the Express router
		// More info: https://visionmedia.github.io/page.js/
		page('/', function () {
		  app.route = 'home';
		});

		page('/users', function () {
		  console.log('page users');
		  app.route = 'users';
		});

1. npm install && bower install

1. gulp serve

1. Browse to Users page from the drawer

The two logs are displayed in Mac Chrome/Safari but only the `WebComponentsReady!` is displayed in iOS 8.4 Safari (Confirmed by connecting from Mac Safari).
I asked my friend who has a Android to try it out, and looks like it's not called in Android too.

I'm creating a element for each page(contents of section tag), and I want to notify them when selected.
I'm doing something like the following, but it doesn't get called in iOS.

	document.querySelector('app-page-users').didShow(); // didShow is a manually implemented function

If this is a known issue due to browser compatibility, are there any work arounds for notifying my elements?

**Comment by addyosmani** [comment]
I'll test this out on iOS and get back to you. Afaik, this should be working without issue.

**Comment by kenjitayama** [comment]
Thanks!
I need this for loading data from the server at that timing.

**Comment by kenjitayama** [comment]
I'd like to share a workaround that I came up with, although not ideal.

index.html
```
<section data-route="users">
  <app-page-users selected-page="[[route]]"></app-page-users>
</section>
```

AppPageBehavior.js (used in element app-page-users.html)
```
/* exported AppPageBehavior */
var AppPageBehavior = {
  properties: {
    selectedPage: {
      type: Boolean,
      observer: '_selectedPageChanged'
    }
  },

  _selectedPageChanged: function(newValue, oldValue) {

    var routeName = this.routeName;

    if (oldValue !== routeName && newValue === routeName) {
      if (typeof this._didAppear === 'function') {
        this._didAppear();
      }
    }

    if (oldValue === routeName && newValue !== routeName) {
      if (typeof this._didDisappear === 'function') {
        this._didDisappear();
      }
    }
  }
};
```

Not a good design because pages themselves should not be responsible for knowing which route is selected. But it works.
And anyway, my previous method couldn't do something like a  `didDisappear`.

**Comment by kenjitayama** [comment]
@addyosmani 
I've tracked down the problem to some extent.

1. I found out it wasn't reproducing sometimes, but quickly selecting the menu in the drawer(each time closing) always reproduces the problem.
2. Commenting out paper-menu and adding the following onclicks fixes the problem(althogh corrupting the design).

		
		  <a data-route="home" href="/" onclick="app.onMenuSelect();">
		    <iron-icon icon="home"></iron-icon>
		    <span>Home</span>
		  </a>

		  <a data-route="users" href="/users" onclick="app.onMenuSelect();">
		    <iron-icon icon="info"></iron-icon>
		    <span>Users</span>
		  </a>

		  <a data-route="contact" href="/contact" onclick="app.onMenuSelect();">
		    <iron-icon icon="mail"></iron-icon>
		    <span>Contact</span>
		  </a>
		

My guess is that some event for paper-menu is preventing the callbacks of page.js from being called.

**Comment by kenjitayama** [comment]
@addyosmani Pull requested a solution :)

**Comment by addyosmani** [comment]
Thanks for the PR!

**Comment by chuckh** [comment]
@kenjitayama thanks for the PR. I tested this on iOS and on desktop Chrome. It fixes this issue but:

1. If you right click on the menu item to open in new tab it takes you to a blank page
2. If you hover of the menu item it shows  `javascript:void(0)` as the link instead of `localhost:3000/ or localhost:3000/users` etc.

## Another possible solution is to:

remove  `on-iron-select="onMenuSelect"`
`<paper-menu class="list" attr-for-selected="data-route" selected="[[route]]">`

add ` on-click="onMenuSelect"` to
`<a data-route="home" href="/" on-click="onMenuSelect">`
`<a data-route="users" href="/users" on-click="onMenuSelect">`
`<a data-route="contact" href="/contact" on-click="onMenuSelect">`

Keep the original app.onMenuSelect code

```
app.onMenuSelect = function() {
    var drawerPanel = document.querySelector('#paperDrawerPanel');
    if (drawerPanel && drawerPanel.narrow) {
      drawerPanel.closeDrawer();
    }
  };
```

This fixes the problem, plus hovering and right clicking to new tab works too.

_Note on-tap does not fix the problem._

_If we go with this approach we may want to rename `onMenuSelect` to `onDataRouteClick`._

cc: @addyosmani

**Comment by kenjitayama** [comment]
@chuckh 
I tried your solution, and worked perfectly!

> If we go with this approach we may want to rename onMenuSelect to onDataRouteClick

Rename looks good to me too.

Thanks for the solution!
PSK is helping me build my app a lot!

cc: @addyosmani

**Comment by addyosmani** [comment]
We landed a fix for this in https://github.com/PolymerElements/polymer-starter-kit/pull/256 which successfully does the trick.
