### ISSUE TITLE
Browsersync conflicts with socket.io

### ISSUE THREAD

**Issue by jenyckee** [PolymerElements/polymer-starter-kit#241]
I have a project where I want to do socket communication. So I adapted the gulp file and serve with nodemon and my own express server + socket.io. I let browsersync watch the files in the app folder and everything works fine however it seems that socket.io is conflicting with the browswersync socket.io connection. I keep getting a "Connection closed before receiving a handshake response" error on the client.

**Comment by addyosmani** [comment]
Could you share the adapted gulpfile so we can take a look?

**Comment by jenyckee** [comment]
'use strict';

    // Include Gulp & Tools We'll Use
    var gulp = require('gulp');
    var nodemon = require('gulp-nodemon');

    var $ = require('gulp-load-plugins')();
    var del = require('del');
    var runSequence = require('run-sequence');
    var browserSync = require('browser-sync');
    var reload = browserSync.reload;
    var merge = require('merge-stream');
    var path = require('path');
    var fs = require('fs');
    var glob = require('glob');

    var AUTOPREFIXER_BROWSERS = [
      'ie >= 10',
      'ie_mob >= 10',
      'ff >= 30',
      'chrome >= 34',
      'safari >= 7',
      'opera >= 23',
      'ios >= 7',
      'android >= 4.4',
      'bb >= 10'
    ];

    var styleTask = function (stylesPath, srcs) {
      return gulp.src(srcs.map(function(src) {
          return path.join('app', stylesPath, src);
        }))
        .pipe($.changed(stylesPath, {extension: '.css'}))
        .pipe($.autoprefixer(AUTOPREFIXER_BROWSERS))
        .pipe(gulp.dest('.tmp/' + stylesPath))
        .pipe($.if('*.css', $.cssmin()))
        .pipe(gulp.dest('dist/' + stylesPath))
        .pipe($.size({title: stylesPath}));
    };

    // Compile and Automatically Prefix Stylesheets
    gulp.task('styles', function () {
      return styleTask('styles', ['**/*.css']);
    });

    gulp.task('elements', function () {
      return styleTask('elements', ['**/*.css']);
    });

    // Lint JavaScript
    gulp.task('jshint', function () {
      return gulp.src([
          'app/scripts/**/*.js',
          'app/elements/**/*.js',
          'app/elements/**/*.html'
        ])
        .pipe(reload({stream: true, once: true}))
        .pipe($.jshint.extract()) // Extract JS from .html files
        .pipe($.jshint())
        .pipe($.jshint.reporter('jshint-stylish'))
        .pipe($.if(!browserSync.active, $.jshint.reporter('fail')));
    });

    // Optimize Images
    gulp.task('images', function () {
      return gulp.src('app/images/**/*')
        .pipe($.cache($.imagemin({
          progressive: true,
          interlaced: true
        })))
        .pipe(gulp.dest('dist/images'))
        .pipe($.size({title: 'images'}));
    });

    // Copy All Files At The Root Level (app)
    gulp.task('copy', function () {
      var app = gulp.src([
        'app/*',
        '!app/test',
        '!app/precache.json'
      ], {
        dot: true
      }).pipe(gulp.dest('dist'));

      var bower = gulp.src([
        'bower_components/**/*'
      ]).pipe(gulp.dest('dist/bower_components'));

      var elements = gulp.src(['app/elements/**/*.html'])
        .pipe(gulp.dest('dist/elements'));

      var swBootstrap = gulp.src(['bower_components/platinum-sw/bootstrap/*.js'])
        .pipe(gulp.dest('dist/elements/bootstrap'));

      var swToolbox = gulp.src(['bower_components/sw-toolbox/*.js'])
        .pipe(gulp.dest('dist/sw-toolbox'));

      var vulcanized = gulp.src(['app/elements/elements.html'])
        .pipe($.rename('elements.vulcanized.html'))
        .pipe(gulp.dest('dist/elements'));

      return merge(app, bower, elements, vulcanized, swBootstrap, swToolbox)
        .pipe($.size({title: 'copy'}));
    });

    // Copy Web Fonts To Dist
    gulp.task('fonts', function () {
      return gulp.src(['app/fonts/**'])
        .pipe(gulp.dest('dist/fonts'))
        .pipe($.size({title: 'fonts'}));
    });

    // Scan Your HTML For Assets & Optimize Them
    gulp.task('html', function () {
      var assets = $.useref.assets({searchPath: ['.tmp', 'app', 'dist']});

      return gulp.src(['app/**/*.html', '!app/{elements,test}/**/*.html'])
        // Replace path for vulcanized assets
        .pipe($.if('*.html', $.replace('elements/elements.html', 'elements/elements.vulcanized.html')))
        .pipe(assets)
        // Concatenate And Minify JavaScript
        .pipe($.if('*.js', $.uglify({preserveComments: 'some'})))
        // Concatenate And Minify Styles
        // In case you are still using useref build blocks
        .pipe($.if('*.css', $.cssmin()))
        .pipe(assets.restore())
        .pipe($.useref())
        // Minify Any HTML
        .pipe($.if('*.html', $.minifyHtml({
          quotes: true,
          empty: true,
          spare: true
        })))
        // Output Files
        .pipe(gulp.dest('dist'))
        .pipe($.size({title: 'html'}));
    });

    // Vulcanize imports
    gulp.task('vulcanize', function () {
      var DEST_DIR = 'dist/elements';

      return gulp.src('dist/elements/elements.vulcanized.html')
        .pipe($.vulcanize({
          dest: DEST_DIR,
          strip: true,
          inlineCss: true,
          inlineScripts: true
        }))
        .pipe(gulp.dest(DEST_DIR))
        .pipe($.size({title: 'vulcanize'}));
    });

    // Generate a list of files that should be precached when serving from 'dist'.
    // The list will be consumed by the <platinum-sw-cache> element.
    gulp.task('precache', function (callback) {
      var dir = 'dist';

      glob('{elements,scripts,styles}/**/*.*', {cwd: dir}, function(error, files) {
        if (error) {
          callback(error);
        } else {
          files.push('index.html', './', 'bower_components/webcomponentsjs/webcomponents-lite.min.js');
          var filePath = path.join(dir, 'precache.json');
          fs.writeFile(filePath, JSON.stringify(files), callback);
        }
      });
    });

    // Clean Output Directory
    gulp.task('clean', del.bind(null, ['.tmp', 'dist']));

    var BROWSER_SYNC_RELOAD_DELAY = 500;

    gulp.task('nodemon', function (cb) {
      var called = false;
      return nodemon({

        // nodemon our server
        script: 'server.js',

        // watch core server file(s) that require server restart on change
        watch: ['*.js']
      })
        .on('start', function onStart() {
          // ensure start only got called once
          if (!called) { cb(); }
          called = true;
        })
        .on('restart', function onRestart() {
          // reload connected browsers after a slight delay
          setTimeout(function reload() {
            browserSync.reload({
              stream: false   //
            });
          }, BROWSER_SYNC_RELOAD_DELAY);
        });
    });

    gulp.task('serve', ['styles', 'elements', 'images', 'nodemon'], function () {

      // for more browser-sync config options: http://www.browsersync.io/docs/options/
      browserSync.init({

        // watch the following files; changes will be injected (css & images) or cause browser to refresh
        files: ['app/**/*.*'],

        // informs browser-sync to proxy our expressjs app which would run at the following location
        proxy: 'http://localhost:3000',

        // informs browser-sync to use the following port for the proxied app
        // notice that the default port is 3000, which would clash with our expressjs
        port: 4000
      });

      gulp.watch(['app/**/*.html'], reload);
      gulp.watch(['app/styles/**/*.css'], ['styles', reload]);
      gulp.watch(['app/elements/**/*.css'], ['elements', reload]);
      // gulp.watch(['app/{scripts,elements}/**/*.js'], ['jshint']);
      gulp.watch(['app/images/**/*'], reload);
    });

    // Build Production Files, the Default Task
    gulp.task('default', ['clean'], function (cb) {
      runSequence(
        ['copy', 'styles'],
        'elements',
        ['html'],
        'vulcanize',
        cb);
    });

**Comment by jenyckee** [comment]
It appears to be a problem with the combination nodemon + browsersync I think. Each time nodemon restarts the server browsersync gets confused. Therefore I now use one of both depending on if I'm working server side or client side.

**Comment by kenjitayama** [comment]
I'm having this problem too.

I use Sails.js (which uses Express internally), but I'm not launching it from my gulpfile.
I launch Sails first, and then launch Browsersync from gulpfile manually, with proxying configuration to Sails.
The browserSync URL (http://localhost:3000) had the problem, but the raw Sails URL (http://localhost:1337) did not.

I tried changing the browserSync port to 4000, but no success.
One thing I don't understand is, why socket.io is trying to connect to the same port that I configured for browserSync.
In the following error, 3000 changed to 4000.

```
WebSocket connection to 'ws://localhost:4000/socket.io/?__sails_io_sdk_version=0.11.0&__sails_io_sdk_platform=browser&__sails_io_sdk_language=javascript&EIO=3&transport=websocket' failed: Connection closed before receiving a handshake response
```

Here is my gulpfile (very few changes from v1.0.2)
```
/*
Copyright (c) 2015 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/

'use strict';

// Include Gulp & Tools We'll Use
var gulp = require('gulp');
var $ = require('gulp-load-plugins')();
var del = require('del');
var runSequence = require('run-sequence');
var browserSync = require('browser-sync');
var reload = browserSync.reload;
var merge = require('merge-stream');
var path = require('path');
var fs = require('fs');
var glob = require('glob');

var AUTOPREFIXER_BROWSERS = [
  'ie >= 10',
  'ie_mob >= 10',
  'ff >= 30',
  'chrome >= 34',
  'safari >= 7',
  'opera >= 23',
  'ios >= 7',
  'android >= 4.4',
  'bb >= 10'
];

var styleTask = function (stylesPath, srcs) {
  return gulp.src(srcs.map(function(src) {
      return path.join('app', stylesPath, src);
    }))
    .pipe($.changed(stylesPath, {extension: '.css'}))
    .pipe($.autoprefixer(AUTOPREFIXER_BROWSERS))
    .pipe(gulp.dest('.tmp/' + stylesPath))
    .pipe($.if('*.css', $.cssmin()))
    .pipe(gulp.dest('dist/' + stylesPath))
    .pipe($.size({title: stylesPath}));
};

// Compile and Automatically Prefix Stylesheets
gulp.task('styles', function () {
  return styleTask('styles', ['**/*.css']);
});

gulp.task('elements', function () {
  return styleTask('elements', ['**/*.css']);
});

// Lint JavaScript
gulp.task('jshint', function () {
  return gulp.src([
      'app/scripts/**/*.js',
      'app/elements/**/*.js',
      'app/elements/**/*.html'
    ])
    .pipe(reload({stream: true, once: true}))
    .pipe($.jshint.extract()) // Extract JS from .html files
    .pipe($.jshint())
    .pipe($.jshint.reporter('jshint-stylish'))
    .pipe($.if(!browserSync.active, $.jshint.reporter('fail')));
});

// Optimize Images
gulp.task('images', function () {
  return gulp.src('app/images/**/*')
    .pipe($.cache($.imagemin({
      progressive: true,
      interlaced: true
    })))
    .pipe(gulp.dest('dist/images'))
    .pipe($.size({title: 'images'}));
});

// Copy All Files At The Root Level (app)
gulp.task('copy', function () {
  var app = gulp.src([
    'app/*',
    '!app/test',
    '!app/precache.json'
  ], {
    dot: true
  }).pipe(gulp.dest('dist'));

  var bower = gulp.src([
    'bower_components/**/*'
  ]).pipe(gulp.dest('dist/bower_components'));

  var elements = gulp.src(['app/elements/**/*.{html,js}'])
    .pipe(gulp.dest('dist/elements'));

  var swBootstrap = gulp.src(['bower_components/platinum-sw/bootstrap/*.js'])
    .pipe(gulp.dest('dist/elements/bootstrap'));

  var swToolbox = gulp.src(['bower_components/sw-toolbox/*.js'])
    .pipe(gulp.dest('dist/sw-toolbox'));

  var vulcanized = gulp.src(['app/elements/elements.html'])
    .pipe($.rename('elements.vulcanized.html'))
    .pipe(gulp.dest('dist/elements'));

  return merge(app, bower, elements, vulcanized, swBootstrap, swToolbox)
    .pipe($.size({title: 'copy'}));
});

// Copy Web Fonts To Dist
gulp.task('fonts', function () {
  return gulp.src(['app/fonts/**'])
    .pipe(gulp.dest('dist/fonts'))
    .pipe($.size({title: 'fonts'}));
});

// Scan Your HTML For Assets & Optimize Them
gulp.task('html', function () {
  var assets = $.useref.assets({searchPath: ['.tmp', 'app', 'dist']});

  return gulp.src(['app/**/*.html', '!app/{elements,test}/**/*.html'])
    // Replace path for vulcanized assets
    .pipe($.if('*.html', $.replace('elements/elements.html', 'elements/elements.vulcanized.html')))
    .pipe(assets)
    // Concatenate And Minify JavaScript
    .pipe($.if('*.js', $.uglify({preserveComments: 'some'})))
    // Concatenate And Minify Styles
    // In case you are still using useref build blocks
    .pipe($.if('*.css', $.cssmin()))
    .pipe(assets.restore())
    .pipe($.useref())
    // Minify Any HTML
    .pipe($.if('*.html', $.minifyHtml({
      quotes: true,
      empty: true,
      spare: true
    })))
    // Output Files
    .pipe(gulp.dest('dist'))
    .pipe($.size({title: 'html'}));
});

// Vulcanize imports
gulp.task('vulcanize', function () {
  var DEST_DIR = 'dist/elements';

  return gulp.src('dist/elements/elements.vulcanized.html')
    .pipe($.vulcanize({
      dest: DEST_DIR,
      strip: true,
      inlineCss: true,
      inlineScripts: true
    }))
    .pipe(gulp.dest(DEST_DIR))
    .pipe($.size({title: 'vulcanize'}));
});

// Generate a list of files that should be precached when serving from 'dist'.
// The list will be consumed by the <platinum-sw-cache> element.
gulp.task('precache', function (callback) {
  var dir = 'dist';

  glob('{elements,scripts,styles}/**/*.*', {cwd: dir}, function(error, files) {
    if (error) {
      callback(error);
    } else {
      files.push('index.html', './', 'bower_components/webcomponentsjs/webcomponents-lite.min.js');
      var filePath = path.join(dir, 'precache.json');
      fs.writeFile(filePath, JSON.stringify(files), callback);
    }
  });
});

// Clean Output Directory
gulp.task('clean', del.bind(null, ['.tmp', 'dist']));

// Watch Files For Changes & Reload
gulp.task('serve', ['styles', 'elements', 'images'], function () {
  browserSync({
    notify: false,
    snippetOptions: {
      rule: {
        match: '<span id="browser-sync-binding"></span>',
        fn: function (snippet) {
          return snippet;
        }
      }
    },
    // Run as an https by uncommenting 'https: true'
    // Note: this uses an unsigned certificate which on first access
    //       will present a certificate warning in the browser.
    // https: true,
    server: {
      baseDir: ['.tmp', 'app'],
      routes: {
        '/bower_components': 'bower_components'
      }
    }
  });

  gulp.watch(['app/**/*.html'], reload);
  gulp.watch(['app/styles/**/*.css'], ['styles', reload]);
  gulp.watch(['app/elements/**/*.css'], ['elements', reload]);
  gulp.watch(['app/{scripts,elements}/**/*.js'], ['jshint']);
  gulp.watch(['app/images/**/*'], reload);
});

// Build and serve the output from the dist build
gulp.task('serve:dist', ['default'], function () {
  browserSync({
    notify: false,
    snippetOptions: {
      rule: {
        match: '<span id="browser-sync-binding"></span>',
        fn: function (snippet) {
          return snippet;
        }
      }
    },
    // Run as an https by uncommenting 'https: true'
    // Note: this uses an unsigned certificate which on first access
    //       will present a certificate warning in the browser.
    // https: true,
    server: 'dist'
  });
});


// Build Production Files
gulp.task('build', ['clean'], function (cb) {
  runSequence(
    ['copy', 'styles'],
    'elements',
    ['jshint', 'images', 'fonts', 'html'],
    'vulcanize', 'precache',
    cb);
});


// Called from Sails.js. Do nothing.
gulp.task('default', function (cb) {
  cb();
});

// copy bower_components to .tmp (workaround for failing to do something like app.use('/bower_components', theStaticMiddleware) in Sails.js)
gulp.task('tmpBowerComponents', function() {
  return gulp.src('bower_components/**').pipe(gulp.dest('.tmp/bower_components'));
});

// start browsing
gulp.task('browse', ['styles', 'elements', 'images', 'tmpBowerComponents'], function () {

  browserSync.init({
    //notify: false,
    proxy: 'localhost:1337',
    snippetOptions: {
      rule: {
        match: '<span id="browser-sync-binding"></span>',
        fn: function (snippet) {
          return snippet;
        }
      }
    }

    // following paths are configured at Sails.js side (non production)
    //server: {
    //  baseDir: ['.tmp', 'app'],
    //  routes: {
    //    '/bower_components': 'bower_components'
    //  }
    //}
  });

  gulp.watch(['app/**/*.html'], browserSync.reload);
  gulp.watch(['app/styles/**/*.css'], ['styles', browserSync.reload]);
  gulp.watch(['app/elements/**/*.css'], ['elements', browserSync.reload]);
  gulp.watch(['app/{scripts,elements}/**/*.js'], ['jshint']);
  gulp.watch(['app/images/**/*'], browserSync.reload);
});


// Load tasks for web-component-tester
// Adds tasks for `gulp test:local` and `gulp test:remote`
try { require('web-component-tester').gulp.init(gulp); } catch (err) {}

// Load custom tasks from the `tasks` directory
try { require('require-dir')('tasks'); } catch (err) {}
```

**Comment by chuckh** [comment]
@jenyckee @kenjitayama have you tried configuring the Socket.IO path and namespace & domain to avoid collisions.  See http://www.browsersync.io/docs/options/#option-socket.

```
// To change the namespace used by Browsersync
socket: {
    namespace: '/someothername'
}

// By default, Browsersync is configured to use the domain
// of your page in order to connect to socket.io
// eg: location.host + '/browser-sync
// but, should you need to change that, provide the `domain` property
socket: {
    domain: 'localhost:3000'
}
```

**Comment by jenyckee** [comment]
This was indeed the resolution if I remember correctly.
