### ISSUE TITLE
Loading index.html no default content is shown

### ISSUE THREAD

**Issue by kenny0202** [PolymerElements/polymer-starter-kit#248]
When running my application I am expecting "data-route="home"" contents to be loaded, but the contents are not. I have not changed or modified any code to the basic 1.0.2 project. Any reasons why?

**Comment by Frikki** [comment]
@kenny0202 You really need to provide some more information, like which platform you are running on; whether you are seeing any errors in the dev console; if there were any errors running the `gulp` tasks, etc.

**Comment by kenny0202** [comment]
I'm working on a windows platform using Apache as the server. There are no errors on the dev console.  I haven't use the gulp commands yet. But when I eventually ran it using 'gulp serve' I have gotten an error on 'images' process-nexttick-args   and running 'gulp' i get the same error message
