### ISSUE TITLE
Paper-button not showing in paper material sections

### ISSUE THREAD

**Issue by kenny0202** [PolymerElements/polymer-starter-kit#249]
```html
<section data-route="chat">
              <paper-material elevation="1">
                <h2 class="paper-font-display2">Chat</h2>
                <p>This is the chat section</p>
               <paper-button raised>raised button</paper-button>
              </paper-material>
            </section>
```

when running this i should be expecting a button to show up, but instead only the text of the button shows no button is displayed. 

i have made sure that my elements.html contains the paper-button.html. for some reason it still does not show.

just tested adding the import to index.html it displays the button fine. my index.html imported the elements html but does not import the paper-button there. any way i can have the paper-button in elements.html instead of index.html? there were no errors on the dev console.

**Comment by addyosmani** [comment]
Just to check: are you seeing the unstyled paper-button during `gulp serve` or `gulp` production build?

**Comment by xXSirenSxOpusXx** [comment]
When you click or interact with the button do you get the swipe effect? I ran into a similar issue with an app i just built, my solution was to apply css styling to the paper-button element.

**Comment by cguldogan** [comment]
Did you add bower components in to your page ?
 <link rel="import" href="bower_components/paper-button/paper-button.html">

**Comment by addyosmani** [comment]
When you make sure to include the paper-button import in elements.html, everything will work as expected. I imagine this may have been the original issue. Tested and verified working locally:

<img width="425" alt="screen shot 2015-11-19 at 17 21 13" src="https://cloud.githubusercontent.com/assets/110953/11278262/136e41a8-8ee2-11e5-9fb3-06f62efcf982.png">

**Comment by robdodson** [comment]
You can always use this to check if your elements are registered: https://www.polymer-project.org/0.5/docs/polymer/debugging.html#unregistered-element-bookmarklet
