### ISSUE TITLE
Optimizing for pagespeed insights

### ISSUE THREAD

**Issue by tjsavage** [PolymerElements/polymer-starter-kit#25]
There's probably only so much that is possible, but wherever we can we should optimize the build process from a clean download to score highly on the [Pagespeed Insights](https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fpolymerelements.github.io%2Fpolymer-starter-kit%2F%23!%3F) tool

**Comment by bppffnn** [comment]
:+1:

**Comment by hourliert** [comment]
:+1:

**Comment by chuckh** [comment]
@addyosmani would this tool work `gulp-minify-html` -> https://www.npmjs.com/package/gulp-minify-html for this issue?

**Comment by addyosmani** [comment]
Some decisions:

* Let's see if we can get https://github.com/kangax/html-minifier (the recommended option in the Vulcanize readme) working for us. @chuckh have you found gulp-minify-html (rather https://www.npmjs.com/package/minimize the module it uses) works well for this use-case?
* Let's defer on critical-path CSS to next year as this needs further thoughts around how to address it for progressive webapps and application-shell architectures

**Comment by moderndeveloperllc** [comment]
@addyosmani I this this issue is a bit out of date. The current master has HTML and inline CSS/JS minification for the elements.vulcanized.html file and other files:

Line 86:
```
// Minify any HTML
    .pipe($.if('*.html', $.minifyHtml({
      quotes: true,
      empty: true,
      spare: true
```

and line 196:
```
.pipe($.minifyInline())
```

**Comment by addyosmani** [comment]
Afaik we had/have some outstanding issues with minification post vulcanize for a few scenarios. Will double check in case those are sorted now and close accordingly if we're all set.

**Comment by robdodson** [comment]
@addyosmani what's your thought on this issue. I think if we're planning to do an app-layout overhaul then that may be a better time to address this. I'm in favor of closing till then.

**Comment by robdodson** [comment]
Augmenting my previous statement, if not closing, at least removing the `p0` label.

**Comment by abdonrd** [comment]
Any news about this?

**Comment by addyosmani** [comment]
I'm in favour of us closing until the big refactor is done.

**Comment by abdonrd** [comment]
@addyosmani The big refactor? What is that? :grin:

**Comment by addyosmani** [comment]
All good things. We'll publish more information after we've had a chance to flesh some ideas out :)

**Comment by mbana** [comment]
hi, what's the official word on this?
