### ISSUE TITLE
gulp-uncss in package.json

### ISSUE THREAD

**Issue by Frikki** [PolymerElements/polymer-starter-kit#250]
In release v1.0.2 `package.json` under `devDependencies`, I find the entry `"gulp-uncss": "^1.0.1"`. However, I find no reference to it in `gulpfile.js`. Is it used at all? If so, where?

**Comment by addyosmani** [comment]
Dropped via https://github.com/PolymerElements/polymer-starter-kit/commit/dcb01a5ee61bf8cef580a276d70b446afb8ceeca
