### ISSUE TITLE
Error after vulcanize

### ISSUE THREAD

**Issue by felixzapata** [PolymerElements/polymer-starter-kit#251]
Hi, after download and install all the packages and dependencies, for the kit, when I execute ``gulp default`` I obtain this error:

[11:42:58] 'html' all files 49.84 kB
[11:42:58] Finished 'html' after 1.26 s
[11:42:58] Starting 'vulcanize'...
ERROR finding /my-route/polymer-starter-kit-master/dist/bower_components/paper-styles/font-roboto/roboto.html

**Comment by felixzapata** [comment]
I think the problem is in paper-styles/classes/typography.html when it loads the roboto.html file. It would be necessary move up another directory.

**Comment by felixzapata** [comment]
[There is a pull request pending for this] (https://github.com/PolymerElements/paper-styles/pull/45).

**Comment by azakus** [comment]
Fixed by https://github.com/PolymerElements/paper-styles/pull/45
