### ISSUE TITLE
Using MDL with PSK

### ISSUE THREAD

**Issue by karan** [PolymerElements/polymer-starter-kit#252]
Is it a considered good practice to use MDL with PSK? I want to use some UI elements that are not present in PSK (cards, grids), but I don't want to write and maintain all that CSS.

**Comment by addyosmani** [comment]
You can use MDL and PSK together, but this repo doesn't aim to provide guidance on this just yet. We do plan on eventually bringing some of the things you see in MDL (grids, templates) over to Polymer however that's TBD timeline wise :)
