### ISSUE TITLE
Vulcanize fails in certain elements files

### ISSUE THREAD

**Issue by meaziz** [PolymerElements/polymer-starter-kit#253]
[21:34:01] Starting 'vulcanize'...
ERROR finding /dist/bower_components/paper-drawer-panel/paper-drawer-panel.css
ERROR finding /dist/bower_components/paper-item/paper-item-shared.css
ERROR finding /dist/bower_components/promise-polyfill/Promise.js

There seems to be a problem with the vulcanite task related to those files in particular

**Comment by meaziz** [comment]
after further investigation it seems the problem that Gulp doesn't copy the bower_components/**/*.js or  bower_components/**/*.css to the dist folder when building.

**Comment by azakus** [comment]
No, you'd have to do that yourself. I suggest moving the files first, then vulcanizing in-place.

**Comment by Frikki** [comment]
@azakus 
> No, you'd have to do that yourself. I suggest moving the files first, then vulcanizing in-place.

Seriously???

**Comment by addyosmani** [comment]
@meaziz As @azakus mentions above, new files you reference in the project need to be copied over to their final destination yourself. The way to automate this is [documented](https://github.com/PolymerElements/polymer-starter-kit#how-do-i-add-new-javascript-files-to-starter-kit-so-theyre-picked-up-by-the-build-process) in the README (just use build blocks) or alternatively you can specify the files to be copied as part of the `copy` task. Both of these options should result in the correct files going into `dist`, but I'd recommend the build blocks where possible.
