### ISSUE TITLE
Missing 'ms' module causes 'gulp serve' to fail with module not found error

### ISSUE THREAD

**Issue by gesrat-cisco** [PolymerElements/polymer-starter-kit#254]
I hadd to add the 'ms' module to the following path in order to get the server to run - ".../node_modules/browser-sync/node_modules/serve-index/node_modules/debug"

**Comment by addyosmani** [comment]
I haven't been able to repro this I'm afraid. Could you let me know what version of PSK you were using?

**Comment by gesrat-cisco** [comment]
Couple of points..

1.  My installation of node was 0.10.x and not the recommended version of 0.12.x – could this have been the issue ?

2.  PSK download – zip file – indicates version 1.0.2

-Grant

**Comment by gesrat-cisco** [comment]
After upgrading Node, I retried the install and basic build as per the README and it all seems to work.  I guess there is a reason people write README files after all …. :)   Thanks for your help.

From: Grant Emeny-Smith <gemenysm@cisco.com<mailto:gemenysm@cisco.com>>
Date: Monday, July 20, 2015 at 8:37 AM
To: PolymerElements/polymer-starter-kit <reply@reply.github.com<mailto:reply@reply.github.com>>, PolymerElements/polymer-starter-kit <polymer-starter-kit@noreply.github.com<mailto:polymer-starter-kit@noreply.github.com>>
Subject: Re: [polymer-starter-kit] Missing 'ms' module causes 'gulp serve' to fail with module not found error (#254)

Couple of points..

1.  My installation of node was 0.10.x and not the recommended version of 0.12.x – could this have been the issue ?

2.  PSK download – zip file – indicates version 1.0.2

-Grant

**Comment by arthurvr** [comment]
Can we close this now? It's resolved right?
