### ISSUE TITLE
Display Square Mask in Mobile

### ISSUE THREAD

**Issue by SayChunKim** [PolymerElements/polymer-starter-kit#258]
Found minor issue when trying to host site in github and via localhost testing. The paper elements including fab showing square mask

http://stackoverflow.com/questions/28490634/polymer-paper-fab-display-square-mask-in-mobile

Should this issue have to be fixed in v1.0?

Development platform: Ubuntu 14.10
Starter-Kit -version: 1.0.2

Hope helps.

**Comment by addyosmani** [comment]
Is this an issue you're able to reproduce outside of PSK? or does it only occur when paper-fab is added to a PSK project?

**Comment by SayChunKim** [comment]
@addyosmani  seems happens after i added the paperfab lib into element.html and use <paper-fab> into index.html

Is it appropiate to add styles for <body> with:

style="-webkit-tap-highlight-color: rgba(0,0,0,0);

Hope helps

**Comment by SayChunKim** [comment]
Update: Tried in paper-icon-button as well. Managed reproduce issue in mobile view

![screenshot_2015-07-20-07-08-51 2](https://cloud.githubusercontent.com/assets/7574227/8768364/413d58fe-2eb0-11e5-9f93-08deaacfc14a.png)
![screenshot_2015-07-20-07-08-02 3](https://cloud.githubusercontent.com/assets/7574227/8768365/4154bf08-2eb0-11e5-9f08-5ef3936a17de.png)

**Comment by chuckh** [comment]
Just tested this from the master branch it is working fine on iPhone 5s, iPad Mini and Nexus 7.  @SayChunKim are you still having this problem when using the master branch of PSK?  If not lets close this issue.

**iPhone 5s screenshot**
![image](https://cloud.githubusercontent.com/assets/19915/9611609/762dc5ba-5095-11e5-9750-f489f1964180.png)

**Comment by addyosmani** [comment]
Thanks for re-testing this @chuckh?

**Comment by SayChunKim** [comment]
Thanks for update @chuckh ! I will check later and close if there isn't any issue about this :)

Cheers

**Comment by chuckh** [comment]
@SayChunKim can we close this now?

**Comment by SayChunKim** [comment]
Tested working in latest version. We can close this. Thanks reminding @chuckh !
