### ISSUE TITLE
PSK cannot be used with Jekyll

### ISSUE THREAD

**Issue by AdFad666** [PolymerElements/polymer-starter-kit#259]
Jekyll is eating `selected="{{route}}"` so the page is blank except for the header and navigation, and the navigation doesn't work.

**Comment by addyosmani** [comment]
This is a generic problem with Polymer's syntax for two-way binding (`{{`) conflicting with Jekyll's and unfortunately isn't specific to PSK. Jekyll has support for `{%raw%}`Free form non `{{parsed}} {%endraw%}`, which I believe we use over on the Polymer site (powered by Jekyll).

cc @ebidel who worked on the site source.

**Comment by arthurvr** [comment]
This sounds like a problem many people that want to use polymer run into and makes me think it's something for the main repo or the documentation, before we build something in (if we plan to)

**Comment by arthurvr** [comment]
ping ;)

**Comment by addyosmani** [comment]
Looking at this issue in more depth, it would appear that this is a problem not specific to Polymer and which many other static site generators run into when being used with libraries that have their own templating solution using curly braces. I'll defer to the static site generator docs externally for guides on how to change their syntax to workaround this.
