### ISSUE TITLE
Wrong url for page.js

### ISSUE THREAD

**Issue by Amir-Mousavi** [PolymerElements/polymer-starter-kit#263]
Hi, there is a problem with code in line 11 file "routing.html" in version 1.0.3.
The current code is:
`<script src="../../bower_components/page/page.js"></script>`
that causes 404 error.
It must be:
`<script src="../bower_components/page/page.js"></script>`

**Comment by addyosmani** [comment]
There was an issue in PSK light 1.0.3 that I've just fixed up. Can you retry https://github.com/PolymerElements/polymer-starter-kit/releases/download/v1.0.3/polymer-starter-kit-light-1.0.3.zip and let me know if it still has this issue?

**Comment by Amir-Mousavi** [comment]
Yes, I tested it! It's up and running. Thanks for your great work!

**Comment by addyosmani** [comment]
:+1:
