### ISSUE TITLE
Question about larger scale routing/rendering

### ISSUE THREAD

**Issue by benjaminapetersen** [PolymerElements/polymer-starter-kit#265]
I'm curious to know if there are is a Polymer component for routing/rendering for larger scale projects. I'm thinking something along the lines of Angular's `ng-view` directive.  If it does exist or if there is a recommendation I'd love to see it in the starter kit.   `<iron-pages>` works off of a show/hide mechanism.  I'm guessing this would eventually have scaling issues.  

To test the current example, I added a simple component inside `<section data-route="users">` with a `created` and `ready` callback and found they both are fired immediately though the `/users` route is not activated.  

I previously incorporated [app-router](https://github.com/erikringsmuth/app-router) into a Polymer 0.5 project and found it to be fairly intuitive in that it would delay instantiation/rendering of components within a route until that route was activated. 

Is there an official supported Polymer component in the works?  [More routing](https://github.com/PolymerLabs/more-routing) looks promising for more robust routes, but still doesn't solve the view rendering issue.  

Thanks!

**Comment by cnbuff410** [comment]
\sub

**Comment by EdVaIl** [comment]
Try to use the https://github.com/Plastikit/plastik-lazy-route-selector with the https://github.com/PolymerLabs/more-routing

**Comment by donflopez** [comment]
We are made [steroid-polyter](https://github.com/bquarks/steroid-polyter) to solve this problem, we load only the page that is necessary, we have layout schema and the use of Polymer Elements like extensions, without attach them into the DOM maintaining his live across the routes.

The router also have some hooks like before (before instantiate the element), action (just before attach it to the dom), after (just after be attached) and some more things, PR and recommendations are welcome!

**Comment by benjaminapetersen** [comment]
Yeah, this is definitely about the prescribed way to scale an app.  There are some good third party options, but I'm thinking there must be a "recommended default" using core polymer components to answer this architectural question.  Its more or less about knowing where to put controller/glue code and how to make the lifecycle methods useful.

**Comment by addyosmani** [comment]
We're working on a more official routing solution at the moment but it might be another few months before it's ready. In the mean time I recommend trying https://github.com/atotic/excess-router which is :+1:
