### ISSUE TITLE
main.css vs app-theme.html

### ISSUE THREAD

**Issue by Frikki** [PolymerElements/polymer-starter-kit#267]
I am a bit confused about the purposes of these two files. I am aware that `app-theme.html` is a stylesheet shimmed with custom props by `custom style`, while `main.css` isn’t. But couldn’t every style block be in `app-theme.html`? Why have `main.css` unless for the purpose of critical style blocks that affect the page before elements are loaded, and is that its sole purpose?

**Comment by addyosmani** [comment]
The purpose of `main.css` is to define styles that can be applied outside of Polymer's custom CSS properties implementation. Some of the use-cases include defining styles that you want to be applied for a splash screen, styles for your application 'shell' before it gets upgraded using Polymer or as you mentioned, critical style blocks that you want parsed before your elements are.

**Comment by chuckh** [comment]
This subject is now covered in readme.md. See https://github.com/PolymerElements/polymer-starter-kit#application-theming--styling.
