### ISSUE TITLE
Code style issues

### ISSUE THREAD

**Issue by arthurvr** [PolymerElements/polymer-starter-kit#270]
We deliver JSCS, so let's make it pass by default too :)

```
$ jscs *.js app/scripts/**/*.js
...

12 code style errors found.
```

Besides from that, I'd like to discuss if there's a way we can lint scripts inside of `<script>` tags. That's IMHO a missing piece of tooling at the moment. With polymer and web components in general, you end up writing a bunch of inline scripts and it's difficult to lint those. Thoughts?

**Comment by addyosmani** [comment]
+1

The majority of modern JS tools assume they'll be operating directly against script rather than content that is inline. It's one of the reasons I had to write https://github.com/addyosmani/oust to extract inline `<script>` so that it could be passed on to something like JSCS/JSHint and then have the result returned. I'd prefer core tools tackled this themselves though.

I've made the case for Polymer using external scripts/styles for these reasons, but we're still using inline as folks tend to prefer it atm. I'd be interested in us researching what the best option for getting inline script linting for JSCS is here.

**Comment by arthurvr** [comment]
> I'd be interested in us researching what the best option for getting inline script linting for JSCS is here.

On a slightly related note: would we (PSK and WSK) consider switching to ESLint instead of JSHint + JSCS one day? We've moved some Yeoman generators (gulp-webapp too) to ESLint recently. I'm asking this now as if we'd consider that it doesn't make much sense anymore to do research specific to JSCS.

> It's one of the reasons I had to write https://github.com/addyosmani/oust to extract inline `<script>` so that it could be passed on to something like JSCS/JSHint and then have the result returned. I'd prefer core tools tackled this themselves though.

+1. Oust is great to do linting, but it only works one direction. I can't use features like `jscs --fix` with oust, or am I totally wrong?

**Comment by addyosmani** [comment]
I was just pointed to https://github.com/jscs-dev/node-jscs/pull/1038 which is quite relevant to us here :)

**Comment by arthurvr** [comment]
> I was just pointed to jscs-dev/node-jscs#1038 which is quite relevant to us here :)

I am personally still more of a ESLint fan, but yes, that would do it for us. Yay! :birthday:

**Comment by arthurvr** [comment]
Happy to take care of this issue once the JSCS PR lands.

**Comment by addyosmani** [comment]
Thanks @arthurvr!

**Comment by felixzapata** [comment]
hi, another option maybe is to use [``gulp-html-extract``](https://github.com/FormidableLabs/gulp-html-extract) and then passing the content to the ``jscs`` task.
```javascript
gulp.src(glob)
    .pipe(extract())
    .pipe(jscs())
```

**Comment by arthurvr** [comment]
@felixzapata Yes, but it won't take that long till JSCS has the feature so I guess it's better just to wait.

**Comment by samccone** [comment]
My money is on it will be a while :). If we can get something working now that would be awesome and we can always rip it out when jscs supports this use case

**Comment by felixzapata** [comment]
For now, that solution is valid for me until the JSCS task has the feature.  ;)

With the `oust` task I could not extract the JavaScript inline code from the script tag inside my HTML component file.

**Comment by felixzapata** [comment]
I think is better to add a condition to extract only the scripts when the file has the HTML extension:

```javascript
var gulpif = require('gulp-if');
.....
gulp.src(glob)
    .pipe(gulpif('*.html', extract()))
    .pipe(jscs())
```

This way, if you have javascript files, the JSCS task will check it too. I've seen that there is a ``jscs`` config file added to the project. I will try to make later a pull request with this changes.

**Comment by samccone** [comment]
awesome @felixzapata !!!!!!!!!! looking forward to seeing this :+1: :+1: :+1: :+1:

**Comment by felixzapata** [comment]
hi @samccone, I've just sent the pull request

**Comment by samccone** [comment]
woot merged, we can close this :+1:
