### ISSUE TITLE
default design

### ISSUE THREAD

**Issue by gertcuykens** [PolymerElements/polymer-starter-kit#273]
1) Menu should draw back sooner by default els you get this

![image](https://cloud.githubusercontent.com/assets/863731/8888302/a5e33368-32a8-11e5-8349-8345cd628b8f.png)

2) No use to set the blue header app title smaller if the blue header height itself stays at the same height?

![image](https://cloud.githubusercontent.com/assets/863731/8888307/ca2f18b8-32a8-11e5-98c3-e06ba0f3752d.png)

![image](https://cloud.githubusercontent.com/assets/863731/8888312/e06a3644-32a8-11e5-8355-f50c53e3783c.png)

**Comment by robdodson** [comment]
I'm not seeing the 1st issue anymore.

The 2nd issue is more of a complaint against paper-toolbar's design, where using the `.tall` class forces the toolbar to a certain height. This is improved in the new [app-layout elements](http://polymerlabs.github.io/app-layout/) I believe, where you can stack as many toolbars as you want and they behave more like divs.

We're planning to switch to app-layout elements in the new year to improve this. For now, I believe the workaround would be to style the size of the toolbar directly, and not rely on it scaling to fit the text within it.
