### ISSUE TITLE
resize header bug

### ISSUE THREAD

**Issue by gertcuykens** [PolymerElements/polymer-starter-kit#274]
When you resize the window width while condensed, the title app is displayed wrong
![image](https://cloud.githubusercontent.com/assets/863731/8888571/1930dc44-32b3-11e5-8325-c22a0838e475.png)

**Comment by SayChunKim** [comment]
Which version of PSK? That could be issue of id of container or app.js code error.

Hope helps

**Comment by gertcuykens** [comment]
master version, ps does it work for you? When you resize chrome horizontally while condenstated?

**Comment by chuckh** [comment]
I just tested with master and was able to replicate this problem.

**Comment by chuckh** [comment]
I have done some more testing found the following:

1. It happens when drawer is opened or closed, after paper-responsive-change event is fired
2. It is not a timing issue (using async did help when calling the transforms)
3. Maybe addressed / fixed when issue https://github.com/PolymerElements/paper-scroll-header-panel/issues/25 is addressed.

![resize-header-bug](https://cloud.githubusercontent.com/assets/19915/9767997/eccad406-56d5-11e5-911e-7f4a0ee5dc09.gif)

**Comment by robdodson** [comment]
Per the discussion with the team here: PolymerElements/paper-scroll-header-panel#25

The advice is to migrate to app-layout elements vs. trying to fix this in paper-scroll-header-panel. @addyosmani @chuckh what would you like to do with this issue?

**Comment by chuckh** [comment]
Lets keep this open until we migrate to app-layout elements.

**Comment by jsilvermist** [comment]
Is there any update on this? It's still very much an issue in the latest PSK release, as can be seen in Chrome when using emulation for a larger device such as the Nexus 6P and switching between portrait and landscape.

**Comment by robdodson** [comment]
@jsilvermist We're completely dropping the paper-* elements that are causing this issue in PSK2. I think this is an issue with those elements and is outside our control to fix.

**Comment by jsilvermist** [comment]
@robdodson Oh since the app elements seemed to serve the same purpose, I was under the impression they would take the place of their paper counterparts once finished.

**Comment by robdodson** [comment]
@jsilvermist I think they will. In our PSK2 branch we're using them

**Comment by robdodson** [comment]
Closing as we've now moved to [app-layout elements](https://github.com/PolymerElements/app-layout). Please file issues related to headers/drawers/etc on that repo.
