### ISSUE TITLE
<firebase-element> appears deprecated

### ISSUE THREAD

**Issue by maria-le** [PolymerElements/polymer-starter-kit#278]
##### The current version of the PSK appears to use a deprecated version of `<firebase-element>`.

I think this because the [Polymer-Project  site](https://elements.polymer-project.org/elements/firebase-element?active=firebase-collection) seems to describe a different version of `<firebase-element>` than the one being used in the current release of PSK.

For example, the site version uses an element called `<firebase-auth>` instead of the one called `<firebase-login>` used here.

Update: It appears maybe the `<firebase-element>` versions in question are 0.5.6 and 1.0.2?

**Comment by chuckh** [comment]
PSK does not currently use firebase-element.

**Comment by maria-le** [comment]
Yeah. I just noticed that. I think I was looking at an old version of PSK.
