### ISSUE TITLE
iron-list needs to be added in the next build

### ISSUE THREAD

**Issue by DmitryAuine** [PolymerElements/polymer-starter-kit#281]
iron-list needs to be added in the next build

**Comment by addyosmani** [comment]
iron-list is included in https://github.com/PolymerElements/iron-elements/blob/master/bower.json (1.0.3) so we should get this by bumping the element set in the next release.

**Comment by arthurvr** [comment]
> so we should get this by bumping the element set in the next release.

We're using a caret so is there a real need to bump it?

**Comment by addyosmani** [comment]
You're right. Manually verified we're using the caret so we're all good to go on this one.
