### ISSUE TITLE
Suggestion: remove web-component-tester as a dev dep

### ISSUE THREAD

**Issue by crhym3** [PolymerElements/polymer-starter-kit#282]
This would cut off about 150Mb from node_modules after "npm install".

Plus, web-component-tester [suggests](https://github.com/Polymer/web-component-tester#running-your-tests) installing `wct` globally anyway, which currently makes unnecessary copies of web-component-tester package.

Users can alway execute `wct` to run tests, when installed globally.

/cc @devnook

**Comment by arthurvr** [comment]
:-1: When you install WCT globally, you have to use a specific version everywhere on all your projects. Now, if you run `npm test`, it uses the project-specific version. That's important as the versions of WCT your test suite is compatible with might not be the same in all projects.

Besides from that global installs aren't possible in every environment and many people have trouble with permissions. 

> This would cut off about 150Mb from node_modules after "npm install".

In a typical workflow that doesn't matter so much. You only run `npm install` once anyways, and good CI systems will cache it.

**Comment by arthurvr** [comment]
> Plus, web-component-tester suggests installing wct globally anyway, which currently makes unnecessary copies of web-component-tester package.

And that's honestly something I think should change.

**Comment by robbbz** [comment]
What @arthurvr said is a really valid and important concern. NPM is designed like that for a reason, and don't try to force the system.

Years ago it was considered best practice to install `mocha` globally, we had to stop doing that for exactly the same reason after Mocha 2. I don't want Polymer to fall into the same trap.

**Comment by crhym3** [comment]
Are you saying things like `bower` and maybe even `npm` should be installed locally as well? I've seen `{npm,bower} install` failng so many times to install a specific package and the "fix" was to upgrade/downgrade the tool version.

**Comment by robbbz** [comment]
@crhym3 No, because npm isn't a direct dependency, it's a development tool. WCT **does** make breaking changes and we can't always (and don't always need to be) up to date. And I know in many cases a global installation works fine, but not when things scale up. You quickly see various people on your project with other versions of WCT, other error messages, and difficulties to debug together.

> failng so many times to install a specific package and the "fix" was to upgrade/downgrade the tool version.

As those are things you can't even have per-project (npm is managed by npm itself) that wouldn't be possible. Of those packages latest should be the assumption, npm is in fact pretty okay, the problem is just that people don't update. And talking about the "when things scale up" factor, in fact it sometimes happens, then. People need to use things like `nvm` then, but you can't assume everybody to use that.

**Comment by crhym3** [comment]
Your argument just seems like a workaround for a tool that "makes breaking changes". 

It's insane that one ends up with hundreds of megs of npm packages just to build a simple few pages website.

**Comment by robbbz** [comment]
> It's insane that one ends up with hundreds of megs of npm packages just to build a simple few pages website.

No, that's the way a package manager works and that's a feature, not a problem.

> Your argument just seems like a workaround for a tool that "makes breaking changes".

No, I'm just trying to point out why npm is made this way and why you shouldn't abuse the system.

**Comment by crhym3** [comment]
Well, I guess there's nothing else left to discuss if a feature is what it's called. Thanks.

**Comment by arthurvr** [comment]
> No, I'm just trying to point out why npm is made this way and why you shouldn't abuse the system.

This isn't abusing the system. npm has global packages for a reason, too.

It basically boils down to eighter you prefer being safe with a specific version and no global installation, or you prefer bytes (speed) and easiness. I prefer the former but it's just a preference. The latter is a perfectly valid argument too.
