### ISSUE TITLE
Mixins applied to an element from an external stylesheet are missing in builds

### ISSUE THREAD

**Issue by sfeast** [PolymerElements/polymer-starter-kit#283]
Here's one way to reproduce:

1) Define a custom mixin in app-theme.html in the :root selector. Something like:
```
--demo: {
      color:yellow;
      background-color:blue;
    };
```
2) Move the styles in my-greeting.html to an external stylesheet (such as my-greeting.css).
3) Apply the mixin as described here - https://www.polymer-project.org/1.0/docs/devguide/styling.html#custom-css-mixins to your my-greeting.css. For example you can do:
```
:host {
	display: block;
	@apply(--demo);
}
```

Result:
When using ```gulp serve``` it works as expected, but when building the app (i.e. build with ```gulp```), the resulting app does not include the mixin styling.

Notes:
1) Custom properties are working with the build, just not mixins.
2) I noticed this when the ```iron-flex-layout ``` mixins I had applied were not appearing in my built app.
3) Mixins are working when applied in the element's html under a ```<style>``` tag, this seems to just be in external stylesheets.

**Comment by devAtPolydeals** [comment]
@sfeast  Does it work from the app directory? I doubt external sytlesheets will work with mixins, just because css doesn't know about mixins and I don't know if Polymer will flatten the css before it renders the page. You can try making it an HTML file and load Polymer and CSS in that HTML file, I am guessing this might work.

**Comment by sfeast** [comment]
@devAtPolydeals I think you're asking me if mixins work when served (```gulp serve``` for example) & if so the answer is yes they do work in that case.

The problem seems to be that some step in the build process is filtering out the @apply statements from the css since they are missing in elements.vulcanized.html (just using the default build process here). If I manually add them back in then things work as expected.

**Comment by robdodson** [comment]
@azakus have you seen this with vulcanize?

**Comment by sfeast** [comment]
FYI - the culprit seems to be cssmin. I'm not yet very familiar with the details of the default build setup but if you remove

```.pipe($.if('*.css', $.cssmin()))```

from the 'styles' task in gulpfile.js, then although the css does not get minified, it does have the mixins left intact.

Also note that by default cssmin is not applied against any included Polymer elements with external css, so those elements come out ok.

**Comment by robdodson** [comment]
Hm darn.. that make sense.

@azakus any idea how we could minify <style is="custom-style"> elements appearing in external imports?

**Comment by azakus** [comment]
@robdodson No, I've yet to find a good way to minimize CSS that doesn't blow stuff up.

**Comment by addyosmani** [comment]
https://github.com/Polymer/vulcanize/issues/229 confirms the issue is definitely not vulcanize, so the next step is to explore how we can address CSS minification with `custom-style` without causing things to break.

In the interim, we'll at minimum document this in the README and may add a note to the Gulpfile around the CSSMin section.

cc @arthurvr as an FYI on this pipeline issue.

**Comment by sfeast** [comment]
A few observations with the latest psk (1.1.0):

With the new default vulcanize task mixins (in external stylesheets) are being left intact but they are still not working correctly.

However if I customize the default vulcanize task to what's here - https://github.com/PolymerElements/polymer-starter-kit#if-you-require-more-granular-configuration-of-vulcanize-than-polybuild-provides-you-an-option-by - then mixins are not only left intact but they work as well.

And finally I've also noticed that if I modify the customize vulcanize task by adding in polyclean's cleanCss function
```
.pipe(polyclean.cleanCss())
```
then again the mixins are left intact but do not work.

**Comment by samccone** [comment]
Hi guys #386 should resolve the issue for everyone :) :clap: :cactus: :cake: 

Let me know if you are still seeing this issue!

**Comment by diddledan** [comment]
this isn't fixed for me, but I can get it working by altering polybuild per PolymerLabs/polybuild#9

**Comment by samccone** [comment]
@diddledan did you try off of master?

We will cut a release tomorrow of this :)

**cc:** @addyosmani
