### ISSUE TITLE
Paper-scroll-header-panel

### ISSUE THREAD

**Issue by SayChunKim** [PolymerElements/polymer-starter-kit#285]
When switching the pages through menu, the content  doesn't reset back to initial height and paper-scroll-header-panel doesn't back to form that it hasn't condenses. Any solutions/workaround for now?

Version: 1.0.3

**Comment by flaiker** [comment]
See #202, a workaround is mentioned

**Comment by addyosmani** [comment]
From that issue: 

> setting manually document.getElementById("mainContainer").scrollTop = 0 will scroll back up.

Let's file this as a bug and aim to land a workaround/fix for 1.0.4.

**Comment by SayChunKim** [comment]
SGTM. Thanks ! @addyosmani

**Comment by arthurvr** [comment]
Can we close this now that https://github.com/PolymerElements/polymer-starter-kit/commit/ca0a9fca55d9add799e1d8b272b77acb0ff7f0b1 landed?

**Comment by addyosmani** [comment]
I believe we can, yes. Thanks for pinging this issue, @arthurvr. Always helpful :sparkles
