### ISSUE TITLE
improved layout example

### ISSUE THREAD

**Issue by jptrainor** [PolymerElements/polymer-starter-kit#286]
The [0.5 layout documentation] (https://www.polymer-project.org/0.5/docs/polymer/layout-attrs.html) is not correct for 1.0. There is no 1.0 documentation, yet, other than the iron-flex-layout demo code (which newcomers may not head to as their first step - I know I didn't!). To help point developers in the right direction consider adding a more complex layout example to one of the starter kit's custom elements.

Here is the fragment of css and html that I got working to begin with:
```
<link rel="import" href="../../../bower_components/iron-flex-layout/iron-flex-layout.html">
<style>
    [horizflex] {
      @apply(--layout-flex);
      @apply(--layout-horizontal);
    }
</style>
<template>
    <div horizflex>
      <div>Alpha</div>
      <div class="flex"  style="text-align:center">Beta (flex)</div>
      <div>Gama</div>
    </div>
</template>
```

**Comment by emersonbottero** [comment]
You still can use styles in classes declarations, but you have to import paper-styles-classes. Not that the complex example is not worthy, but if you are struggling using classes is pretty simple.

**Comment by jptrainor** [comment]
Thanks for the tip. I see that paper-styles-classes is already included in the elements.html file.  I had not noticed that before, or clued into the fact that it links iron-flex-layout.

Adding layout css to one or both of the starter kit custom elements would help those who are introducing themselves to polymer via the starter kit. Issues of layout have to be addressed nearly immediately by anyone building an application. Sorting out the css is a bit complicated and is a stumbling point, particularly since there is a paucity of documentation at the moment.

**Comment by addyosmani** [comment]
Where possible, layout configuration is delegated to the existing paper element set to avoid introducing too much complexity in the default app boilerplate we provide. That said, I've added a docs tag to this issue so we can explore whether there's anything we can do to make it more clear how layout CSS can be tackled.

**Comment by robdodson** [comment]
There's an updated guide for iron-flex-layout now: https://elements.polymer-project.org/guides/flex-layout

@addyosmani have you had any more thoughts on this? Does it fall into the PSK bucket of responsibilities, or maybe this sort of info belongs with iron-flex-layout and we just link out to it? /cc @arthurevans @kaycebasques
