### ISSUE TITLE
Edge browser throwing DuplicateDefinitionError

### ISSUE THREAD

**Issue by bflora2** [PolymerElements/polymer-starter-kit#287]
Microsoft's new Windows 10 Edge browser throws hundreds of "DuplicateDefinitionError"s when loading a page with paper elements. The page is slow to load if Edge does not already have the paper element files cached from a previous visit. The problem can be seen by going to the Starter Kit's paper dialog demo page. On more complex pages the paper elements can fail to render correctly even after Polymer has fully initialized (i.e., elements rendered with incorrect styles).

**Comment by addyosmani** [comment]
Thanks for reporting this. I've been testing on earlier builds of Edge and IE11 but haven't come across these exceptions until now. That said the final Edge shipped with W10 hasn't been tested with PSK and I'll verify the issues. 

When you say the paper elements fail to render on more complex pages, are you seeing this independently of PSK too?

**Comment by bflora2** [comment]
> When you say the paper elements fail to render on more complex pages, are you seeing this 
> independently of PSK too?

No. Interestingly, if I point Edge to the paper demos in the official Polymer catalog, those seem to work fine, so that may provide a nice clue.

> This sounds like the same error I was having. Try testing with the webcomponentsjs on master, as I 
> believe this PR may fix it

Thanks, I'll give that a try today and report back.

**Comment by bflora2** [comment]
> This sounds like the same error I was having. Try testing with the webcomponentsjs on master

Bingo! That fixed it. Thanks, Polymer-ci!
