### ISSUE TITLE
Gulp tasks should be named functions wrapped and without runSequence

### ISSUE THREAD

**Issue by dman777** [PolymerElements/polymer-starter-kit#289]
The gulp tasks have been written against gulp convention.  The true intention of the gulp design is to write regular Javascript functions, and only make the task for calling them. With this format, you would never need `runSequence` which uses(or used to use) `gulp.start()`. 

If you need sync, use a promise library like [blue bird performance promise library](https://github.com/petkaantonov/bluebird/blob/master/API.md). I believe Gulp 4.0 has it's own promise's but I prefer performance bluebird. 

This is from the authors of Gulp. Sources:
[gulpjs/gulp#755](https://github.com/gulpjs/gulp/issues/755#issuecomment-61884019)
[gulpjs/gulp#458](https://github.com/gulpjs/gulp/issues/458#issuecomment-62057370)
example on proper convention:

```javascript
function getJsFiles() {
    var sourcePaths = [
        './app/scripts/**/*.js',
        '!./app/scripts/**/*.spec.js',
        '!./app/scripts/app.js'
    ];

    var sources = gulp.src(sourcePaths, { read: false }).pipe(angularFilesort());

    return gulp.src('./app/index.html')
        .pipe(injector(sources, { ignorePath: 'app', addRootSlash: false }))
        .pipe(gulp.dest('./app'));
} 
```
----------------------------
```javascript 
gulp.task('js', function () {
    jsStream = getJsFiles();
});
```

**Comment by Frikki** [comment]
:+1:

**Comment by arthurvr** [comment]
You're correct, it's kind of a hack. But actually, I think the version we have at the moment is just a little more readable and understandable to most of our users. I haven't followed it all but I think https://github.com/gulpjs/gulp/issues/355 makes this all much easier, so I'd say we should just postpone fixing this issue till Gulp 4 comes out (normally soon). We'll need to do many updates then anyways.

**Comment by dman777** [comment]
Just to add.... it's been a few months but last I checked `runSequence` used `gulp.start()` which will be deprecated in gulp 4.0. For this reason,   `runSequence` will break in Gulp 4.0.

**Comment by addyosmani** [comment]
> You're correct, it's kind of a hack. But actually, I think the version we have at the moment is just a little more readable and understandable to most of our users

:+1: This echoes my sentiments too. We could keep this issue open until Gulp 4 is properly out and then tackle it correctly.

**Comment by samccone** [comment]
@dman777 I took an initial pass at this by pulling out non specific logic into functions.
If you would like to take it further / :x: to run-sync which imho is not the worst thing ever PRs are welcome!

**Comment by dman777** [comment]
@samccone Sorry about the late response. I would but I'm backed up on other projects :relaxed: Sorry!

**Comment by samccone** [comment]
No worries. This is OSS so any help is appreciated
