### ISSUE TITLE
routing.html is not read

### ISSUE THREAD

**Issue by celron** [PolymerElements/polymer-starter-kit#291]
While the documentation states that to configure routes to modify app/elements/routing.html, this appears not to be picked up by application.

To solve this issue, the contents of routing.html has to be placed in something like app.js

**Comment by jdepypere** [comment]
I don't quite understand the issue. Making changes in `routing.html` does work. Check thay your cache is disabled. Handy for development is when using the Chrome devtools, click the gear icon and check "Disable cache (while DevTools is open)".

**Comment by addyosmani** [comment]
I would echo the comments from @jdepypere above. Changes to routing.html on all supported platforms (Windows, OSX and Linux) should be working fine. Could you confirm you have caching disabled and let us know what browser you're testing in too?

**Comment by arthurvr** [comment]
This issue is kinda incomplete and we never got an answer to our questions so let's close it due to inactivity?

**Comment by addyosmani** [comment]
sgtm
