### ISSUE TITLE
Mixins defined in external stylesheets are stripped from builds

### ISSUE THREAD

**Issue by sfeast** [PolymerElements/polymer-starter-kit#296]
Similar to https://github.com/PolymerElements/polymer-starter-kit/issues/283 but this is when defining a mixin, for example:

```
   :host {
      display: block;
      --paper-button: {
        background-color: purple;
      };
    }
```

elements.vulcanized.html will not contain the --paper-button mixin defined here in the corresponding element's style.

**Comment by rycastaneda** [comment]
can confirm

    paper-drawer-panel {
                --paper-drawer-panel-left-drawer-container: {
                    background-color: var(--primary-background-color);
                    color: var(--dark-primary-color);
                }
                --paper-drawer-panel-main-container: {
                    background-color: var(--dark-primary-color);
                    color: var(--light-primary-color);
                    overflow: auto;
                };
            }

just works on gulp serve not on gulp serve:dist

**Comment by samccone** [comment]
cc @ebidel -- is this a vulcanize issue?

**Comment by rycastaneda** [comment]
mine is fixed, it seems that I am missing semi-colons on some mixins. Will there be support for linting css mixins in the future?

**Comment by ebidel** [comment]
Yes you need semi-colons to define mixins. This type of issue usually
happens with various CSS minifiers out there. I suggest remove it from the
build process.

**Comment by samccone** [comment]
somewhat related I think https://github.com/PolymerElements/polymer-starter-kit/issues/534

**Comment by robdodson** [comment]
I believe this may have been fixed when we removed `minifyInline`. https://github.com/PolymerElements/polymer-starter-kit/pull/565

To test I added a mixin to `shared-styles.html`

```html
paper-button {
  --paper-button: {
    background-color: purple;
  };
}
```

and added a `paper-button` to the page. For both `gulp serve` and `gulp serve:dist` I'm seeing the purple background on the button. @rycastaneda @sfeast could you do a check out of the latest PSK and try for yourself to verify?

**Comment by sfeast** [comment]
@robdodson just tested & looks good in the latest PSK, thanks!

**Comment by robdodson** [comment]
glad to hear it :)
