### ISSUE TITLE
Question: paper-button is all white in content region? Is this due to an override?

### ISSUE THREAD

**Issue by ktiedt** [PolymerElements/polymer-starter-kit#301]
I am using the starter-kit (PSK) as a launchpad for elements that may not have backend support yet to dev against our actual project... and I noticed when I added a <paper-button> that its borders are completely invisible on the white background of the PSK.. if I mouse over the button text, the icon and background become visible and the ripple effect works fine... just surprised to see (or not) the hard to notice button in the content region.

**Comment by robdodson** [comment]
I believe this is working as intended. You can see the demo here: https://elements.polymer-project.org/elements/paper-button?view=demo:demo/index.html

That's just how the material design spec says buttons should behave.

**Comment by ktiedt** [comment]
Ahh thanks @robdodson I suppose I should have checked there, the exmaple I was looking at was all raised.
