### ISSUE TITLE
Paths to bower_components... routing.html ≠ elements.html

### ISSUE THREAD

**Issue by leoj3n** [PolymerElements/polymer-starter-kit#308]
Regarding paths to bower_components, [routing.html#L11](https://github.com/PolymerElements/polymer-starter-kit/blob/5a4663df3b169798af56300973bf46be360238f0/app/elements/routing.html#L11) and [elements.html#L12](https://github.com/PolymerElements/polymer-starter-kit/blob/5a4663df3b169798af56300973bf46be360238f0/app/elements/elements.html#L12) differ.

To build a working Cordova app, I changed `../../` to `../` in routing.html.

Am still a bit confused as the web version seems able to find page.js either way.

**Comment by addyosmani** [comment]
@chuckh would you have some time to help confirm this issue? We've got two PRs open regarding routing/page.js paths (https://github.com/PolymerElements/polymer-starter-kit/pull/306, https://github.com/PolymerElements/polymer-starter-kit/pull/303), however as far as I can tell this isn't actually required. The full and lite versions of PSK refer to different bower paths for page.js which might be why there's some confusion, however it might be good to get a second pair of eyes on this as it appears to be working for me.

**Comment by chuckh** [comment]
@addyosmani I will take a look at later today or tomorrow.

**Comment by chuckh** [comment]
@addyosmani I tested both ways in Chrome and Firefox and it worked ok for me. I do think we should change `<script src="../../bower_components/page/page.js"></script>` to `<script src="../bower_components/page/page.js"></script>` so it is consistent with elements.html.

**Comment by addyosmani** [comment]
@chuckh Thanks for taking a look. I'm personally fine with us making that change for consistency sakes.

**Comment by addyosmani** [comment]
@chuckh Assigned this one to you for now in case you get a chance to update. I'm going to go through the PR backlog next then try to land support for polybuild.

**Comment by arthurvr** [comment]
> I'm personally fine with us making that change for consistency sakes.

Sounds good. :+1:

**Comment by chuckh** [comment]
@addyosmani pr #303 made the change form `<script src="../../bower_components/page/page.js"></script> ` to `<script src="../bower_components/page/page.js"></script>`  so I am closing this issue.
