### ISSUE TITLE
Explore support for polybuild

### ISSUE THREAD

**Issue by addyosmani** [PolymerElements/polymer-starter-kit#312]
https://github.com/polymerlabs/polybuild

**Comment by arthurvr** [comment]
Sounds like something not really suitable for a minor release (looking at the milestone), though totally :+1:. Would be really cool if it can simplify stuff and make our build process more robust.

**Comment by addyosmani** [comment]
@arthurvr Very well caught. This should totally belong in a 1.1. I think we might have discussed going for a larger release on the next round rather than a 1.0.4 which may well make sense.
