### ISSUE TITLE
Explore support for conditionally & async loading Web Component polyfills

### ISSUE THREAD

**Issue by addyosmani** [PolymerElements/polymer-starter-kit#313]
As part of #178 :zap: :zap: :zap:  

References:
* https://aerotwist.com/blog/polymer-for-the-performance-obsessed/
* https://github.com/ebidel/polymer-gmail/blob/master/scripts/app.js#L50

and there's Glen Madderns's snippet:

```js
/**
 * Conditionally loads webcomponents polyfill if needed.
 * Credit: Glen Maddern (geelen on GitHub)
 */
var webComponentsSupported = ('registerElement' in document
  && 'import' in document.createElement('link')
  && 'content' in document.createElement('template'));

if (!webComponentsSupported) {
  var wcPoly = document.createElement('script');
  wcPoly.src = '/third_party/webcomponents-lite.min.js';
  wcPoly.onload = lazyLoadPolymerAndElements;
  document.head.appendChild(wcPoly);
} else {
  lazyLoadPolymerAndElements();
}

function lazyLoadPolymerAndElements () {
  // Set up the element imports.
}
```

**Comment by addyosmani** [comment]
@samccone Interested in me assigning this one to you?

**Comment by samccone** [comment]
sure thing @addyosmani

**Comment by addyosmani** [comment]
Awesome. Just invited you. Will assign once it's been accepted.

**Comment by arthurvr** [comment]
Really cool!

**Comment by arthurvr** [comment]
@addyosmani Is the milestone correct? Sounds like something for at least a minor release ;)

**Comment by addyosmani** [comment]
You're correct. I need to bump that to 1.1. Good catch!

**Comment by moderndeveloperllc** [comment]
(Moved comment here from #178 as this is better place)
@samccone The only issue I can think of offhand with the async polyfill loading, as designed above, is that it makes it very difficult to do any sort of versioning (gulp-rev - #230) or concatenation of the js file with other scripts (using gulp-useref) during the gulp build process. Just something to keep in mind.

**Comment by addyosmani** [comment]
Thanks for sharing the concern, @moderndeveloperllc. I think there are a few ways we could go about ameliorating this:

* Document how to disabling async polyfill loading / switch back from this design as part of the README
* Document how to *enable* async polyfill loading as part of a recipe. 
* Craft a workaround that would allow async polyfill loading to work with revisioning as part of a future release. 

I think that we'll need to wait and see what solution @samccone comes up with before we decide. I'd personally love for users to get the perf benefits here by default if we can manage that.

**Comment by addyosmani** [comment]
@ebidel Other than polymail, are there any other async loading patterns you've masterfully crafted worth us keeping in mind? :zap:

**Comment by moderndeveloperllc** [comment]
I would vote for option 1 actually. Disabling async would be useful if you concatenated the webcomponents file with other app JS via `gulp-useref`. 

The more that I think about it, the more I think you might not have to worry about versioning in relation it async loading. A future versioning system would most likely be optional like service workers. I think at that point, using `gulp-replace` along with the `gulp-useref/gulp-rev/gulp-rev-replace` workflow would allow for replacing `/third_party/webcomponents-lite.min.js` with something like `/js/webcomponents-lite-273c2cin3f.js`.

**Comment by samccone** [comment]
Ok, so enumerating the tasks here:

When a user opts into the the async perf optimization the following processing with happen.

1. Recursively gather a deduped list html imports
2. Generate a *dynamic* async load script and inline into the index.html page

```js
function webComponentsSupported() {//codehere}
function polyfillAndInit() {//codehere}

function initElements() {
  ['DYNAMIC', 'ARRAY', 'OF', 'SOURCES'].forEach(function() {
    var link = document.createElements('link');
    //.....
  });
}

webComponentsSupported() ? initElements() : polyfillAndInit();
```


---

seem good to everyone?

**Comment by addyosmani** [comment]
SGTM. What approach did you have in mind for the opt-in? Statically including the options commented out, performing runtime checks against some flag or adding these optimisations in at build time?

**Comment by samccone** [comment]
In my mind if someone wanted a perf build they could run something like
`gulp build --optimized` or something... thoughts?

**Comment by moderndeveloperllc** [comment]
Thinking about using something like [yargs](https://www.npmjs.com/package/yargs)? Just my opinion, but I would make the flag a bit more descriptive like `--async-loading`. I'm guessing for most folks that the list of elements would just be `elements/elements.vulcanized.html`? or am I misunderstanding what that block is for?

**Comment by addyosmani** [comment]
@samccone I personally wouldn't mind a build time approach to this. Do you think it would be more user-friendly than enumerated/documented steps folks would have to manually apply to their local PSK? I'm pretty down for us exploring your idea.

**Comment by ebidel** [comment]
Hmm. Not sure if we should recommend delay loading imports via script. That's perfect for lazy loading bundles later on, but the huge benefit of having an import declared early on in the page with the `async` attr is that the browser can and start parsing, executing sub-scripts, and prefetch sub-resources right away. 

What about the app shell concept or splash screen while the imports are loading?
https://gist.github.com/ebidel/c72e5b9b7ce7588ef468
https://gist.github.com/ebidel/1ba71473d687d0567bd3

**Comment by samccone** [comment]
hmmm good point @ebidel 

A pure lazy load approach might not be ideal here.. so let me spit ball an idea. What if in any of the html pages we could do something like this

```html
<!-- lazy-element-load -->
<link ...>
<link ...>
<link ...>
<link ...>
<!-- lazy-element-load -->
```

Which would group and lazy load load the imports.

----

The big hold up for me is that this is might be kinda bypassing the easy to use level and jumping right into a convoluted setup with lots of edge cases to consider. (not to mention complex to implement correctly for a general use case)

The more I think about it, I think a well written post on balancing the approaches of async and lazy load might be best, so that users can be informed how to best implement this.....

thoughts?

**Comment by addyosmani** [comment]
Word. Perhaps we should ship this as a recipe that outlines the steps
needed for adding to PSK, pros/cons and related code snippets?

As this is still experimental stuff it could start as a doc in the repo and
be promoted to built-in when we're happy with how well the ideas here work.
Keeps PSK low friction. Is that more favourable to folks?

**Comment by arthurvr** [comment]
> Word. Perhaps we should ship this as a recipe that outlines the steps
> needed for adding to PSK, pros/cons and related code snippets?

:+1:

**Comment by addyosmani** [comment]
I've also looped in @nicolasgarnier in case he's interested in helping here. Is anyone down for helping us write the recipe for integrating in some of the perf patterns we're aiming for into PSK? :star:
