### ISSUE TITLE
routing doesn't work on project gh-pages built from dist directory using gulp

### ISSUE THREAD

**Issue by bartonhammond** [PolymerElements/polymer-starter-kit#320]
Steps followed:
1) mkdir foo & cd foo & yo Polymer
2) git init
3) remove 'dist' from .gitignore
4) gulp
5) git add .; git commit -m "commit", 
6) git remote add origin https://github.com/bartonhammond/foo.git
7) git push -u origin master
8) git subtree push --prefix dist origin gh-pages

Results:
0) Navigate to http://bartonhammond.github.io/foo/:
1) the page.js hashbang does not display in URL
2) http://bartonhammond.github.io/foo/ does NOT show the "Welcome" stuff - the content is empty
3) clicking menu "home" temporarily displays "Welcome" stuff but then 404 as it redirects to http://bartonhammond.github.io/
4) backing up and taking menu items "users" or "contact" does same behavior (flash content then 404)

Not sure what I'm doing wrong.

**Comment by arthurvr** [comment]
Hm, that sounds strange. If you just run `gulp`, do you see any errors? If you just run a static server inside of the `dist` does everything work as expected?

**Comment by bartonhammond** [comment]
No errors running gulp.
I run python -m SimpleHTTPServer 8000 in dist and it behaves fine.
The links above are live if you want to see it in action.
Thanks.

**Comment by addyosmani** [comment]
I'm seeing a missing webcomponents polyfill import when loading up that page on gh-pages. Can you let us know if http://bartonhammond.github.io/foo/bower_components/webcomponentsjs/webcomponents-lite.min.js is in the location the page is searching for on your /foo destination?

**Comment by samccone** [comment]
The reason why routing does not work is because gh-pages has a root path such as **foo**

bartonhammond.github.io**/foo**

To fix this with page.js you have to use
http://visionmedia.github.io/page.js/#pagebasepath


Let me know if this resolves everything for you @bartonhammond

**Comment by bartonhammond** [comment]
@addyosmani: .gitignore had bower_components.  I removed that line and commit/pushed and it's close to being right.
when http://bartonhammond.github.io/foo/ is hit, the content is empty. but if you click "home", the content appears.

**Comment by bartonhammond** [comment]
@samccone   I tried adding the pagebasepath page.base('/foo')  after adding the bower_components and it did *not* appear to fix the issue.

**Comment by addyosmani** [comment]
@bartonhammond I'm glad the dependencies now appear to be getting properly resolved. 

Let's try to get the other issue resolved. The tip from @samccone using page.js's base path is how I've tackled this problem on gh-pages before. I see that the version on latest takes you to `http://bartonhammond.github.io/foo/#!/foo/`. 

If you attempt to serve your app from the root directory of your project, does something similar happen? i.e

```python -m SimpleHTTPServer 8000 LOCATION_OF_PSK```

Then navigate to http://localhost:8000/dist/

**Comment by bartonhammond** [comment]
@addyosmani  thanks for your assistance...

Steps followed:
1) add page.('/dist') to foo/routing.html 
```javascript
 window.addEventListener('WebComponentsReady', function() {
    page.base('/dist');
   ....
   });
```
2) gulp
3) python -m SimpleHTTPServer 8000 dist/

Results:
1) navigate to http://localhost:8000/dist/ -> everything looks fine
2) click "home" -> URL changes to http://localhost:8000/ and page displays directory listing
3) click browser back button -> URL changes to http://localhost:8000/dist/ & page again looks fine
4) click "users" -> URL changes to http://localhost:8000/users and error code 404 displayed
5) same behavior for menu "contact"

I notice that the hashbang is not working now.

**Comment by bartonhammond** [comment]
Since this is still not working after adding the ```javascript page('/dist')```, should this be considered a Issue/bug with page/page.js?

**Comment by addyosmani** [comment]
I think if we can reduce this down to a simple demo that demonstrates that using a similar (but stripped down) setup where we try to `page('/dist')` that would make a strong case for this being an issue that needs fixing on the page.js side. I haven't been able to find anything on the Polymer side of how we're using this that indicates it's a bug with how we're using page.js.

**Comment by bartonhammond** [comment]
I thought the app http://bartonhammond.github.io/foo/ which was generated by "yo polymer" was a pretty simple basic case.  If I were to strip it down to bare essentials would that suffice? Or would that still be too big?

**Comment by jeffposnick** [comment]
I've run into this as well, and setting `page.base(window.location.pathname.replace(/\/$/, ''));` within `routing.html` seems to resolve it. When the site is served from a top-level path, it behaves as it previous did, and when the site is served from a few levels down the path (e.g. as it would be when using GitHub Pages), it will use the correct base path.

As long as `hashbang: true` is also set, I think that that would work.

**Comment by chuckh** [comment]
I have deployed PSK at http://proplanr.github.io/polymer-starter-kit. But routing does not work correctly. I found the following:

1. http://proplanr.github.io/polymer-starter-kit gets redirected to  http://proplanr.github.io
2. Tapping on Home, Users, or Contacts works but shows `http://proplanr.github.io/#!/users` instead of `http://proplanr.github.io//polymer-starter-kit#!/users` for example. Also if you refresh page these urls don't work.
3. Favicon does not work

Tried page.js 1.6.4 and master branch does not fix routing.

Tried `page.base(window.location.pathname.replace(/\/$/, ''));` and `page.base('/polymer-starter-kit');` got these results:

1. http://proplanr.github.io/polymer-starter-kit works with no redirect
2. Tapping on Home, Users or Contacts gets 404 shows `http://proplanr.github.io/users` instead of `http://proplanr.github.io//polymer-starter-kit#!/users` for example 
3. Favicon does not work

**Comment by jeffposnick** [comment]
Here's the code I'm using: https://github.com/jeffposnick/polymer-starter-kit/blob/firebase-demo/app/elements/routing.html#L25

I also modified some of the routing info just to include my own page names, and in retrospect those changes (especially to `*`) are also needed to get the initial routing correct.

You can see the deployed version at https://jeffy.info/polymer-starter-kit/ and confirm functionality.

I'm not sure how generic a solution this is, though. Maybe it can points folks in the right direction at least.

**Comment by chuckh** [comment]
Thanks @jeffposnick you pointed me the right direction.

I got Github pages hosting to work including routing for PSK. You can see it at http://proplanr.github.io/polymer-starter-kit/.  You can see the changes at https://github.com/proplanr/polymer-starter-kit/commit/90bb19cb85f5b9f9dca4f136fe4e6f9588867c54.  I did the following to make it work:

### Deploy
1. Added gulp-gh-pages and dependency
2. Created deploy-gh-pages and build-deploy-gh-pages gulp tasks
3. Added `. publish/` to .gitingore

### Routing
1. Set page.base using `window.location.pathname.replace(/\/$/, '')`
2. Added app.baseUrl for base pathname
3. Added app.baseUrl route
4. Removed all `/` from data-route
5. Added app.getUrl function to add pathname to links

### Misc
1. Added `<link rel="shortcut icon" href="/polymer-starter-kit/favicon.ico"/>` with comments
2. Added demo link to readme.md

@addyosmani @samccone should I make a pull request for PSK repository to make these changes?

**Comment by samccone** [comment]
https://github.com/PolymerElements/polymer-starter-kit/commit/7082366bc258ae748837d3adfe754e70955180f9

takes care of this :dancer:
