### ISSUE TITLE
Gulp Serve Terminal Error and Dependencies Package.JSON

### ISSUE THREAD

**Issue by SayChunKim** [PolymerElements/polymer-starter-kit#323]
Got Latest Git Clone from PSK 1.0.3 from fresh Yosemite (installed bower, node.js and npm)

Found this error:

<code>Error: Cannot find module './lib/_stream_readable.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/sckim/polymer-starter-kit/node_modules/polybuild/node_modules/gulp-util/node_modules/multipipe/node_modules/duplexer2/node_modules/readable-stream/readable.js:1:90)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)</code>

Seems it's not able to allocate the js file. Any enlightenment?

Next, it seems many left dependencies not writen in package.json , shall these be added? 
<b>
  "dependencies": {
    "async-each-series": "^1.0.0",
    "browser-sync-client": "^2.2.1",
    "browser-sync-ui": "^0.5.14",
    "connect": "^3.4.0",
    "core-util-is": "^1.0.1",
    "dev-ip": "^1.0.1",
    "easy-extender": "^2.3.1",
    "eazy-logger": "^2.1.2",
    "emitter-steward": "0.0.1",
    "immutable": "^3.7.4",
    "inherits": "^2.0.1",
    "isarray": "0.0.1",
    "lodash": "^3.10.1",
    "portscanner": "^1.0.0",
    "process-nextick-args": "^1.0.2",
    "readable-stream": "^2.0.2",
    "resp-modifier": "^5.0.2",
    "serve-index": "^1.7.2",
    "serve-static": "^1.10.0",
    "ua-parser-js": "^0.7.9",
    "ucfirst": "^1.0.0"
  } </b>

**Comment by addyosmani** [comment]
Could you try an `npm cache clean` followed by a reinstall of the dependencies (`npm install`) and let us know if the same issue occurs? On other repos I've seen occasional failures of './lib/_stream_readable.js' actually managing to resolve, though don't have a ticket handy I can reference.

**Comment by SayChunKim** [comment]
@addyosmani Thanks for suggesting. Sadly, the problem still persist, i will try rollback to previous 1.0.2 branch since i didn't have much issue in Ubuntu and Windows previously. 

Cheers

**Comment by addyosmani** [comment]
Sounds good. Let us know how you get on with 1.0.2 and we'll try to double-check what other upstream issues might be causing this.

**Comment by samccone** [comment]
hi @SayChunKim  can you try this on the latest master with node 0.12.x.. 

---

I am going to close this for now, but we can reopen if you are still hitting your head during the install phase.
