### ISSUE TITLE
Inline CSS Prefixer

### ISSUE THREAD

**Issue by Tanbouz** [PolymerElements/polymer-starter-kit#325]
From what I understand the Polymeric way is including styles inline in elements. However, it seems the included autoprefixer in the gulp file isn't processing inline css. Shouldn't an inline prefixer be included?

**Comment by addyosmani** [comment]
This is a good point. With our increasing move towards in-import styles, we really need to either figure out an inline prefixing solution or drop Autoprefixer. https://github.com/RebelMail/html-autoprefixer may be what we're looking for. 

```js
var htmlAutoprefixer = require("html-autoprefixer");
var htmlString = "<html><head><style>:fullscreen a { transition: transform 1s; }</style></head><body><h1 style='font-feature-settings: \"liga\", \"dlig\";'>Hello</h1><my-element></my-element></body></html>";

var prefixed = htmlAutoprefixer.process(htmlString);
```

It would be awesome if we could find someone to explore how well this works in practice. My current concerns are how well this setup might work with CSS custom properties in Polymer stylesheets and whether it causes the tool to choke or it's able to work fine here.

**Comment by addyosmani** [comment]
This is the only Polymer project I was able to find using it. Unfortunately it's using Brocolli and Ember in the mix too: https://github.com/pk4media/ember-cli-polymer-toolchain/blob/3c614b6420b6a8116f4571a302826a5a634542d5/index.js

**Comment by robdodson** [comment]
Closing this as a PSK issue. You should be able to add autoprefixr to inline CSS using the new Custom Build project https://github.com/PolymerElements/generator-polymer-init-custom-build
