### ISSUE TITLE
problems installing Node packages with Npm version 2.13.0 

### ISSUE THREAD

**Issue by felixzapata** [PolymerElements/polymer-starter-kit#331]
Hi, when I try to install the node modules, the console throws some ummet depencies warnings related with the web component tester, polybuild, gulp-imagemin and some other.

This error only happens with a Mac OS with Node version 0.12.4 and Npm version 2.13.0.

In another computer with Ubuntu and a lower version of Node and Npm, this problems does not happen. 

I´m not very sure if is problem related with my Mac OS or with some dependencies versions in the package file, after update the Node and Npm version.

**Comment by samccone** [comment]
@felixzapata mind posting the errors?

**Comment by felixzapata** [comment]
I think is related with the versions of some packages. I will try to install it manually. Yesterday, with another project I had the same problem, I solved it this way.

**Comment by addyosmani** [comment]
I would try to `npm cache clean` and run a fresh installation of the dependencies to see if that fixes the issues you're running into. Could you try that?

**Comment by felixzapata** [comment]
Yes I did it yesterday too.

**Comment by felixzapata** [comment]
i´m going to close this issue because I think it was aleatory. Now, I can install the dependencies without problems (only some delay but it is due to my computer).
