### ISSUE TITLE
Author docs/recipe for adding ES6/Babel support

### ISSUE THREAD

**Issue by addyosmani** [PolymerElements/polymer-starter-kit#332]
@nicolasgarnier would it be possible to land this in here before the summit?

**Comment by nicolasgarnier** [comment]
I have something kind of ready to add now. Where is the best place to host this? an .md file under `docs/`?

**Comment by addyosmani** [comment]
Yep! We're going to use `docs/` as a recipe. Something along the same lines of how https://github.com/gulpjs/gulp/tree/master/docs/recipes is approached.

**Comment by nicolasgarnier** [comment]
Up for review at #333 !

**Comment by addyosmani** [comment]
Awesome. Thanks!
