### ISSUE TITLE
Routing within my components not working

### ISSUE THREAD

**Issue by rbjarnason** [PolymerElements/polymer-starter-kit#334]
I can't seem to use window.location=url nor page(url) to offer navigation from within my components.  The address bar changes but I do not go to the new route, if I manually select the browser address bar and press return then I go to the new route. Any ideas?

**Comment by rbjarnason** [comment]
This is with a recent download of polymer-starter-kit from here and the links in the drawer on the left work...

**Comment by flaiker** [comment]
Both ways seem to work fine for me (on latest master):
```
window.location = 'https://www.google.com';
```
```
page('/users');
```

This is from within the `my-greeting`-component inside a script-tag in the template. Can you maybe provide a code example or specify where exactly you are calling these?

**Comment by rbjarnason** [comment]
Ah, window.location = 'https://www.google.com' also works for me. The problem only happens with hashbang urls.

If I add <paper-button on-tap="_onTapMe">TAP ME</paper-button> to the bottom of my-list element then this function replicates my problem on a clean master.
```javascript
      _onTapMe: function () {
          window.location = "#!/users/Rob";
        },
```
It changes the address bar but I have to manually click the address bar and press return to go to /user/Rob

**Comment by rbjarnason** [comment]
Ok, problem solved! :)

page("/users/Rob") does work, the hashbang is automatically added.
