### ISSUE TITLE
Build system doesn't preserve async on script tags

### ISSUE THREAD

**Issue by ebidel** [PolymerElements/polymer-starter-kit#336]
If I put `async` on https://github.com/PolymerElements/polymer-starter-kit/blob/master/app/index.html#L50, the build system replaces it with the .min.js version, but my `async` awesome is gone :(

**Comment by addyosmani** [comment]
Thanks for catching this. We'll get this nailed before the summit.

**Comment by addyosmani** [comment]
Looks like the usage for this is:

```js
  <!-- build:js scripts/async.js async -->
  <script type="text/javascript" src="scripts/three.js"></script>
  <script type="text/javascript" src="scripts/four.js"></script>
  <!-- endbuild -->
```

so it should (in theory) be a one line change.

**Comment by ebidel** [comment]
Oh interesting. I'll give that a try.

**Comment by addyosmani** [comment]
@ebidel Awesome. Do let us know if that does the trick :tophat: 

@samccone fyi about useref + `async` in case you run into similar challenges with the perf work.

**Comment by samccone** [comment]
yep :| I have mixed feeling about html files as build manifests but that is a conversation for another day :goat: :sun_with_face:  

@ebidel did this resolve the async fun for you¿

**Comment by addyosmani** [comment]
friendly ping @ebidel

**Comment by samccone** [comment]
friendly ping :goat:

**Comment by samccone** [comment]
![screen shot 2015-10-07 at 9 57 29 am](https://cloud.githubusercontent.com/assets/883126/10344768/03d1b88a-6cda-11e5-9587-30a5133b1c06.png)
![screen shot 2015-10-07 at 9 57 24 am](https://cloud.githubusercontent.com/assets/883126/10344769/03d1f50c-6cda-11e5-8480-a5965c07561a.png)



:space_invader: Verified to work :space_invader:

`gulp serve:dist`

Thanks @addyosmani and @ebidel
