### ISSUE TITLE
broken html generated when running gulp with firebase-auth

### ISSUE THREAD

**Issue by rbeers** [PolymerElements/polymer-starter-kit#338]
When running gulp serve:dist, I am getting a broken page when I add firebase-auth to elements.html.  Running gulp:serve displays the page fine.

Steps to reproduce.
* fresh clone PSK, npm install, bower install
* add firebase element
```sh
bower install GoogleWebComponents/firebase-element --save
```
* add firebase-auth to elements.html
```html
<link rel="import" href="../bower_components/firebase-element/firebase-auth.html">
```
* run gulp
```sh
gulp serve:dist
```

* output
<img width="541" alt="screen shot 2015-08-28 at 2 14 38 am" src="https://cloud.githubusercontent.com/assets/6262309/9540278/e2734b78-4d2a-11e5-8b4f-e0de87e55b94.png">

My Environment
- npm: 2.10.1
- node: v0.12.4

**Comment by rbeers** [comment]
Update: 
setting inlineScripts: false in vulcanize fixed the problem

**Comment by addyosmani** [comment]
Thanks for commenting back about the solution. I'm a little surprised this was causing breakage. Were you using PSK 1.0.3 or the version in master? Either way it looks like it's worth filing this issue upstream with Vulcanize, especially if there's a reproducible test case or code-samples you can share.

https://github.com/polymer/vulcanize

**Comment by rbeers** [comment]
I was using the version in master with no additional mods other than the steps above.
