### ISSUE TITLE
Styling across elements (main.css | app-theme.html)

### ISSUE THREAD

**Issue by AaronLayton** [PolymerElements/polymer-starter-kit#339]
I've just started a new Polymer app starting from the yeoman generator - the 2 main files are confusing as the Starter Kit only shows a `flat` app example where everything is defined in the main shell.

I created `page-*` elements for each of my pages and then placed them inside `iron-page` to keep the main shell clean. My pages contain their own `<paper-scroll-header-panel>` and `<paper-material>`

I ended up making a shared-styles.html

``` html
<dom-module id="shared-styles">
  <template>
    <style>
       paper-material { ... }
    </style>
  </template>
</dom-module>
```

and then importing that into my `page-*` elements via

``` html
<link rel="import" href="..\..\styles/shared-styles.html">

<dom-module id="page-add-program">
  <template>
    <style include="shared-styles"></style>
```

I can see some work is already being done in this area so figured I would just make a new issue, post what I did and then reference the other issues.

@addyosmani will there be any plans for a more indepth starter package, one that shows multiple pages setup as different elements and hero transitions between them?

**Comment by AaronLayton** [comment]
https://github.com/PolymerElements/polymer-starter-kit/pull/328
https://github.com/PolymerElements/polymer-starter-kit/issues/267

**Comment by addyosmani** [comment]
@AaronLayton Thanks for the issue! I've been working on a few apps this week that do element transitions between pages and I've been achieving this using https://github.com/PolymerElements/neon-animation/tree/master/demo (which have demos up on http://elements.polymer-project.org). You're basically going to want to use `<neon-animated-pages>`: https://github.com/PolymerElements/neon-animation/blob/master/demo/declarative/index.html.

Were you thinking more of apps that had multiple pages that were lazy-loaded in, or are you fine with the content being in the main app shell but just transitioned in? Some more detail would be helpful :)

We don't currently have plans for a more in-depth starter package, but do plan on providing more in-depth starter guides (docs on the Polymer site) and in-repo recipes that walk through achieving specific tasks. This could include a multi-page setup with neon-animation transitions in between. I would suggest opening up an issue for the latter so we can track it.

**Comment by AaronLayton** [comment]
> Are you basing your work off this or the last stable version of the project?

Yup, just started the other day really - started with `yo polymer` giving me version `1.1.1`. I see, the approach I have now seems to work for common styling between my pages and the app-theme is just controlling my variables.

> Were you thinking more of apps that had multiple pages that were lazy-loaded in, or are you fine with the content being in the main app shell but just transitioned in? Some more detail would be helpful :)

Sorry my bad, I was thinking more of just keeping my index.html small and readable. For example I have this

```html
<iron-pages attr-for-selected="data-route" selected="{{route}}">
    <section data-route="addprogram">
        <page-add-program ></page-add-program>
    </section>
    <section data-route="listprograms">
        <page-list-programs></page-list-programs>
    </section>
</iron-pages>
```

The `page-*` elements don't need to be lazy loaded, but if its easy enough to add in then that would be great when running on the web (not needed if in a WebView container). So the above would be an example of a multi page setup where each `page-*` could have their own headers setup, or no headers at all. I guess my question is, is there a specific way you imagine people splitting up their app into manageable pages?

> I've been working on a few apps this week that do element transitions between pages

Ah brilliant, I have just looked at the demo's. I should be able to throw something together that takes advantage of them based on what I learnt from 0.5

> I would suggest opening up an issue for the latter so we can track it.

OK - https://github.com/PolymerElements/polymer-starter-kit/issues/340

**Comment by robdodson** [comment]
We're planning to have multiple template projects for PSK 2

**Comment by robdodson** [comment]
I think I'm going to close this issue as stale if that's ok with folks.

**Comment by AaronLayton** [comment]
Works for me
