### ISSUE TITLE
Multi-page setup with neon-animation transitions

### ISSUE THREAD

**Issue by AaronLayton** [PolymerElements/polymer-starter-kit#340]
Provide documentation on how to setup a mutli-page app with `neon-animations`, possibly focusing on 

* Best practice way of splitting up your app to separate pages
* `hero-transition`
* `cascaded-animation`
* `slide-up-animation`

**Comment by addyosmani** [comment]
I'll do my best to publish a PSK + neon-animation sample in the coming weeks that we can build on here. Alternatively might make for a good recipe.

**Comment by stephenkeep** [comment]
@addyosmani have you had chance to work on this. Im looking to start a PSK project with animation this week.

**Comment by samccone** [comment]
I know @ebidel may have been working on something related

CC @ebidel

**Comment by robdodson** [comment]
FWIW, there are guides on [using neon-animations](https://elements.polymer-project.org/guides/using-neon-animations) in the Element's Catalog and I shot some polycasts covering using neon-animated-pages and the neon-animation behaviors.

- https://www.youtube.com/watch?v=wMhq1o0DULM&index=14&list=PLNYkxOF6rcIDdS7HWIC_BYRunV6MHs5xo
- https://www.youtube.com/watch?v=Lwvi1u4XXzc&list=PLNYkxOF6rcIDdS7HWIC_BYRunV6MHs5xo&index=16

**Comment by MarcosGalaviz** [comment]
Rob very interesting, but how can we implement it with the sections of the Polymer Starter Kit? I am, a little confused :(

**Comment by MarcosGalaviz** [comment]
I realy would like an example of PSK with neon-pages :(

**Comment by JustinXinLiu** [comment]
I created a demo project ([code](https://github.com/JustinXinLiu/polymer-app-design) & [live demo](https://twitter.com/justinxinliu/status/685073908404371456)) here based on PSK with the use of `neon-animated-pages` instead of `iron-pages`.

Much credit should be given to @vguillou for his awesome [`neon-page-behavior`](https://github.com/vguillou/neon-page-behavior) add-on. It basically allows your page to use a different animation configurations when transitioning from/to other pages. I wish `neon-animated-pages` could have it built-in though!

P.S. Responsive design hasn't been done yet so please view it in Mobile device mode. :)

**Comment by vguillou** [comment]
I had such an example ready so I published it : 
https://github.com/vguillou/polymer-starter-kit/tree/neon-animated-pages-basic

It features the most basic integration of `neon-animated-pages` in PSK v1.2.3 with global declarative transitions.
If you want to see what you have to change exactly to integrate it into an existing app based on PSK, i suggest you take a look at the [commit details](https://github.com/vguillou/polymer-starter-kit/commit/8eee54ef87653eb441dab68b6bd8a6624d29271b).

@PolymerTeam (@addyosmani, @samccone, @robdodson)  : I could very well submit a PR with a recipe explaining how integrate `neon-animated-pages` in PSK. What do you think ?

@JustinXinLiu : Amazing demo! :+1: Glad `neon-page-behavior` is of some help.

**Comment by addyosmani** [comment]
I would personally be down for a recipe. We might need to figure out long
term how to keep it up to date but this is the same challenge we have with
the rest of the recipes today.

**Comment by robdodson** [comment]
Fixed by #700
