### ISSUE TITLE
PSK light not playing well with Chrome Dev Editor

### ISSUE THREAD

**Issue by marcacohen** [PolymerElements/polymer-starter-kit#344]
Repro steps

- Unpack PSK light zip file.
- "Open folder" to unpacked contents inside CDE.
- Run generates this error: "Failed to load extension from: /Users/marccohen/Desktop/polymer-starter-kit-light-1.0.3/app. The 'manifest_version' key must be present and set to 2 (without quotes). See developer.chrome.com/extensions/manifestVersion.html for details.".
- Add "manifest_version": 2 to app/manifest.json file.
- Retry, get "Failed to load extension from: /Users/marccohen/Desktop/polymer-starter-kit-light-1.0.3/app. Required value 'version' is missing or invalid. It must be between 1-4 dot-separated integers each between 0 and 65536.".
- Add "version": "1" to app/manifest.json file.
- Retry, getting "Failed to load extension from: /Users/marccohen/Desktop/polymer-starter-kit-light-1.0.3/app. Invalid value for 'icons'.".
- Not sure how to fix icons value but self-assigning to work on this further.

This may be due to the manifest format changing in a recent version of chrome canary/prod.

Per this page: https://developer.chrome.com/extensions/manifest
It would appear that version and manifest_version are missing, and the icons value is improperly formatted.

**Comment by marcacohen** [comment]
Looks like I can't self assigned this bug, probably because I'm not a contrib. 

nivco or addyo: can one of you add me to the proj? thx!

**Comment by addyosmani** [comment]
Thanks Marc! cc @tjsavage for adding Marc to the repo. I have permission to add you to the PolymerElements org but we probably want to limit that to just PSK. 

@marcacohen have you seen https://github.com/PolymerElements/polymer-starter-kit/pull/329? Does that run into similar issues?

**Comment by marcacohen** [comment]
Thanks for the pointer to #329, Addy. By switching from manifest.json to web-app-manifest.json, as advocated there, it causes CDE to treat this project as a web app, not a Chrome app and the PSK light package then work for me inside CDE. 

I'll submit a PR to rename manifest.json so that it works "out of the box" and people won't have to make that change manually.

**Comment by marcacohen** [comment]
+tjsavage

Hey Taylor,

Can you add me to the PSK repo? Would like to self-assign this issue and
submit a PR to fix.

Thanks,

Marc

On 5 September 2015 at 16:39, Addy Osmani <notifications@github.com> wrote:

> Thanks Marc! cc @tjsavage <https://github.com/tjsavage> for adding Marc
> to the repo. I have permission to add you to the PolymerElements org but we
> probably want to limit that to just PSK.
>
> @marcacohen <https://github.com/marcacohen> have you seen #329
> <https://github.com/PolymerElements/polymer-starter-kit/pull/329>? Does
> that run into similar issues?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PolymerElements/polymer-starter-kit/issues/344#issuecomment-137968264>
> .
>



-- 
Marc Cohen
marccohen@google.com <mco@google.com>
http://about.me/marc1

**Comment by addyosmani** [comment]
@marcacohen Is this now fine per the Polymer Summit codelabs and the recipe we have in master?

**Comment by marcacohen** [comment]
Yes, we decided the place to fix this is in CDE, no PSK. For now the recipe
gives a suitable work around but thanks for the reminder - I still need to
write a bug on the CDE issue tracker.

On 23 September 2015 at 10:58, Addy Osmani <notifications@github.com> wrote:

> @marcacohen <https://github.com/marcacohen> Is this now fine per the
> Polymer Summit codelabs and the recipe we have in master?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PolymerElements/polymer-starter-kit/issues/344#issuecomment-142550060>
> .
>



-- 
Marc Cohen
marccohen@google.com <mco@google.com>
http://about.me/marc1

**Comment by addyosmani** [comment]
Thanks for confirming :star:

**Comment by marcacohen** [comment]
CDE bug here:
https://github.com/GoogleChrome/chromedeveditor/issues/3995
