### ISSUE TITLE
Dynamicly set content height instead of static 900px?

### ISSUE THREAD

**Issue by kenjitayama** [PolymerElements/polymer-starter-kit#345]
I'm wondering if the `.content { height: 900px; }` in app-theme.html could be done better.

When the actual content height is smaller than 900px, it scrolls away when scrolling down. Bit strange.

So I played around with the css height value.
If it is smaller than the actual content height, it won't scroll away, but the whole panel bounces when scrolled down, in iOS.
`screen height - header toolbar height + 1px` looks like the ideal value.

I'm not really skilled in CSS and couldn't figure out a good solution.
Any good ideas?

**Comment by addyosmani** [comment]
We played around with trying to set the height of `.content` dynamically to avoid the issue you mention. 

Unfortunately, reading and then changing height/width alters the geometry of the element. That means that it may affect the position or size of other elements on the page, both of which require the browser to perform layout operations.

Once those layout operations have completed any damaged pixels will need to be painted and the page must then be composited together. This means you take a perf hit so we opted to keep it to a fixed height value and encourage folks to customise it based on how high they deem their content to be.
