### ISSUE TITLE
bower_components folder ends up in the wrong location

### ISSUE THREAD

**Issue by the-programmer** [PolymerElements/polymer-starter-kit#346]
I'm not 100% if this is the correct location or not but I'm gonna start here.

What I found: If you use [yo](http://yeoman.io/) to get a scaffold up and running the bower_components folder seems to end up in the wrong location.

It could be my lack of experience with all the tooling but the full workflow is tricky if you are doing this for the 1st time.

What I did (I'm using cloud9 for testing here):
```sh
nvm install v0.12.7
npm install -g bower
npm install -g yo
echo "export NODE_PATH=$NODE_PATH:/home/ubuntu/.nvm/versions/node/v0.12.7/lib/node_modules" >> ~/.bashrc && source ~/.bashrc
mkdir polymer
cd polymer
npm install -g generator-polymer
yo polymer
```
I did found that I should be using this one-liner
```sh
cd polymer-starter-kit && npm install && bower install
```
but I was hoping that yo would handle this.

Should I re-open this issue in https://github.com/yeoman/generator-polymer or can this be handled here as well? 
Since I also get this problem when I try to clone this repo and run
```sh
git clone https://github.com/PolymerElements/polymer-starter-kit.git
cd polymer-starter-kit/
bower install
```

**Comment by robdodson** [comment]
I think some of your message was cut off

**Comment by the-programmer** [comment]
Yep, I was typing and somehow I managed to hit the submit button a bit to early, it's now updated.

**Comment by robdodson** [comment]
Thanks for updating. It's not clear from the issue: Where were you expecting the bower_components directory to end up, and where did it actually end up?

**Comment by the-programmer** [comment]
my bad, If you look at all the paths in index.html they all direct to bower_components as if it is in the same folder as index.html. However bower_components can be found 1 folder up.

The current folder layout:
```
app/
    index.html
bower_components/
```
(index.html can't find bower_components)

The working folder layout:
```
app/
    index.html
    bower_components/
```
(index.html can find all the required files)

**Comment by robdodson** [comment]
I see. That's actually [by design](http://yeoman.io/blog/bower_components-in-project-root.html) though I agree it can be confusing.

When you run the local server `gulp serve` it will mount that directory and serve from it, as if it were in the `app` directory. So this is working as expected but maybe we should include a mention of this in the documentation somewhere. I think a few folks have raised a similar issue. @addyosmani wdyt?

**Comment by arthurvr** [comment]
Are you using PSK lite or the version with tooling? `gulp serve` routes `bower_components` to the right place. You can read about the system at the yeoman blog: http://yeoman.io/blog/bower_components-in-project-root.html

**Comment by the-programmer** [comment]
Thanks for the fast responses.

At the moment I'm totally new to the "modern" way of building web-apps (it seems to look like all you need to do is connect all the modules and you have a new web-app) (my last time was pure HTML).

So to answer arthurvr I'm using the version with tooling `yo`, however it seems that my cloud development (cloud9) platform has some issues with the `gulp serve` command since it crashes due to missing modules.

Tomorrow I'll try again and if that fails I'll re-try it on my raspberry pi 2 (slowish but it works quite ok).

**Comment by robdodson** [comment]
> I would love to help, do you know the best way to start writing a tutorial? (read: what do you need?)

Yeah that'd be great. Take a look at the [issues section](https://github.com/PolymerElements/polymer-starter-kit/issues) there are issues labeled `help-wanted` or `documentation`. Those would be good places to start.

**Comment by danielvanmil** [comment]
I now have an issue with the "gulp test:local" task on windows 7, see the log below. It looks like the mechanism described above is not used with with the gulp WCT test task is it as the test works when I copy the bower_components directory to the /app location. Could this be an issue or am I doing something wrong. Thanks in advance.

Daniel van Mil.

```
[21:10:12] Starting 'wct:local'...
Installing and starting Selenium server for local browsers
Selenium server running on port 52577
Web server running on port 2000 and serving from C:\My-projects\polymer-starter-kit-1.1.0\polymer-starter-kit-1.1.0
chrome 45                Beginning tests via http://localhost:2000/components/polymer-starter-kit-1.1.0/generated-index.html?cli_browser_id=0
404 GET /components/polymer-starter-kit-1.1.0/app/bower_components/polymer/polymer.html
chrome 45                ? Test Suite Initialization

  Polymer is not defined
    <unknown> at   <unknown> at /components/polymer-starter-kit-1.1.0/app/elements/my-greeting/my-greeting.html:30:0
    <unknown> at   <unknown> at /components/polymer-starter-kit-1.1.0/app/elements/my-greeting/my-greeting.html:41:0

chrome 45                ? app/test/my-greeting-basic.html » my-greeting tests » Welcome!

  Cannot read property 'textContent' of null

404 GET /components/polymer-starter-kit-1.1.0/app/bower_components/polymer/polymer.html
chrome 45                ? Test Suite Initialization

  Polymer is not defined
    <unknown> at   <unknown> at /components/polymer-starter-kit-1.1.0/app/elements/my-list/my-list.html:30:0
    <unknown> at   <unknown> at /components/polymer-starter-kit-1.1.0/app/elements/my-list/my-list.html:49:0

chrome 45                ? app/test/my-list-basic.html » my-list tests » Item lengths should be equalled

  expected 6 to equal 0

chrome 45                Tests failed: 4 failed tests
Test run ended in failure: 4 failed tests

chrome 45 (0/0/4)
[21:11:38] 'wct:local' errored after 1.43 min
[21:11:38] Error: 4 failed tests
```
