### ISSUE TITLE
Any recipe to add support for less ?

### ISSUE THREAD

**Issue by wenerme** [PolymerElements/polymer-starter-kit#351]
No familiar with gulp, I use 
```
gulp.task('styles', () => {
  return gulp.src('app/styles/*.less')
    .pipe($.plumber())
    .pipe($.sourcemaps.init())
    .pipe($.less())
    .pipe($.autoprefixer({browsers: ['last 1 version']}))
    .pipe($.sourcemaps.write('.'))
    .pipe(gulp.dest('.tmp/styles'))
    .pipe(reload({stream: true}));
});
```
before, but I don't know how to apply this for PSK gulp.

**Comment by addyosmani** [comment]
We'll wait to see if there are others that also want a recipe for this. At the moment our current recommendations are to just use the CSS custom properties setup in Polymer rather than Sass/Less and it gets you pretty far.

**Comment by addyosmani** [comment]
After thinking this over a little further, I think we're going to try encouraging use of the CSS custom property implementation in Polymer over Less or Sass (for simplicity). At the moment, the best bet for Less support of a structure like this:

* Split source into my-element.html / my-element.less
* At build time, run my-element.less through the Less compiler to generate my-element.css
* Run vulcanize over the final output. If you run into issues with the css being external, you can add a step in your pipeline that inlines the generated Less -> CSS stylesheet back into my-element.html

**Comment by wenerme** [comment]
After get familiar with Polymer css, it's ok now.Kind of hard for beginner.
