### ISSUE TITLE
Enable use of use strict in elements

### ISSUE THREAD

**Issue by chuckh** [PolymerElements/polymer-starter-kit#352]
Currently `use strict` in custom elements will cause jshint to fail. Will look for solution, possibly using http://jshint.com/docs/options/#nonew

**Comment by arthurvr** [comment]
Ref https://github.com/yeoman/generator-polymer/commit/7abbba3a519f8a1547cc0980f142e624d39c5a87 - let's revert that one when this is fixed.

**Comment by samccone** [comment]
changing our jshint config by disabling this http://jshint.com/docs/options/#nonew should make everything happy ;)

**Comment by chuckh** [comment]
@arthurvr @samccone @robdodson I trying adding  ` "nonew": false,` to .`jsintrc` in PSK. Still get same error. Tried  `"nonew": true,` same results.  I am using the latest gulp-jshint v1.11.2 and jshint 2.8.0.

Results of `gulp or gulp serve`.
```
Users/chuckh/DevPolymerLocal/polymer-starter-kit/app/elements/my-greeting/my-greeting.html
  line 30  col 3  Missing 'new' prefix when invoking a constructor.

  ⚠  1 warning

[11:46:48] 'jshint' errored after 3.15 s
[11:46:48] Error in plugin 'gulp-jshint'
Message:
    JSHint failed for: /Users/chuckh/DevPolymerLocal/polymer-starter-kit/app/elements/my-greeting/my-greeting.html
[11:46:48] 'default' errored after 4.9 s
[11:46:48] Error in plugin 'gulp-jshint'
Message:
    JSHint failed for: /Users/chuckh/DevPolymerLocal/polymer-starter-kit/app/elements/my-greeting/my-greeting.html
[11:46:48] images all files 35.41 kB
[11:46:48] Finished 'images' after 2.79 s
[11:46:48] html all files 51.23 kB
[11:46:48] Finished 'html' after 2.07 s
```

.jsintrc contents:
```json
{
  "node": true,
  "browser": true,
  "bitwise": true,
  "camelcase": true,
  "curly": true,
  "eqeqeq": true,
  "immed": true,
  "indent": 2,
  "latedef": true,
  "noarg": true,
  "nonew": false,
  "quotmark": "single",
  "undef": true,
  "unused": true,
  "globals": {
    "wrap": true,
    "unwrap": true,
    "Polymer": true,
    "Platform": true,
    "page": true,
    "app": true
  }
}
```

Any other suggestions besides not using `'use strict';` in elements (does work in app.js).

**Comment by chuckh** [comment]
Adding `"newcap": false,` to `.jsintrc` fixed the problem. PR #353 adds this.

**Comment by addyosmani** [comment]
🍩🍦Thanks for addressing in the PR!
