### ISSUE TITLE
paper-material element question

### ISSUE THREAD

**Issue by goof03** [PolymerElements/polymer-starter-kit#362]
When i use use paper-material in my own element i lost is normal padding. is it normal ? how to restore it please ?

**Comment by moderndeveloperllc** [comment]
This question is more appropriately asked in the individual repository: https://github.com/PolymerElements/paper-material/issues

**Comment by samccone** [comment]
:+1: @goof03 mind reopeneing here https://github.com/PolymerElements/paper-material/issues

thx for the bug report :bug: :sparkling_heart: !!
