### ISSUE TITLE
Polyclean fails after adding ES2015 code

### ISSUE THREAD

**Issue by alexpaluzzi** [PolymerElements/polymer-starter-kit#369]
I wasn't sure whether to drop this in the `polyclean` repo or this one--

I had this working the other day, so I started from scratch but got the same error. Going to continue to investigate on my end, but wanted to create this in the meantime in-case someone already knows about it.

```
[16:02:14] Starting 'clean'...
[16:02:14] Finished 'clean' after 269 ms
[16:02:14] Starting 'default'...
[16:02:14] Starting 'copy'...
[16:02:14] Starting 'styles'...
[16:02:15] styles all files 98 B
[16:02:15] Finished 'styles' after 1.18 s
[16:02:17] copy all files 8.82 MB
[16:02:17] Finished 'copy' after 2.94 s
[16:02:17] Starting 'elements'...
[16:02:17] Starting 'js'...
[16:02:18] Finished 'elements' after 1.51 s
[16:02:19] Finished 'js' after 1.77 s
[16:02:19] Starting 'jshint'...
[16:02:19] Starting 'images'...
[16:02:20] Starting 'fonts'...
[16:02:20] Starting 'html'...
[16:02:21] Finished 'images' after 2.21 s
[16:02:21] Finished 'fonts' after 1.1 s
[16:02:23] Finished 'jshint' after 3.85 s
[16:02:23] html all files 54.89 kB
[16:02:23] Finished 'html' after 2.29 s
[16:02:23] Starting 'vulcanize'...
[16:02:27] Error in plugin "polyclean"
Message:
    Unexpected token: punc ())
```

Node 4.0.0
Windows 7
(Will be on Linux machine tonight and plan on testing there.)

**Comment by alexpaluzzi** [comment]
Everything runs until you start actually changing stuff to ES2015 code.

Following: http://www.code-labs.io/codelabs/polymer-es2015/
The `Unexpected token: punc ())` occurs after I added all of the fat arrows to the `routing.html` file.
When I took them all out, it ran again. Then I tried changing the `my-list` component to use a ES2015 class. Now the error from polyclean is: `Unexpected token: name (MyList)`.

I think something is out of order here. I will continue to work on it.

**Comment by alexpaluzzi** [comment]
Seem to have found the issue:
https://github.com/mishoo/UglifyJS2/issues/448

This is probably worth mentioning in the ES2015 doc.

**Comment by alexpaluzzi** [comment]
FWIW, I'm also seeing `js` files in the `scripts` directory being copied twice to source somehow in the polybuild/vulcanize process.

**Comment by addyosmani** [comment]
This may be an issue with crisper not correctly stripping out the JS. Running ES5 output with Uglify should work fine, but we'll of course run into trouble if the sources are still in ES2015. @nicolasgarnier could you help take a look here?

**Comment by addyosmani** [comment]
Friendly ping @nicolasgarnier

**Comment by nicolasgarnier** [comment]
The issue with duplicate JS files has been fixed in https://github.com/PolymerElements/polymer-starter-kit/pull/434

Do you still want me to investigate the issue with Crisper + Polyclean since we've removed Polyclean usage? :D If you think this may come back we should definitely have a look before that happends though.

btw thanks for investigating @alexpaluzzi !

**Comment by addyosmani** [comment]
Thanks for the reminder about this being fixed in #434. I think it's going to be a while until/if we switch back to using the Crisper and Polyclean setup. Let's close this. Will reopen if we discover @alexpaluzzi or anyone else is still running into issues with the recipe.

**Comment by alexpaluzzi** [comment]
:+1::+1::+1: Will take it for a spin later today. Thanks guys.

**Comment by ebidel** [comment]
We should investing crisper/polylean though. If you can't use those tools,
thats a bug and affects all Polymer devs.
