### ISSUE TITLE
dev setup : Need to have gulp script serve from Dist folder, but watch App for changes.

### ISSUE THREAD

**Issue by gedw99** [PolymerElements/polymer-starter-kit#371]
Let me explain.

During Dev, 
I can run off the App folder with watching, and nice browser updates
I cant point my golang server to "App" folder because the "bowercomponents" folder is above, outside the hosting root.  

Kind of frustrating, but well...

So, the only thing i need is to be able to have the gulp script serve from Dist folder, but watch for App for changes.  Is there a command to do this ??

**Comment by chuckh** [comment]
You can run `gulp serve:dist` to serve from dist folder, but it won't look for changes. A custom gulp task would need to be created to do so.

**Comment by gedw99** [comment]
Thanks. I ended up writting a task, so I can use golang as the server.
Good enough for our needs.

Thanks for responding.
