### ISSUE TITLE
gulp Error: ENOENT, open '.../dist/index.build.html'

### ISSUE THREAD

**Issue by vl4dt** [PolymerElements/polymer-starter-kit#373]
I just wanted to try the latest PSK, clonned it and installed dependencies as usual.

Tried many things, cleared npm cache, updated node, etc., keep getting the following error running gulp:

```bash
(master) psk110 ツ gulp
[01:54:48] Using gulpfile ~/Projects/psk110/gulpfile.js
[01:54:48] Starting 'clean'...
[01:54:48] Finished 'clean' after 246 ms
[01:54:48] Starting 'default'...
[01:54:48] Starting 'copy'...
[01:54:49] Starting 'styles'...
[01:54:51] styles all files 98 B
[01:54:51] Finished 'styles' after 1.2 s
[01:54:52] copy all files 10.97 MB
[01:54:52] Finished 'copy' after 3.7 s
[01:54:52] Starting 'elements'...
[01:54:52] Finished 'elements' after 6.62 ms
[01:54:52] Starting 'jshint'...
[01:54:53] Starting 'images'...
[01:54:54] Starting 'fonts'...
[01:54:54] Starting 'html'...
[01:54:55] Finished 'fonts' after 880 ms
[01:54:56] Finished 'jshint' after 4.49 s
[01:54:56] images all files 35.41 kB
[01:54:56] Finished 'images' after 3.1 s
[01:54:56] html all files 51.25 kB
[01:54:56] Finished 'html' after 2.17 s
[01:54:56] Starting 'vulcanize'...
[01:55:01] Finished 'vulcanize' after 4.54 s
[01:55:01] Starting 'rename-index'...
[01:55:01] Finished 'rename-index' after 2.35 ms
[01:55:01] Finished 'default' after 13 s
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/Users/vl4dt/Projects/psk110/dist/index.build.html'
    at Error (native)
(master) psk110 ✖
```

**Comment by flaiker** [comment]
I just did the following:
```
$ git clone git@github.com:PolymerElements/polymer-starter-kit.git
$ cd polymer-starter-kit
$ npm install -g gulp bower && npm install && bower install
$ gulp
```

And it worked fine for me. Can you try installing the dependencies again (sometimes they timeout and some are missing) and also renaming your project folder to `polymer-starter-kit` (see #257).

If that does not help, operating system, npm/node/gulp versions? Also what kind of shell are you using to execute these commands, I had problems using git bash for example.

**Comment by addyosmani** [comment]
The latest tagged version contains the same version as you see in master (per the comment from @flaiker) and we haven't had issues building it on Mac or Windows. Could you try reinstalling and if that fails sharing more info about your setup?

**Comment by vl4dt** [comment]
**Setup:**
OS X 10.10.5
XCode Version 7.0 (7A220)
zsh 5.0.5 (x86_64-apple-darwin14.0), plus Prezto
node v4.1.0 (updated from a v0.12.x version in an attempt to solve the issue)
npm 2.14.3
bower 1.5.2

Tried what @flaiker suggested but I got:
**Permission denied (publickey)**

However, tried once more, ran the following leaving the directory as *polymer-starter-kit* as suggested:

First attempt:
```zsh
$ git clone https://github.com/PolymerElements/polymer-starter-kit.git
$ npm install -g gulp bower
$ npm install
$ bower install
```

Output:
[http://pastebin.com/aeMyX3CG](http://pastebin.com/aeMyX3CG)

Did a second try from scratch again:
```zsh
$ git clone https://github.com/PolymerElements/polymer-starter-kit.git
$ npm install -g gulp bower && npm install && bower install
```

Output:
[http://pastebin.com/Qbw00ERx](http://pastebin.com/Qbw00ERx)

This time it made it once but the second time I try to run gulp it again hits the same error condition and never recovers.

**Comment by robdodson** [comment]
ah I think the problem might be node v4. Can you try with 0.12?

**Comment by robdodson** [comment]
oh nvm I just saw that you upgraded from 0.12 to try to solve the issue. :P

**Comment by vl4dt** [comment]
Actually @robdodson there was a difference when I tried with v0.12 before, I didn't see any build errors, with v4 there were some build errors, still npm (which is the one I presume needs to be compiled) managed to build in v4 too, both cases with v0.12 and v4 behave the same when building with gulp

**Comment by robdodson** [comment]
npm isn't compiling, it's one of the npm dependencies that's trying to compile something. You definitely want to use 0.12 because web-component-tester depends on stuff that doesn't work in v4 yet, like socket.io.

**Comment by samccone** [comment]
hopefully everything will get resolved this week for 4.0 upstream :+1: 

https://twitter.com/SocketIO/status/645755967934697472

**Comment by addyosmani** [comment]
It appears that we're building up a few different exceptions at build time due to Node 4.0 support being tried. Per the other thread, I'm happy to indicate PSK currently recommends 0.12 (over Node 4.0) at least until we can verify cross-platform that everything in our workflow works reliably.

**Comment by samccone** [comment]
ok I dug through your paste bin and it looks like the reason things are not compiling correctly is because at one point someone on your system installed a Unity plugin / extension which xcode is no longer able to load... thus preventing xcode from running / compiling

> 2015-09-20 14:20:51.030 xcodebuild[65367:1488173] [MT] PluginLoading: Required plug-in compatibility UUID 0420B86A-AA43-4792-9ED0-6FE0F2B16A13 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin' not present in DVTPlugInCompatibilityUUIDs

Perhaps take a look at

https://developer.appcelerator.com/question/173705/problem-building-ipad-applications

https://developer.appcelerator.com/question/160136/pluginloading-required-plug-in-compatibility-uuid-for-plug-in-at-path--not-present-in-dvtplugincompatibilityuuids


---

I am going to close since this is a local env issue (and not a general project issue), however feel free to follow up if you are still stuck!

:sparkler:

**Comment by vl4dt** [comment]
Just wanted to share this with you guys because we were close to the solution, I went back to node 0.12.7 as @robdodson and @addyosmani suggested, the error persisted but decided not to update node until all PSK dependencies are ready for it, uninstalled the Unity plugin, @samccone, I am to blame for installing this plugin lol, anyway, the error persisted and honestly was a bit frustrated.

I tried the exact same thing in my office's linux box and gulp didn't throw this error, so, long story short, passing **[del](https://www.npmjs.com/package/del)** the parent directory in the _rename-index*_ task in **gulpfile.js** fixed the problem for good.

[gulpfile.js:169](https://github.com/vl4dt/polymer-starter-kit/blob/gulpfile-fix/gulpfile.js#L169)

**Comment by samccone** [comment]
woah crazy @vl4dt totally not what I expected then! I will reopen this until we have a resolution on your open PR

thanks for working though this with us :+1:
