### ISSUE TITLE
Android Application error

### ISSUE THREAD

**Issue by Dragod** [PolymerElements/polymer-starter-kit#374]
I got this error when I run the application on my android device (android 5.0.1) Galaxy S4, cliking on any of the menu button.

It is running just fine on my Desktop Chrome/Firefox/IE11

Maybe he can't load any file thart require an internet connection like I used jquery from google CDN &  a firebase?

![menu_error](https://cloud.githubusercontent.com/assets/4368630/9980262/91373212-5f89-11e5-8998-5f51ca94e5cf.png)

Did commented out all my new code & js, html import but this bug still

**Comment by flaiker** [comment]
Is that the AOSP android browser? Because I doubt that one is supported by Polymer.

**Comment by Dragod** [comment]
I have no idea what AOSP. I install the apk on my phone and when I click on any of the menu it gives that error

**Comment by flaiker** [comment]
Which APK exactly are you installing?

AOSP -> Android Open Source Project, it has its own webbrowser which isn't as maintained and supported anymore

**Comment by Dragod** [comment]
I run gulp then I copy the content from dist folder to the app/www folder the I run cordova build android.  
Once the build is done I install the apk he just created on the app/platforms/android/build/outputs/apk folder. The app is running fine, but once I click any of the menu I get the error

**Comment by flaiker** [comment]
I had no idea PSK supported Cordova nor do I have any experience with it.

Might have to wait for someone else to help you with that.

**Comment by Dragod** [comment]
Thanks, in the meantime I try to install crosswalk plugin for cordova and see what happend.

**Comment by Dragod** [comment]
Solved. For some reason I had to create a folder named android_asset inside 
AndroidStudioProject/myappname/app/src/main/android_asset 

Then I paste the content of www folder and it's now working. 

Also replaced jquey & firebase CDN lin with bower. Look like file that require a connection do not work.

**Comment by arthurvr** [comment]
Glad it's resolved :)

That's not really an issue shipping with the starter kit so let's close this?

**Comment by Dragod** [comment]
Sure can close it.
