### ISSUE TITLE
poly-build/uglify breaks firebase.js

### ISSUE THREAD

**Issue by sfeast** [PolymerElements/polymer-starter-kit#378]
To reproduce:
1) Import one of the polymer firebase elements in a psk app.
2) Build the app.
3) Run the build in any browser.

Result:
Uncaught SyntaxError: Unexpected token ILLEGAL

Reason:
poly-clean's uglifyJS function is run by poly-build & it appears uglify breaks firebase.js which is included by the firebase elements.

A workaround is to use https://github.com/PolymerElements/polymer-starter-kit#if-you-require-more-granular-configuration-of-vulcanize-than-polybuild-provides-you-an-option-by and use the excludes option in vulcanize, i.e.:

```
.pipe($.vulcanize({
      stripComments: true,
      inlineCss: true,
      inlineScripts: true,
      excludes: [path.resolve('./dist/bower_components/firebase/firebase.js')]
    }))
```

**Comment by addyosmani** [comment]
Thanks for filing this bug and providing the workaround. It's unfortunate that an `excludes` config is required for firebase.js. I've posted this bug upstream at https://github.com/PolymerLabs/polyclean/issues/4 which is where we'll need to explore getting it addressed. If we can get it fired there we should be able to pick up the latest version via polybuild.

(Side: this may well be a general issue with firebase.js + Uglify, however we'll loop in the right team once we know for certain).

**Comment by archana-s** [comment]
gulp.task('vulcanize', function () {
  var DEST_DIR = 'dist/elements';
  return gulp.src('dist/elements/elements.vulcanized.html')
    .pipe($.vulcanize({
      stripComments: true,
      inlineCss: true,
      inlineScripts: true,
      excludes: [path.resolve('./dist/bower_components/firebase/firebase.js')]
    }))
    .pipe(gulp.dest(DEST_DIR))
    .pipe($.size({title: 'vulcanize'}))
});

This still doesnt fix it for me.

**Comment by kishaningithub** [comment]
This repo https://github.com/PolymerLabs/todo-list/ uses firebase-element but does not seem to be affected by this bug. 

Why is that?? 

In its bower.json i see 
"firebase-element": "GoogleWebComponents/firebase-element#61-kschaaf-local-key" 

what is that "61-kschaaf-local-key" thing???

**Comment by VandeurenGlenn** [comment]
@kishaningithub Polybuild isn't used there yet.

**Comment by addyosmani** [comment]
What @VandeurenGlenn kindly pointed out. This issue is only visible when using polybuild or one of the transitive dependencies like polyclean.

**Comment by addyosmani** [comment]
We've reverted back to not using Polybuild in master and haven't been able to repro the issues with Firebase scripts over there. I'd suggest pulling down latest and using that version instead of the Polybuild one.

**Comment by deltaepsilon** [comment]
I'm reproducing it on a fresh Starter Kit project. The exclude trick is working for now.

**Comment by joncostello** [comment]
I can reproduce it with these steps:
yo polymer
yo polymer:el test-firebase
bower install --save GoogleWebComponents/firebase-element

Insert a <test-firebase> tag in index.html(I put it above the <my-greeting> tag).

Inside test-firebase.html:
link firebase-document
above hello from test-firebase put a <firebase-document> tag

gulp serve:dist 
Result:
blank page. Dev console has the Uncaught SyntaxError: Unexpected token ILLEGAL

**Comment by samccone** [comment]
Hi @deltaepsilon and @joncostello this seems to be a polybuild issue would you mind opening an issue in the polybuild repo https://github.com/PolymerLabs/polybuild so we can track it in the correct place.

Thanks for the issue and steps to reproduce :clap: 

cc  @azakus

**Comment by joncostello** [comment]
Thanks @samccone I created a new issue there: https://github.com/PolymerLabs/polybuild/issues/27

**Comment by zboralski** [comment]
I think it is vulcanize issue... 

https://github.com/Polymer/vulcanize/issues/304 

not only polybuild/polyclean chokes on the output of vulcanize but even chrome complains before it has a chance to complain about CSP:

```
Uncaught SyntaxError: Unexpected token ILLEGAL
```

and that is after running only vulcanize... no polybuild, no crisper nothing...
