### ISSUE TITLE
When disabling shady DOM PSK stops working

### ISSUE THREAD

**Issue by David-Mulder** [PolymerElements/polymer-starter-kit#379]
In app.js

    document.getElementById('mainContainer')

can't be found when shadom DOM is used and thus the entire PSK stops working.

**Comment by davidrissato** [comment]
is this element in your main html and outside a template is=dom-bind? Shadow DOM intends to hide things, and if this tag isn't in the main html, it won't be found under document's content children DOM. It will be hidden in the shadow root.

**Comment by David-Mulder** [comment]
Yeah I know... it's not a hard thing to fix... it's just that by default it should support the non-polyfilled Polymer as well.

**Comment by addyosmani** [comment]
Another comment from #438 cross-posting:

the following logic in `app.js` makes an assumption by accessing internal implementation specific logic, namely an internal id

```javascript
  // Scroll page to top and expand header
  app.scrollPageToTop = function() {
    document.getElementById('mainContainer').scrollTop = 0;
  };
```

wouldn't it be better to implement this as follows?

```javascript
  // Scroll page to top and expand header
  app.scrollPageToTop = function() {
    document.getElementById('mainArea').scroller.scrollTop = 0;
  };
```

by adding the `id="mainArea"`, *or something similar*, in `index.html`

```html
.
.
.
    </paper-scroll-header-panel>

    <!-- Main Area -->
    <paper-scroll-header-panel id="mainArea" main condenses keep-condensed-header>

    <!-- Main Toolbar -->
.
.
.
```
