### ISSUE TITLE
🚠 Cross browser compat issues

### ISSUE THREAD

**Issue by samccone** [PolymerElements/polymer-starter-kit#383]
* [x] https://github.com/PolymerElements/polymer-starter-kit/issues/379
* [x] https://github.com/PolymerElements/polymer-starter-kit/issues/237
* [x] https://github.com/PolymerElements/polymer-starter-kit/issues/199
* [x] https://github.com/PolymerElements/polymer-starter-kit/issues/166

**Comment by chuckh** [comment]
@samccone can this be close since #379 has been resolved?

**Comment by samccone** [comment]
:dancer:
