### ISSUE TITLE
Angular 2.p alpha 37 and polymer-starter-kit

### ISSUE THREAD

**Issue by vagabondtt1503** [PolymerElements/polymer-starter-kit#387]
Dear,

I am researching about angular 2.0 al37 and polymer. Can anyone has example which use angular 2.0 in polymer-starter-kit?

Thanks.

**Comment by addyosmani** [comment]
We don't currently have an example of using both Angular 2 and Polymer Starter Kit together, however there has been experimentation of using Angular 2 and Polymer directly with a few patches. Take a look at some of the links in http://stackoverflow.com/questions/29218327/has-anyone-got-angular-2-0-alpha-working-with-polymer-elements.
