### ISSUE TITLE
Data binding array not trigger observer

### ISSUE THREAD

**Issue by zohon** [PolymerElements/polymer-starter-kit#388]
When push item on an array with :

this.push('allRules', {name : 'test'}); 

for example. The observe of allRules dont call the function associate with it.

Here is a codePen for example http://codepen.io/anon/pen/yYajXV

Thanks

**Comment by robdodson** [comment]
I believe you need to use a separate observers object to observe sub property changes to an array.
https://www.polymer-project.org/1.0/docs/devguide/properties.html#array-observation

http://codepen.io/anon/pen/NGRzNj
