### ISSUE TITLE
Starterkit app have lot of lag

### ISSUE THREAD

**Issue by Dragod** [PolymerElements/polymer-starter-kit#389]
I'm building my first android app with polymerstarterkit but look very laggy on my galaxy s4. Anything that I can do to have a better performance?
I know this isn't really a bug but I was expecting to be faster on a phone. More responsive.

**Comment by samccone** [comment]
@Dragod would you be able to upload some timeline info via
https://developers.google.com/web/tools/setup/remote-debugging/remote-debugging

Without that it is hard to help here.

--

I am going to close this one as a non-issue (directly related to PSK) however we can continue the conversation here :sparkles:
