### ISSUE TITLE
CI should run jshint over codebase

### ISSUE THREAD

**Issue by samccone** [PolymerElements/polymer-starter-kit#393]

**Comment by addyosmani** [comment]
:+1:

**Comment by robdodson** [comment]
Does this work now? I see [this line](https://github.com/PolymerElements/polymer-starter-kit/blob/master/travis-runner.sh#L16) in the travis runner and we're extracting js from our elements now in the gulp task. Are there any parts that are missing?

**Comment by samccone** [comment]
Oh yeah this is working now :)
