### ISSUE TITLE
migrate CI over to travis

### ISSUE THREAD

**Issue by samccone** [PolymerElements/polymer-starter-kit#394]
We have a few custom needs for our test suite

* .js wct configs
* running jshint / jscs / other lint tasks

The current polymer test runner can not accommodate these needs, however travis can

The downside here is that we no longer get "free" test runs across multiple browsers, however I do not think that is so important right now.

**Comment by addyosmani** [comment]
:+1:

**Comment by JeremybellEU** [comment]
@samccone This process has finished, hasn't it? All current PR's use Travis as CI.

**Comment by samccone** [comment]
yep! good catch @TimvdLippe :)
