### ISSUE TITLE
Running tests - Polymer is not defined

### ISSUE THREAD

**Issue by dev-e-loper** [PolymerElements/polymer-starter-kit#395]
I'm able to run `gulp serve` without an issue. Running tests with `gulp test:local` I get the following 

chrome 45                Beginning tests via http://localhost:2000/components/starter_kit/generated-index.html?cli_brows
er_id=0
404 GET /components/starter_kit/app/bower_components/polymer/polymer.html
chrome 45                ? Test Suite Initialization

  Polymer is not defined
    <unknown> at   <unknown> at /components/starter_kit/app/elements/my-greeting/my-greeting.html:30:0
    <unknown> at   <unknown> at /components/starter_kit/app/elements/my-greeting/my-greeting.html:41:0

I've put the starter kit project in c:\dev\starter_kit directory.  I'm not sure why the tests are looking in compontents/starter_kit directory...am I missing something here?

**Comment by samccone** [comment]
hey @dev-e-loper 

checkout the patch here
https://github.com/PolymerElements/polymer-starter-kit/pull/384

It will fix this issue!
