### ISSUE TITLE
Why do we polybuild index.html?

### ISSUE THREAD

**Issue by kaste** [PolymerElements/polymer-starter-kit#397]
In the recent version of the polymer-starter-kit we vulcanize/polybuild the index.html, which leads to a blown up >100kB index.html file. Shouldn't we vulcanize the elements.html just like we ever did?

On a side note: the gulp file still refers to a elements.vulcanized.html file which is unused right now.

**Comment by ebidel** [comment]
We should be careful about doing this. Making the main page too big can
actually be slower. I saw this with chromestatus and in lining a ton of
json on the page. Xhring it instead was faster.

In the world of http2, it might even be faster to have smaller chunks for
the browser to preload.

**Comment by addyosmani** [comment]
Let's take a closer look at our polybuild setup for the next release. I agree with Eric's concerns about the cost of inlining vs. XHRing in.

**Comment by addyosmani** [comment]
In the latest version of PSK in master, we've reverted to using vulcanize directly rather than relying on polybuild. Could you retest using this version and let us know if you're still running intro the same issues as you saw with polybuild?

**Comment by addyosmani** [comment]
Closing as I haven't been able to repro this against master now.
