### ISSUE TITLE
specific built-in icons seem to be discarded when imported via elements.html

### ISSUE THREAD

**Issue by mvpmvh** [PolymerElements/polymer-starter-kit#398]
Is it just me, or does importing a specific built-in icon (e.g. communication, av, etc) get discarded when imported in elements.html? If I import `iron-icons` and `av-icons` and later try to use some av-icons in my application, there is an empty space where the av icons should be.

A snippet from elements.html

    <link rel="import" href="../bower_components/iron-icons/av-icons.html">
    <link rel="import" href="../bower_components/iron-icons/iron-icons.html">
    ...

A snippet from index.html

    <iron-icon icon="av:games"></iron-icon>
    ...

Results in an empty space where the controller icon should be. However, if I move the av-icons definition outside of elements.html and into index.html directly, the icon appears as expected.

**Comment by mvpmvh** [comment]
ignore. (the missing icons were due to some seriously heavy caching, apparently).

**Comment by samccone** [comment]
:+1: no worries
