### ISSUE TITLE
Default tests not working

### ISSUE THREAD

**Issue by BorntraegerMarc** [PolymerElements/polymer-starter-kit#400]
Hi there :)

I downloaded and installed the PSK 1.1.0  with all libraries. The actual site works fine and with no error, but when I run the tests with 'gulp test:local' I get the following error:

```
404 GET /components/polymer-starter-kit-1.1.0/app/bower_components/polymer/polymer.html
chrome 44                ✖ Test Suite Initialization

  Polymer is not defined
    <unknown> at   <unknown> at /components/polymer-starter-kit-1.1.0/app/elements/my-greeting/my-greeting.html:30:0
    <unknown> at   <unknown> at /components/polymer-starter-kit-1.1.0/app/elements/my-greeting/my-greeting.html:41:0
```

Therefore all other tests also fail... Tested it on Windows 10 and Ubuntu 14.04

**Comment by samccone** [comment]
@BorntraegerMarc did you change the root folder of the project?

When did you download PSK?

**Comment by samccone** [comment]
I think that this PR should have resolved this issue
https://github.com/PolymerElements/polymer-starter-kit/pull/384

**Comment by BorntraegerMarc** [comment]
Hi @samccone I downloaded the project last Monday, if I'm correct. But not the master branch, just the actual released version. Should I try it with the master?

**Comment by samccone** [comment]
I would appreciate it if you would try :)

**Comment by BorntraegerMarc** [comment]
No problemo :) Just tested it and it looks like the master branch works fine... Except, that the tests fail on firefox but I think that's a Windows 10 problem... I'm going to wait for a new release and close the issue. Thanks :)

**Comment by samccone** [comment]
No problem. Thanks for checking !
