### ISSUE TITLE
npm & bower issues when installing the Starter Kit

### ISSUE THREAD

**Issue by salah-saleh** [PolymerElements/polymer-starter-kit#402]
Hi, I get the following errors when I run npm install && bower install on the Starter Kit. My npm version is 3.3.5, node version 0.12.2

	npm install && bower install

	> bufferutil@1.2.1 install /Users/sam/Documents/projects/web-projects/polymer-summit-examples/polymer-starter-kit-1.1.0/node_modules/bufferutil
	> node-gyp rebuild

	  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
	  SOLINK_MODULE(target) Release/bufferutil.node

	> dtrace-provider@0.6.0 install /Users/sam/Documents/projects/web-projects/polymer-summit-examples/polymer-starter-kit-1.1.0/node_modules/dtrace-provider
	> node scripts/install.js

	> fsevents@1.0.0 install /Users/sam/Documents/projects/web-projects/polymer-summit-examples/polymer-starter-kit-1.1.0/node_modules/fsevents
	> node-pre-gyp install --fallback-to-build

	[fsevents] Success: "/Users/sam/Documents/projects/web-projects/polymer-summit-examples/polymer-starter-kit-1.1.0/node_modules/fsevents/lib/binding/Release/node-v14-darwin-x64/fse.node" already installed
	Pass --update-binary to reinstall or --build-from-source to recompile

	> gifsicle@3.0.1 postinstall /Users/sam/Documents/projects/web-projects/polymer-summit-examples/polymer-starter-kit-1.1.0/node_modules/gifsicle
	> node lib/install.js

	  ✔ gifsicle pre-build test passed successfully

	> jpegtran-bin@3.0.4 postinstall /Users/sam/Documents/projects/web-projects/polymer-summit-examples/polymer-starter-kit-1.1.0/node_modules/jpegtran-bin
	> node lib/install.js

	  ✔ jpegtran pre-build test passed successfully
	npm WARN prefer global jshint@2.8.0 should be installed with -g

	> optipng-bin@3.0.2 postinstall /Users/sam/Documents/projects/web-projects/polymer-summit-examples/polymer-starter-kit-1.1.0/node_modules/optipng-bin
	> node lib/install.js

	  ✔ optipng pre-build test passed successfully

	> sauce-connect-launcher@0.12.0 postinstall /Users/sam/Documents/projects/web-projects/polymer-summit-examples/polymer-starter-kit-1.1.0/node_modules/sauce-connect-launcher
	> node scripts/install.js

	> utf-8-validate@1.2.1 install /Users/sam/Documents/projects/web-projects/polymer-summit-examples/polymer-starter-kit-1.1.0/node_modules/utf-8-validate
	> node-gyp rebuild

	  CXX(target) Release/obj.target/validation/src/validation.o
	  SOLINK_MODULE(target) Release/validation.node

	> wct-local@1.6.0 postinstall /Users/sam/Documents/projects/web-projects/polymer-summit-examples/polymer-starter-kit-1.1.0/node_modules/wct-local
	> node scripts/postinstall.js

	----------
	selenium-standalone installation starting
	----------

	---
	selenium install:
	from: http://selenium-release.storage.googleapis.com/2.47/selenium-server-standalone-2.47.1.jar
	to: /Users/sam/Documents/projects/web-projects/polymer-summit-examples/polymer-starter-kit-1.1.0/node_modules/selenium-standalone/.selenium/selenium-server/2.47.1-server.jar
	---
	chrome install:
	from: http://chromedriver.storage.googleapis.com/2.18/chromedriver_mac32.zip
	to: /Users/sam/Documents/projects/web-projects/polymer-summit-examples/polymer-starter-kit-1.1.0/node_modules/selenium-standalone/.selenium/chromedriver/2.18-x64-chromedriver
	---
	File from http://selenium-release.storage.googleapis.com/2.47/selenium-server-standalone-2.47.1.jar has already been downloaded
	---
	File from http://chromedriver.storage.googleapis.com/2.18/chromedriver_mac32.zip has already been downloaded

	-----
	selenium-standalone installation finished
	-----

	> wct-sauce@1.6.6 postinstall /Users/sam/Documents/projects/web-projects/polymer-summit-examples/polymer-starter-kit-1.1.0/node_modules/wct-sauce
	> node scripts/postinstall.js

	Prefetching the Sauce Connect binary.
	module.js:338
	    throw err;
	          ^
	Error: Cannot find module 'js-yaml'
	    at Function.Module._resolveFilename (module.js:336:15)
	    at Function.Module._load (module.js:278:25)
	    at Module.require (module.js:365:17)
	    at require (module.js:384:17)
	    at Object.<anonymous> (/usr/local/lib/node_modules/bower/node_modules/configstore/index.js:9:12)
	    at Module._compile (module.js:460:26)
	    at Object.Module._extensions..js (module.js:478:10)
	    at Module.load (module.js:355:32)
	    at Function.Module._load (module.js:310:12)
	    at Module.require (module.js:365:17)
	    at require (module.js:384:17)

**Comment by Dragod** [comment]
try npm install js-yaml

**Comment by salah-saleh** [comment]
I tried but I still get exactly the same errors.

**Comment by Dragod** [comment]
So you need to wait for someone that know more than me :)

**Comment by addyosmani** [comment]
Can you try:

```
$ rm -fr ./node_modules/
$ npm cache clean
$ npm install
```

To see if the dependency issue can be resolved from a freshly cleaned cache?

**Comment by salah-saleh** [comment]
yes, thank you Addi.

**Comment by samccone** [comment]
:+1:

**Comment by sajjadmurtaza49** [comment]
➜  my-project  sudo npm install npm@2.11.0 && npm install -g gulp && npm install -g bower && npm install && bower install
npm@2.11.0 node_modules/npm
npm ERR! Linux 3.13.0-24-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "gulp"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! path /usr/bin/gulp
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, unlink '/usr/bin/gulp'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, unlink '/usr/bin/gulp'] errno: -13, code: 'EACCES', path: '/usr/bin/gulp' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
npm ERR! error rolling back Error: EACCES, unlink '/usr/bin/gulp'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EACCES, unlink '/usr/bin/gulp'] errno: -13, code: 'EACCES', path: '/usr/bin/gulp' }

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sajad/p_projects/my-project/npm-debug.log

**Comment by robdodson** [comment]
@sajjadmurtaza49 please don't respond to multiple issues with the same error, it just spams everyone.

This looks like a permissions error. Try running `npm install -g gulp`, if you get another EACCES error then your current user account may not have the ability to touch `/usr/bin`. If that's the case you might try running `sudo npm install -g gulp`. I'd recommend running the above commands one after another, without the `&&` and see where you run into an error. Better to do it that way than jumble it all together.

**Comment by sajjadmurtaza49** [comment]
@robdodson  okay - i removed from other.
➜  my-project  sudo npm install -g gulp
/usr/bin/gulp -> /usr/lib/node_modules/gulp/bin/gulp.js
gulp@3.9.0 /usr/lib/node_modules/gulp
├── interpret@0.6.6
├── pretty-hrtime@1.0.1
├── deprecated@0.0.1
├── archy@1.0.0
├── minimist@1.2.0
├── semver@4.3.6
├── tildify@1.1.2 (os-homedir@1.0.1)
├── v8flags@2.0.10 (user-home@1.1.1)
├── chalk@1.1.1 (escape-string-regexp@1.0.3, ansi-styles@2.1.0, supports-color@2.0.0, strip-ansi@3.0.0, has-ansi@2.0.0)
├── orchestrator@0.3.7 (stream-consume@0.1.0, sequencify@0.0.7, end-of-stream@0.1.5)
├── liftoff@2.2.0 (extend@2.0.1, rechoir@0.6.2, flagged-respawn@0.3.1, resolve@1.1.6, findup-sync@0.3.0)
├── vinyl-fs@0.3.14 (graceful-fs@3.0.8, mkdirp@0.5.1, strip-bom@1.0.0, defaults@1.0.3, vinyl@0.4.6, through2@0.6.5, glob-stream@3.1.18, glob-watcher@0.0.6)
└── gulp-util@3.0.6 (array-differ@1.0.0, array-uniq@1.0.2, lodash._reescape@3.0.0, lodash._reinterpolate@3.0.0, beeper@1.1.0, lodash._reevaluate@3.0.0, object-assign@3.0.0, replace-ext@0.0.1, vinyl@0.5.3, lodash.template@3.6.2, multipipe@0.1.2, through2@2.0.0, dateformat@1.0.11)
➜  my-project  gulp serve                                          
module.js:338
    throw err;
          ^
Error: Cannot find module 'browser-sync'


--------------

I tried sudo  npm install browser-syncbut same error.
Actually i'm on learning stage

**Comment by robdodson** [comment]
Yeah so you've *globally* installed gulp, which is good.

Next you need to install the project's *local* dependencies (that's where it's looking for browser-sync). To do that, `cd` into the project directory and run `npm install`.

Then try `gulp serve`.

**Comment by sajjadmurtaza49** [comment]
Whaooooooooooooooo Your are great.
Thank you so much.

**Comment by robdodson** [comment]
Sure thing :)

**Comment by lepatlamass** [comment]
hi guys when i tried to install gulp globally this is the error i get in windows 10
C:\Users\lepat>npm install -g gulp
npm WARN install Couldn't install optional dependency: Failed to parse json
npm WARN install Unexpected token '\u0000' at 1:1
npm WARN install
npm WARN install ^

**Comment by robdodson** [comment]
Did you check for a similar issue on the gulp GitHub repo? It seems like
it's more specific to that project so if someone doesn't know the answer
off the top of their head you might try looking over there

**Comment by lepatlamass** [comment]
I have checked and all the answer i got was not working will tryng and install it in linux and see.thanks for your help
