### ISSUE TITLE
Single Page Application for polymer-starter-kit

### ISSUE THREAD

**Issue by thanhtruong0315** [PolymerElements/polymer-starter-kit#403]
Dear all,

I used polymer-starter-kit few days ago. That is excellent example for polymer 1.0. But, I have a small issue about routing. When I click Users (nav menu), I realize sections in page is show / hide, did not load HTML template. So, if I would like to implement dashboard, I will put all code to dashboard page, and then, show or hide for each section.

Does anyone have other way better?

Thanks.

**Comment by addyosmani** [comment]
What we have in PSK is meant to show a simple/naive application where showing and hiding views makes sense for showing how multi-view routing could work. For anything more complex, I'd recommending lazy-loading in your other views and making sure your routing hooks up well to that.

Some reference you can look at:

https://github.com/GoogleChrome/ioweb2015
https://github.com/ebidel/polymer-gmail/
