### ISSUE TITLE
Service worker is broken in PSK 1.1.0

### ISSUE THREAD

**Issue by Holi0317** [PolymerElements/polymer-starter-kit#404]
To reproduce,
1. Get a fresh install of PSK
2. Follow README.md/Service Worker to enable service worker support
3. `gulp:serve`, and open devtool. Service worker tries to get bootstrap file from the root, instead of elements/. This happens because platinum elements is in index.build.js.

To fix this, either move bootstrap file to root or, as mentioned in #397, roll back to vulcanize.

**Comment by addyosmani** [comment]
This looks like it happened as part of our switch to polybuild for 1.1.0. 

We'll likely need to try customizing the polybuild workflow to avoid tampering with the Platinum setup or as you mention, move back to the more verbose vulcanize setup and include the extra polyclean/crisper steps ourselves.

cc @samccone as an FYI.

**Comment by addyosmani** [comment]
@samccone Moving this to the 1.1.1 pipeline. We might want to triage if there are other issues related to our switch to polybuild that we'll want addressed upstream before the next release: https://github.com/PolymerElements/polymer-starter-kit/issues?utf8=✓&q=is%3Aissue+is%3Aopen+polybuild

**Comment by addyosmani** [comment]
In the latest version of PSK in master, we've reverted to using vulcanize directly rather than relying on polybuild. Could you retest using this version and let us know if you're still running intro trouble?

**Comment by Holi0317** [comment]
It works after changing back to vulcanize.

Sorry for the late reply.
