### ISSUE TITLE
app-theme.html isn't parsed

### ISSUE THREAD

**Issue by azumbrunnen** [PolymerElements/polymer-starter-kit#405]
I've just cloned this repo and started building a new project and it seems like app-theme.html doesn't get parsed anymore. I can enter arbitrary values and it doesn't seem to have any impact.

I know that you changed some stuff in the styling system, does this have anything to do with that?

**Comment by addyosmani** [comment]
When you say it doesn't get parsed anymore, do you mean changes you're making to the app-theme aren't getting applied? Any further details that can help us repro what you're seeing would be helpful. Thanks!

**Comment by robdodson** [comment]
You may need to double check that the HTML import for app-theme isn't being cached. Try opening the devtools and going into settings. There should be an option to "disable cache when devtools is open". Check that, leave the devtools open, make changes and refresh.

**Comment by addyosmani** [comment]
I'm quite sure Rob's right about this being a caching issue. I just tried (after a `gulp serve`) to update app-theme and it's correctly causing a reload with the values taking affect.This is working fine over BrowserSync in the browsers we target. I'd suggest clearing your cache and refreshing the page to try it again.
