### ISSUE TITLE
Mac gulp serve page blank until toggle between browser tabs

### ISSUE THREAD

**Issue by shersher** [PolymerElements/polymer-starter-kit#406]
Mac Yosemite
node v0.12.7
gulp CLI version 3.9.0
bower 1.5.3
uninstalled generator-polymer and npm generator-polymer (version looks like 1.2.0)
made new app directory and cd to it, then:
yo polymer
npm install && bower install
Quit Chrome from toolbar
Quit Terminal window
in new Terminal window, ran gulp serve and the Chrome browser loads quickly with the tab properly titled Polymer Starter Kit.  The page remains blank and will eventually display the unresponsive error and ask to  'Kill' the page. If I quit Terminal, quit Chrome and retry but only wait a few seconds after the blank page to open a new tab and return to the Polymer tab, the app displays.  

Can you help?

**Comment by shersher** [comment]
Solved!  Last night I began to have a blank screen on a Gitter site; I disabled all extensions and it now works as expected.  Surprisingly, I progressively enabled the extensions expecting to find the offending extension but...none of them caused the failure to recur.  Nuts.

**Comment by samccone** [comment]
:+1:
