### ISSUE TITLE
paper-item issue during vulcanize, finding paper-item-shared.css error

### ISSUE THREAD

**Issue by buele** [PolymerElements/polymer-starter-kit#407]
#### Envirnoment:

```
$ node -v
v0.10.40
$ npm -v
1.4.28
$ bower -v
1.5.2
```

#### bower.json:

```
{
  "name": "polymer-starter-kit",
  "private": true,
  "dependencies": {
    "polymer": "Polymer/polymer#^1.1.2",
    "iron-elements": "PolymerElements/iron-elements#^1.0.0",
    "paper-elements": "PolymerElements/paper-elements#^1.0.0",
    "platinum-elements": "PolymerElements/platinum-elements#^1.1.0",
    "neon-elements": "PolymerElements/neon-elements#^1.0.0",
    "page": "visionmedia/page.js#~1.6.3"
  },
  "devDependencies": {
    "web-component-tester": "*",
    "test-fixture": "PolymerElements/test-fixture#^1.0.0"
  }
}
```
Previous week the vulcanize has worked, after a week I have refreshed the bower_components (via bower install) and the vulcanize doesn't work anymore.  

#### logs:
```
[12:02:02] Error in plugin 'gulp-vulcanize'
Message:
    ENOENT, open '/data/rbua/git/XMF-DevTeam/DHuS.polymer/client/polymer_client/src/main/frontend/dist/bower_components/paper-item/paper-item-shared.css'
Details:
    errno: 34
    code: ENOENT
    path: /data/rbua/git/XMF-DevTeam/DHuS.polymer/client/polymer_client/src/main/frontend/dist/bower_components/paper-item/paper-item-shared.css
    fileName: /data/rbua/git/XMF-DevTeam/DHuS.polymer/client/polymer_client/src/main/frontend/dist/index.html
```

**Comment by addyosmani** [comment]
Thanks for your bug report. Is it possible to try downgrading your version of vulcanize/gulp-vulcanize to the one you had the week before and see if that's still working? If so, we can then look into what exact change broke this.

**Comment by buele** [comment]
Thank you for your prompt reply.

The version of vulcanize is: 6.0.0.

We have the problem from the paper-item commit:
https://github.com/PolymerElements/paper-item/commit/22bab8a2f875dcbfad6328b6774545d229f6379f 

We haven't problems with before commits

**Comment by samccone** [comment]
Hi @buele would you mind running `rm -rf node_modules && rm -rf bower_components && npm i && bower i` and the trying again

I think one of your modules might be slightly out of date :)

**Comment by samccone** [comment]
@buele are you still hitting this one?

**Comment by addyosmani** [comment]
To add to that, if you are still hitting this one, could you try testing against master too to see if it's been addressed?

**Comment by buele** [comment]
Dear @samccone and @addyosmani, I have just tested it running "rm -rf node_modules && rm -rf bower_components && npm i && bower i" and switching to the master branch, and all works well now!

Thank you guys.
