### ISSUE TITLE
Question: how to redirect from page to page in starterkit

### ISSUE THREAD

**Issue by Dragod** [PolymerElements/polymer-starter-kit#409]
Do you guys can tell me how to redirect? Unfortunately I can't get it working on my phone.

the window.location look like it's only working on desktop browser

**Comment by cnbuff410** [comment]
isn't it done by page.js?

**Comment by addyosmani** [comment]
If you're trying to force a redirect from one view/page to another you can do this using page.js. The docs there cover a few different ways of tackling this: https://visionmedia.github.io/page.js/
