### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by azumbrunnen** [PolymerElements/polymer-starter-kit#414]
Running NPM 2.14.4, I'm unable to build with the new gulpfile.

I get this error with a freshly cloned repo:

`events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/Users/azumbrunnen/Desktop/polymer-starter-kit/dist/index.build.html'
    at Error (native)
`

any suggestions? The error message isn't exactly helpful in this case.

**Comment by addyosmani** [comment]
Could you provide some more information on which version of PSK and OS you were testing with?

**Comment by azumbrunnen** [comment]
The version is the current one as per two hours ago. I'm working on Yosemite.

**Comment by samccone** [comment]
so `node 4.1.1`

:)

**Comment by azumbrunnen** [comment]
Yes I have node 4.1.1 installed.
