### ISSUE TITLE
PSK 1.1.0: JS error on Win8/IE11 preventing page render (distributed only)

### ISSUE THREAD

**Issue by eriwen** [PolymerElements/polymer-starter-kit#416]
I'm encountering a couple JS errors that prevent the page from rendering using un-modified polymer-starter-kit-1.1.0.zip. Note that this only occurs after distributing or `gulp serve:dist`

Steps to reproduce
 * Unzip polymer-starter-kit-1.1.0.zip. Install all the things.
 * `gulp serve:dist`
 * Open in IE 11

Here's a screenshot of the JS debugger:
<img width="1280" alt="screen shot 2015-10-03 at 7 08 27 pm" src="https://cloud.githubusercontent.com/assets/51534/10266104/c62cb3c4-6a02-11e5-971d-db5576ff3569.png">

I thought it may be related to the shared styles, so I removed the code related to that and I get a partially rendered page where the `<paper-drawer-panel>` isn't rendered correctly. You can see an example of this on http://www.stacktracejs.com/ in IE11 and IE10.

I wish I could give more detail here, but it only seems to happen after vulcanizing and maybe there's not a way to use source-maps with Polymer.

**Comment by samccone** [comment]
@addyosmani Do you have a windows box to verify this on?

**Comment by plusCubed** [comment]
Windows 10 x64, IE11. Same issue since 1.1.0. I should note it works fine in Edge or any other browser.

**Comment by samccone** [comment]
thanks @plusCubed, we will get the sorted

**Comment by gedw99** [comment]
I have also a failure of the same type
Its starter kit with a few extra standard elements

You can see what i mean here.
https://dev.modern.ie/tools/screenshots/#https://dev-dot-berlininfusions-website.appspot.com/

**Comment by addyosmani** [comment]
@samccone do you have access to a Windows box yet? If not, we can assign this one to me.

**Comment by samccone** [comment]
@addyosmani should have one by EOW

**Comment by sbley** [comment]
Same here with Windows 8 and IE11. A fresh starter kit 1.1.1 shows a blank page after `gulp serve:dist` with the javascript error mentioned above. Starter kit 1.0.3 works fine though.

**Comment by samccone** [comment]
@sbley would you mind trying off of master? We removed polybuild on the tip of the tree

**Comment by sbley** [comment]
@samccone Works fine now, thanks!

**Comment by samccone** [comment]
:+1: :clap:

**Comment by eriwen** [comment]
Thanks folks!
