### ISSUE TITLE
Gulp quits after clean task. 

### ISSUE THREAD

**Issue by pengying** [PolymerElements/polymer-starter-kit#417]
Moving thread https://github.com/PolymerElements/polymer-starter-kit/commit/b756fa270a076ebe6536a374c3a72c5fac6d989a#commitcomment-13586910 to issues

I don't think the problem's been fixed.

Not sure if it's better to return the promise
    
    return del(['.tmp', 'dist'], cb);

or to call the callback

    del(['.tmp', 'dist']).then(function() {cb();});

**Comment by samccone** [comment]
@pengying do you have any steps to reproduce the "bug"

**Comment by pengying** [comment]
Did some research.  I was using `Del 2.0.2`.  `Del 1.2.1` clean works.  I think I was installing modules manually to get a better understanding of what the gulp file was doing.  But it's a useful note for anyone else encountering the clean issue.

**Comment by samccone** [comment]
word, thanks for the research @pengying
