### ISSUE TITLE
Polymber.Base.transform illegal invocation

### ISSUE THREAD

**Issue by tjahelka** [PolymerElements/polymer-starter-kit#418]
When running polymer 1.1.0, the following lines in app.js:addEventListener cause an error

   // Scale bottomContainer and bottom sub title to nothing and back
    Polymer.Base.transform('scale(' + scaleBottom + ') translateZ(0)', bottomContainer);

    // Scale middleContainer appName
    Polymer.Base.transform('scale(' + scaleMiddle + ') translateZ(0)', appName);

Uncaught TypeError: Illegal invocationPolymer.Base._addFeature.transform @ polymer.html:1225(anonymous function) @ app.js:55Polymer.Base._addFeature.fire @ polymer.html:1199Polymer._transformHeader @ paper-scroll-header-panel.html:515Polymer._updateScrollState @ paper-scroll-header-panel.html:586Polymer._scroll @ paper-scroll-header-panel.html:555

**Comment by samccone** [comment]
hey @tjahelka this seems to be a question / debug request related to polymer and not directly to PSK

Would you mind filing this over here?
https://github.com/Polymer/polymer

Thanks!  :sparkles:

**Comment by tjahelka** [comment]
My apologies, I thought since app.js was part of the PSK and that is where the offending code is that this was a PSK issue.  I'll open against polymer.

**Comment by samccone** [comment]
ah, disregard then we will take a look internally since it may be a simple misuse of the code by us, can you give us steps to reproduce your issue? Thanks!

**Comment by tjahelka** [comment]
Please close.  I archived my original PSK and started over and the error is gone.  Comparing the 2, somehow I had a partial/corrupted index.html.  Thank you for your help.
