### ISSUE TITLE
ES6: Investigate 

### ISSUE THREAD

**Issue by ebidel** [PolymerElements/polymer-starter-kit#419]

**Comment by samccone** [comment]
different from? https://github.com/PolymerElements/polymer-starter-kit/blob/master/docs/add-es2015-support-babel.md

**Comment by arthurvr** [comment]
I guess this issue was supposed to be https://github.com/PolymerElements/polymer-starter-kit/issues/420? Can we close this one?

**Comment by samccone** [comment]
sgtm

**Comment by ebidel** [comment]
Yes, https://github.com/PolymerElements/polymer-starter-kit/issues/420 :)
