### ISSUE TITLE
Proposal: global function for tasks directory

### ISSUE THREAD

**Issue by gertcuykens** [PolymerElements/polymer-starter-kit#425]
At the moment the plugin tasks directory is pretty useless because you need to modify the gulpfile anyway. 

What about doing the following so nobody needs to touch the gulpfile.

Create a global function you can define in the tasks folder that does the watch stuff
```js
function watch(){
  gulp.watch(['app/**/*.html'], ['js', reload]);
  gulp.watch(['app/styles/**/*.css'], ['styles', reload]);
  gulp.watch(['app/elements/**/*.css'], ['elements', reload]);
  gulp.watch(['app/{scripts,elements}/**/*.js'], ['jshint', 'js']);
  gulp.watch(['app/images/**/*'], reload);
}
```

Create a global asset 
```js
var assets = $.useref.assets({searchPath: ['.tmp', 'dist']});
```

Just put this block completely in the tasks directory
```
gulp.task('default', ['clean'], function (cb) {
  runSequence(
    ['copy', 'styles'],
    ['elements', 'js'],
    ['jshint', 'images', 'fonts', 'html'],
    'vulcanize', // 'cache-config',
    cb);
});
```

And lastly make a global https variable
```js
var https = false
```

**Comment by gertcuykens** [comment]
So we end up with a default.js in the tasks directorie that looks like this
```js
var https=false

var assets = $.useref.assets({searchPath: ['.tmp', 'dist']});

function myWatch(){
  gulp.watch(['app/**/*.html'], ['js', reload]);
  gulp.watch(['app/styles/**/*.css'], ['styles', reload]);
  gulp.watch(['app/elements/**/*.css'], ['elements', reload]);
  gulp.watch(['app/{scripts,elements}/**/*.js'], ['jshint', 'js']);
  gulp.watch(['app/images/**/*'], reload);
}

gulp.task('default', ['clean'], function (cb) {
  runSequence(
    ['copy', 'styles'],
    ['elements', 'js'],
    ['jshint', 'images', 'fonts', 'html'],
    'vulcanize', // 'cache-config',
    cb);
});
```

**Comment by gertcuykens** [comment]
https://gist.github.com/gertcuykens/b701a557c5019dc41b50

This example works except I can't get it in my task folder default.js :)

**Comment by gertcuykens** [comment]
Its working, only need to get https://github.com/gertcuykens/polymer-starter-kit/blob/master/gulpfile.js#L26-L38 into https://github.com/gertcuykens/polymer-starter-kit/blob/master/tasks/default.js :) Any gulp experts that can comment how to do this?

**Comment by gertcuykens** [comment]
Yeeej its working :D
https://github.com/gertcuykens/polymer-starter-kit/blob/master/gulpfile.js

**Comment by samccone** [comment]
awwweeesome! @gertcuykens mind opening a PR?

**Comment by robdodson** [comment]
Would it be ok if I close this issue so we can just track the work in https://github.com/PolymerElements/polymer-starter-kit/pull/435?

**Comment by gertcuykens** [comment]
closing :)
