### ISSUE TITLE
Service Worker Issue in PSK

### ISSUE THREAD

**Issue by pippintook** [PolymerElements/polymer-starter-kit#427]
:5000/sw-import.js?baseURI=http%3A%2F%2Flocalhost%3A5000%2Fbower_components…platinum-sw-register.html&clientsClaim=true&skipWaiting=true&version=1.0:1 GET http://localhost:5000/sw-import.js?baseURI=http%3A%2F%2Flocalhost%3A5000%2F…2Fplatinum-sw-register.html&clientsClaim=true&skipWaiting=true&version=1.0 net::ERR_FAILED

^^ The error message I get in the console when I run gulp serve on my Polymer Starter Kit project.
I haven't uncommented those blocks of service worker code so I'm not sure why this seems to still be trying to import some sort of sw-import?

**Comment by Holi0317** [comment]
Duplicated #404?

**Comment by pippintook** [comment]
Yeah, that's the same thing. Thanks.
