### ISSUE TITLE
proper way to do styling. Seems broken right now

### ISSUE THREAD

**Issue by gedw99** [PolymerElements/polymer-starter-kit#429]
Shared style dont work in the current PSK.
It needs to be updated to reflect the current docs !
https://www.polymer-project.org/1.0/docs/devguide/styling.html#style-modules

Example:
I take the PaperMenu (from the left nav) out of the index.html, and make it into a custom element in the "elements" folder.
You can see the new element called "my-left.nav" in the index.html:

````
      <paper-scroll-header-panel drawer fixed>

        <!-- Drawer Toolbar -->
        <paper-toolbar id="drawerToolbar">
          <span class="paper-font-title">Logo - User Name (later)</span>
        </paper-toolbar>

        <!-- Drawer Content -->
        <my-left-menu></my-left-menu>

      </paper-scroll-header-panel>
```


Do all the normal correct things to wire it up so it loads when i hit index.html
BANG - styling for it is all gone. I can see the text, so i know its loading.

**Comment by addyosmani** [comment]
Thanks for filing this issue. In master, we have a recommended setup for shared styles that should work out of the box. Could you confirm what version of PSK you were using at the time when you ran into this and whether master addresses the issue you were seeing?

**Comment by gedw99** [comment]
@addyosmani 
This was a while ago and that code has moved on allot.
I was using PSK 1.1.1

I think that its best to close this, which i will do. If i hit this again i will raise a issue
