### ISSUE TITLE
vulcanise and Ignoring duplicate element definition: paper-menu

### ISSUE THREAD

**Issue by gedw99** [PolymerElements/polymer-starter-kit#430]
I upgraded to polymer 1.1.5

i noticed that vulcan now picks up duplicates. Cool

when i gulp, and i get:
```
11:20:04] Starting 'vulcanize'...
Ignoring duplicate element definition: paper-menu
Ignoring duplicate element definition: custom-style
Ignoring duplicate element definition: dom-template
Ignoring duplicate element definition: dom-repeat
Ignoring duplicate element definition: array-selector
Ignoring duplicate element definition: dom-if
Ignoring duplicate element definition: dom-bind
Ignoring duplicate element definition: iron-iconset-svg
Ignoring duplicate element definition: iron-icon
Ignoring duplicate element definition: iron-meta
Ignoring duplicate element definition: iron-meta-query
[11:20:20] Finished 'vulcanize' after 16 s

```

Can it tell me where the duplicate is from ? 
It would make it easier to remove it then in the html element :)

**Comment by ebidel** [comment]
Duplicates are totally fine and it's what vulcanize is for. The output is probably too helpful, and therefore, misleading. You want to keep this imports as is so the elements have their necessary dependencies and can be used without vulcanization. It's job is to find the dupes and prune for you.

**Comment by gedw99** [comment]
Thanks. I get it.
But it would be helpful to know which elements, because then I can learn where there is duplicity in the tree of components ??
