### ISSUE TITLE
Making the left paperDrawerPanel reacting to responsive width

### ISSUE THREAD

**Issue by gedw99** [PolymerElements/polymer-starter-kit#432]
We are trying to make the drawer respond a bit differently from what it does in the demo

    We have the same menu buttons in the top menu & the left drawer panel.
    We want this behaviour.
      when desktop mode (responsiveWidth > 300px):
        - hide hamburger, and hence the left drawerPanel
        - show the top menu
      when mobile mode (responsiveWidth < 300px):
        - show hamburger, and hence on press the left drawerPanel
        - hide the top menu

at the moment the only event i can tap into is:
addEventListener('paper-responsive-change', function(e)
This is after the event, but i really need to get access to the before event

I am wondering if someone can recommend an approach.

**Comment by addyosmani** [comment]
This issue was moved to PolymerElements/paper-drawer-panel#104
