### ISSUE TITLE
app.js accesses internal implementation specific logic, namely an internal id

### ISSUE THREAD

**Issue by Nejat** [PolymerElements/polymer-starter-kit#438]
the following logic in `app.js` makes an assumption by accessing internal implementation specific logic, namely an internal id

```javascript
  // Scroll page to top and expand header
  app.scrollPageToTop = function() {
    document.getElementById('mainContainer').scrollTop = 0;
  };
```

wouldn't it be better to implement this as follows?

```javascript
  // Scroll page to top and expand header
  app.scrollPageToTop = function() {
    document.getElementById('mainArea').scroller.scrollTop = 0;
  };
```

by adding the `id="mainArea"`, *or something similar*, in `index.html`

```html
.
.
.
    </paper-scroll-header-panel>

    <!-- Main Area -->
    <paper-scroll-header-panel id="mainArea" main condenses keep-condensed-header>

    <!-- Main Toolbar -->
.
.
.
```

**Comment by robdodson** [comment]
Working on a PR to fix this: https://github.com/PolymerElements/polymer-starter-kit/pull/431

**Comment by addyosmani** [comment]
I've moved your comment to #379 and am closing this as a dupe. We'll be addressing this issue in #431 as Rob mentions above.
