### ISSUE TITLE
Vulcanize and Root Paths

### ISSUE THREAD

**Issue by vinerz** [PolymerElements/polymer-starter-kit#439]
Hello everyone! I am having issues to deal with mixed depth paths on my app.

For example:

```
http://localhost:5000/login
http://localhost:5000/dialog/authorize
```

Both URLs are resolved to `index.html` on root dir.
The issue comes when I have to access `/dialog/authorize`, because all my assets fail to load.

It could be easily solved by prepending a `/` to the sources and hrefs, so the browser will search those files on the root web directory. When I do this, the development version works perfectly, but then all the gulp tasks (mainly vulcanize) start to yell about not found files because they are now searching for **/**bower_components/polymer/polymer.html, which is now relative to the Ubuntu root directory.

What can I do to fix both sides?

Thanks in advance,
Vinicius

**Comment by jakecoffman** [comment]
I'm having the same exact issue!

If it helps someone figure out what we're doing wrong, here's a diff of what I did to get to the state that @vinerz is describing: https://github.com/jakecoffman/stldevs-frontend/commit/d338b4a77f008d24a1a6e9f5c3f93bdb00a0eed8

**Comment by jakecoffman** [comment]
A workaround for now using hashbangs is to use a rewrite like this: https://github.com/jakecoffman/stldevs-frontend/blob/224ce34ccf702d1e7bceeca03e4fbba3e9eff6f7/nginx

The html5 urls would be nicer though!

**Comment by vinerz** [comment]
Hey Jake, thanks for the tip! Unfortunately, due to a limitation of the project that was previously developed based on real paths, I can't make use of the hashbang feature. At least this issue is not urgent for me because the development works and I don't need to use the dist version for now. I can wait for a solution.

**Comment by chuckh** [comment]
I got deep pretty URLs working on Firebase.com hosting by doing the following:  

**- Adding below rewrites rules to firebase.json**
```
  "firebase": "polymer-starter-kit",
  "public": "dist",
  "ignore": [
    "firebase.json",
    "**/.*",
    "**/node_modules/**"
  ],
  "rewrites": [ {
    "source": "**",
    "destination": "/index.html"
  } ]
}
```

**- Added `<base href="/">` to `head` in index.html**

**-  Set `hashbang: false` in routing.html**

You can see this working at https://polymer-starter-kit.firebaseapp.com/users/Chuck

It also works with `gulp serve` and `gulp serve:dist`! :fireworks: :dancer: :smiley:

**Comment by MeTaNoV** [comment]
+1 ! :)
Is it plan to have a gulp deploy to firebase option in PSK in a near future?

**Comment by chuckh** [comment]
@MeTaNoV I just added a pull request with a Firebase deploy recipe. You can see recipe at: https://github.com/PolymerElements/polymer-starter-kit/blob/firebase-deploy-recipe/docs/deploy-to-firebase-pretty-urls.md.

**Comment by MeTaNoV** [comment]
I like that! Thanks! :+1: :smile_cat:

**Comment by robdodson** [comment]
Sweet! I didn't know Firebase could rewrite urls, that's awesome :D

**Comment by robdodson** [comment]
@vinerz @jakecoffman is this still an issue with the latest PSK? We moved the `bower_components` directory into the `app` dir with this PR https://github.com/PolymerElements/polymer-starter-kit/pull/568
