### ISSUE TITLE
Router styles

### ISSUE THREAD

**Issue by MartinsThiago** [PolymerElements/polymer-starter-kit#440]
I know there's a lot of question about routers, and also several of them on [customelements.io](https://customelements.io) but I feel like there's no one chosen by the community yet... or at least I didn't get one that satisfy-me :sweat_smile:

Is there any plan to have one `iron-router` as `more-routing` is not in the RoadMap OR any suggestion different from `app-router`,`more-routing`,`page.js`?

ps: some thing I would get really happy with, is a routing behavior... some thing I could add to my element then use like `<page-main elm="/foo"> <page-contact elm="/bar">`. I am trying to develop something with this approach... would a route behavior be a good strategy? -> [easy-router](https://github.com/MartinsThiago/easy-router)

**Comment by albertolobrano** [comment]
Looking at https://github.com/PolymerLabs/app-layout/blob/master/bower.json  it looks like the guys from google are working on a new set of components. Maybe they will give us a router :)

**Comment by addyosmani** [comment]
The current state of routing is that we're working on a new routing component which isn't quite ready just yet, but we hope to be in a position to release it early next year. In the mean time, https://github.com/atotic/excess-router is something I'm happy to recommend and https://github.com/atotic/excess-router/blob/master/demo/index.html is a demo that could be intergrated into a PSK app fairly easily. `more-routing` is going to be deprecated in the near future so I'd probably use either excess-router, page.js or a community router in the mean time.
