### ISSUE TITLE
scrollToTop function fails with native shadowdom

### ISSUE THREAD

**Issue by diddledan** [PolymerElements/polymer-starter-kit#441]
When using chrome's native shadowdom, Line 71 of app.js cannot find the element with id of "mainContainer" because it is inside a shadow. This causes javascript execution to die which on my test rig leads to the example iron-page not rendering at all.

I fixed it by replacing line 71 with

    var headerPanel = document.querySelector('paper-scroll-header-panel[main]');
    if (headerPanel) {
      headerPanel.$.mainContainer.scrollTop = 0;
    }

**Comment by addyosmani** [comment]
This is the same issue as https://github.com/PolymerElements/polymer-starter-kit/pull/431 and https://github.com/PolymerElements/polymer-starter-kit/issues/379, right?

**Comment by diddledan** [comment]
sorry, I didn't find those when I did a cursory search. Yes they both appear to be the same issue.
