### ISSUE TITLE
gulp default task doesn't copy images to dist/

### ISSUE THREAD

**Issue by NicolasRannou** [PolymerElements/polymer-starter-kit#446]
On master (https://github.com/PolymerElements/polymer-starter-kit/commit/5672469c8814cfd0227cb2e260e08e51d713b793)

```
$> git clone https://github.com/PolymerElements/polymer-starter-kit.git
$> cd polymer-starter-kit/
$> npm install
$> bower install
$> gulp
$> ls dist/images/touch
<empty>
```

Platform: OSX (10.11.1 Beta (15B38b))
Node: v0.10.21
Gulp: 3.9.0

**Comment by addyosmani** [comment]
Thanks. Confirmed. Dupe of https://github.com/PolymerElements/polymer-starter-kit/issues/257
