### ISSUE TITLE
Polymer.Base.mixin is not a function

### ISSUE THREAD

**Issue by flyntde** [PolymerElements/polymer-starter-kit#447]
This issue may be more general than polymer-starter-kit, but I found it while running PSK version 1.1.0 and 1.1.1.  The problem results in a blank screen and the error messages below in the console:

![screen shot 2015-10-19 at 2 34 43 pm](https://cloud.githubusercontent.com/assets/3250429/10587554/9c518d8a-766f-11e5-8c81-e9d43e4fa369.png)

The error only occurs in Chrome (Version 46.0.2490.71 (64-bit)) but not Safari.  Also, this only occurs in the non-vulcanized PSK.  **gulp serve:dist** does not exhibit the problem.

I tried two different versions of bower (1.5.3 and 1.6.3) --  both exhibit the problem in chrome on a late model macbook pro running os x v10.11

**Comment by robdodson** [comment]
Maybe unrelated but that scroll error makes me wonder. Are you using
webcomponetns.js with shadow dom set to true?

**Comment by flyntde** [comment]
@robdodson:
> Maybe unrelated but that scroll error makes me wonder. Are you using
> webcomponetns.js with shadow dom set to true?

I don't think that is it, because I am using the unaltered index.html that is shipped with the PSK which only uses webcomponents-lite.js.  I did this with several un-altered copies of the PSK, installed via yeoman and also the downloaded zip files for 1.1.0 and 1.1.1.  When I load the page from gulp/browser-sync, I get these errors only in Chrome only on my mac.  The same version of Chrome on an ubuntu machine works fine (PSK 1.1.1), and Safari on my Mac works fine.

In the chrome developer console when the problem occurs, indeed Polymer.Base has no object called mixin after loading index.html.  I even removed and reinstalled Chrome.  Perhaps I can create a JSBIN with a minimal index.html to demonstrate the problem, however it seems to follow my mac and chrome so not sure whether anybody else will be able to see it.  

I  believe the line of code that throws is 19 of accessors.html.  I have not run the debugger yet, but I will let you know if I discover difference between safari and chrome.

**Comment by flyntde** [comment]
closing this and opening new issue https://github.com/Polymer/polymer/issues/2601

This may be related to https://github.com/Polymer/polymer/issues/1911
