### ISSUE TITLE
Is it possible to have custom elements in the head ?

### ISSUE THREAD

**Issue by gedw99** [PolymerElements/polymer-starter-kit#450]
i am generating all icons for all OS's. The pngs, html and manifest.
The current PSK does have them all :) They do keep changing allot.

So, i woudl like to wrap it with a polymer component. 
Is it possible to have custom elements in the head ?

**Comment by addyosmani** [comment]
I personally wouldn't. In browsers that don't natively support Custom Elements, the icons for those OSs will need to wait for the polyfills to be loaded and executed before the content from your element can be correctly parsed and rendered. By not wrapping the icons in an element, the browsers parsers can pick up the icons very early on and it's generally quicker. Can you wrap them? Maybe, but you might run into some interesting timing issues as a side-effect :)

**Comment by gedw99** [comment]
Makes sense. Thanks for feedback.

I will stick with generating into the head at design time for now.
