### ISSUE TITLE
latest version of npm's del module breaks gulp clean

### ISSUE THREAD

**Issue by Nejat** [PolymerElements/polymer-starter-kit#452]
while playing with the latest SPK, from it's github repository, I found that updating the `npm del` module to it's latest version 2.0.2 breaks any `gulp` task that depends on `gulp clean`, though the `clean` task itself seems to work fine.

`package.json` has the following `del` entry: `"del": "^1.1.1",`, which installs version `1.2.1`, when you run `npm install`, which works as expected.

updating any of the other packages to their latest versions, including adding the es6 recipe packages `gulp-babel`, `gulp-crisper` & `gulp-sourcemaps`, does not exhibit the same behavior

reverting `del` back to `1.2.1` seems to eliminate the problem

**Comment by vinerz** [comment]
@Nejat, I've managed to fix this issue by changing this block:

```js
// Clean output directory
gulp.task('clean', function (cb) {
  del(['.tmp', 'dist'], cb);
});
```

to this:

```js
// Clean output directory
gulp.task('clean', function (cb) {
  return del(['.tmp', 'dist'], cb);
});
```

**Comment by moderndeveloperllc** [comment]
There was a ticket a while back where the devs went back and forth on putting that `return` in. Looks like they will have to revisit that if they up the `del` module.

**Comment by samccone** [comment]
>  I found that updating the npm del module to it's latest version 2.0.2

That is correct 2.x is a semver "breaking" bump and why we have it locked :lock: to 1.x
https://github.com/PolymerElements/polymer-starter-kit/blob/master/package.json#L6

manually updating libs to their latest version regardless of what we have in package.json will tend to break things sometimes :)


@Nejat If you would like to open a PR bumping the version and fixing the use to conform to the new API in 2, that would be more than welcome, thanks! :sparkles:
