### ISSUE TITLE
 PSK 1.1.1 on Edge (Win 10) not working at all when vulcanised

### ISSUE THREAD

**Issue by gedw99** [PolymerElements/polymer-starter-kit#453]
Env:
- Server:
 - OSX
 - node 4.0.0
- Browser: 
 - Edge (win 10) inside virtual box

Steps to reproduce:

- download PSK 1.1.1 from website as zip.
- after standard node and bower install.
- Edge browser is running inside Virtual box, and it can reach server using 10.0.2.2, which is default setup.
- start servers:

```
gulp serve
http://10.0.2.2:5000/
- all works fine

gulp serve:dist
http://10.0.2.2:5001/
- blank screen  !!!! Yikes !!!


```

Edge Console of  http://10.0.2.2:5001 gives me:

```
DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
10.0.2.2:5001
HTML1300: Navigation occurred.
10.0.2.2:5001
SCRIPT5007: Unable to get property 'removeChild' of undefined or null reference
index.build.js (6,4395)

```

**Comment by chrissterling** [comment]
Yep same here on both IE11 and Edge and Azure Website as server.

SCRIPT5007: Unable to get property 'removeChild' of undefined or null reference
index.build.js (15,7320)

**Comment by gedw99** [comment]
@chrissterling 
Can you try the meta tag added to the page ?
http://stackoverflow.com/questions/5787245/ie9-javascript-error-script5007-unable-to-get-value-of-the-property-ui-obje

**Comment by gedw99** [comment]
@chrissterling 
i just tested 1.1.1 now and its working in IE11 and edge.

**Comment by addyosmani** [comment]
We're seeing similar wrt everything working in Edge now. Please feel free to ping this issue or open a new one if you notice master broken there.
