### ISSUE TITLE
Question: State problems with routing

### ISSUE THREAD

**Issue by BorntraegerMarc** [PolymerElements/polymer-starter-kit#454]
Hi there

I'm building my polymer app and used PSK 1.1.0 as a starting point. I noticed that polymer somehow is persisting the site state. For example:
When the home site is opening then the user first sees a Welcome text with a little paper-input. When the user changes the value of the input and goes to the contact page and then comes back to the welcome page: the input text is still the same...

Example with my app:
I'm building a registration wizard with two steps and I'm using neon-animated-pages to switch between the paper-cards. When I'm navigating to another page on the last registration step and come back: I'm not at the first step! The state somehow does not reset itself... It should start at the first step again.

Is this behavior desired?

**Comment by albertolobrano** [comment]
Yes it is.  You are working on a single page application,the neon-animated-pages adds or removes elements to the dom without reloading so the state remains the same.  The component that handles the registration should reset it's internal state when you finalize the last step.

**Comment by BorntraegerMarc** [comment]
@albertolobrano Thank you very much! Do you have an example on how to do this? I didn't find a 'reset' method on the neon-animated-pages element.

And how do I know, when I should reset the element? Is there a way to check, when the user changes pages?

Thanks :)

**Comment by robdodson** [comment]
You can handle page changes here in the router: https://github.com/PolymerElements/polymer-starter-kit/blob/master/app/elements/routing.html

The router is using [page.js](https://visionmedia.github.io/page.js/). It'd be worthwhile for you to read through those docs to get an understanding for how it works and what you can do with it.

**Comment by BorntraegerMarc** [comment]
Hi @robdodson 
Thanks for the reply, Going to dig into page.js to see if I can fix the problem... Gonna post the solution if I'm successful...

BTW: Awesome youtube videos :)

**Comment by albertolobrano** [comment]
sorry for my late reply.    Based on your use case i would do a component user registration that handle the wizard.  On the last step, when you leave the wizard and go to another page the component will reset its own internal variables to the starting state.

**Comment by BorntraegerMarc** [comment]
So... We fixed the problem with a big hack...  We now just call 'window.location = 'http://localhost:5000/';'
This of course is a normal redirect and automatically resets everything. It is definitely not a good solution but it works for now... So, I'm closing the issue :)
