### ISSUE TITLE
Why auto executing Polymer object in the custom elements?

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/polymer-starter-kit#456]
Here: [app / elements / my-list / my-list.html](https://github.com/PolymerElements/polymer-starter-kit/blob/master/app/elements/my-list/my-list.html#L27)

And here: [app / elements / my-greeting / my-greeting.html](https://github.com/PolymerElements/polymer-starter-kit/blob/master/app/elements/my-greeting/my-greeting.html#L27)

**Comment by moderndeveloperllc** [comment]
I believe it's so that they can get the `use strict;` into this scope without contaminating the global scope. The Polymer function will execute when the file is included anyways.

**Comment by samccone** [comment]
> they can get the use strict; into this scope without contaminating the global scope

Exactly :)

**Comment by abdonrd** [comment]
Thanks to both!

**Comment by robdodson** [comment]
The [IIFE](https://en.wikipedia.org/wiki/Immediately-invoked_function_expression) also allows you to create private variables that your element can have access to, but aren't available in the global scope.

**Comment by abdonrd** [comment]
Thanks @robdodson! :)
