### ISSUE TITLE
unable to add javascript inside body of index.html

### ISSUE THREAD

**Issue by spidi123q** [PolymerElements/polymer-starter-kit#457]
for particual reason i cant include .js file via router.html. i want it to place before </body> tag.
when i do it in normal way it works fine for testing but when i build project java script disapperars
please help

**Comment by robdodson** [comment]
You're just adding a script tag somewhere in the `<body>`? I wonder if vulcanize is pulling it out for some reason

**Comment by addyosmani** [comment]
@spidi123q could you try this out with the version of PSK in master please? We were previously using `polybuild` for some of our optimisations and there's a small chance one of our other tools (vulcanize or crisper) had an unintended impact on this use case.

**Comment by ThomasShaped** [comment]
I'm having a *similar* problem I think. I'm trying to build an app in Cordova and polybuild always fails at vulcanize because it can't find the cordova.js file. It can't find it because Cordova hasn't injected that file yet!

As far as I can tell there's no way to exclude files from vulcanize using the gulp-plugin, is there?

**Comment by moderndeveloperllc** [comment]
@ThomasShaped You might want to look at the latest gulpfile. They've removed polybuild for the moment due to issues. Perhaps the latest version might help?

**Comment by ThomasShaped** [comment]
@moderndeveloperllc Yeah I had a look and it's working with the code from Master, thanks! Jumped the gun a bit I think! Hope it gets into the next release soon so others don't scratch their head at it like I did.

**Comment by addyosmani** [comment]
Closing as fixed in master. Thanks!
