### ISSUE TITLE
Style var default value for background-image

### ISSUE THREAD

**Issue by kilombo** [PolymerElements/polymer-starter-kit#462]
Hi, i'm new on Polymer, but on my element, i set <code>background-image: var(--myelement-background-image,url(https://elements.polymer-project.org/images/polymer.svg));</code> as a default value and it doesn't work.
With <code>background-color: var(--myelement-background-color, #eee);</code> it works fine.

**Comment by robdodson** [comment]
This is an upstream Polymer issue. I created a bug to track it: https://github.com/Polymer/polymer/issues/3221

**Comment by robdodson** [comment]
I'd like to close this if that's OK since this isn't an issue specific to PSK. Happy to reopen if others disagree.
