### ISSUE TITLE
Split the app-theme.html so a polymerthemes.com file can get dropped in.

### ISSUE THREAD

**Issue by gertcuykens** [PolymerElements/polymer-starter-kit#463]
Currently you can not just replace app-theme.html with one of the generated themes. Example https://polymerthemes.com/custom-style/?base=dark-side make sure you communicate with the style team so changing themes would be replacing a file without touching a single line of code.

PS polymerthemes.com is also part of the polymer team right? Or am I talking to two separate companies :) If so I need to complain at the other side to make it app-theme.html compatible.

**Comment by moderndeveloperllc** [comment]
@gertcuykens Pretty sure that the themes site is not official Google.

**Comment by gertcuykens** [comment]
Thanks I missed that :) closing this one.
