### ISSUE TITLE
Gulp Copy Task: ignoring .DS_Store and other hidden system only files

### ISSUE THREAD

**Issue by Nejat** [PolymerElements/polymer-starter-kit#464]
it would be great if the `gulp copy` task included the following negation to ignore mac's `.DS_Store` settings file in the `gulp.src` command: `'!**/.DS_Store'`

i realize it is a very mac specific request; any alternative generic solution would be great also

i'm going to put the same request to the `gulp` team meanwhile, maybe they come up with a better solution

**Comment by Nejat** [comment]
[Ignoring OS specific files, i.e. files like .DS_Store](https://github.com/gulpjs/gulp/issues/1352)

**Comment by robdodson** [comment]
I submitted a pull request with this change. I agree a more generic solution would be better but it looks like the gulp folks don't have one. I could go either way on this so I'll leave it to the rest of the team to decide. What say you @addyosmani @chuckh @samccone? :+1: or :-1: ?

**Comment by chuckh** [comment]
:+1:

**Comment by samccone** [comment]
:+1:
