### ISSUE TITLE
Don't include __MACOSX or .DS_Store in release

### ISSUE THREAD

**Issue by fredj** [PolymerElements/polymer-starter-kit#469]
A `__MACOSX/` directory and `app/.DS_Store` file are present (at least) in `polymer-starter-kit-light-1.1.1.zip`

**Comment by fredj** [comment]
Only `polymer-starter-kit-light` is affected, not `polymer-starter-kit`

**Comment by addyosmani** [comment]
This is my fault. It's an artefact of our light release process. For future releases, I'll make a note to ensure our tooling needs to avoid those two files.

**Comment by fredj** [comment]
See also #464

**Comment by robdodson** [comment]
Btw I added a PR to address the .DS_Store issue https://github.com/PolymerElements/polymer-starter-kit/pull/618

**Comment by fredj** [comment]
Thanks !
