### ISSUE TITLE
Improve support for pre-built binary versions on Windows

### ISSUE THREAD

**Issue by steinhoff1989** [PolymerElements/polymer-starter-kit#47]
Hi,

I can't open the "polymer-starter-kit-with-checked-in-dependencies-1.0.0.zip".

"The compressed (zipped) folder is invalid..." 

THX

**Comment by nballinger** [comment]
Same here.

**Comment by addyosmani** [comment]
Could you let me know what OS you're on / whether you used a native decompression tool or something third party?

**Comment by steinhoff1989** [comment]
You are right.

Win7 native decompression ist not working.

7zip » worked

**Comment by nballinger** [comment]
Reported corrupt by Win7 SP1 native tool. OK in WinRAR 5 on Win7, unzip
6.00 on CentOS 6.6.

**Comment by addyosmani** [comment]
I've just re-tagged and re-compressed everything with new zip tools. Could you retry?

**Comment by whittssg** [comment]
I just redownloaded and got 2511 errors while extracting using winrar

**Comment by addyosmani** [comment]
Are you on Windows? (the new binaries should just be tar.gz files)

**Comment by addyosmani** [comment]
Btw, for anyone running into this, grab the non-checked in dependencies version https://github.com/PolymerElements/polymer-starter-kit/releases. I'll take a look at the issue you ran into after our talk this morning.

**Comment by nballinger** [comment]
Confirming... polymer-starter-kit-with-checked-in-dependencies-1.0.0.tar.gz,
WinRAR 5, Win7 SP1. 25k+ errors before I aborted.

**Comment by whittssg** [comment]
Yes i am on windows.. Tried with 7zip as well - same issue. I will try the non-checked in version. Thanks

**Comment by addyosmani** [comment]
I've created a new version of the zip on Windows and posted to https://github.com/PolymerElements/polymer-starter-kit/releases/tag/v1.0.0. Could someone verify that the new zip works for them?

**Comment by nballinger** [comment]
Redownloaded polymer-starter-kit-with-checked-in-dependencies-1.0.0.zip.

Win7 SP1 native tools still report the file is corrupt.

Works fine in WinRAR 5.

**Comment by addyosmani** [comment]
Thanks for checking. Fwiw, I couldn't get native SP1 tools to compress (had to use 7-zip).

**Comment by nballinger** [comment]
I tried the same on the unpacked files. Native tools are complaining about
long paths. Might just be SOL on Windows with this.

**Comment by addyosmani** [comment]
Okay. I'm going to close this as fixed now that we have updated zips in the release page, but have added a note that third-party zip tools will need to be used to extract.
