### ISSUE TITLE
in the light version, bower.json does not re-install components in the app/ directory

### ISSUE THREAD

**Issue by steren** [PolymerElements/polymer-starter-kit#474]
In polymer-starter-kit-light-1.1.1.
If I delete the bower_components of the app directory (in order to add everything to git)
And then run bower install, the bower_component folder is created at the root of my project, not in app/bower_component.

**Comment by steren** [comment]
Suggestion is to add a .bowerrc with this content

````
{
  "directory": "app/bower_components/"
}
````

**Comment by addyosmani** [comment]
The light builds should always include a `.bowerrc` file to allow installation in the correct location. Checking out the latest light, it does indeed include such a file with the content:

```
{
	"directory": "app/bower_components/"
}
```

Are you sure you don't have a `.bowerrc` file somewhere else in the same path that might be overriding this location?

**Comment by steren** [comment]
My bad, there is indeed the correct .bowerrc.
I have probably missed it in a copy paste.
