### ISSUE TITLE
Question: Nested routing

### ISSUE THREAD

**Issue by DmT021** [PolymerElements/polymer-starter-kit#475]
Hi. Is there a way to define nested routes?
For example, an application can have the following routes:
```
/login
/landing
/main
    /foo
    /bar
```
where `/foo` and `/bar` are sub-routes of `/main`.
What I want is to declare an element for `/main`, and process all sub-routes inside that element without managing the prefix `/main`.
But the page.js is designed to have flat routes structure. I mean all routes are declared with full paths.
The express 4 router is more flexible in this case, because it uses `use` function to build chains of routes.
So, is there something that can help me?

**Comment by robdodson** [comment]
I don't think page.js does anything like what you're describing. The Polymer team is working on a forthcoming router but that's still work-in-progress. We're also not tied to page.js, if you find another client side router that you prefer which has this feature it should be easy to swap out.

@addyosmani @samccone @chuckh should we keep this issue open or close or...?

**Comment by robdodson** [comment]
Going to close but happy to reopen if folks think we need it.

I think `router.js` will give you nesting route behavior. You could swap out page.js for this if you like: https://github.com/tildeio/router.js/
