### ISSUE TITLE
Weird unmet dependencies on Windows 10 / Node 4.2.1

### ISSUE THREAD

**Issue by roelofr** [PolymerElements/polymer-starter-kit#476]
I am having a hard time getting all the dependencies installed on my system. It's probably something on my end, but I figured, asking won't hurt.

## Expected outcome

Everything gets installed, everyone is happy, we can throw a party.

## Actual outcome

```
npm WARN unmet dependency F:\development\xyz.polymer-starter-kit\node_modules\web-component-tester requires glob@'^4.0.6' but will load
npm WARN unmet dependency F:\development\xyz.polymer-starter-kit\node_modules\glob,
npm WARN unmet dependency which is version 5.0.15
npm WARN unmet dependency F:\development\xyz.polymer-starter-kit\node_modules\gulp-autoprefixer\node_modules\gulp-util requires object-assign@'^3.0.0' but will load
npm WARN unmet dependency F:\development\xyz.polymer-starter-kit\node_modules\gulp-autoprefixer\node_modules\object-assign,
npm WARN unmet dependency which is version 2.1.1
npm WARN unmet dependency F:\development\xyz.polymer-starter-kit\node_modules\gulp-autoprefixer\node_modules\gulp-util requires through2@'^2.0.0' but will load
npm WARN unmet dependency F:\development\xyz.polymer-starter-kit\node_modules\gulp-autoprefixer\node_modules\through2,
npm WARN unmet dependency which is version 0.6.5
npm WARN unmet dependency F:\development\xyz.polymer-starter-kit\node_modules\gulp-imagemin\node_modules\gulp-util requires object-assign@'^3.0.0' but will load
npm WARN unmet dependency F:\development\xyz.polymer-starter-kit\node_modules\gulp-imagemin\node_modules\object-assign,
npm WARN unmet dependency which is version 4.0.1
npm WARN unmet dependency F:\development\xyz.polymer-starter-kit\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\vinyl-fs requires merge-stream@'^1.0.0' but will load
npm WARN unmet dependency F:\development\xyz.polymer-starter-kit\node_modules\merge-stream,
npm WARN unmet dependency which is version 0.1.8
```
I tried running this in MSYS2 and good ol' cmd but to no avail. I'm running node 4.2.1, more information below:
```js
{
	npm: '2.14.7',
	ares: '1.10.1-DEV',
	http_parser: '2.5.0',
	icu: '56.1',
	modules: '46',
	node: '4.2.1',
	openssl: '1.0.2d',
	uv: '1.7.5',
	v8: '4.5.103.35',
	zlib: '1.2.8'
}
```

I used a fresh clone (3cd9c27e845ef9becae9891746a1561b801f4477).

As said, this could just be me

## Steps to reproduce

1. Clone the repository, install node.js v4.2.1 (LTS)
2. Run `bower install` and `npm install`

**Comment by peter-mueller** [comment]
For me nodejs was installed in .../Program Files (x86)/nodejs and i had the same problem.

1. Uninstall NodeJS
2. Remove node_modules folder in der PSK (`rd /S node_modules`) 
3. Install NodeJS in a path without spaces (e.g `C:/nodejs`)
4. `npm install -g gulp bower && npm install && bower install`

This made it work **for me**.

**Comment by roelofr** [comment]
@peter-mueller Thanks, that did the trick. Turns out some dependencies create paths longer than Windows's max length (which is really just stupid, but well...).

Installing Node in C:\tools\node and moving the cache from appdata to C:\tools\npm-cache (`npm config set cache` for those with the same problems) solved the issue.
