### ISSUE TITLE
WCT tests fail out of the box

### ISSUE THREAD

**Issue by cayblood** [PolymerElements/polymer-starter-kit#477]
I'm getting the following errors when trying to run the web component tests after running npm install and bower install:

<pre>
∴ gulp test:local
[21:28:02] Using gulpfile ~/Source/work/newplasma/imprompter/gulpfile.js
[21:28:02] Starting 'wct:local'...
Installing and starting Selenium server for local browsers
Selenium server running on port 55503
Web server running on port 2000 and serving from /Users/carl/Source/work/newplasma/imprompter
safari 9.0.1             Beginning tests via http://localhost:2000/components/imprompter/generated-index.html?cli_browser_id=2
404 GET /components/imprompter/bower_components/webcomponentsjs/webcomponents.min.js
404 GET /components/imprompter/bower_components/webcomponentsjs/webcomponents.min.js
404 GET /components/imprompter/bower_components/test-fixture/test-fixture-mocha.js
safari 9.0.1             ✖ app/test/my-greeting-basic.html » my-greeting tests » "before each" hook for "Welcome!"

  Can't find variable: fixture
    <unknown> at   <unknown> at my-greeting-basic.html:40:0

404 GET /components/imprompter/bower_components/webcomponentsjs/webcomponents.min.js
404 GET /components/imprompter/bower_components/test-fixture/test-fixture-mocha.js
safari 9.0.1             ✖ app/test/my-list-basic.html » my-list tests » "before each" hook for "Item lengths should be equalled"

  Can't find variable: fixture
    <unknown> at   <unknown> at my-list-basic.html:39:0

safari 9.0.1             Tests failed: 2 failed tests
chrome 46                Beginning tests via http://localhost:2000/components/imprompter/generated-index.html?cli_browser_id=0
404 GET /components/imprompter/bower_components/webcomponentsjs/webcomponents.min.js
404 GET /components/imprompter/bower_components/webcomponentsjs/webcomponents.min.js
404 GET /components/imprompter/bower_components/test-fixture/test-fixture-mocha.js
404 GET /components/imprompter/bower_components/test-fixture/test-fixture.html
firefox 39               Beginning tests via http://localhost:2000/components/imprompter/generated-index.html?cli_browser_id=1
404 GET /components/imprompter/bower_components/webcomponentsjs/webcomponents.min.js
chrome 46                ✖ app/test/my-greeting-basic.html » my-greeting tests » "before each" hook for "Welcome!"

  fixture is not defined
    <unknown> at   Context.<anonymous> at my-greeting-basic.html:40:0

404 GET /components/imprompter/bower_components/webcomponentsjs/webcomponents.min.js
404 GET /components/imprompter/bower_components/test-fixture/test-fixture-mocha.js
404 GET /components/imprompter/bower_components/test-fixture/test-fixture.html
chrome 46                ✖ app/test/my-list-basic.html » my-list tests » "before each" hook for "Item lengths should be equalled"

  fixture is not defined
    <unknown> at   Context.<anonymous> at my-list-basic.html:39:0

chrome 46                Tests failed: 2 failed tests
404 GET /components/imprompter/bower_components/webcomponentsjs/webcomponents.min.js
404 GET /components/imprompter/bower_components/test-fixture/test-fixture-mocha.js
404 GET /components/imprompter/bower_components/test-fixture/test-fixture-mocha.js
firefox 39               ✖ app/test/my-greeting-basic.html » my-greeting tests » "before each" hook for "Welcome!"

  fixture is not defined
    <unknown> at   <unknown> at my-greeting-basic.html:40:0

404 GET /components/imprompter/bower_components/webcomponentsjs/webcomponents.min.js
404 GET /components/imprompter/bower_components/test-fixture/test-fixture-mocha.js
404 GET /components/imprompter/bower_components/test-fixture/test-fixture-mocha.js
firefox 39               ✖ app/test/my-list-basic.html » my-list tests » "before each" hook for "Item lengths should be equalled"

  fixture is not defined
    <unknown> at   <unknown> at my-list-basic.html:39:0

firefox 39               Tests failed: 2 failed tests
Test run ended in failure: 2 failed tests

chrome 46 (0/0/2)                       firefox 39 (0/0/2)                      safari 9.0.1 (0/0/2)
[21:28:07] 'wct:local' errored after 5.02 s
[21:28:07] Error: 2 failed tests
</pre>

**Comment by cayblood** [comment]
The following patch fixed this issue:

<pre>
∴ git diff
diff --git a/wct.conf.js b/wct.conf.js
index 2ea6e1e..a292938 100644
--- a/wct.conf.js
+++ b/wct.conf.js
@@ -10,8 +10,7 @@ var ret = {
 var mapping = {};
 var rootPath = (__dirname).split(path.sep).slice(-1)[0];

-mapping['/components/' + rootPath  +
-'/app/bower_components'] = 'bower_components';
+mapping['/components/' + rootPath + '/bower_components'] = 'app/bower_components';

 ret.webserver.pathMappings.push(mapping);
</pre>

**Comment by addyosmani** [comment]
@samccone were you able to reproduce this when testing? I've pulled latest master and the WCT tests are running fine for me on Mac. 

```
Web server running on port 2000 and serving from /Users/addyo/projects/io-workspace/polymer-starter-kit
safari 9.0.1             Beginning tests via http://localhost:2000/components/polymer-starter-kit/generated-index.html?cli_browser_id=3
chrome 47                Beginning tests via http://localhost:2000/components/polymer-starter-kit/generated-index.html?cli_browser_id=0
safari 9.0.1             Tests passed
chrome 48                Beginning tests via http://localhost:2000/components/polymer-starter-kit/generated-index.html?cli_browser_id=1
chrome 47                Tests passed
chrome 48                Tests passed
firefox 41               Beginning tests via http://localhost:2000/components/polymer-starter-kit/generated-index.html?cli_browser_id=2
firefox 41               Tests passed
Test run ended with great success

chrome 47 (2/0/0)                       chrome 48 (2/0/0)
firefox 41 (2/0/0)                      safari 9.0.1 (2/0/0)
[09:31:04] Finished 'wct:local' after 11 s
[09:31:04] Starting 'test:local'...
[09:31:04] Finished 'test:local' after 22 μs
```

**Comment by cayblood** [comment]
I just downloaded the 1.1.1 release, so this may have been fixed already in master, for all I know.

**Comment by samccone** [comment]
yep @addyosmani tests locally for me pass .... @cayblood let us know!

**Comment by cayblood** [comment]
Yes, master appears to be working. I would recommend making another release soon, as your downloadable release appears to be broken.

**Comment by peramsathyam** [comment]
@addyosmani:
What is workaround you did fixing the issue with Safari Driver
```
Error: Until Selenium's SafariDriver supports Safari 6.2+, 7.1+, & 8.0+, you must
manually install it. Follow the steps at:
https://github.com/SeleniumHQ/selenium/wiki/SafariDriver#getting-started
```

Should I have to sign-up for the paid individual apple developer program and the build the driver my own?

**Comment by peramsathyam** [comment]
I did this work around.
Instead of the latest selenium web driver 
- Downloaded selenium-2.44 
- Unziped the jar file `selenium-server-2.44.0.jar` 
- Double clicked the safari extension at the path `org/openqa/selenium/safari/SafariDriver.safariextz` 

Then I am able to run the test successfully with `gulp test:local`
````
18:42:45] Starting 'wct:local'...
Installing and starting Selenium server for local browsers
Selenium server running on port 49298
Web server running on port 2000 and serving from /Users/jpnath/Develop/Production/weavler-webshop
safari 9.0.3             Beginning tests via http://localhost:2000/components/weavler-webshop/generated-index.html?cli_browser_id=2
chrome 48                Beginning tests via http://localhost:2000/components/weavler-webshop/generated-index.html?cli_browser_id=0

firefox 44               Beginning tests via http://localhost:2000/components/weavler-webshop/generated-index.html?cli_browser_id=1
safari 9.0.3             Tests passed
firefox 44               Tests passed
chrome 48                Tests passed
Test run ended with great success
```
