### ISSUE TITLE
Question: Convert light to full install

### ISSUE THREAD

**Issue by janjtv** [PolymerElements/polymer-starter-kit#483]
Is there an easy way to convert a light to a full install? Or do i need to manually copy and paste the important files over?

**Comment by arthurvr** [comment]
> Or do i need to manually copy and paste the important files over?

I don't think we have a much easier way, so yes. You might still run into some compatibility issues though, when the tooling depends on the actual file content. Also don't forget to install dependencies.

This is why I don't like encouraging the use of the light version though. When apps scale up the tooling gets more and more welcome.

**Comment by robdodson** [comment]
I'm going to close this but happy to reopen if folks feel this needs more discussion
