### ISSUE TITLE
Gulp not working in PSK 1.1.0

### ISSUE THREAD

**Issue by kenny0202** [PolymerElements/polymer-starter-kit#487]
I was using PSK 1.0.3 few months back and gulp vulcanized and build everything fine. 

I started on a new project using PSK 1.1.0. When I ran "gulp" it only ran 2 lines then the process stopped without any error. Only the images folder was the output of the vulcanize.

The 2 lines that spit out when running gulp are

"using gulpfile ...gulpfile.js"
"Starting 'clean'..."

Then the process stops. 

Is this a known issue in 1.1.x?

**Comment by addyosmani** [comment]
Could you try the latest version in master with a fresh `npm install` and let us know if you run into the same issue? If you could share your version of Node and Gulp too that would be appreciated.

**Comment by kenny0202** [comment]
I created a new directory and extracted the 1.1.0 PSK, ran gulp and it worked fine. 

Node is 0.12.7 Gulp is 3.9.0

Did the fresh npm install, but the same 2 lines ran then process exited.

**Comment by moderndeveloperllc** [comment]
@kenny0202 I ran into this with having `del 2.0.2` in my `node-modules` directory. PR #490 fixed this a few hours ago. You would need to download the latest master/ branch that fixes the `delete` function in the gulp file.

**Comment by addyosmani** [comment]
This should no longer be an issue in master.
