### ISSUE TITLE
app-name scaling broken

### ISSUE THREAD

**Issue by chuckh** [PolymerElements/polymer-starter-kit#491]
app-name is always scaled to 0.5 (50%): 

![image](https://cloud.githubusercontent.com/assets/19915/11042280/0ddd3f92-86cb-11e5-817b-43a7e7faf537.png)

app-name should be this when expanded:
![image](https://cloud.githubusercontent.com/assets/19915/11042330/47964382-86cb-11e5-80c7-4a40a4a6cab2.png)

**Comment by addyosmani** [comment]
Thanks folks!
