### ISSUE TITLE
Polymer Starter Kit not compatible with firefox's webcomponents flag

### ISSUE THREAD

**Issue by jlgerber** [PolymerElements/polymer-starter-kit#495]
When attempting to load the starter kit without modifications, it white screens when you turn on firefox's webcomponents experimental features flag. What is going on?

**Comment by samccone** [comment]
@jlgerber are there any errors in console? What version of firefox are you on?

**Comment by robdodson** [comment]
This is a known issue. Unless it's been recently updated the Firefox webcomponents stuff is pretty outdated

**Comment by samccone** [comment]
kk closing this for now then
