### ISSUE TITLE
Navigaton issue in Safari

### ISSUE THREAD

**Issue by michelecos** [PolymerElements/polymer-starter-kit#498]
In Safari 9.0.1 on El Capitan 10.11.1 I have the following issue:

clicking exactly on the labels or the icons in the sidebar, that is inside the <svg> element, or on the <span> *Users* or *Contact*, the box containing the link gets focused, but navigation is not invoked. On a second click navigation happens normally.
On the other hand, clicking in the empty area in the box of *Users* or *Contact*, inside the <a>, the box gets focused and navigation in the content area is correct.
This does not happen with Safari on iOS. Verified on an iPad and an iPhone, both with iOS 9.

**Comment by addyosmani** [comment]
Just to confirm: are you seeing this behaviour in the version that's in master?

**Comment by michelecos** [comment]
Yes, downloaded the zip yesterday evening

Michele Costabile
michelecos@yahoo.com

**Comment by gedw99** [comment]
+1 i had this too and have it now on a clean PSK 1.1.1 on safari and FF

its been there for ages and still not fixed. sorry to say it.
1. if you click on the white space, works on all browsers
2. if you click on the text, it needs two clicks on safari and ff.

**Comment by samccone** [comment]
@michelecos @gedw99 any interest in investigating a patch for this?

**Comment by chuckh** [comment]
This has been fixed in master with pr #470. You go to https://polymer-starter-kit.firebaseapp.com with Safari and Firebox and test.

**Comment by gedw99** [comment]
thanks @chuckh

**Comment by michelecos** [comment]
OK, bug fixed

Michele Costabile
michelecos@yahoo.com
