### ISSUE TITLE
Error with gulp build

### ISSUE THREAD

**Issue by damibarbieri** [PolymerElements/polymer-starter-kit#504]
Win 8.1
PSK 1.1.0
npm 2.10.1

```
$ gulp serve
[18:06:39] Using gulpfile c:\Users\damian.barbieri\codelabe\polymer-starter-kit-
1.1.0\polymer-starter-kit-1.1.0\gulpfile.js
[18:06:39] Starting 'styles'...
[18:06:41] Starting 'elements'...
[18:06:41] Starting 'images'...
[18:06:41] Finished 'elements' after 515 ms
Unhandled rejection Error: spawn c:\Users\damian.barbieri\codelabe\polymer-start
er-kit-1.1.0\polymer-starter-kit-1.1.0\node_modules\gulp-imagemin\node_modules\i
magemin\node_modules\imagemin-optipng\node_modules\optipng-bin\vendor\optipng.ex
e ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)
[18:06:41] styles all files 98 B
[18:06:41] Finished 'styles' after 2.47 s
```

Any help appreciated!

Thanks

**Comment by samccone** [comment]
@damibarbieri when you typed npm install what kind of errors did you get?

it looks like you are having issues installing some native extensions

**Comment by damibarbieri** [comment]
I did the whole thing again and I got this big list of errors & warnings. It didn't happen the first time...

$ npm install
\


> gifsicle@3.0.1 postinstall c:\Users\damian.barbieri\codelabe\polymer-starter-k
it-1.1.0\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\imagemin-
gifsicle\node_modules\gifsicle
> node lib/install.js

module.js:338
    throw err;
          ^
Error: Cannot find module 'readable-stream/transform'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (c:\Users\damian.barbieri\codelabe\polymer-starter-kit
-1.1.0\node_modules\gulp-imagemin\node_modules\gulp-util\node_modules\through2\t
hrough2.js:1:79)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)



> optipng-bin@3.0.2 postinstall c:\Users\damian.barbieri\codelabe\polymer-starte
r-kit-1.1.0\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\imagem
in-optipng\node_modules\optipng-bin
> node lib/install.js

module.js:338
    throw err;
          ^
Error: Cannot find module 'readable-stream/transform'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (c:\Users\damian.barbieri\codelabe\polymer-starter-kit
-1.1.0\node_modules\gulp-imagemin\node_modules\gulp-util\node_modules\through2\t
hrough2.js:1:79)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
npm WARN optional dep failed, continuing imagemin-gifsicle@4.2.0


> jpegtran-bin@3.0.5 postinstall c:\Users\damian.barbieri\codelabe\polymer-start
er-kit-1.1.0\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\image
min-jpegtran\node_modules\jpegtran-bin
> node lib/install.js

module.js:338
    throw err;
          ^
Error: Cannot find module 'readable-stream/transform'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (c:\Users\damian.barbieri\codelabe\polymer-starter-kit
-1.1.0\node_modules\gulp-imagemin\node_modules\gulp-util\node_modules\through2\t
hrough2.js:1:79)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
npm WARN optional dep failed, continuing imagemin-optipng@4.3.0
npm WARN optional dep failed, continuing imagemin-jpegtran@4.3.1
npm WARN optional dep failed, continuing fsevents@1.0.5
npm WARN optional dep failed, continuing imagemin-svgo@4.1.2
\


> bufferutil@1.2.1 install c:\Users\damian.barbieri\codelabe\polymer-starter-kit
-1.1.0\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-c
lient\node_modules\engine.io-client\node_modules\ws\node_modules\bufferutil
> node-gyp rebuild

/
c:\Users\damian.barbieri\codelabe\polymer-starter-kit-1.1.0\node_modules\browser
-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.i
not defined npm_config_node_gyp (node "c:\Program Files (x86)\nodejs\node_module
s\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )
else (rebuild)
Los proyectos de esta solución se van a compilar de uno en uno. Para habilitar l
a compilación en paralelo, agregue el modificador "/m".
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.t
argets(55,5): error MSB8020: The build tools for Visual Studio 2010 (Platform T
oolset = 'v100') cannot be found. To build using the v100 build tools, please i
nstall Visual Studio 2010 build tools.  Alternatively, you may upgrade to the c
urrent Visual Studio tools by selecting the Project menu or right-click the sol
ution, and then selecting "Retarget solution". [c:\Users\damian.barbieri\codela
be\polymer-starter-kit-1.1.0\node_modules\browser-sync\node_modules\socket.io\n
ode_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node
_modules\bufferutil\build\bufferutil.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\Program Files (x86)\nodejs\node_mo
dules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074
:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "c:\\Program Files (x86)\\nodejs\\node_modules\\npm\\nod
e_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\Users\damian.barbieri\codelabe\polymer-starter-kit-1.1.0\node_mo
dules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_mod
ules\engine.io-client\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok

> bufferutil@1.2.1 install c:\Users\damian.barbieri\codelabe\polymer-starter-kit
-1.1.0\node_modules\browser-sync\node_modules\socket.io\node_modules\engine.io\n
ode_modules\ws\node_modules\bufferutil
> node-gyp rebuild


c:\Users\damian.barbieri\codelabe\polymer-starter-kit-1.1.0\node_modules\browser
-sync\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules
\bufferutil>if not defined npm_config_node_gyp (node "c:\Program Files (x86)\nod
ejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.
js" rebuild )  else (rebuild)
Los proyectos de esta solución se van a compilar de uno en uno. Para habilitar l
a compilación en paralelo, agregue el modificador "/m".
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.t
argets(55,5): error MSB8020: The build tools for Visual Studio 2010 (Platform T
oolset = 'v100') cannot be found. To build using the v100 build tools, please i
nstall Visual Studio 2010 build tools.  Alternatively, you may upgrade to the c
urrent Visual Studio tools by selecting the Project menu or right-click the sol
ution, and then selecting "Retarget solution". [c:\Users\damian.barbieri\codela
be\polymer-starter-kit-1.1.0\node_modules\browser-sync\node_modules\socket.io\n
ode_modules\engine.io\node_modules\ws\node_modules\bufferutil\build\bufferutil.
vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\Program Files (x86)\nodejs\node_mo
dules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074
:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "c:\\Program Files (x86)\\nodejs\\node_modules\\npm\\nod
e_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\Users\damian.barbieri\codelabe\polymer-starter-kit-1.1.0\node_mo
dules\browser-sync\node_modules\socket.io\node_modules\engine.io\node_modules\ws
\node_modules\bufferutil
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm WARN optional dep failed, continuing bufferutil@1.2.1

> utf-8-validate@1.2.1 install c:\Users\damian.barbieri\codelabe\polymer-starter
-kit-1.1.0\node_modules\browser-sync\node_modules\socket.io\node_modules\engine.
io\node_modules\ws\node_modules\utf-8-validate
> node-gyp rebuild


c:\Users\damian.barbieri\codelabe\polymer-starter-kit-1.1.0\node_modules\browser
-sync\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules
\utf-8-validate>if not defined npm_config_node_gyp (node "c:\Program Files (x86)
\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-
gyp.js" rebuild )  else (rebuild)
Los proyectos de esta solución se van a compilar de uno en uno. Para habilitar l
a compilación en paralelo, agregue el modificador "/m".
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.t
argets(55,5): error MSB8020: The build tools for Visual Studio 2010 (Platform T
oolset = 'v100') cannot be found. To build using the v100 build tools, please i
nstall Visual Studio 2010 build tools.  Alternatively, you may upgrade to the c
urrent Visual Studio tools by selecting the Project menu or right-click the sol
ution, and then selecting "Retarget solution". [c:\Users\damian.barbieri\codela
be\polymer-starter-kit-1.1.0\node_modules\browser-sync\node_modules\socket.io\n
ode_modules\engine.io\node_modules\ws\node_modules\utf-8-validate\build\validat
ion.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\Program Files (x86)\nodejs\node_mo
dules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074
:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "c:\\Program Files (x86)\\nodejs\\node_modules\\npm\\nod
e_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\Users\damian.barbieri\codelabe\polymer-starter-kit-1.1.0\node_mo
dules\browser-sync\node_modules\socket.io\node_modules\engine.io\node_modules\ws
\node_modules\utf-8-validate
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm WARN optional dep failed, continuing bufferutil@1.2.1

> utf-8-validate@1.2.1 install c:\Users\damian.barbieri\codelabe\polymer-starter
-kit-1.1.0\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.
io-client\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-valid
ate
> node-gyp rebuild


c:\Users\damian.barbieri\codelabe\polymer-starter-kit-1.1.0\node_modules\browser
-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.i
o-client\node_modules\ws\node_modules\utf-8-validate>if not defined npm_config_n
ode_gyp (node "c:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\
..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
Los proyectos de esta solución se van a compilar de uno en uno. Para habilitar l
a compilación en paralelo, agregue el modificador "/m".
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.t
argets(55,5): error MSB8020: The build tools for Visual Studio 2010 (Platform T
oolset = 'v100') cannot be found. To build using the v100 build tools, please i
nstall Visual Studio 2010 build tools.  Alternatively, you may upgrade to the c
urrent Visual Studio tools by selecting the Project menu or right-click the sol
ution, and then selecting "Retarget solution". [c:\Users\damian.barbieri\codela
be\polymer-starter-kit-1.1.0\node_modules\browser-sync\node_modules\socket.io\n
ode_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node
_modules\utf-8-validate\build\validation.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\Program Files (x86)\nodejs\node_mo
dules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074
:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "c:\\Program Files (x86)\\nodejs\\node_modules\\npm\\nod
e_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\Users\damian.barbieri\codelabe\polymer-starter-kit-1.1.0\node_mo
dules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_mod
ules\engine.io-client\node_modules\ws\node_modules\utf-8-validate
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.2.1
npm WARN optional dep failed, continuing utf-8-validate@1.2.1
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "c:\\Program Files (x86)\\nodejs\\node.exe" "c:\\Program Files (x8
6)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! path C:\Users\damian.barbieri\AppData\Roaming\npm-cache\array-differ\1.
0.0\package\package.json
npm ERR! code EPERM
npm ERR! errno -4048

npm ERR! Error: EPERM, rename 'C:\Users\damian.barbieri\AppData\Roaming\npm-cach
e\array-differ\1.0.0\package\package.json'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM, rename 'C:\Users\damian.barbieri\AppData\Roaming\npm-
cache\array-differ\1.0.0\package\package.json']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   path: 'C:\\Users\\damian.barbieri\\AppData\\Roaming\\npm-cache\\array
-differ\\1.0.0\\package\\package.json',
npm ERR!   parent: 'gulp-util' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Users\damian.barbieri\codelabe\polymer-starter-kit-1.1.0\npm-deb
ug.log
/c/Program Files (x86)/nodejs/npm: line 14:  6180 Signal 112              (core
dumped) "$basedir/node.exe" "$basedir/node_modules/npm/bin/npm-cli.js" "$@"

**Comment by damibarbieri** [comment]
Then I run it again and see an issue when node-gyp and MSBuild...

> bufferutil@1.2.1 install c:\Users\damian.barbieri\codelabe\polymer-starter-kit
-1.1.0\node_modules\web-component-tester\node_modules\socket.io\node_modules\soc
ket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\bufferu
til
> node-gyp rebuild


c:\Users\damian.barbieri\codelabe\polymer-starter-kit-1.1.0\node_modules\web-com
ponent-tester\node_modules\socket.io\node_modules\socket.io-client\node_modules\
engine.io-client\node_modules\ws\node_modules\bufferutil>if not defined npm_conf
ig_node_gyp (node "c:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-b
in\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
Los proyectos de esta solución se van a compilar de uno en uno. Para habilitar l
a compilación en paralelo, agregue el modificador "/m".
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets
(5039,39): error MSB4023: No se pueden evaluar los metadatos del elemento "%(Fu
llPath)". Los metadatos del elemento "%(FullPath)" no pueden aplicarse a la rut
a de acceso "Release\obj\bufferutil\bufferutil.node". c:\Users\damian.barbieri\
codelabe\polymer-starter-kit-1.1.0\node_modules\web-component-tester\node_modul
es\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_m
odules\ws\node_modules\bufferutil\build\Release\obj\bufferutil\bufferutil.node
[c:\Users\damian.barbieri\codelabe\polymer-starter-kit-1.1.0\node_modules\web-c
omponent-tester\node_modules\socket.io\node_modules\socket.io-client\node_modul
es\engine.io-client\node_modules\ws\node_modules\bufferutil\build\bufferutil.vc
xproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\Program Files (x86)\nodejs\node_mo
dules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074
:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "c:\\Program Files (x86)\\nodejs\\node_modules\\npm\\nod
e_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\Users\damian.barbieri\codelabe\polymer-starter-kit-1.1.0\node_mo
dules\web-component-tester\node_modules\socket.io\node_modules\socket.io-client\
node_modules\engine.io-client\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.2.1

**Comment by samccone** [comment]
hi @damibarbieri thanks for the info, it looks like you are running into some windows specific compile errors when it is trying to build image-opt

Check out my response here for how to fix your compiler setup:
https://github.com/PolymerElements/polymer-starter-kit/issues/500#issuecomment-155615307

If you do not want to mess with this, you could just remove image-opt from your package.json and then comment out this line
https://github.com/PolymerElements/polymer-starter-kit/blob/master/gulpfile.js#L131

---
xref

https://github.com/PolymerElements/polymer-starter-kit/issues/505


---

let me know if you run into any thing else

**Comment by damibarbieri** [comment]
thanks @samccone ! I was able to work this out eventually :smiley: ! :+1:

**Comment by damibarbieri** [comment]
hi @samccone. I am having this scenario now:
$  gulp serve
[17:56:35] Using gulpfile c:\Users\damian.barbieri\codelab\polymer-starter-kit\g
ulpfile.js
[17:56:35] Starting 'lint'...
[17:56:36] Starting 'styles'...
[17:56:36] Starting 'elements'...
[17:56:36] Starting 'images'...
[17:56:36] Finished 'elements' after 160 ms

events.js:141
      throw er; // Unhandled 'error' event
      ^
 Error: spawn c:\Users\damian.barbieri\codelab\polymer-starter-kit\node_modules\
optipng-bin\vendor\optipng.exe ENOENT
    at exports._errnoException (util.js:860:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:450:9)
    at process._tickCallback (node.js:364:17)

I tried commenting the suggested line and removed the gulp-imagemin from my package.json. But when I run gulp serve I got that the images task was not defined. I didn't want to mess with the gulpfile more as I'm not used to.

**Comment by samccone** [comment]
@damibarbieri you will need to edit your gulp file also to fully remove it, it looks like the same error though, try rm -rf your node_modules and install again

**Comment by damibarbieri** [comment]
@samccone after re-installing a few gulp plugins it eventually worked! However, is there any cookbook to make this work smoothly on Windows? I spent some time reading all the open issues in node-gyp and so, but I didn't have any luck with those answers :disappointed:
