### ISSUE TITLE
only run image opt on deploy

### ISSUE THREAD

**Issue by samccone** [PolymerElements/polymer-starter-kit#505]
There is no need to run this for normal serve, and really only needs to be run when you deploy.
There are quite a few install issues on non osx platforms with image opt as well, so this might help to cut down on the volume of issues that we get as well.

thoughts?

**Comment by addyosmani** [comment]
When you say only run on `deploy`, I'm reading this as only run during production build (precursor to deploy). Could you confirm that's what you mean? If so, I'm :100: down for us not running image opt during serve as long as we're ensuring image paths for assets dropped in continue to function as expected.
