### ISSUE TITLE
Automate deploy PSK to GitHub Pages

### ISSUE THREAD

**Issue by chuckh** [PolymerElements/polymer-starter-kit#507]
These are the steps to deploy to http://polymerelements.github.io/polymer-starter-kit:

1. Uncomment this line `// app.baseUrl = '/polymer-starter-kit/';` in app.js near the top and save
2. Run `gulp test:local` and `gulp serve` and test
3. If all is ok run `gulp build-deploy-gh-pages`
4. Go to http://polymerelements.github.io/polymer-starter-kit/ and test
5. Comment out this line `app.baseUrl = '/polymer-starter-kit/';` in app.js near the top and save. So it will not end up in master.

Lets automate it when pr is merged or nightly.

**Comment by samccone** [comment]
https://github.com/marionettejs/marionettejs.com/blob/master/travis-runner.sh#L6-L19

we can lift how we do it here ^

**Comment by chuckh** [comment]
:+1: looks like that could work. Just need to add logic for handling steps 1 and 5.

**Comment by addyosmani** [comment]
Hah. I didn't realise https://github.com/marionettejs/marionettejs.com/blob/master/.travis.yml#L17 was possible. Lifting what Sam has sounds like a solid plan forward here.

**Comment by samccone** [comment]
:bow:

**Comment by chuckh** [comment]
I got  this working by using ghPages config option of remoteUrl using GH_TOKEN.  It test if `gulp deploy-gh-pages` being run by Travis Cl if so it uses `remoteUrl` other wise uses default settings. This way `deploy-gh-pages` can be run locally or by Travis Cl.

```Javascript
gulp.task('deploy-gh-pages', function() {
  return gulp.src(dist('**/*'))
    // Check if running task from Travis Cl, if so run using GH_TOKEN
    // otherwise run using ghPages defaults.
    .pipe($.if(process.env.TRAVIS === 'true', $.ghPages({
      remoteUrl: 'https://$GH_TOKEN@github.com/polymerelements/polymer-starter-kit.git',
      silent: true,
      branch: 'gh-pages'
    }), $.ghPages()));
});
```

See results of Travis CL build at: https://travis-ci.org/PolymerElements/polymer-starter-kit/builds/93412673

This took a lot of trial and error, but we finally got! :dancers: :wine_glass: :+1:

**Comment by samccone** [comment]
yay awesome work @chuckh heh yay autodeploy
