### ISSUE TITLE
Promise and Fetch API

### ISSUE THREAD

**Issue by santosborom** [PolymerElements/polymer-starter-kit#511]
Hi Team:
Just wanted to know if it is legal and possible to include Fetch and Promise APIs as a dependency in app.js? If yes, what must one do? Thanks in advance.

**Comment by addyosmani** [comment]
Pretty much the same way you would do so in other webapps. You'll probably want to `bower install` or `npm install` the Fetch and Promise polyfills for browsers without support and then reference them via `<script>` in either your index.html or elements.html. You should then just be able to use those APIs. If it's specific elements you want to use them with, reference script in the element. There shouldn't be much more work involved.

**Comment by santosborom** [comment]
Thanks for your reply mate. Yes i get all that but what i was refering to was writing fetch and promise inside the JavaScript file called "app.js" .
