### ISSUE TITLE
Make it easier to work with Firebase Hosting

### ISSUE THREAD

**Issue by mbleigh** [PolymerElements/polymer-starter-kit#512]
Firebase engineer here :fire: :wolf:

I've just had my first chance in months to do a little diving into Polymer and wanted to get an app up and running with the Polymer Starter Kit and Firebase Hosting. Firebase Hosting is migrating to using [Superstatic](https://github.com/firebase/superstatic) as its serving engine (see [this PR for progress on that](https://github.com/firebase/superstatic/pull/187)) which means it'll be possible to run things identically locally.

I would **love** to make Superstatic work super-well with PSK so that PSK apps are dead simple to deploy to Firebase. There are a few catches though:

1. It gets really messy trying to make all of the relative URLs work with pushState.
2. Mounting `bower_components` as a route means Superstatic can't work its mojo.

What I had to do to make things work the way I needed:

1. Replace all relative links with absolute links in `app/index.html`
2. Move `bower_components` into `app`, `.gitignore` it there, and add a `.bowerrc` that points to `app/bower_components`
3. Update the `gulpfile.js` to install Superstatic as a middleware instead of the existing connect fallback middleware

None of this is terribly difficult, but it will be quite a few manual steps for Firebase users to go through to get PSK up and running. I'd very much prefer not to maintain a fork of PSK for Firebase's purposes, so I'm curious: are the above changes something that could potentially be put into the main repo? I'd be happy to pull it into a PR, but I'd want to know that such a PR has a chance of merge before I do the legwork here.

Goooooo Polymer!

**Comment by MeTaNoV** [comment]
FYI, the is a Polymer recipe incoming in [PR 509](https://github.com/PolymerElements/polymer-starter-kit/pull/509) that you could follow and eventually complement/discuss.
I am also looking forward to this one!
Since you are also from Firebase, I would like to know if you have a pointer to show how to integrate a third party authentification? In my use-case, I would like to be able to sign-in use Steam authentification.

**Comment by mbleigh** [comment]
@MeTaNoV it's definitely possible, but would require you to run your own server. Basically you'd need to redirect your users to a server you run that is capable of OAuth-ing to Steam, then you'd want to [mint a Custom Authentication Token](https://www.firebase.com/docs/web/guide/login/custom.html) for use with your Firebase app.

**Comment by MeTaNoV** [comment]
@mbleigh , that's what I feared... I would have to do it GoogleAppEngine, but if I start there, I will tend to use the all its infrastructure...

**Comment by chuckh** [comment]
Hi @mbleigh will Superstatic be replacing `firebase serve` in the near future?

**Comment by mbleigh** [comment]
Firebase serve *is* Superstatic :)

There will be a new version of Superstatic coming out soon with major
updates to internals, but the Firebase serve command in the 2.0 CLI was
made possible by Superstatic and is already using it.

**Comment by chuckh** [comment]
> 1. Replace all relative links with absolute links in app/index.html

@mbleigh you should not have to do this step if your are using master branch and following pr #509 instructions.

**Comment by chuckh** [comment]
> Firebase serve *is* Superstatic :)   ***very cool!*** :+1: 

I was able to get `firebase serve` to work ok with the steps in pr #509.   I did not have to move `bower_components`.

**Comment by addyosmani** [comment]
@mbleigh is there further work that needs to be done for #509 to get this in line with the best way to deploy using Firebase today? It wasn't clear to me whether the current CLI using superstatic under the hood meant that we were good to go or whether we should hold out for a new superstatic release.

**Comment by mbleigh** [comment]
@addyosmani so the deploy part is pretty much sorted, but ideally the `gulp serve` and `gulp serve:dist` could use the Superstatic middleware directly so that the experience would be identical.

Today, `firebase serve` will work as described in #509 but not for the in-development server. The reason I mentioned `bower_components` is that while I am in the process of adding multiple public directory support (i.e. `.tmp` and `app`) I don't think it makes sense for the library to add path-mounting at this time.

Another solution could be to use gulp to copy everything from bower_components into `.tmp` which would obviate the move but end up with doubled files.

**Comment by robdodson** [comment]
I'm all for just moving bower_components into app. I [understand the reason it isn't in there](http://yeoman.io/blog/bower_components-in-project-root.html) but also disagree with the reasoning :) I think it adds complexity to the project, and doesn't just affect this use case but also makes tools like `web-component-shards` hard to use. If you find it annoying that results from bower_components show up when you search for files then **ignore the bower_components dir in your search**!

**Comment by ValueBC** [comment]
I agree that hosting to Firebase should be simple and not bloated with "bower_components". It takes to long to tweak the gulpfile.js to not upload unused files. Firebase is  a great host/database!

**Comment by chuckh** [comment]
For now you could add `"**/bower_components/**"` so `firebase deploy` does not upload bower_components folder.

```javascript
{
  "firebase": "myfirebase",
  "public": "app",
  "ignore": [
    "firebase.json",
    "**/.*",
    "**/node_modules/**"
    "**/bower_components/**"
  ]
}
```

**Comment by robdodson** [comment]
wouldn't you miss out on the web components polyfills then?

**Comment by chuckh** [comment]
You are correct @robdodson, my bad. Maybe something like below might work. 

```json
{
  "firebase": "polymer-starter-kit",
  "public": "dist",
  "ignore": [
    "firebase.json",
    "**/.*",
    "**/node_modules/**"
    "/bower_components/**"
    "!/bower_components/webcomponentsjs"
  ]
}
```

Firebase.json supports git .ingore patterns such as http://git-scm.com/docs/gitignore.

**Comment by robdodson** [comment]
Today we landed https://github.com/PolymerElements/polymer-starter-kit/pull/568 which takes care of the biggest hurdle (moving `bower_components`).

I guess that leaves 2 parts: replacing relative paths with absolute paths (I'm all for this, I do it anyway for all of my AppEngine projects) and replacing connect middleware with Superstatic. @mbleigh is Superstatic at a point where we can go ahead and do the swap or are you still working on it?

**Comment by mbleigh** [comment]
:tada: woo!

@robdodson 4.0 is still a WIP ([see PR](https://github.com/firebase/superstatic/pull/187)) which is what we'd want to use. The branch is stable and most work is done, but actual release won't happen til next week.

**Comment by robdodson** [comment]
oh that's fine, we can wait till then. Keep me posted on its progress :)

**Comment by samccone** [comment]
oh hey @mbleigh :wave:

**Comment by MeTaNoV** [comment]
@mbleigh nice job! Are you sometimes aound on Slack? :)

**Comment by robdodson** [comment]
I think I'm going to close this issue and recommend instead that we build a Polymer CLI generator specifically tailored to Firebase. This would also be a good place to show off usage of Polymerfire. Because Polymer CLI will accept any yeoman generator that starts with `generator-polymer-init` this should be pretty easy to build and we can use https://github.com/PolymerElements/generator-polymer-init-custom-build as an example

**Comment by George35mk** [comment]
can i ask if you can help me i have jast connect my domain name with firebase hosting when i push changes in my firebase hosting with firebase tools with  cmd the only changes i make is on random free hosting url that firebse give me i want my changes to push on my conected domain name plz help me i am new
