### ISSUE TITLE
Menu buttons stay selected on Chrome

### ISSUE THREAD

**Issue by btelles** [PolymerElements/polymer-starter-kit#515]
Just downloaded the v1.1.1, ran:

* npm install, 
* bower install, 
* gulp
* gulp serve

Navigating to localhost:5000 and clicking on the left-hand menu items changes the page, but leaves the background of the buttons in a seemingly hover state. This happens on both Chrome and Firefox on Ubuntu. Any idea what may be causing this?

Here's a screenshot:

http://s23.postimg.org/awy1lu5p7/click_and_focus.png

Here's the full output from the debugger. Doesn't look like anything's amiss:

```Our app is ready to rock!
page-compiled.js:17466 settings	create new/default
page-compiled.js:18125 ui	createsettingsprovider start
page-compiled.js:18140 ui	createsettingsprovider end
chrome-extension://ijfnhedakljnjnojgcapmeopkngjlgih/page-compiled.js:18049 ui	xul window load
chrome-extension://ijfnhedakljnjnojgcapmeopkngjlgih/page-compiled.js:18064 ui	xul window load reviewer setup
chrome-extension://ijfnhedakljnjnojgcapmeopkngjlgih/page-compiled.js:15506 recorderui	update
chrome-extension://ijfnhedakljnjnojgcapmeopkngjlgih/page-compiled.js:13154 msgr	NoData
chrome-extension://ijfnhedakljnjnojgcapmeopkngjlgih/page-compiled.js:13154 msgr	ClickToStart
chrome-extension://ijfnhedakljnjnojgcapmeopkngjlgih/page-compiled.js:15543 recorderui	setbartooltip: ClickToStart
chrome-extension://ijfnhedakljnjnojgcapmeopkngjlgih/page-compiled.js:17476 settings	get qaMode false
chrome-extension://ijfnhedakljnjnojgcapmeopkngjlgih/page-compiled.js:17476 settings	get serverNameProd hotshots.corp.google.com
chrome-extension://ijfnhedakljnjnojgcapmeopkngjlgih/page-compiled.js:13534 ui	baseurisupplierfunction () { [native code] }--hotshots.corp.google.com
chrome-extension://ijfnhedakljnjnojgcapmeopkngjlgih/page-compiled.js:13537 reviewpanel	loginchecker finished```

**Comment by btelles** [comment]
FWIW, looks like the "a" tag is retaining its pseudo selector "::after" after the mouse gets clicked up...perhaps this is a problem with paper-menu, or another style?

**Comment by lapteuh** [comment]
I have the same issue.

**Comment by addyosmani** [comment]
I'm testing against master and haven't been able to reproduce this issue. Would you mind testing out http://polymerelements.github.io/polymer-starter-kit/? (this is a recent build and similarly doesn't have this issue).

**Comment by lapteuh** [comment]
@addyosmani I tested http://polymerelements.github.io/polymer-starter-kit/ and it's not have the bug. This bug reproduced for me only if i use `gulp serve` on Windows.

**Comment by timwangdev** [comment]
The same bug here.
seems that `opacity:0.12;` is not built in `paper-menu` element `::after` style.

**Comment by timwangdev** [comment]
polymer-starter-kit-light-1.1.1 don't have this bug.

**Comment by addyosmani** [comment]
This issue is fixed by https://github.com/PolymerElements/paper-menu/pull/62 and we'll get this once a new paper-menu version has been tagged.

**Comment by addyosmani** [comment]
https://github.com/PolymerElements/polymer-starter-kit/commit/d0e743044b1a378cbc65c9c2425b7f516778893a addresses this problem but we'll want to switch to not having to manually resolve this once a new `paper-menu` release is made.

**Comment by colindevs** [comment]
@addyosmani is the fix out yet, if not, when will it be?
Just `yo polymer`ed a new PSK app, and I'm getting the same thing after `gulp serve` in Canary:
![screen shot 2015-11-24 at 6 04 06 pm](https://cloud.githubusercontent.com/assets/12850952/11383446/395d4d12-92d6-11e5-8265-3df40cd0cd55.png)
![screen shot 2015-11-24 at 6 04 21 pm](https://cloud.githubusercontent.com/assets/12850952/11383447/39666c30-92d6-11e5-9a75-4528c0bc5c01.png)

**Comment by colindevs** [comment]
@addyosmani if not out yet, is there a manual way to resolve this issue?

**Comment by btelles** [comment]
Easiest solution is to add the following to elements.html:

    <link rel="import" href="../bower_components/paper-styles/color.html">
