### ISSUE TITLE
Error when running gulp serve:dist

### ISSUE THREAD

**Issue by quaintcow** [PolymerElements/polymer-starter-kit#521]
Hey guys, thanks so much for your work I love the starter kits!

There's no error when running "gulp serve"
but when I run "gulp serve:dist" I get the error below

"Uncaught TypeError: Cannot read property 'trim' of undefined" - index.build.js 6

**Comment by addyosmani** [comment]
What version are you experiencing this in? Can you try master and let us know if you still see the issue there?

**Comment by quaintcow** [comment]
Polymer Starter Kit 1.1.1

**Comment by addyosmani** [comment]
Yay. Thanks!
