### ISSUE TITLE
ES2015: ReferenceError: dist is not defined

### ISSUE THREAD

**Issue by machados** [PolymerElements/polymer-starter-kit#526]
Hi! I just followed the recipe to use Babel to transpile from ES2015 but I'm getting the following error from gulp:

[00:17:30] Starting 'js'...
[00:17:30] 'js' errored after 465 ms
[00:17:30] ReferenceError: dist is not defined
(...)

The recipe doesn't list the dist() function definition. 
Or maybe I missed something since I'm new to gulp?

**Comment by ragingwind** [comment]
Which version do you use for? latest version 1.1.1 wasn't to use `dist()` yet. I think, you use `dist` string instead of `dist()` function

**Comment by machados** [comment]
I got the version that comes with yeoman. But then I applied the recipe to add ES2015 in the docs (https://github.com/PolymerElements/polymer-starter-kit/blob/master/docs/add-es2015-support-babel.md) 

This commit seems be the problem:

https://github.com/PolymerElements/polymer-starter-kit/commit/83de84cc649c40b2d3bfb7cff1da917087b6c231

I reverted that commit manually and go it working.
Maybe the yeoman version is too old, I'm not sure how to find the version of the yeoman polymer generator.

**Comment by ragingwind** [comment]
It's not a problem. Just mismatched of each version. The document you referred that is up-to-date version not stable version using in the polymer generator. As I know that yeoman generator use v1.1.1 so [this doc version](https://github.com/PolymerElements/polymer-starter-kit/blob/39ad99ceae860924682ae13c420fa622bdac5ee8/docs/add-es2015-support-babel.md) would be perfect for yours version which is almost same version of you reverted. Or you can use [v1.2.0 rc verison](https://github.com/PolymerElements/polymer-starter-kit/releases/tag/v1.2.0-rc.1)

**Comment by machados** [comment]
Makes sense, thanks!

**Comment by samccone** [comment]
:+1: thx @ragingwind
