### ISSUE TITLE
WCT ECMAScript 6 problems

### ISSUE THREAD

**Issue by BorntraegerMarc** [PolymerElements/polymer-starter-kit#527]
Hi there

I downloaded the newest PSK version and installed all dependencies and run the tests -> Everything works fine. Now I decided to add a little validation to the greeting element. So I added this code:
```javascript
<paper-input id="greetingInput" label="Greeting" required auto-validate value="{{greeting}}"></paper-input>

validate: function() {
	if (this.$.greetingInput.validate()) {
		console.log('Valid!');
	} else {
		console.log('Not valid!');
	}
}
```

And here is my test:
```javascript
test('should validate greeting', function() {
	greeting.validate();
	greetingInput = greeting.querySelector('#greetingInput');
	expect(greetingInput.hasAttribute('invalid')).to.equal(false);
});
```

Now to my problem:
When I run the tests like this, then everything looks fine, but when I migrate the code to EMCAScript 6, then I get the following error:
## Expected outcome

Everything works as before.

## Actual outcome

```
this.$.greetingInput.validate is not a function
```

Any ideas?

**Comment by BorntraegerMarc** [comment]
Aright, I identified the problem:
I didn't import my dependency: <link rel="import" href="./../../../../bower_components/paper-input/paper-input.html">

So in the test suite, he didn't recognize the paper-input. Closing isue...

**Comment by MeTaNoV** [comment]
I would recommend to use `polylint` beforehand which would detect such import issue! :)
