### ISSUE TITLE
The selected menu item background makes the item unreadable

### ISSUE THREAD

**Issue by hickscorp** [PolymerElements/polymer-starter-kit#528]
The `polymer-starter-kit` menu has a weird behavior for the selected item.

## Expected outcome

Same result as the one observed when browsing [demo website](http://polymerelements.github.io/polymer-starter-kit/). Eg: the menu item background has a low opacity, making it slightly dim and allowing text from the selected item to be read.

## Actual outcome

The selected menu item background has the same color as the text, making it impossible to read.

## Steps to reproduce

Please keep in mind that i'm fairly new to Polymer.

I tried using the `polymer-boilerplate` code using two following methods, each time with the same issue:

- Downloading the tarball,
- Directly cloning the repo ( 272c28eb9e12b29f1b5ffebca2e40d55855df9e9 ).

Maybe this is related to #515?

![screenshot_2015-11-23_10-23-03](https://cloud.githubusercontent.com/assets/822933/11334323/3673bc36-91cc-11e5-9d44-738c1e8b373e.png)

Edit: This definitely has to be related to #515; if i click a menu item and refresh the page, the selected menu item looks ok. I can confirm that this bug also occurs using Chrome, Firefox and Ice Weasel.

![screenshot_2015-11-23_10-37-51](https://cloud.githubusercontent.com/assets/822933/11334640/47421ce0-91ce-11e5-9707-ae3fd98541ff.png)

**Comment by addyosmani** [comment]
This is indeed related to https://github.com/PolymerElements/polymer-starter-kit/issues/515. We'll need to wait for an upstream release to be made before this issue is resolved but it should be coming soon.

**Comment by hickscorp** [comment]
@addyosmani Thanks for your help. Would you like me to close the issue as a duplicate then?

**Comment by addyosmani** [comment]
We'll be getting out a new release shortly. I consider it unacceptable for us to ship with this bug in place so we might try locking in the dependency to the specific commit that fixes this. Hang on tight please.

**Comment by addyosmani** [comment]
See response in #515. Should be temporarily fixed in master but we'll bump to latest paper-menu when that gets a release.
