### ISSUE TITLE
gulp deploy gives error

### ISSUE THREAD

**Issue by VikramTiwari** [PolymerElements/polymer-starter-kit#532]
```
Task 'deploy' is not in your gulpfile
```

**Comment by samccone** [comment]
@VikramTiwari did you see this gulp task documented anywhere? I am curious as to what made you think this would work :)

**Comment by VikramTiwari** [comment]
haha well, my bad. Should have gone through documentation first, which lists the correct method.

Though `gulp deploy` is the obvious command that I would use at times, hence the mistake. Close it if you want to :P
