### ISSUE TITLE
Mixins in external stylesheets being stripped from builds

### ISSUE THREAD

**Issue by rycastaneda** [PolymerElements/polymer-starter-kit#534]
Not sure if this is the right place to post this. There is a problem when minifying polymer mixins that those with 
```
    width: 100% ;
   --iron-image-width: 100%;
```
followed by a mixin, will result to a code with missing comma. Like this.
```
    width: 100% --iron-image-width: 100%;
```
example can be found on https://github.com/PolymerElements/paper-card/blob/master/paper-card.html#L87

**Comment by robdodson** [comment]
See this comment: https://github.com/PolymerElements/polymer-starter-kit/issues/296#issuecomment-166002525
