### ISSUE TITLE
sudo npm run deps: -> Error: EACCES, permission denied....

### ISSUE THREAD

**Issue by vl4dt** [PolymerElements/polymer-starter-kit#54]
Error: EACCES, permission denied '/root/.config/configstore/bower-github.yml'
You don't have access to this file.

    at Object.fs.openSync (evalmachine.<anonymous>:438:18)
    at Object.fs.readFileSync (evalmachine.<anonymous>:289:15)
    at Object.create.all.get (/home/ricardo/dev/liu-bob-psk/node_modules/web-component-tester/node_modules/bower/node_modules/configstore/index.js:34:29)
    at Object.Configstore (/home/ricardo/dev/liu-bob-psk/node_modules/web-component-tester/node_modules/bower/node_modules/configstore/index.js:27:44)
    at readCachedConfig (/home/ricardo/dev/liu-bob-psk/node_modules/web-component-tester/node_modules/bower/lib/config.js:22:23)
    at defaultConfig (/home/ricardo/dev/liu-bob-psk/node_modules/web-component-tester/node_modules/bower/lib/config.js:11:24)
    at Object.<anonymous> (/home/ricardo/dev/liu-bob-psk/node_modules/web-component-tester/node_modules/bower/lib/index.js:40:32)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
npm ERR! web-component-tester@3.1.3 postinstall: `node scripts/postinstall.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the web-component-tester@3.1.3 postinstall script.
npm ERR! This is most likely a problem with the web-component-tester package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/postinstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls web-component-tester
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.16.7-21-desktop
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/ricardo/dev/liu-bob-psk
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.23
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ricardo/dev/liu-bob-psk/npm-debug.log
npm ERR! not ok code 0

npm ERR! polymer-starter-kit@0.0.0 deps: `npm install -g gulp && npm install -g bower && npm install && bower install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the polymer-starter-kit@0.0.0 deps script.
npm ERR! This is most likely a problem with the polymer-starter-kit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install -g gulp && npm install -g bower && npm install && bower install
npm ERR! You can get their info via:
npm ERR!     npm owner ls polymer-starter-kit
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.16.7-21-desktop
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "run" "deps"
npm ERR! cwd /home/ricardo/dev/liu-bob-psk
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.23
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ricardo/dev/liu-bob-psk/npm-debug.log
npm ERR! not ok code 0

**Comment by Kaestlyn** [comment]
I managed to get around this by just running the commands defined in the package.json myself:
```shell
sudo npm install -g gulp
sudo npm install -g bower
sudo npm install
bower install
```

**Comment by vl4dt** [comment]
Still fails here on my machine:
Error: EACCES, permission denied '/root/.config/configstore/bower-github.yml'

Same file as before

**Comment by addyosmani** [comment]
@vl4dt were you able to work around this using the commands directly? I would suggest checking if permissions are setup correctly too: https://docs.npmjs.com/getting-started/fixing-npm-permissions

Btw, for anyone getting stuck with the tooling version of PSK, there's also a non-tooling version available: https://github.com/PolymerElements/polymer-starter-kit/releases

**Comment by addyosmani** [comment]
Another option. Try `sudo chown -R [user name] ~/.config` and `sudo chown -R [user name] ~/.cache`

**Comment by vl4dt** [comment]
Success!

@addyosmani I tried running the command manually as @Kaestlyn suggested, at some point one of them failed at the same point.

After all the problem was permissions were not setup correctly, followed what you suggested: https://docs.npmjs.com/getting-started/fixing-npm-permissions, chose to change npm's default directory permissions, ran:

```zsh
$ npm run deps
$ gulp test:local
$ gulp
$ gulp serve
```

All successful, no warnings or error, thanks a lot both!

**Comment by addyosmani** [comment]
Fantastic. Thanks!

**Comment by kbwatts** [comment]
Still getting the EACCESS errors even after fixing npm permissions, but then running each command separately as suggested by @Kaestlyn seems to work for me.

**Comment by omarjebari** [comment]
This worked for me:

> sudo bower install --allow-root

**Comment by cjpillette** [comment]
Thank you @vl4dt 
I've indeed followed what you've done.

$ sudo chown -R my_user_name /usr/local/lib/node_modules
$ sudo chown -R my_user_name /usr/local/bin
$ sudo chown -R my_user_name /usr/local/share
$ npm install gulp-cli --global

It worked :)

**Comment by nanothermite** [comment]
Just to be clear, when I do this on my linux box wearing my admin hat, I operate as root, so why would my userid not be able to have read access to any of the installation dirs?

**Comment by robdodson** [comment]
@rictic have you seen this issue with web-component-tester before?

**Comment by rictic** [comment]
I haven't, that's strange. Where does wct use bower?

@azakus have you heard of such?

**Comment by RicardoBarroso** [comment]
@addyosmani solution worked for me. Here goes a slightly modified version not requiring you to fill in your username:
```
sudo chown -R $USER ~/.config/lab/AwesomeProject$ sudo chown -R $USER ~/.cache
```

**Comment by hayat12** [comment]
for me i refresh the font (the folder which is complaining ) folder permissions then restart the terminal and it works

**Comment by Jayprecode** [comment]
what also causes this error is due to incorrect path
