### ISSUE TITLE
Consider catching errors in vulcanize gulp task.

### ISSUE THREAD

**Issue by arodic** [PolymerElements/polymer-starter-kit#542]
This has been a big time saver for me. Vulcanize sometimes silently fails and this will show the error:

```javascript
 .on('error', function(e) {
   console.log(e);
  });
```

**Comment by samccone** [comment]
this would be helpful, @arodic any interest in opening a PR?

**Comment by arodic** [comment]
Sure, coming up.

**Comment by arodic** [comment]
I was not able to reproduce the bug on latest (silent vulcanize errors). Perhaps there was something wrong on my side. Closing.

**Comment by samccone** [comment]
:+1: no problem
