### ISSUE TITLE
TypeError: Cannot convert undefined or null to object in task lint

### ISSUE THREAD

**Issue by cnbuff410** [PolymerElements/polymer-starter-kit#544]
Download 1.2 directly, then did npm install and bower install, then do "gulp serve", and here is the error output:
```
[12:37:13] Starting 'lint'...
[12:37:14] 'lint' errored after 1.18 s
[12:37:14] TypeError: Cannot convert undefined or null to object
    at Function.keys (native)
    at copyConfiguration (/Users/cnbuff410/node_modules/gulp-jscs/node_modules/jscs/lib/config/configuration.js:1181:12)
    at NodeConfiguration.Configuration._processConfig (/Users/cnbuff410/node_modules/gulp-jscs/node_modules/jscs/lib/config/configuration.js:474:5)
    at NodeConfiguration.Configuration.load (/Users/cnbuff410/node_modules/gulp-jscs/node_modules/jscs/lib/config/configuration.js:238:10)
    at StringChecker.configure (/Users/cnbuff410/node_modules/gulp-jscs/node_modules/jscs/lib/string-checker.js:67:29)
    at Checker.configure (/Users/cnbuff410/node_modules/gulp-jscs/node_modules/jscs/lib/checker.js:28:39)
    at Object.module.exports (/Users/cnbuff410/node_modules/gulp-jscs/index.js:35:10)
    at Gulp.<anonymous> (/Users/cnbuff410/gulpfile.js:124:11)
    at module.exports (/Users/cnbuff410/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/cnbuff410/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
```
It's caused by this line in lint task:

  .pipe($.jscs())

**Comment by samccone** [comment]
@cnbuff410 mind rm -rf node_modules and npm i again?

do you get any errors when you install?

**Comment by cnbuff410** [comment]
That didn't fix it. 

I didn't get any errors. Only warnings I'm getting is 

npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.
npm WARN engine launchpad@0.4.9: wanted: {"node":"^0.12"} (current: {"node":"4.2.1","npm":"2.14.7"})
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.

**Comment by addyosmani** [comment]
Can you upgrade to npm3 and try again? (`npm install -g npm@latest`)

**Comment by cnbuff410** [comment]
Tried and still nope. Same error.

**Comment by cnbuff410** [comment]
I'm on Mac 10.11.1, downloaded the source code from tar file

**Comment by mmadjer** [comment]
Yep, same here.
Same steps performed and same error.

**Comment by samccone** [comment]
I have just done a clean install off of master and everything seems to be working for me... so I am a bit stumped here

@mmadjer @cnbuff410 mind trying master?

**Comment by mmadjer** [comment]
Still no luck with clean install off of master.
Something suspicious with this on 'npm install'?

```
npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.
npm WARN engine launchpad@0.4.9: wanted: {"node":"^0.12"} (current: {"node":"4.2.1","npm":"2.14.7"})
 
...

npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.
```

**Comment by samccone** [comment]
nope these warning are fine,

to be clear this errors when you run `npm run lint` you get the error?

**Comment by mmadjer** [comment]
I used `gulp`.
But running `npm run lint` throws the same error. Here is the npm debug log dump:
`
0 info it worked if it ends with ok
1 verbose cli [ '/Users/mvalkovic/.nvm/versions/v4.2.1/bin/node',
1 verbose cli   '/Users/mvalkovic/.nvm/versions/v4.2.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'lint' ]
2 info using npm@2.14.7
3 info using node@v4.2.1
4 verbose run-script [ 'prelint', 'lint', 'postlint' ]
5 info prelint @
6 info lint @
7 verbose unsafe-perm in lifecycle true
8 info @ Failed to exec lint script
9 verbose stack Error: @ lint: `gulp lint`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/Users/mvalkovic/.nvm/versions/v4.2.1/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/Users/mvalkovic/.nvm/versions/v4.2.1/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:818:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid @
11 verbose cwd /Users/mvalkovic/Projects/madjer.info
12 error Darwin 15.0.0
13 error argv "/Users/mvalkovic/.nvm/versions/v4.2.1/bin/node" "/Users/mvalkovic/.nvm/versions/v4.2.1/bin/npm" "run" "lint"
14 error node v4.2.1
15 error npm  v2.14.7
16 error code ELIFECYCLE
17 error @ lint: `gulp lint`
17 error Exit status 1
18 error Failed at the @ lint script 'gulp lint'.
18 error This is most likely a problem with the  package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     gulp lint
18 error You can get their info via:
18 error     npm owner ls
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
`

**Comment by ohanhi** [comment]
I can confirm this bug. I am on OS X 10.11.1, Node 4.1.0 and NPM 3.5.0. This happens both when running `gulp` and `npm run lint`.

```bash
$ npm run lint

> @ lint /Users/ohan/path/to/project
> gulp lint

[10:47:45] Using gulpfile ~/path/to/project/gulpfile.js
[10:47:45] Starting 'lint'...
[10:47:46] 'lint' errored after 702 ms
[10:47:46] TypeError: Cannot convert undefined or null to object
    at Function.keys (native)
    at copyConfiguration (/Users/ohan/path/to/project/node_modules/jscs/lib/config/configuration.js:1181:12)
    at NodeConfiguration.Configuration._processConfig (/Users/ohan/path/to/project/node_modules/jscs/lib/config/configuration.js:474:5)
    at NodeConfiguration.Configuration.load (/Users/ohan/path/to/project/node_modules/jscs/lib/config/configuration.js:238:10)
    at StringChecker.configure (/Users/ohan/path/to/project/node_modules/jscs/lib/string-checker.js:67:29)
    at Checker.configure (/Users/ohan/path/to/project/node_modules/jscs/lib/checker.js:28:39)
    at Object.module.exports (/Users/ohan/path/to/project/node_modules/gulp-jscs/index.js:35:10)
    at Gulp.<anonymous> (/Users/ohan/path/to/project/gulpfile.js:124:11)
    at module.exports (/Users/ohan/path/to/project/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/ohan/path/to/project/node_modules/orchestrator/index.js:273:3)

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/Cellar/node/4.1.0/bin/node" "/usr/local/bin/npm" "run" "lint"
npm ERR! node v4.1.0
npm ERR! npm  v3.5.0
npm ERR! code ELIFECYCLE
npm ERR! @ lint: `gulp lint`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ lint script 'gulp lint'.
```

**Comment by addyosmani** [comment]
Are you seeing this with `gulp serve` too or just when running `gulp`?

**Comment by mmadjer** [comment]
I see it with `gulp serve` too.

**Comment by addyosmani** [comment]
I'm a little stumped as we haven't been able to repro this on Windows 10 and OSX 10.10. Can folks share what OS they're seeing this on so we can take another stab at reproducing?

**Comment by mmadjer** [comment]
I'm on Mac OSX 10.11.1
Node v4.2.1
NPM v2.14.7
Modules:
Orchestrator v0.3.7
Gulp-jscs v3.0.2
jscs v2.6.0

**Comment by ohanhi** [comment]
I maybe got it now. The OS X default extractor doesn't extract the .jscsrc and .jshintrc files, which results in an error. Adding the files manually later fixed it for me. Can others verify? @mmadjer, @cnbuff410 ?

**Comment by addyosmani** [comment]
That's super weird (thanks for checking!). I just extracted the latest release and see both `.jscsrc` and `.jshintrc` extracted correctly to my `polymer-starter-kit-1.2.0` directory. This was using the default archive utility.

**Comment by ohanhi** [comment]
Okay, maybe there's multiple ways of doing it, and we are just using a less common way. Or you have hidden files shown in Finder, and we don't?

**Comment by addyosmani** [comment]
I have hidden files shown in Finder (which might be one reason they're not showing up for others) :)

**Comment by ohanhi** [comment]
Yes, I think this is the root of the problem. Provided adding the files fixes it for the others, that is.

**Comment by mmadjer** [comment]
I can confirm that if .jscsrc and .jshintrc files are missing results in an error.
What I did was download the polymer-starter-kit-1.2.0.zip, extracted and copied the content over to my project folder. Those files are not copied over. :/

**Comment by addyosmani** [comment]
@mmadjer were you using the default extractor or a different unzipping tool?

**Comment by mmadjer** [comment]
The default extractor. The files are extracted and present but I did not copy the whole folder I selected all files within the folder and copy & paste into my projects folder.

**Comment by addyosmani** [comment]
Ah. That's the issue then. Would it help if we added a note to the release notes/install instructions about being careful with hidden files that are needed for linting?

**Comment by mmadjer** [comment]
I guess so. I haven't thought about of any hidden files while copying the files over this way.
It might remind people of that. :o)

**Comment by ohanhi** [comment]
@addyosmani I think that's the first step. The real issue here though is the usability of the errors: "Cannot convert undefined or null to object" really doesn't help in figuring out some files are missing from my setup. Most likely there are other similar problems that people may run into with the Starter Kit. For this particular issue, simply checking the presence of the dotfiles and giving a human-readable error about them being necessary would suffice.

**Comment by samccone** [comment]
great idea @ohanhi , any interest in opening up a PR to implement this idea?

Thanks!

**Comment by cnbuff410** [comment]
Thanks guys! I can confirm it fixes the issue on my side.

**Comment by samccone** [comment]
ok i just looked at the zip download... and the files are in there, so I think the ideal solution here would be to as @ohanhi said put a sane error message in the console in this case

**Comment by ohanhi** [comment]
@samccone I'll try implementing it, but since I haven't worked with Gulp that much, it might not be a very idiomatic solution in the end. We'll see.

**Comment by samccone** [comment]
anything is appreciated, and we can help you land it if you are interested :+1:

**Comment by addyosmani** [comment]
Fwiw, a note about this has been added to the release notes.

**Comment by ohanhi** [comment]
@samccone PR is up. :tada:

**Comment by jarrodek** [comment]
That may not be all of it. I had the same problem. I run project on Mac OS X yesterday from fresh polymer zip file. I've unpacked it using command line since I noticed missing dot files.
Everything was OK until today. When I tried to run the project in the morning I've received similar error (I don't remember which one, I didn't have time to develop today anyway). But I packed up files to zip and I tried to develop at home now. I have Windows 10 here.
At first I had "Cannot convert undefined or null to object" error. It was because of lack of dot files. However after I've copied this files from PSK zip file and run it again I've received different error. It was after pointing some warnings in app.js file. The warnings was about declaring and not using variables. Until I removed all not used variables I couldn't use "gulp serve" command because it raised an error.
Now it is working but it was weard that I needed to remove warnings before it started to work.

**Comment by robdodson** [comment]
@jarrodek that second error is jshint working as expected :D

**Comment by jarrodek** [comment]
@robdodson in overall it make sense - not to leave unwanted trash in the code. However when you're developing the app it's quite annoying :)

**Comment by robdodson** [comment]
@jarrodek disable it then? For most the value in jshint comes when it finds an actual error that would have broken your app. If you don't like the warnings you can edit the `.jshintrc` to modify how noisy it will be.

**Comment by jarrodek** [comment]
@robdodson I totally agree. I just was surprised for a moment and thought that the project is somehow broken. It obviously not.

**Comment by MiguelDebruyne** [comment]
Had the same problem today, copied the files from my own boilerplate (web coding template) while  hidden files were hidden and it didn't copy those files which resulted in this error. Still the same error though which doesn't make a lot of sense.

**Comment by jijo-paulose** [comment]
Issue moved to [PolymerElements/app-elements #6](https://github.com/PolymerElements/app-elements/issues/6) via [**ZenHub**](https://www.zenhub.com/)

**Comment by jijo-paulose** [comment]
Issue moved to [PolymerElements/app-elements #7](https://github.com/PolymerElements/app-elements/issues/7) via [**ZenHub**](https://www.zenhub.com/)
