### ISSUE TITLE
Google-chart not working properly with PSK

### ISSUE THREAD

**Issue by samcarecho** [PolymerElements/polymer-starter-kit#546]
Polymer: 1.2.3
polymer-starter-kit: 1.2.0
google-charts: 1.0.4

Let's assume the following code as an example:
```html
<google-chart
    type='column'
    options='{"title": "Responsive chart", "vAxis": {"minValue" : 0, "maxValue": 10}}' 
    cols='[{"label": "Data", "type": "string"},{"label": "Value", "type": "number"}]'
    rows='[["Col1", 5.0],["Col2", 5.0],["Col3", 5.0]]'>
</google-chart>
```

When the page renders, the rows attribute is missing and the chart does not render at the first load of the page.
```html
<google-chart 
    type="column" 
    options="{&quot;title&quot;: &quot;Responsive chart&quot;, &quot;vAxis&quot;: {&quot;minValue&quot; : 0, &quot;maxValue&quot;: 10}}" 
    cols="[{&quot;label&quot;: &quot;Data&quot;, &quot;type&quot;: &quot;string&quot;},{&quot;label&quot;: &quot;Value&quot;, &quot;type&quot;: &quot;number&quot;}]">
    <iron-ajax id="ajax" handle-as="json" class="style-scope google-chart" hidden=""></iron-ajax>
    <div id="chartdiv" class="style-scope google-chart"></div>
    <google-legacy-loader class="style-scope google-chart"></google-legacy-loader>
</google-chart>
```

If I inject the rows using the console, as following:
```
$0.rows = [["Col1", 5.0],["Col2", 5.0],["Col3", 5.0]];
```
The chart is drawn.

Google-chart seems to be working fine, as it's own demo works faultless.
Maybe something within PSK, is causing the "rows" attribute to be striped from the tag.
Could  this be a bug?

I've pushed the entire code that I'm working on to:
https://github.com/samcarecho/jourplat.git (branch "demo01")

**Comment by samccone** [comment]
cc @ebidel ^

**Comment by samcarecho** [comment]
@samccone, @ebidel already saw this. I first posted in google-chart's issue tracker. 
The issue was closed there as the problem does not seem to be related to google-chart.

https://github.com/GoogleWebComponents/google-chart/issues/76

**Comment by samccone** [comment]
ah word ok :) thanks

**Comment by moderndeveloperllc** [comment]
@samcarecho Just curious, what happens if you pass the information in via a **data** attribute? 
```
data="[["Data", "Value"], ["Col1", 5.0],["Col2", 5.0],["Col3", 5.0]]"
```

**Comment by samcarecho** [comment]
@moderndeveloperllc if I remove "cols", "rows" and add "data", the issue persists..
The "data" attribute is also striped from the "google-chart" element.

The only way to make the element render the chart is to inject the data and force a redraw, using javascript.

**Comment by sgomes** [comment]
I've seen this problem in the old 0.5 version, and it was due to a simple but easy to miss fact: `[[` is Polymer template syntax. Have you tried adding a space in between the brackets: `rows='[ ["Col1", 5.0],["Col2", 5.0],["Col3", 5.0] ]'` and seeing if that fixes it?

**Comment by samcarecho** [comment]
@sgomes indeed adding the extra space did solve the issue. After adding it, the chart renders properly and the "rows" attribute is not plucked from the "google-chart" element.

But... This does not seem to be an issue related to the Polymer code it self, as the "google-chart" demo renders normally without the need for the extra space.

https://github.com/GoogleWebComponents/google-chart/blob/master/demo/index.html

It seems that some code specific to Polymer Starter Kit is plucking the attribute when it finds "[[" (as adding the extra space to just the opening square brackets renders the chart).

Maybe the PSK template syntax should be reviewed, to avoid plucking of attributes whose values are a list of lists or array of arrays.

Or at least a warning about this should be posted somewhere in the documentation.


Cheers

**Comment by JeremybellEU** [comment]
@samcarecho The parsing of arrays in attributes is fixed in Polymer as of https://github.com/Polymer/polymer/pull/3017

**Comment by samcarecho** [comment]
@JeremybellEU, will the fix be available on Polymer's next release, 1.2.4?
Thanks.

**Comment by JeremybellEU** [comment]
Yes, the next released version.

**Comment by samcarecho** [comment]
@JeremybellEU Thanks for the info about the release and the Polymer 3017 issue! :)

Cheers
