### ISSUE TITLE
Add travis recipe checker

### ISSUE THREAD

**Issue by chuckh** [PolymerElements/polymer-starter-kit#552]
Add to travis-runner.sh a checker for our recipes. :computer: :mag: :white_check_mark: 

from: @samccone on Slack
> soooooo if we format the code changes as patches :heavy_plus_sign: :heavy_minus_sign: 
and on CI walk all the examples and try and apply the patches...
and they do not cleanly go in... we blow up :boom:  
it will force us to update the recipes :scroll:  as we make code changes
so the burden of maintenance is moved into our normal workflow... it will also allow easier maintenance of recipes over time :clock1: :clock2: :clock4:

**Comment by addyosmani** [comment]
:+1:

**Comment by chuckh** [comment]
One possible approach is to use gemini utility for regression testing of web pages using screenshots https://github.com/gemini-testing/gemini.  Vaadin project is planning to use it. Per this [comment](https://plus.google.com/u/0/114229924035668909209/posts/evKaqv8mc3Q?cfem=1).

**Comment by chuckh** [comment]
Closing in favor of PSK2 which does not have recipes.  Instead of doing recipes we can create custom templates.
