### ISSUE TITLE
Build process breaks layouts in 1.2.0

### ISSUE THREAD

**Issue by vaadin-marcus** [PolymerElements/polymer-starter-kit#557]
Layouts break when running app with `gulp serve:dist`, see screenshots below:

Running with `gulp serve`: 
<img width="954" alt="serve" src="https://cloud.githubusercontent.com/assets/883698/11547125/81bfe944-9906-11e5-90ed-901e49c4fac1.png">

Running with `gulp serve:dist`
<img width="945" alt="dist-serve" src="https://cloud.githubusercontent.com/assets/883698/11547127/83fbf2f2-9906-11e5-96a0-4c3459a05542.png">

Steps to reproduce:
1. Download PSK 1.2.0
2. npm install && bower install && gulp serve:dist
3. Layouts are broken

Possibly/probably related to https://github.com/Polymer/polymer/issues/3126

**Comment by chuckh** [comment]
I see this problem now also. You can see the problem live at http://polymerelements.github.io/polymer-starter-kit/.

This does not happen on https://polymer-starter-kit.firebaseapp.com/ which was built a couple days ago using 1.2.0.  Might be an upstream issue related to deprecating /deep/ work going on now. See https://blog.polymer-project.org/announcements/2015/12/01/deprecating-deep/.

**Comment by addyosmani** [comment]
Fixed by https://github.com/PolymerElements/polymer-starter-kit/pull/563. We'll tag a new release Monday.
