### ISSUE TITLE
Distorted style when doing gulp serve:dist

### ISSUE THREAD

**Issue by vishnudevk** [PolymerElements/polymer-starter-kit#559]
When i am doing **gulp serve:dist** the page looks different from **gulp serve**.
components are distorted in dist. same issue is coming while deploying in firebase also
Please find attached screenshots
with  **gulp serve**.
![serve](https://cloud.githubusercontent.com/assets/4205634/11559513/8f1e34d6-99df-11e5-9521-131a51300b5a.PNG)
with  **gulp serve:dist**
![dist](https://cloud.githubusercontent.com/assets/4205634/11559515/93142a0a-99df-11e5-95c0-8b04d9067c42.PNG)

**Comment by addyosmani** [comment]
Fixed by https://github.com/PolymerElements/polymer-starter-kit/pull/563. Tag coming Monday.
