### ISSUE TITLE
(minor) your instructions for starting the minimal starter have a bad dash

### ISSUE THREAD

**Issue by salamanders** [PolymerElements/polymer-starter-kit#56]
The instructions in README.md have `python –m SimpleHTTPServer 8080`
but the dash is an "evil" dash, so if you copy-paste the command you get `python: can't open file '–m': [Errno 2] No such file or directory`

Replacing with a normal "minus" fixed it.

**Comment by addyosmani** [comment]
Patched in branch. Thanks @salamanders!

**Comment by joelklein123** [comment]
Had a similar problem. Thanks
