### ISSUE TITLE
Babel Recipe Fails on dist()

### ISSUE THREAD

**Issue by paranoid-android** [PolymerElements/polymer-starter-kit#560]
In the [Babel Recipe](https://github.com/PolymerElements/polymer-starter-kit/blob/master/docs/add-es2015-support-babel.md), the last line is

`.pipe(gulp.dest(dist()));`

This line causes the following error:
```
[22:21:46] Starting 'js'...
[22:21:46] 'js' errored after 530 ms
[22:21:46] ReferenceError: dist is not defined
    at Gulp.<anonymous> (/Users/user/MyApp/gulpfile.js:122:21)
    at module.exports (/Users/user/MyApp/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
...
```
I do not see anywhere in the recipe that explains where `dist` comes from. Can someone please tell me where `dist` comes from and update the recipe?

**Comment by moderndeveloperllc** [comment]
@paranoid-android You may want to compare your `gulpfile.js` to the latest in `master`. Lines 40-44 are:

```
var DIST = 'dist';

var dist = function(subpath) {
  return !subpath ? DIST : path.join(DIST, subpath);
};
```

**Comment by samccone** [comment]
:+1: yep @moderndeveloperllc
