### ISSUE TITLE
Do we really need the whole "bower_components" directory copied to "dist" ?

### ISSUE THREAD

**Issue by fabito** [PolymerElements/polymer-starter-kit#562]
I'm deploying the generated app into appengine and noticed that it has too many files mostly due to the bower_components directory (69Mb). 
I'm thinking about tweaking the `app.yaml` a bit to excluded unnecessary files.
I'm planning to share it as a recipe afterwards.

**Comment by moderndeveloperllc** [comment]
@fabito Might want to check out the discussion here: https://github.com/PolymerElements/polymer-starter-kit/issues/84 Personally, I change the gulpfile to vulvcanize everything I need into the elements file so I don't need bower_components in dist/ but it does cause issues for certain types of deploys.
