### ISSUE TITLE
Fix whatever's up with iron-flex-layout

### ISSUE THREAD

**Issue by robdodson** [PolymerElements/polymer-starter-kit#564]
Related to https://github.com/PolymerElements/polymer-starter-kit/pull/563

I'm looking into this with @notwaldorf 

cc @samccone @chuckh @addyosmani 

To repro:

Delete [this line](https://github.com/PolymerElements/polymer-starter-kit/blob/master/bower.json#L12) from `bower.json`.

Run `gulp serve` to see the normal version. Then run `gulp serve:dist` to see the broken version.

**Comment by robdodson** [comment]
Starting with the scrunched up search icons. It looks like the vulcanized version of `paper-toolbar #topBar` is no longer `display: flex`. Not sure why though :)

**Comment by robdodson** [comment]
I think this is the issue:

https://github.com/PolymerElements/polymer-starter-kit/blob/master/gulpfile.js#L196

This gulpfile needs some house cleaning, there are 3 CSS minifiers in here :P

**Comment by samccone** [comment]
https://github.com/PolymerElements/polymer-starter-kit/pull/486#issue-115633232

rational ^

https://github.com/PolymerElements/polymer-starter-kit/commit/7e4b990e3ad71c102b7da646872724885b5f78a0

commit ^

seems like the inline minifier is not handling "polymer css" correctly, however the original issue is valid
We can revert this PR and then look into how to fix the original issue?

thoughts @robdodson ?

**Comment by robdodson** [comment]
Yeah we should revert the PR. Polymer CSS is "special" in that it uses all sorts of new standards like custom properties and mixins which most CSS minifiers do not play nice with. The Polymer team is working on a real CSS parser to improve this.
