### ISSUE TITLE
Can't install dependencies

### ISSUE THREAD

**Issue by joshmutus** [PolymerElements/polymer-starter-kit#57]
downloaded polymer starter kit, I have node.js and bower installed, following instructions in README.md

when I type:
```
sh
$ npm run deps
```

I get the error:
```
npm WARN package.json polymer-starter-kit@0.0.0 No repository field.
sh: bower: command not found
npm ERR! weird error 127
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
```

bower is certainly installed. And I obviously fail the test:

```sh
$ gulp test:local
```

**Comment by addyosmani** [comment]
Could you let me know what version of Node (and npm) you have installed?

**Comment by joshmutus** [comment]
I just apt-get'd nodejs yesterday
```
sh-4.3$ npm --version
1.3.10
sh-4.3$ nodejs --version
v0.10.25
sh-4.3$ node --version
v0.10.25
```

**Comment by addyosmani** [comment]
The latest version of Node is v0.12.4. I would try to upgrade to it. If that fails, http://stackoverflow.com/questions/21168141/can-not-install-packages-using-node-package-manager-in-ubuntu is related to your issue imo. In short, you can also try `sudo apt-get install nodejs-legacy`.

**Comment by joshmutus** [comment]
So I've installed the latest version of node and npm on my workstation and I'm getting the same error. I did the same nodejs-legacy thing actually before filing this issue.

**Comment by joshmutus** [comment]
This is the traceback
```
npm WARN package.json polymer-starter-kit@0.0.0 No repository field.
npm WARN prefer global bower@1.4.1 should be installed with -g
/usr/bin/env: node: No such file or directory
npm ERR! weird error 127
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
```
