### ISSUE TITLE
Remove deprecated /deep/ imports

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/polymer-starter-kit#570]
The next imports has the deprecated `/deep/`:

* `iron-flex-layout/classes/iron-flex-layout.html`
* `paper-styles/paper-styles-classes.html`

**Comment by moderndeveloperllc** [comment]
@abdonrd As those are dependencies of this project, tickets should be started on the specific repositories, not here. I think there are already tickets for this on both, but I could be wrong!

**Comment by abdonrd** [comment]
@moderndeveloperllc Both `iron-flex-layout` and `paper-styles` have the alternative with mixins.
We need to make changes here in the PSK. :)

**Comment by robdodson** [comment]
Yeah I think we'll need to update the places in `index.html` where we may be using `layout` or `flex` and switch our styles over to using mixins.

**Comment by robdodson** [comment]
I tacked on a `p0` label because we should probably do this sooner rather than later since it's unclear when the deprecated bits will be removed.

**Comment by abdonrd** [comment]
@robdodson please, take a look #616. :)
