### ISSUE TITLE
Error when enable Service Worker support

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/polymer-starter-kit#571]
When I enable Service Worker support, I have this console error:

<img width="664" alt="screen shot 2015-12-06 at 16 31 07" src="https://cloud.githubusercontent.com/assets/1007051/11614081/6d70f74c-9c37-11e5-8286-5bcb264ae3d0.png">

I do this in a new PSK 1.2 version project.

**Comment by robdodson** [comment]
I think this is related to this bug https://code.google.com/p/chromium/issues/detail?id=541797&q=service%20worker%20ERR_FILE_EXISTS&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified

@jeffposnick and I discussed this. He mentioned that it shouldn't have any negative effects but I'm cc'ing him here just in case to verify.

**Comment by abdonrd** [comment]
Ok, thanks @robdodson!

**Comment by jeffposnick** [comment]
Right. It's a scary-looking console message, but it's just harmless noise that will hopefully go away in a future version of Chrome.

**Comment by abdonrd** [comment]
Thanks for the confirmation, @jeffposnick!
