### ISSUE TITLE
Production build does not work in v1.2.0

### ISSUE THREAD

**Issue by tanx** [PolymerElements/polymer-starter-kit#573]
I downloaded polymer starter kit v1.2.0 from the github releases page and followed all the build instructions. After running `gulp` and then `gulp serve:dist` this is what my the page looks like:

https://tankredhase.com/mail-playground/

Notice how the layout is not correct and the icons are all over the place. When I run simply `gulp serve` it works.

Note: All I changed in the code was the [baseUrl in app.js](https://github.com/tanx/mail-playground/commit/df0c64e29a61ace83a227af845b3db488949b904) like it said under [gh-pages deployment](https://github.com/PolymerElements/polymer-starter-kit#github-pages). Other than that it's a clean slate from v1.2.0.

Perhaps there is an issue with the vulcanize step? Just guessing here, since I'm just starting out with Polymer. Great work on the starter kit btw. Super helpful!

**Comment by tanx** [comment]
Update: so I used the current master and the issue seems to be resolved already have been resolved in https://github.com/PolymerElements/polymer-starter-kit/commit/266e8f9064cc52c4159c0b4c122ad92907821a7b

I guess I'll just upgrade to v1.2.1 once it's out. Thanks!

**Comment by samccone** [comment]
:+1:
