### ISSUE TITLE
paper-toolbar #topBar

### ISSUE THREAD

**Issue by Negashev** [PolymerElements/polymer-starter-kit#574]
with an increase in text `.app-name`, `paper-icon-button` fall under `.app-name` and no longer work

youtube
[![paper-toolbar #topBar](http://img.youtube.com/vi/I_9nA2X7RfQ/0.jpg)](https://www.youtube.com/watch?v=I_9nA2X7RfQ "paper-toolbar #topBar")

**Comment by robdodson** [comment]
Does this happen if you start the toolbar off with a lot of text, or only if you dynamically add text?

**Comment by samccone** [comment]
Will reopen if you have any more details @Negashev
