### ISSUE TITLE
Question about updating Polymer Starter Kit

### ISSUE THREAD

**Issue by zboralski** [PolymerElements/polymer-starter-kit#575]
I love the Polymer Starter Kit. However, I find it really hard to synchronise PSK commits once you have an customised app up and running.

Wouldn't it be possible to split it into two repos? One for the build environment and another repo for the sample app. Maintaining an app and keeping it up to date with Polymer Starter Kit would be much easier this way.

**Comment by addyosmani** [comment]
I wonder if this is something we could better cater with through Tooling. Splitting up the repo further would add some overhead to maintenance but we'll take another look at how we can ease the upgrade path early next year.

**Comment by MeTaNoV** [comment]
It is tedious but achievable if you kept the original PSK you forked, then incrementally (and often) update it and your app with the new version... I did it when I started a small app example. Not optimal but, yeah, the world isn't perfect! :)

**Comment by cnbuff410** [comment]
Well, if you keep up with PSK by git merge, it basically screw up your commit history because all the commits of PSK which you really don't care that much would show up in your history.

We have a company repo based on PSK and essentially we stopped tracking new PSK commit after we had some prototype up and running.

**Comment by flaiker** [comment]
@cnbuff410
Can't you do something like `git merge --squash upstream/polymer-starter-kit` to keep history clean?

**Comment by cnbuff410** [comment]
Wow, thank you for the tip @flaiker, didn't know about this option before. Will definitely try it out next time!

**Comment by MeTaNoV** [comment]
yup, this is a good one to keep in mind! :)

**Comment by robdodson** [comment]
Going to track this over in https://github.com/PolymerElements/polymer-starter-kit/issues/631
