### ISSUE TITLE
There are any plans to migrate PSK from 'dom-bind centric' to 'app-element centric'?

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/polymer-starter-kit#576]
Like the talk [Thinking in Polymer (The Polymer Summit 2015)](https://www.youtube.com/watch?v=ZDjiUmx51y8).

**Comment by robdodson** [comment]
Yep we'll probably be working on that in the new year

**Comment by robdodson** [comment]
oh sorry I thought you were asking if we were going to use the [app-layout elements](https://github.com/PolymerLabs/app-layout).

No, we will not be creating a `<my-app>` element. We will also *not* be using `dom-bind`. Instead we're experimenting with a 3rd approach that let's us lazily data bind elements just sitting in the `<body>`.

I'd like to close this as it's more of question than an issue.

**Comment by abdonrd** [comment]
Thanks @robdodson!

**Comment by nylki** [comment]
@robdodson Can the process be tracked in a different issue? :)
I really dislike the behaviour of `dom-bind` being basically a replacement of `body` as outlined here: http://stackoverflow.com/questions/35002817/polymer-accessibility-when-js-is-disabled-with-dom-bind/35003215#35003215
