### ISSUE TITLE
Request for Chrome Packaged App recipe

### ISSUE THREAD

**Issue by maria-le** [PolymerElements/polymer-starter-kit#577]
Could you please [create and share a recipe](https://github.com/PolymerElements/polymer-starter-kit/blob/master/docs/README.md) for how to make a Chrome Packaged App from PSK?

**Comment by robdodson** [comment]
Hm is this the same thing? https://github.com/PolymerElements/polymer-starter-kit/blob/master/docs/mobile-chrome-apps.md

Apologies if it's not. Packaged apps are not my domain :D

**Comment by robdodson** [comment]
Ah nvm, you're talking about a desktop app, yeah?

**Comment by maria-le** [comment]
Yes. Correct. Desktop. Chrome Apps (while phasing out the legacy term "packaged," apparently) are very "next-level."

[Here's the overview](https://developer.chrome.com/apps/about_apps).

I see Polymer as being so incredibly powerful because with a single code base we can deploy in minutes to web, mobile (Android and iOS) and (with Chrome Apps) to "native desktop" (look-and-feel anyway). See what I mean? That's next-level.

Anyway, it's worth looking at.

Also, please see the question I left for @Arthur about this in the slack site a few hours ago while you had stepped away.

**Comment by robdodson** [comment]
My understanding is [Chrome Apps are being discontinued in favor of Progressive Web Apps](http://blog.chromium.org/2016/08/from-chrome-apps-to-web.html). Because PSK is a Progressive Web App by default, I'm going to close this issue if that's ok.
