### ISSUE TITLE
really frivolous, verging on me being a bit nit-picky, but: Travis CL?

### ISSUE THREAD

**Issue by diddledan** [PolymerElements/polymer-starter-kit#578]
https://github.com/PolymerElements/polymer-starter-kit/blob/master/gulpfile.js#L319

I'm not sure about you, but I've not seen the word "integration" spelt with an L before.

**Comment by samccone** [comment]
Prs welcome @diddledan  :)

**Comment by samccone** [comment]
Thanks for the spot @diddledan and thanks for the fix @chuckh 

woohoo :tada:
