### ISSUE TITLE
gzip

### ISSUE THREAD

**Issue by robrez** [PolymerElements/polymer-starter-kit#582]
Any talk of adding a gzip task to gulp?

**Comment by samccone** [comment]
mind expanding on the questions?

1. what is the output?
2. why is this needed?
3. what would we gzip exactly?

**Comment by robrez** [comment]
I was thinking it would be nice gzip any of the .html resources that window up in `dist/` for browsers/servers that support `Accepted-Encoding: gzip`.

eg: https://www.nginx.com/resources/admin-guide/compression-and-decompression/

For example, `dist/` would end up w/ `elements.vulcanized.html` and `elements.vulcanized.html.gz`

**Comment by samccone** [comment]
by defauly nginx will take care of the compression for us...
https://www.nginx.com/resources/admin-guide/compression-and-decompression/

As will most "Static" servers, so I am not sure if we get big wins here... thoughts?

**Comment by robrez** [comment]
Reading over it again, I think you're right!

I missed the the detail about the `gzip` directive supports dynamic/runtime compression.

> Note that the gzip_static directive does not enable on-the-fly compression. It merely uses a file compressed beforehand by any compression tool. To compress content (and not only static content) at runtime, use the gzip directive.

**Comment by samccone** [comment]
tbh I had to do some reading also! 

so thanks for the very interesting question :book:

**Comment by robrez** [comment]
:100:
