### ISSUE TITLE
Add auto deploy and test for Firebase

### ISSUE THREAD

**Issue by chuckh** [PolymerElements/polymer-starter-kit#583]
Currently I manually deploy to Firebase using below script. Lets add this process and possibly a test to travis_runner.sh.  I am working a pr now for this.

## Background:
@robdodson 
> @samccone yeah, right now it sounds like chuck is manually running these scripts. Even for the convenience of being able to always hit the URL and know it's running the latest stable PSK on Firebase would be useful.

@samccone
>sure we can add a CI deploy "test" that would then hit the server after the deploy and run a quick smoke test of the page via selenium....

## Script I created to deploy PSK to Firebase

```
clear
echo Build and Deploy PSK to Firebaseapp.com Server
echo  Comment: $1
echo
echo Making Changes to PSK for Firebase
cp firebase.json polymer-starter-kit/firebase.json
cd polymer-starter-kit
sed -i.tmp 's/<!-- Chrome for Android theme color -->/<base href="\/">\'$'\n<!-- Chrome for Android theme color -->/g' app/index.html
sed -i.tmp "s/hashbang: true/hashbang: false/" app/elements/routing.html

echo Starting Build Process
gulp
echo Finished Build Process, will start Firebase Deploy to PRODUCTION Server next
echo
echo Press any key to continue,  or control-c to abort
read -n 1 -s
echo
echo Starting Deploy Process to Firebaseapp.com Server -- polymer-starter-kit.firebaseapp.com
firebase deploy -m "$1"

echo Undoing Changes to PSK for Firebase
cp app/index.html.tmp app/index.html
cp app/elements/routing.html.tmp app/elements/routing.html
rm app/elements/routing.html.tmp
rm app/index.html.tmp
rm firebase.json

echo Done
firebase open

cd ../
```

**Comment by robdodson** [comment]
Going to close this in favor of the PR if that's ok?

**Comment by chuckh** [comment]
:+1:
