### ISSUE TITLE
Dist serve is different from complete project

### ISSUE THREAD

**Issue by stefanoantonel** [PolymerElements/polymer-starter-kit#585]
Hi team! 
I have a problem when I want to use the files in the dist folder. 

## The application looks like this: 

![screenshot_2015-12-12_12-05-02](https://cloud.githubusercontent.com/assets/4954312/11762540/dfa96cd2-a0c8-11e5-8ee8-d61dcaeb9b07.png)

But after vulcanize and use 
```
gulp serve:dist
```

## This is the application in the dist folder:

![screenshot 2015-12-12 11 58 24](https://cloud.githubusercontent.com/assets/4954312/11762539/dfa6f09c-a0c8-11e5-993f-0d01115fd023.png)

I don't understand why this pages are not the same after the vulcanization process.. 
Thank you so much!

**Comment by robdodson** [comment]
Which version of the starter kit are you using?
Which browser are you on?
Do you have any errors in the console?

**Comment by stefanoantonel** [comment]
Hi there! 
I'm using PSK 1.2.0. 
Using Google Chrome Version 47.0.2526.73 (64-bit) on Linux. 
I have no errors in console. Just a warning. 

![screenshot_2015-12-14_14-23-00](https://cloud.githubusercontent.com/assets/4954312/11788160/57f0278e-a26e-11e5-8bd9-feebd1c8b339.png)

**Comment by samccone** [comment]
What about in your terminal console?

**Comment by stefanoantonel** [comment]
I didn't have any error in the terminal neither.
I tried to upgrade to polymer 1.2.1 and it worked! 

The only thing.. Now I'm having another error but I think that this is another topic!
![screenshot_2015-12-14_15-07-56](https://cloud.githubusercontent.com/assets/4954312/11789337/9078745c-a274-11e5-92cd-ff35ec0cb32e.png)

Thank you so much!
