### ISSUE TITLE
menu automatically opens in landscape mode 

### ISSUE THREAD

**Issue by arangates** [PolymerElements/polymer-starter-kit#589]
i was testing polymer starter kit with my oneplus one and found that meny automatically opens in landscape mode and menu button is not displayed

**Comment by nagarjunredla** [comment]
The breakpoint for the drawer panel to change to narrow mode is at 600px
<img width="928" alt="screen shot 2015-12-18 at 12 48 38 am" src="https://cloud.githubusercontent.com/assets/8291900/11879425/49167b0e-a521-11e5-89d5-c6e391720d21.png">
The screen width of your oneplus one is greater than 600px in landscape mode, so you see the drawer panel in wide layout.

**Comment by robdodson** [comment]
yeah you should be able to change this by adding a `responsive-width` attribute to the paper-drawer-panel. https://github.com/PolymerElements/polymer-starter-kit/blob/master/app/index.html#L66

**Comment by arangates** [comment]
Thank you... it worked !!!
