### ISSUE TITLE
Consider not using forceNarrow on desktop

### ISSUE THREAD

**Issue by salamanders** [PolymerElements/polymer-starter-kit#59]
https://www.polymer-project.org/1.0/docs/start/getting-the-code.html is great - left hand nav is very responsive, collapses and expands as I change the browser width.  I want that for the starter kit - responsive design out of the box!

Current:
Run app locally
Enlarge window
Menu *doesn't* responsively become a left hand nav

**Comment by addyosmani** [comment]
This is intentional. The Material Design team have recommended that the nav not expand on desktop (per my last discussion with them). We'll re-evaluate this, but this was a conscious decision.

**Comment by chuckh** [comment]
I agree that for the desktop nav should be expanded, but only on first load. This way users see what nav options are available when first loading. Once they tap on a nav item the nav should collapse.  This is a middle ground approach. To do this just don't set   `drawerPanel.forceNarrow = false;` and add some styling for the `<div drawer>`

**Comment by chuckh** [comment]
Suggested changes to Polymer Starter Kit.
1. For desktop start with nav open
2. Put App title on Nav bar
3. Put page title where app name was
4. Collapse nav after selecting menu item﻿

I would be happy to do a pull request if these changes are agreeable @addyosmani.

Screenshot of suggested changes. 

![psk-desktop-open](https://cloud.githubusercontent.com/assets/19915/7902348/ea83f27c-076b-11e5-8826-7160c203009d.png)

**Comment by addyosmani** [comment]
Thanks for exploring these ideas @chuckh. I'll ping them over to our designer for review and let you know what he says :)

**Comment by chuckh** [comment]
@addyosmani below is an  animated gif of these proposed changes. I also corrected the logo, and improved the margins. 

![psk-suggestion](https://cloud.githubusercontent.com/assets/19915/7935419/bba151f4-08e5-11e5-8b60-ce650bd88f5f.gif)

**Comment by beacrea** [comment]
Yeah, I'm confused since the desktop spec seems to be a forced open drawer, per http://www.google.com/design/spec/patterns/navigation-drawer.html#navigation-drawer-content in the behavior section.

**Comment by addyosmani** [comment]
Thanks @chuckh. I'll aim to get feedback this week.

**Comment by addyosmani** [comment]
Just spoke to one of our Material designers. His feedback:

> The drawer should be able to adapt to the context of a product. If navigation is important to the site, it can be permanently exposed when screen space allows for it, like the polymer site. If the importance of navigation depends on how a user interacts with the product, it can be persistent, like music. If a product wants to hide navigation, to keep a users focus on page content, it can be temporary, like how inbox used to be. There is no one solution, instead we offer a flexible system. These patterns are documented in the layout > adaptive ui section of spec where you can see how the different behaviors affect the grid, and in patterns > navigation drawer > behavior  which documents the different visual styles per pattern. 

My interpretation of this is that there isn't a one size fits all answer. @tjsavage do you have any thoughts on how we should proceed here? Keep the current layout (drawer closed on desktop) or switch to open?

**Comment by chuckh** [comment]
That is good feedback and explanation. Which ever way is decided. Styling should be provided for the sidebar to be exposed like Polymer site (`drawerPanel.forceNarrow not being set`).

For the Polymer Starter Kit the readme.md could have instructions on how to change the default.

It could be an option with the Yeoman Generator for Polymer (expose nav for desktop/tablet).

**Comment by addyosmani** [comment]
> For the Polymer Starter Kit the readme.md could have instructions on how to change the default.

I agree with this. It's something I should expand the FAQ in #111 to include guidance on.

**Comment by addyosmani** [comment]
Latest from our designer after thinking about this some more:

> FWIW, I'd lean toward the default behavior being open. The hamburger icon often leads to discoverability issues. 

Let's tackle this after #117 is resolved as some more work on card margins will be needed

**Comment by chuckh** [comment]
I also lean toward the default behavior being open.

Example of the behavior:
![image](https://cloud.githubusercontent.com/assets/19915/8007412/7dcd76ba-0b50-11e5-8790-e14496f651cf.png)
see my App Layout Templates pull request for example of these changes at https://github.com/PolymerElements/app-layout-templates/pull/5

I agree it does make sense to tackle after #117.

**Comment by addyosmani** [comment]
Closed in https://github.com/PolymerElements/polymer-starter-kit/pull/137
