### ISSUE TITLE
Gulp & Firebase issues

### ISSUE THREAD

**Issue by nickabocker** [PolymerElements/polymer-starter-kit#593]
Hello,

I was playing around with the polymer starter kit and created my first app. I've run into three issues and not sure what happened but 1st off when I ran Gulp it created the proper dist folder but didn't transfer scripts, CSS,images etc into the folder. 2ndwhwn I tried to run Firebase deploy it acts like it will work but it never does the debug log says http 200 after "preparing app".   Third thing that has happened is gulp also rearranged the entire structure of my app so now I can not run a simple python server to test.

Any ideas?

Nick

**Comment by robdodson** [comment]
I guess we should try to tackle each of these individually starting with the first.

Can you paste into this comment thread the console output from when you run `gulp`.

**Comment by nickabocker** [comment]
[13:04:15] Using gulpfile ~\Newfolder\Wackerli\gulpfile.js
[13:04:15] Starting 'clean'...
[13:04:15] Finished 'clean' after 32 ms
[13:04:15] Starting 'default'...
[13:04:15] Starting 'copy'...
[13:04:15] 'copy' errored after 27 ms
[13:04:15] Error: Cannot find module 'gulp-size'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at requireFn (C:\Users\nick\Newfolder\Wackerli\node_modules\gulp-load-plugins\index.js:40:16)
    at Object.defineProperty.get (C:\Users\nick\Newfolder\Wackerli\node_modules\gulp-load-plugins\index.js:65:18)
    at Gulp.<anonymous> (C:\Users\nick\Newfolder\Wackerli\gulpfile.js:153:12)
    at module.exports (C:\Users\nick\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\Users\nick\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\Users\nick\node_modules\orchestrator\index.js:214:10)
[13:04:15] 'default' errored after 35 ms
[13:04:15] Error in plugin 'run-sequence'
Message:
    An error occured in task 'copy'.

**Comment by robdodson** [comment]
can you try running `npm install` again/

**Comment by nickabocker** [comment]
C:\Users\nick\Newfolder\Wackerli>npm install
/
> gifsicle@3.0.3 postinstall C:\Users\nick\Newfolder\Wackerli\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\imagemin-gifsicle\node_modules\gifsicle
> node lib/install.js

  √ gifsicle pre-build test passed successfully

> optipng-bin@3.0.4 postinstall C:\Users\nick\Newfolder\Wackerli\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\imagemin-optipng\node_modules\optipng-bin
> node lib/install.js

  √ optipng pre-build test passed successfully

> jpegtran-bin@3.0.6 postinstall C:\Users\nick\Newfolder\Wackerli\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\imagemin-jpegtran\node_modules\jpegtran-bin
> node lib/install.js

  √ jpegtran pre-build test passed successfully
gulp-vulcanize@6.1.0 node_modules\gulp-vulcanize
├── through2@2.0.0 (xtend@4.0.1, readable-stream@2.0.4)
└── gulp-util@3.0.7 (array-differ@1.0.0, array-uniq@1.0.2, fancy-log@1.1.0, lodash._reevaluate@3.0.0, lodash._reescape@3.0.0, lodash._reinterpolate@3.0.0, object-assign@3.0.0, beeper@1.1.0, replace-ext@0.0.1, minimist@1.2.0, has-gulplog@0.1.0, vinyl@0.5.3, chalk@1.1.1, lodash.template@3.6.2, gulplog@1.0.0, multipipe@0.1.2, dateformat@1.0.12)

gulp-changed@1.3.0 node_modules\gulp-changed
├── through2@2.0.0 (xtend@4.0.1, readable-stream@2.0.4)
└── gulp-util@3.0.7 (array-differ@1.0.0, array-uniq@1.0.2, fancy-log@1.1.0, lodash._reevaluate@3.0.0, object-assign@3.0.0, lodash._reinterpolate@3.0.0, lodash._reescape@3.0.0, beeper@1.1.0, replace-ext@0.0.1, minimist@1.2.0, has-gulplog@0.1.0, vinyl@0.5.3, chalk@1.1.1, lodash.template@3.6.2, gulplog@1.0.0, multipipe@0.1.2, dateformat@1.0.12)

gulp-uglify@1.5.1 node_modules\gulp-uglify
├── uglify-save-license@0.4.1
├── deap@1.0.0
├── isobject@2.0.0 (isarray@0.0.1)
├── vinyl-sourcemaps-apply@0.2.0 (source-map@0.5.3)
├── through2@2.0.0 (xtend@4.0.1, readable-stream@2.0.4)
├── uglify-js@2.6.0 (async@0.2.10, uglify-to-browserify@1.0.2, source-map@0.5.3, yargs@3.10.0)
├── fancy-log@1.1.0 (chalk@1.1.1, dateformat@1.0.12)
└── gulp-util@3.0.7 (array-differ@1.0.0, array-uniq@1.0.2, lodash._reescape@3.0.0, beeper@1.1.0, object-assign@3.0.0, lodash._reevaluate@3.0.0, lodash._reinterpolate@3.0.0, replace-ext@0.0.1, has-gulplog@0.1.0, minimist@1.2.0, vinyl@0.5.3, chalk@1.1.1, lodash.template@3.6.2, gulplog@1.0.0, multipipe@0.1.2, dateformat@1.0.12)

gulp-cache@0.2.10 node_modules\gulp-cache
├── object.pick@1.1.1
├── object-assign@3.0.0
├── try-json-parse@0.1.1
├── vinyl@0.5.3 (clone-stats@0.0.1, replace-ext@0.0.1, clone@1.0.2)
├── object.omit@1.1.0 (isobject@1.0.2, for-own@0.1.3)
├── through2@0.6.5 (xtend@4.0.1, readable-stream@1.0.33)
├── bluebird@2.10.2
├── cache-swap@0.2.3 (object-assign@4.0.1, graceful-fs@4.1.2, rimraf@2.4.4, mkdirp@0.5.1)
└── gulp-util@3.0.7 (array-differ@1.0.0, array-uniq@1.0.2, fancy-log@1.1.0, beeper@1.1.0, lodash._reevaluate@3.0.0, lodash._reescape@3.0.0, lodash._reinterpolate@3.0.0, replace-ext@0.0.1, has-gulplog@0.1.0, minimist@1.2.0, chalk@1.1.1, lodash.template@3.6.2, gulplog@1.0.0, through2@2.0.0, multipipe@0.1.2, dateformat@1.0.12)

gulp-size@1.3.0 node_modules\gulp-size
├── chalk@1.1.1 (escape-string-regexp@1.0.3, ansi-styles@2.1.0, supports-color@2.0.0, strip-ansi@3.0.0, has-ansi@2.0.0)
├── through2@2.0.0 (xtend@4.0.1, readable-stream@2.0.4)
├── gzip-size@1.0.0 (concat-stream@1.5.1, browserify-zlib@0.1.4)
├── pretty-bytes@2.0.1 (get-stdin@4.0.1, number-is-nan@1.0.0, meow@3.6.0)
└── gulp-util@3.0.7 (array-differ@1.0.0, array-uniq@1.0.2, fancy-log@1.1.0, lodash._reinterpolate@3.0.0, lodash._reevaluate@3.0.0, lodash._reescape@3.0.0, beeper@1.1.0, object-assign@3.0.0, replace-ext@0.0.1, minimist@1.2.0, has-gulplog@0.1.0, vinyl@0.5.3, lodash.template@3.6.2, gulplog@1.0.0, multipipe@0.1.2, dateformat@1.0.12)

gulp@3.9.0 node_modules\gulp
├── interpret@0.6.6
├── pretty-hrtime@1.0.1
├── deprecated@0.0.1
├── archy@1.0.0
├── minimist@1.2.0
├── tildify@1.1.2 (os-homedir@1.0.1)
├── v8flags@2.0.10 (user-home@1.1.1)
├── semver@4.3.6
├── chalk@1.1.1 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, has-ansi@2.0.0, strip-ansi@3.0.0)
├── orchestrator@0.3.7 (stream-consume@0.1.0, sequencify@0.0.7, end-of-stream@0.1.5)
├── liftoff@2.2.0 (findup-sync@0.3.0, extend@2.0.1, rechoir@0.6.2, flagged-respawn@0.3.1, resolve@1.1.6)
├── vinyl-fs@0.3.14 (graceful-fs@3.0.8, strip-bom@1.0.0, vinyl@0.4.6, defaults@1.0.3, through2@0.6.5, mkdirp@0.5.1, glob-stream@3.1.18, glob-watcher@0.0.6)
└── gulp-util@3.0.7 (array-differ@1.0.0, array-uniq@1.0.2, lodash._reescape@3.0.0, beeper@1.1.0, fancy-log@1.1.0, lodash._reinterpolate@3.0.0, object-assign@3.0.0, lodash._reevaluate@3.0.0, replace-ext@0.0.1, has-gulplog@0.1.0, vinyl@0.5.3, lodash.template@3.6.2, gulplog@1.0.0, through2@2.0.0, multipipe@0.1.2, dateformat@1.0.12)

gulp-useref@1.3.0 node_modules\gulp-useref
├── is-relative-url@1.0.0 (is-absolute-url@1.0.0)
├── brace-expansion@1.1.2 (concat-map@0.0.1, balanced-match@0.3.0)
├── multimatch@2.1.0 (array-differ@1.0.0, arrify@1.0.1, minimatch@3.0.0, array-union@1.0.1)
├── event-stream@3.3.2 (pause-stream@0.0.11, duplexer@0.1.1, from@0.1.3, stream-combiner@0.0.4, map-stream@0.1.0, split@0.3.3, through@2.3.8)
├── through2@0.6.5 (xtend@4.0.1, readable-stream@1.0.33)
├── node-useref@0.3.15
├── gulp-concat@2.6.0 (concat-with-sourcemaps@1.0.4)
├── vinyl-fs@1.0.0 (object-assign@2.1.1, graceful-fs@3.0.8, strip-bom@1.0.0, vinyl@0.4.6, mkdirp@0.5.1, duplexify@3.4.2, glob-watcher@0.0.8, glob-stream@4.1.1)
├── gulp-util@3.0.7 (array-differ@1.0.0, array-uniq@1.0.2, lodash._reescape@3.0.0, object-assign@3.0.0, fancy-log@1.1.0, lodash._reevaluate@3.0.0, beeper@1.1.0, lodash._reinterpolate@3.0.0, replace-ext@0.0.1, has-gulplog@0.1.0, minimist@1.2.0, vinyl@0.5.3, chalk@1.1.1, lodash.template@3.6.2, gulplog@1.0.0, through2@2.0.0, multipipe@0.1.2, dateformat@1.0.12)
└── lodash@3.10.1

gulp-autoprefixer@2.3.1 node_modules\gulp-autoprefixer
├── object-assign@2.1.1
├── through2@0.6.5 (xtend@4.0.1, readable-stream@1.0.33)
├── vinyl-sourcemaps-apply@0.1.4 (source-map@0.1.43)
├── postcss@4.1.16 (js-base64@2.1.9, es6-promise@2.3.0, source-map@0.4.4)
├── gulp-util@3.0.7 (array-differ@1.0.0, array-uniq@1.0.2, fancy-log@1.1.0, object-assign@3.0.0, lodash._reinterpolate@3.0.0, lodash._reescape@3.0.0, beeper@1.1.0, lodash._reevaluate@3.0.0, replace-ext@0.0.1, minimist@1.2.0, has-gulplog@0.1.0, vinyl@0.5.3, chalk@1.1.1, lodash.template@3.6.2, gulplog@1.0.0, through2@2.0.0, multipipe@0.1.2, dateformat@1.0.12)
└── autoprefixer-core@5.2.1 (num2fraction@1.2.2, browserslist@0.4.0, caniuse-db@1.0.30000377)

gulp-minify-html@1.0.4 node_modules\gulp-minify-html
├── through2@0.6.5 (xtend@4.0.1, readable-stream@1.0.33)
├── gulp-util@3.0.7 (array-differ@1.0.0, array-uniq@1.0.2, beeper@1.1.0, lodash._reescape@3.0.0, object-assign@3.0.0, lodash._reevaluate@3.0.0, fancy-log@1.1.0, lodash._reinterpolate@3.0.0, replace-ext@0.0.1, has-gulplog@0.1.0, minimist@1.2.0, vinyl@0.5.3, chalk@1.1.1, lodash.template@3.6.2, gulplog@1.0.0, through2@2.0.0, multipipe@0.1.2, dateformat@1.0.12)
└── minimize@1.7.4 (emits@3.0.0, async@1.4.2, argh@0.1.4, node-uuid@1.4.7, diagnostics@1.0.1, htmlparser2@3.8.3, cli-color@1.0.0)

gulp-imagemin@2.4.0 node_modules\gulp-imagemin
├── object-assign@4.0.1
├── plur@2.1.1 (irregular-plurals@1.1.0)
├── chalk@1.1.1 (escape-string-regexp@1.0.3, ansi-styles@2.1.0, supports-color@2.0.0, strip-ansi@3.0.0, has-ansi@2.0.0)
├── through2-concurrent@1.1.0 (through2@2.0.0)
├── pretty-bytes@2.0.1 (get-stdin@4.0.1, number-is-nan@1.0.0, meow@3.6.0)
├── gulp-util@3.0.7 (array-differ@1.0.0, array-uniq@1.0.2, fancy-log@1.1.0, object-assign@3.0.0, lodash._reinterpolate@3.0.0, lodash._reevaluate@3.0.0, lodash._reescape@3.0.0, beeper@1.1.0, replace-ext@0.0.1, minimist@1.2.0, has-gulplog@0.1.0, vinyl@0.5.3, lodash.template@3.6.2, gulplog@1.0.0, through2@2.0.0, multipipe@0.1.2, dateformat@1.0.12)
└── imagemin@4.0.0 (optional@0.1.3, stream-combiner2@1.1.1, concat-stream@1.5.1, readable-stream@2.0.4, buffer-to-vinyl@1.1.0, vinyl-fs@2.2.1, imagemin-svgo@4.2.0, imagemin-gifsicle@4.2.0, imagemin-optipng@4.3.0, imagemin-jpegtran@4.3.2)

C:\Users\nick\Newfolder\Wackerli>

**Comment by nickabocker** [comment]
C:\Users\nick\Newfolder\Wackerli>gulp
[14:27:41] Using gulpfile ~\Newfolder\Wackerli\gulpfile.js
[14:27:41] Starting 'clean'...
[14:27:41] Finished 'clean' after 23 ms
[14:27:41] Starting 'default'...
[14:27:41] Starting 'copy'...
[14:27:43] Starting 'styles'...
[14:27:50] styles all files 98 B
[14:27:50] Finished 'styles' after 7.38 s
[14:28:05] copy all files 12.96 MB
[14:28:05] Finished 'copy' after 24 s
[14:28:05] Starting 'elements'...
[14:28:05] Finished 'elements' after 6.04 ms
[14:28:05] Starting 'jshint'...
[14:28:10] Starting 'images'...
[14:28:17] Starting 'fonts'...
[14:28:17] Starting 'html'...
[14:28:24] Finished 'fonts' after 6.97 s
[14:28:25] Finished 'jshint' after 20 s
[14:28:25] html all files 49.62 kB
[14:28:25] Finished 'html' after 8.2 s
[14:28:26] images all files 35.41 kB
[14:28:26] Finished 'images' after 16 s
[14:28:26] Starting 'vulcanize'...
[14:28:26] Finished 'vulcanize' after 14 ms
[14:28:26] Starting 'rename-index'...
[14:28:26] Finished 'rename-index' after 1.75 ms
[14:28:26] Starting 'remove-old-build-index'...
[14:28:26] Finished 'remove-old-build-index' after 962 μs
[14:28:26] Finished 'default' after 45 s


gulp seems to work now

**Comment by robdodson** [comment]
OK so next part...

> "2ndwhwn I tried to run Firebase deploy it acts like it will work but it never does the debug log says http 200 after "preparing app".

I'm wondering if you can delete your firebase.json and run `npm install -g firebase-tools` again. Then run `gulp`, then `firebase init`. Pick the `dist` directory as the thing you want to deploy and then try `firebase deploy` again.

**Comment by nickabocker** [comment]
here is what happened with this step...
C:\Users\nick\Newfolder\Wackerli>npm install -g firebase-tools
npm WARN optional dep failed, continuing fsevents@1.0.6
C:\Users\nick\AppData\Roaming\npm\firebase -> C:\Users\nick\AppData\Roaming\npm\node_modules\firebase-tools\bin\firebase
firebase-tools@2.1.1 C:\Users\nick\AppData\Roaming\npm\node_modules\firebase-tools
├── exit-code@1.0.2
├── didyoumean@1.2.1
├── jsonschema@1.0.2
├── open@0.0.5
├── progress@1.1.8
├── through@2.3.8
├── filesize@3.1.4
├── uuid@2.0.1
├── node-uuid@1.4.7
├── semver@5.1.0
├── user-home@2.0.0 (os-homedir@1.0.1)
├── commander@2.9.0 (graceful-readlink@1.0.1)
├── rsvp@3.1.0
├── tmp@0.0.27 (os-tmpdir@1.0.1)
├── chalk@1.1.1 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, has-ansi@2.0.0, strip-ansi@3.0.0)
├── cli-table@0.3.1 (colors@1.0.3)
├── universal-analytics@0.3.9 (async@0.2.10, underscore@1.8.3)
├── concat-stream@1.5.1 (inherits@2.0.1, typedarray@0.0.6, readable-stream@2.0.4)
├── cjson@0.3.2 (json-parse-helpfulerror@1.0.3)
├── configstore@1.4.0 (os-tmpdir@1.0.1, object-assign@4.0.1, graceful-fs@4.1.2, xdg-basedir@2.0.0, osenv@0.1.3, write-file-atomic@1.1.4, mkdirp@0.5.1)
├── winston@1.1.2 (cycle@1.0.3, eyes@0.1.8, stack-trace@0.0.9, isstream@0.1.2, async@1.0.0, pkginfo@0.3.1, colors@1.0.3)
├── fstream-ignore@1.0.3 (inherits@2.0.1, minimatch@3.0.0, fstream@1.0.8)
├── fs-extra@0.23.1 (path-is-absolute@1.0.0, jsonfile@2.2.3, graceful-fs@4.1.2, rimraf@2.4.4)
├── update-notifier@0.5.0 (is-npm@1.0.0, semver-diff@2.1.0, string-length@1.0.1, repeating@1.1.3, latest-version@1.0.1)
├── firebase@2.3.2 (faye-websocket@0.9.3)
├── request@2.67.0 (aws-sign2@0.6.0, forever-agent@0.6.1, tunnel-agent@0.4.2, oauth-sign@0.8.0, caseless@0.11.0, is-typedarray@1.0.0, stringstream@0.0.5, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, tough-cookie@2.2.1, qs@5.2.0, form-data@1.0.0-rc3, combined-stream@1.0.5, mime-types@2.1.8, bl@1.0.0, hawk@3.1.2, http-signature@1.1.0, har-validator@2.0.3)
├── tar@2.2.1 (inherits@2.0.1, block-stream@0.0.8, fstream@1.0.8)
├── superstatic@3.0.0 (destroy@1.0.3, caseless@0.10.0, home-dir@1.0.0, globject@1.0.1, on-headers@1.0.1, compare-semver@1.1.0, etag@1.7.0, try-require@1.2.1, char-spinner@1.0.1, basic-auth-connect@1.0.0, connect-livereload@0.5.4, firstkey@0.1.0, is-url@1.2.1, async@1.5.0, install@0.1.8, qs@3.1.0, path-to-regexp@1.2.1, on-finished@2.3.0, mime-types@2.1.8, fast-url-parser@1.1.3, join-path@1.1.0, cache-header@1.0.3, cache-control@1.0.3, serve-favicon@2.3.0, booly@1.0.2, bundles@2.0.0, connect-query@0.2.0, clear-require@1.0.1, string-length@1.0.1, glob@5.0.15, send@0.13.0, pretty-print@1.1.0, minimatch@2.0.10, morgan@1.6.1, finalhandler@0.4.1, connect@3.4.0, compression@1.6.0, router@1.1.3, fs-extra@0.20.1, through2@2.0.0, nash@2.0.4, glob-slasher@1.0.1, express@4.13.3, flatten-to-object@1.0.0, as-array@1.0.0, npmconf@2.1.2, tiny-lr@0.1.7, chokidar@1.4.1, jfig@1.2.0, update-notifier@0.3.2)
├── lodash@3.10.1
└── inquirer@0.8.5 (ansi-regex@1.1.1, figures@1.4.0, cli-width@1.1.0, readline2@0.1.1, rx@2.5.3)

**Comment by robdodson** [comment]
That looks like correct output (the npm WARN can be ignored I believe). What happens if you now do `gulp` followed by `firebase init` and then `firebase deploy`?

**Comment by nickabocker** [comment]
When I preform firebase init I now seem to get an "invalid Firebase specified" error

**Comment by nickabocker** [comment]
it doesn't like it when i put "dist" as public root

**Comment by robdodson** [comment]
did you delete your preexisting firebase.json?

**Comment by nickabocker** [comment]
yes ill do it once more

**Comment by nickabocker** [comment]
i received the "invalid Firebase specified" error again

**Comment by robdodson** [comment]
ok so that sounds like the firebase instance you've selected isn't working for some reason... @mbleigh any ideas?

**Comment by mbleigh** [comment]
@nickabocker please run "firebase list" and check that the project you've specified in the "firebase" key of `firebase.json` is listed. If it's not, you'll need to create a project with that name or sign in with an account that has access.

**Comment by nickabocker** [comment]
ok i will look at this when i get home

**Comment by nickabocker** [comment]
@mbleigh okay that seemed to be part of the issue for some reason i couldn't create it as a new project as i was doing. Once did as you suggested i was able to run the firebase init command it worked and as well as firebase deploy. It did tell me there was no index.html file in the "public" folder however it seems my index file got renamed. Just processed it again and seems to be working now.

**Comment by nickabocker** [comment]
@mbleigh @robdodson thank you guys for your help! it seems the original link generated didn't work but as soon as i ran the link /index.html it worked :-) :+1:
