### ISSUE TITLE
how to resolve data before navigating to it?

### ISSUE THREAD

**Issue by jimmywarting** [PolymerElements/polymer-starter-kit#595]
I tried something like this. But it dosen't seem to work async. sync dose...

    page('/users/:id', function(data, next){

      return fetch("/api/users/" + data.params.id)
        .then(res => res.json())
        .then(list => {
           app.params = { user: user};
           next()
        })

    }, function(data) {
      app.route = 'users';
      console.log(app.params.user)
    });

**Comment by robdodson** [comment]
Does that 2nd function actually run? Seems like you're trying to do something like this: https://visionmedia.github.io/page.js/#separating-concerns

**Comment by jimmywarting** [comment]
Got it to work.
