### ISSUE TITLE
Setting a behavior

### ISSUE THREAD

**Issue by klarkc** [PolymerElements/polymer-starter-kit#596]
Hello, I am having a problem here, and I can't figure why, I have this behavior, in the path: app/elements/behaviors/youtube-api-behavior.html

```
<script>
  FicBehaviors.YoutubeApiBehavior = {
    properties: {
      api: {
        type: Object
      },
      conf: {
        type: Object
      }
    },

    ready: function() {
      if (this.api) {
        // Execute callback
        this.readyApi(this.api, this.conf);
      }
    }
  };
</script>
```

This behavior is being loaded in the app/elements.html file and in the elements that use the behavior.
The FicBehaviors namespace is defined into the `<head>` tag, in app/index.html file, before the elements importation:

```
  <!-- build:js scripts/fic-behaviors.js -->
  <script src="scripts/fic-behaviors.js"></script>
  <!-- endbuild -->
```

fic-behaviors.js file:
```
// Define Behaviors Namespace
window.FicBehaviors = window.FicBehaviors || {};
```

According Polymer [docs](https://www.polymer-project.org/1.0/docs/devguide/behaviors.html), We can define a namespace in the window variable.

When I lint the project:
```
$ gulp lint
[12:30:32] Using gulpfile ~/psk/gulpfile.js
[12:30:32] Starting 'lint'...

app/elements/behaviors/youtube-api-behavior.html-script-0
  line 2  col 3  'FicBehaviors' is not defined.

  ⚠  1 warning


app/elements/fic-featured/fic-featured.html-script-0
  line 7  col 21  'FicBehaviors' is not defined.

  ⚠  1 warning

[12:30:34] 'lint' errored after 1.52 s
[12:30:34] Error in plugin 'gulp-jshint'
Message:
    JSHint failed for: app/elements/behaviors/youtube-api-behavior.html-script-0, app/elements/fic-featured/fic-featured.html-script-0
```

If I define a local FicBehaviors variable `var FicBehaviors = window.FicBehaviors`I have this error in lint:
```
app/elements/behaviors/youtube-api-behavior.html-script-0
  line 3  col 0  Expected indentation of 0 characters

  ⚠  1 warning
```

**Comment by robdodson** [comment]
You need to add it to your `.jshintrc` file in the globals section: https://github.com/PolymerElements/polymer-starter-kit/blob/master/.jshintrc#L16-L22

Also you may want to have your default properties return new, empty objects:

```
properties: {
  api: {
    type: Object,
    value: function() {
      return {};
    }
  },
  conf: {
    type: Object,
    value: function() {
      return {};
    }
  }
}
```

Otherwise all instances of elements that implement this behavior will share the same object on their prototype for api and conf. So if instanceA changes its conf, it will change inside of instanceB, instanceC, etc.  Not sure if you intended that behavior so I wanted to point that out.
