### ISSUE TITLE
Toolbar hiding the scrollbar

### ISSUE THREAD

**Issue by MeTaNoV** [PolymerElements/polymer-starter-kit#598]
On the latest master, I just noticed that the toolbar is hiding the scrollbar. See the screenshot and compare to the Polymer doc page:

![image](https://cloud.githubusercontent.com/assets/11166016/11826699/477e2616-a387-11e5-849e-cfee92f74307.png)

**Comment by robdodson** [comment]
@MeTaNoV That's a known issue with paper-header-panel. I believe it's fixed in the new app-layout elements which we plan to port PSK to.

**Comment by MeTaNoV** [comment]
oki doki!
