### ISSUE TITLE
Cannot find module 'tough-cookie'

### ISSUE THREAD

**Issue by ubs121** [PolymerElements/polymer-starter-kit#599]
Missing module named 'tough-cookie' in gulpfile.js. 

Here is the output:

```sh
$ gulp serve
module.js:339
    throw err;
    ^

Error: Cannot find module 'tough-cookie'
```

**Comment by robdodson** [comment]
Hm can you delete the `node_modules` directory and try running `npm install` again?

**Comment by ubs121** [comment]
I tried `npm install`, but didn't work. Finally commented the following lines in `gulpfile.js`:

```js
//.pipe($.jshint())
//.pipe($.jshint.reporter('jshint-stylish'))
//.pipe($.if(!browserSync.active, $.jshint.reporter('fail')));
```

**Comment by pedrozbb** [comment]
npm cache clean
npm update -g
