### ISSUE TITLE
Can we link to a 'latest' zip?

### ISSUE THREAD

**Issue by robdodson** [PolymerElements/polymer-starter-kit#600]
Our [guide to PSK](https://www.polymer-project.org/1.0/docs/start/psk/set-up.html) states:

> Download the latest PSK release.

> There are two versions of the PSK, a light version (e.g.  polymer-starter-kit-light-x.x.x.zip) and a full version (e.g. polymer-starter-kit-x.x.x.zip). Download the full version.

It would be great if we could just link to a 'latest' tag. Is there some magic we can work to make this happen? I realize GitHub bakes the tag version into the URL so we would need to work around that. Maybe as part of our build process we could push the zips somewhere...? `bit.ly/psk-latest.zip` ?

cc @kaycebasques

**Comment by addyosmani** [comment]
Is the main reason we want this for the guide to PSK? If that's the case, we can use the GitHub API to periodically pull down the latest release URLs (maybe weekly?), cache them so we don't run into API limits and use those URLs for referencing them in the guide.

My only issue with trying to generate and push the zips somewhere is that we lose the ability to easily track all our downloads in one convenient place. 

An alternative is that we just link directly to the [releases](https://github.com/PolymerElements/polymer-starter-kit/releases) page and let folks pick the light or full version from there themselves. Wdyt?

**Comment by flaiker** [comment]
Does this help? https://github.com/PolymerElements/polymer-starter-kit/releases/latest
Not a direct link to zip-files but at least not as overwhelming as the full github-releases page ([ref](https://help.github.com/articles/linking-to-releases/)).

Also there apparently still is this page: https://github.com/PolymerElements/polymer-starter-kit/downloads but I think functionality was phased out as part of the releases system (see one with files [here](https://github.com/adobe-fonts/source-code-pro/downloads)).

**Comment by robdodson** [comment]
@addyosmani this was brought to my attention by @slightlyoff. When you're just getting started and you get dumped off into the releases page, it's kind of like you're getting hit with a wall of text. The notes on that page are useful if you're a previous PSK user, but if you're totally new it's perhaps confusing. I think Alex was thinking that for a guide on using PSK, it should just give you the zip and not make you choose

**Comment by robdodson** [comment]
Going to close this as we would like to encourage everyone to use Polymer CLI to generate their project. This will give them additional features like `polymer build` to productionize their app
