### ISSUE TITLE
change bower to npm

### ISSUE THREAD

**Issue by zhouwenbin** [PolymerElements/polymer-starter-kit#601]
`bower install` always fail when `git config --global url."https://".insteadOf git`.

**Comment by robdodson** [comment]
You need to install a keychain helper. I use the exact same config.

There are a handful of issues already in the Polymer repo related to npm. https://github.com/Polymer/polymer/issues/2578

This is something that will need to be changed at the Polymer and elements level, PSK has limited control over this.
