### ISSUE TITLE
Changes in js files not reflected on the browser in the latest PSK (w/ ES2015 support)

### ISSUE THREAD

**Issue by JustinXinLiu** [PolymerElements/polymer-starter-kit#603]
So I followed this [guide](https://github.com/PolymerElements/polymer-starter-kit/blob/master/docs/add-es2015-support-babel.md) here to add ES2015 support in a latest copy of the PSK.

What I've found is that if I change something in a *js* file, for example, comment out this line of code  `// app.$.headerPanelMain.scrollToTop(true);` in *app.js*. As soon as I save the change, the browser reloads itself, but then if I try to scroll down a bit and navigate to a different page, I can see that the auto scrolling is still there, unless I refresh the page again.

However, changing anything in an *html* file works just fine.

**Comment by robdodson** [comment]
Closing this as we no longer rely on a gulpfile in PSK and there will be some improvements coming to Polymer soon to help with ES2015. Stay tuned.
