### ISSUE TITLE
add-es2015-support-babel is broken with latest version of crsiper

### ISSUE THREAD

**Issue by Nejat** [PolymerElements/polymer-starter-kit#605]
the latest version of `crisper` defaults to `scriptInHead: true` which breaks the build if you follow the recipe

adding the following `{scriptInHead: false}` to the *crisper stream* in the `'js'` *gulp task* of the *es2015 recipe* fixes the issue 

    ...
        .pipe($.if('*.html', $.crisper({scriptInHead: false}))) // Extract JS from .html files
    ...

**Comment by robdodson** [comment]
hm that's a bummer. scriptInHead is a performance feature. I'll take a look

**Comment by robdodson** [comment]
I'm still not 100% on what's causing the issue.. For now I'll update the recipe with the `scriptInHead` workaround
