### ISSUE TITLE
Update WCT to 4.x

### ISSUE THREAD

**Issue by samccone** [PolymerElements/polymer-starter-kit#608]
Step 1. investigate what breaking changes were made in WCT
https://github.com/Polymer/web-component-tester/blob/master/CHANGELOG.md

Step 2. switch back to using the latest version of firefox on CI
https://github.com/PolymerElements/polymer-starter-kit/pull/607

**Comment by azakus** [comment]
Changelog updated. 4.0.0 removed `bower` by serving the fallback modules out of `node_modules` instead of `bower_components`.

**Comment by azakus** [comment]
`wct-local` also is using the latest selenium now (2.48.2).
