### ISSUE TITLE
Routing to urls with parameters does not work using address bar

### ISSUE THREAD

**Issue by flaiker** [PolymerElements/polymer-starter-kit#615]
Hello,

clicking on the url http://polymerelements.github.io/polymer-starter-kit/#!/users/Addy you get to Addy's page. However, if you start at home ( http://polymerelements.github.io/polymer-starter-kit/ ) and then copy paste the users/Addy url in the address bar and press enter you get a 404 error and get redirected to home:
![image](https://cloud.githubusercontent.com/assets/5270359/11912766/a0a6a69c-a64c-11e5-9cf5-648c7c85354b.png)

Tested in latest chrome/chromium. Seems to be an issue with pagejs, not sure if it's in psk's configuration.

**Comment by VandeurenGlenn** [comment]
Same here, when removing the hashbang it worked for me.

**Comment by robdodson** [comment]
Hm, maybe another good reason to move off of the hashbang... We're working on a PR to do this here: https://github.com/PolymerElements/polymer-starter-kit/pull/614

**Comment by VandeurenGlenn** [comment]
Awesome!

**Comment by stefanoantonel** [comment]
So what were the advantages of using hashbang? 
Do you guys recommend not using that anymore?

**Comment by robdodson** [comment]
> So what were the advantages of using hashbang?

If you're not using hashbangs then your server needs to always return `index.html` when someone visits `yoursite.com/foo/bar`. This is how pretty much all single page apps work in production. Because we previously were not providing a local server that was capable of doing these kind of rewrites we defaulted to hashbangs.

> Do you guys recommend not using that anymore?

Correct, if you can not use hashbangs that is preferable.

**Comment by semisided1** [comment]
i removed the hashbang configuration in routing.html ... but if my app is not at / then do a refresh i get a 404. its really easy on mobile to inadvertently refresh the page by swiping down.

**Comment by robdodson** [comment]
@semisided1 that's because your server isn't always serving `index.html`. You need to setup a rule on your server that matches any route and always responds with `index.html`.

**Comment by semisided1** [comment]
added to firebase.json and worked perfectly thanks
    "rewrites": [ {
      "source": "**",
      "destination": "/index.html"
    } ]

**Comment by JGSolutions** [comment]
i have this and still doesn't work

{
  "public": "app",
  "ignore": [
    "firebase.json",
    "**/.*",
    "**/node_modules/**"
  ],
  "rewrites": [
    {
      "source": "!{/bower_components,/elements}/**",
      "destination": "/index.html"
    }
  ]
}

if I add the historyApiFallback() it works

**Comment by robdodson** [comment]
@JGSolutions it doesn't work when you deploy to firebase or it doesn't work locally? That config will only work when you deploy to firebase I believe. You could swap out the local dev server with superstatic and it should work i believe.

**Comment by JGSolutions** [comment]
Thanks for the reply :)

Doesn't work locally. I am using superstatic in gulp:

server: {
      baseDir: ['app'],
      middleware: [superstatic({
        config: {
          public: ['.tmp', 'app']
        }
      })]
  }

I am following this example that from a PR
https://github.com/PolymerElements/polymer-starter-kit/pull/614/commits/c46a1eef1f3ab4db7d30b54ede13bf009b96992e

**Comment by JGSolutions** [comment]
It works when i click around the app but when i refresh i get error: 

Cannot GET /cartlist

**Comment by robdodson** [comment]
@JGSolutions I'm not that familiar with the format but I imagine you need to add a source like "*", otherwise it doesn't know to redirect /cartlist to index.html.

**Comment by JGSolutions** [comment]
@robdodson ok cool i will look into that. Thanks!

**Comment by JGSolutions** [comment]
Cool i figured it out. Adding more config options.

**Comment by MacTheZazou** [comment]
I'm trying to switch to superstatic with the @JGSolutions config, but I have a weird problem when loading the root:

![1](http://puu.sh/pYMgR/08c18861a9.png)

+

![2](http://puu.sh/pYMfw/2e8ad38147.png)

Any idea why?

**Comment by robdodson** [comment]
@MacTheZazou can you post your config file? You may need to ignore your elements directory

"source": "!{/bower_components,/elements}/",

**Comment by MacTheZazou** [comment]
In the gulpfile.js:


```
server: {
baseDir: ['app'],
middleware: [superstatic({
    config: {
        public: ['.tmp', 'app'],
        rewrites: [{
            'source': '**',
            'destination': '/index.html'
        }]
    }
})]
}
});
```

Router.js: 

```
// add #! before urls
    page({});
```

I'v seen the` "source": "!{/bower_components,/elements}/",`

but in the #614  they only modify the firebase config with this...

If I use the #614 config:

```
server: {
    baseDir: ['app'],
    middleware: [superstatic({
        config: {
            public: ['.tmp', 'app']
        }
    })]
}
```

I have the same problem as @JGSolutions :

> It works when i click around the app but when i refresh i get error:
> 
> Cannot GET /cartlist

**Comment by robdodson** [comment]
@mbleigh does the above superstatic config look like it's missing anything to you?

**Comment by MacTheZazou** [comment]
@JGSolutions Any idea? I'm blocked, and I think you go through this problem...

Thank you!

**Comment by JGSolutions** [comment]
@MacTheZazou Stupid question but did you install superstatic npm package? Anyways I am not using this at all as I switched to polymer-cli using the app-router

**Comment by robdodson** [comment]
yeah I think that would be a good recommendation. You can see the app-route setup we're using here https://github.com/Polymer/app-drawer-template as a guide. We're also switching over to this in the psk2 branch of this repo

**Comment by JGSolutions** [comment]
@robdodson I am liking the app-router much better than the page.js. My next step is implementing authenticated routing. I kind of have an idea but not sure if it will work. Does the app-router has some authenticated feature?

**Comment by robdodson** [comment]
@JGSolutions none that I know of. It's pretty simple by design. Probably a better issue to raise on the app-route repo

**Comment by mbleigh** [comment]
You'll need rewrites to do SPA-style serving in superstatic, and to ignore bower_components you'll still need a ** in there:

```json
{
  "rewrites": [
    {"source": "!{/bower_components,/elements}/**", "destination":"index.html"
  ]
}
```

The above should work, please let me know if that configuration is still not serving up `index.html` as expected.

**Comment by MacTheZazou** [comment]
That's perfect!

Thank you so much,  the  rewrites syntax wasn't very understandable for me...

**Comment by robdodson** [comment]
Thanks @mbleigh!

**Comment by MacTheZazou** [comment]
@mbleigh Boooh, the bug is back...

I didn't see it at first, but when I make a complete load of the website with a specific url, the rewriting rule exception don't work...

https://polymerapp.com/ : work well, I can navigate and change url without reloading.
https://polymerapp.com/project/1231231 : Don't work if I directly load this URL, or reload after accessing it via the home-page. The rewrite rule exception don't work, and every received files have the index.html content...

Here is my actual configuration:

```
    server: {
    baseDir: ['app'],
    middleware: [superstatic({
      config: {
        public: ['.tmp', 'app'],
        "rewrites": [{
          "source": "!{/bower_components/, /elements/}/**",
          "destination": "index.html"
        }]
      }
    })]
    }
    });
```

Thank you for futur help!
