### ISSUE TITLE
PSK-based projects & licensing/ownership

### ISSUE THREAD

**Issue by alexkolson** [PolymerElements/polymer-starter-kit#624]
Hi there! I'm developing an app based on the polymer starter kit but have replaced most of the guts of the files. I just used the yeoman generator so I wouldn't have to write all the boilerplate myself. How does copyright and ownership work? I understand that the license must remain but how do I maintain ownership of my project? Having the license and header everywhere make it feel as though ownership is retained by the polymer authors.

**Comment by robdodson** [comment]
not a lawyer but i'll give the best answer I know of :D

you should be able to add your own copyright headers and licenses after the polymer ones. I realize that can make files a little bloated. I think the Polymer team uses a build script to inject them into the distribution files so they don't have to look at them in source but I may be mistaken.

**Comment by samccone** [comment]
yep!

Here is the exact answer:

https://github.com/PolymerElements/polymer-starter-
kit/commit/2dca8f71aef2ed4308372e68226c3619ba43db3a

---

Let us know if you have other questions!
