### ISSUE TITLE
ES2015 + Perf patterns: gulp serve:dist issue on Firefox

### ISSUE THREAD

**Issue by motss** [PolymerElements/polymer-starter-kit#625]
Tried implementing the ES2015 and lazyLoading webcomponents polyfill recipes.
The app does not work on Firefox after running `gulp serve:dist` but it does not have any issue on `gulp serve`. The problem comes from `gulp.task('html')`.

And this is the error log:
![es2015_problem_after_gulp_serve_dist](https://cloud.githubusercontent.com/assets/10607759/11985292/2d794502-a9fe-11e5-8204-a30e43532769.PNG)

**Comment by robdodson** [comment]
I need to update the performance recipe. There are some missing bits, [mentioned here](https://github.com/PolymerElements/polymer-starter-kit/issues/503#issuecomment-166677697)

There are also a few open issues already about the ES2015 recipe, sounds like it needs a tune up as well

**Comment by motss** [comment]
@robdodson thanks...

**Comment by nibuen** [comment]
@motss @robdodson I had a similar problem related to ES2015 not getting translated in dist and found out that the vulcanize task was copying the original app file html instead of the babel translated stuff.  My workaround for now was to copy the rest of bower_components into .tmp (since vulcanize needs all html references) and then had vulcanize point to the .tmp/elements/elements.html file.

**Comment by samccone** [comment]
oh cool thanks for the info @nibuen any interest in opening up a PR to note this fix in the docs?

Thanks!

**Comment by nibuen** [comment]
@samccone Sure I should be able to. Are you ok with copying all bower_components over though?  Guess i can start the PR and talk about it on that...

**Comment by samccone** [comment]
yeah we can chat on the PR :)

thanks a million :space_invader: :sparkles:

**Comment by robdodson** [comment]
Closing this as we're working on improved ES2015 support in Polymer so you shouldn't need a gulp workaround and the perf recipe is now mostly built in to PSK
