### ISSUE TITLE
Can we force polymer webapp to be in landscape mode only

### ISSUE THREAD

**Issue by arangates** [PolymerElements/polymer-starter-kit#626]
now I am using 

meta name="viewport" content="width=device-width, initial-scale=1.0"

But I want the app to open in landscape mode only even if the mobile is held upright. Anyway I can achieve it?

**Comment by robdodson** [comment]
You want to use the [responsive-width](https://elements.polymer-project.org/elements/paper-drawer-panel#responsiveWidth) attribute. Set it to a low value like `<paper-drawer-panel responsive-width="1px">` and it should always force it to keep the landscape mode.
