### ISSUE TITLE
Gulp tasks strips async attribute from index.html

### ISSUE THREAD

**Issue by capira12** [PolymerElements/polymer-starter-kit#627]
When you use the `async` attribute like recommended to prevent render blocking like:
 `<script src="bower_components/webcomponentsjs/webcomponents-lite.min.js" async>`
it is removed in the `dist/index.html` when `gulp`ing the project

**Comment by samccone** [comment]
https://github.com/PolymerElements/polymer-starter-kit/issues/336#issuecomment-135579657

Here is the way to make it work ^ 

:+1:
