### ISSUE TITLE
Bower install not completing on 1st attempt (Windows)

### ISSUE THREAD

**Issue by kbenjamin** [PolymerElements/polymer-starter-kit#629]
I ran a clean install of polymer starter kit under Windows (initially using CMD prompt but later switching to Git Bash shell without improvement) and ran into multiple issues running `bower install`.

I kept getting various errors which would go away on a re-run of `bower install`. I was eventually able to complete the install. 

My guess is that there are dependencies missing from certain components `bower.json` files.

**Comment by samccone** [comment]
@kbenjamin can you post the errors?

**Comment by kbenjamin** [comment]
This turns out to be a problem with bower 1.7.1 (see https://github.com/bower/bower/issues/2118), not your install scripts or dependencies. Go ahead and close this ticket.

FYI, I've done some reinstalls and keep getting random failure points that look like this: 

    bower paper-menu#^1.0.0                             extract archive.tar.gz
    bower iron-validatable-behavior#^1.0.0              extract archive.tar.gz
    bower platinum-https-redirect#^1.0.0                extract archive.tar.gz
    events.js:85
          throw er; // Unhandled 'error' event
                ^
    Error: ENOENT, rename 'C:\Users\Ken\AppData\Local\Temp\mypc-Ken\bower\cefb8f774d98384ed30dec610f03a72d-174564-wZPTqe\archive.tar.gz.207942742'
        at Error (native)
    
or this:
    	
    bower prism#*                                       resolved git://github.com/LeaVerou/prism.git#1.3.0
    bower paper-checkbox#^1.0.0                            EPERM EPERM, unlink 'C:\Users\Ken\AppData\Local\Temp\photon-Ken\bower\ef45b44
    439723f1a6c819e208c3af9f3-181520-uJ6l4O\paper-checkbox-1.1.0\test\basic.html'
    
    Stack trace:
    Error: EPERM, unlink 'C:\Users\Ken\AppData\Local\Temp\photon-Ken\bower\ef45b44439723f1a6c819e208c3af9f3-181520-uJ6l4O\paper-checkbox-1.1.0\test\basic.html'
        at Error (native)
    
    Console trace:
    Error
        at StandardRenderer.error (C:\Users\Ken\AppData\Roaming\npm\node_modules\bower\lib\renderers\StandardRenderer.js:83:37)
        at Logger.<anonymous> (C:\Users\Ken\AppData\Roaming\npm\node_modules\bower\bin\bower:116:30)
        at Logger.emit (events.js:107:17)
        at Logger.emit (C:\Users\Ken\AppData\Roaming\npm\node_modules\bower\node_modules\bower-logger\lib\Logger.js:29:39)
        at C:\Users\Ken\AppData\Roaming\npm\node_modules\bower\lib\commands\index.js:48:20
        at _rejected (C:\Users\Ken\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:844:24)
        at C:\Users\Ken\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:870:30
        at Promise.when (C:\Users\Ken\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:1122:31)
        at Promise.promise.promiseDispatch (C:\Users\Ken\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:788:41)
        at C:\Users\Ken\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:604:44
    System info:
    Bower version: 1.7.1
    Node version: 0.12.7
    OS: Windows_NT 6.1.7601 x64

**Comment by dandv** [comment]
Just installed on Windows as well. Why `npm install` failed because of missing Python, the app runs just fine, and bower installation completed successfully.
