### ISSUE TITLE
"python -m SimpleHTTPServer 8080" is not working on Ubuntu 15.04

### ISSUE THREAD

**Issue by recri** [PolymerElements/polymer-starter-kit#63]
But "python3 -m http.server 8080" works out of the box.

It's a clean install of 15.04 with very little customization.  The error is odd, too, python complains that it could not open the file "-m", but if you leave off the module name and port, then it complains that the module required by -m is missing.

**Comment by addyosmani** [comment]
Could you double check you ran `python -m SimpleHTTPServer 8080` and not the one from the (now older) README? You may be running into https://github.com/PolymerElements/polymer-starter-kit/issues/56

**Comment by recri** [comment]
You're right, it was the em-dash in the README.md that caught me.  Sorry
for the false alarm.

-- rec --

**Comment by addyosmani** [comment]
No worries!
