### ISSUE TITLE
Look into using codemods for migrations

### ISSUE THREAD

**Issue by robdodson** [PolymerElements/polymer-starter-kit#631]
Lots of folks ask how to migrate from one version of PSK to the next. We could maybe see about using something like codemods or a migration script.

Sources:
https://github.com/marionettejs/Marionette.Upgrade
https://github.com/rackt/react-router/blob/master/upgrade-guides/v2.0.0.md#upgrade-automatically-with-codemods
https://github.com/facebook/jscodeshift
https://github.com/rackt/rackt-codemod

**Comment by samccone** [comment]
:+1:

**Comment by abdonrd** [comment]
:+1:

**Comment by addyosmani** [comment]
@samccone how well have migration scripts worked for Mationette in the past? In my experience, they tend to be fragile but definitely interested in us exploring something better for PSK here. It's so manual to upgrade today.

**Comment by zboralski** [comment]
:+1:

**Comment by robdodson** [comment]
I'm going to close this as I don't think anyone has the time to work on it and we've greatly simplified PSK2. I feel like most of the changes people wanted to capture in PSK were additions to the gulpfile but that work is now being done in Polymer CLI and users should be able to reap the benefits of updates to CLI without having to change any of their own code.
