### ISSUE TITLE
Deprecated gulp plugins

### ISSUE THREAD

**Issue by motss** [PolymerElements/polymer-starter-kit#632]
Hi. Would like to know if there is any plan for these deprecated plugins? Thank you.
![deprecated-gulp-plugins](https://cloud.githubusercontent.com/assets/10607759/12074064/b52e07f2-b17a-11e5-8ba7-d19e9e8850c2.png)

Quick Links:
[gulp-htmlmin](https://github.com/jonschlinkert/gulp-htmlmin) based on [html-minifier](https://github.com/kangax/html-minifier)
[gulp-cssnano](https://github.com/ben-eb/gulp-cssnano) based on [cssnano-optimization](http://cssnano.co/optimisations/)

**Comment by samccone** [comment]
hey @motss would you be interested in opening a PR to update these dependencies? 

Thanks for raising this issue :clap:

**Comment by robdodson** [comment]
Closing this in favor of PR https://github.com/PolymerElements/polymer-starter-kit/pull/645
