### ISSUE TITLE
Python Dependency Issue for NPM install to complete.

### ISSUE THREAD

**Issue by Lemony-Andrew** [PolymerElements/polymer-starter-kit#633]
The `node-gyp` dependency causes failure when using `npm install` if Python is not installed.

## Expected outcome

After running `npm install` and `bower update`, `gulp` + `gulp serve` should work.

## Actual outcome

An error is thrown in the middle of running `npm install` because of `node-gyp`. Specifically, because of python. 

## Steps to reproduce

1. Not having Python installed
2. Not having the correct version of python for `node-gyp`: [2.5, 3.0) 3.+ not supported.
3. Not having Python linked in environment variables, windows specific, or usable from cmd 
4. running npm install and normal procedures
5. Run gulp commands and errors will prevent it from performing.

## Note
1. Having Python 3 and above will cause problems with gulp.
2. Even after having python 2.5+ installed, the install gave warnings about path names being too long - but was able to complete installation.

## Fix
For windows
1. Install latest 2.X version of Python from https://www.python.org/downloads/
2. Place python in path http://stackoverflow.com/questions/6318156/adding-python-path-on-windows-7
3. Run npm install and bower update
4. Gulp should work if no other problems existed prior-hand.

**Comment by samccone** [comment]
yeah, :\ https://github.com/nodejs/node-gyp#installation

thanks for documenting this @Lemony-Andrew !
