### ISSUE TITLE
Deploy recipe for Google App Engine

### ISSUE THREAD

**Issue by idosh** [PolymerElements/polymer-starter-kit#634]
Add `app.yaml` along with a recipe to deploy polymer app to google app engine

**Comment by samccone** [comment]
hey @idosh I think an app engine recipe would be super useful,

Any interest in opening up a PR to add this? More than willing to work with you to land this. Thanks for the great idea :bulb:

**Comment by idosh** [comment]
I'll do it! Thanks for the help and willingness
