### ISSUE TITLE
Cannot integrate with polylint

### ISSUE THREAD

**Issue by doctor-g** [PolymerElements/polymer-starter-kit#635]
The starter kit keeps `bower_components` at the project root directory, but this means that polylint cannot run on the project sources because imports cannot be resolved. By extension, this means that polymer-atom cannot lint while working on starter-kit-based projects.

To reproduce:
1. yo polymer
2. polylint --input index.html

This will yield output like:
```
ERROR finding /PROJ/app/bower_components/webcomponentsjs/webcomponents-lite.js
Error: ENOENT, open '/PROJ/app/bower_components/webcomponentsjs/webcomponents-lite.js'
    at Error (native)
```

The linter can be run on the dist folder because gulp has pulled bower_components into the same directory as the app directory contents. That is, this works fine:
1. yo polymer
2. gulp
3. cd dist
4. polylint --input index.html

However, this doesn't let us lint the sources using polymer-atom.

**Comment by samccone** [comment]
cc @garlicnation for ideas on how to resolve this... (my thinking is that polylint should be able to take custom path resolvers)


Thanks @doctor-g for the issue :smile:

**Comment by robdodson** [comment]
I think this should be solved on master because we moved bower_components with this PR: https://github.com/PolymerElements/polymer-starter-kit/pull/568

@doctor-g can you try a checkout from master and let us know if it works for you? Also +1 for custom paths for polylint, that will probably keep coming up

**Comment by doctor-g** [comment]
Yes indeed, polylint and polymer-atom are much happer with the version on master.
I'm a little shaky on the workflow behind yeoman: at what point would a fresh project via `yo polymer` reflect this change?

**Comment by robdodson** [comment]
When we roll out a new tag/release for PSK we'll update the generator to
match

**Comment by samccone** [comment]
ok going to close this issue since it no longer impacts us directly, but I would love to hear any thoughts @garlicnation has.
