### ISSUE TITLE
"Request method 'POST' is unsupported" - sw-toolbox.js

### ISSUE THREAD

**Issue by MauriSalazar** [PolymerElements/polymer-starter-kit#64]
Getting this error after starting application.

![screen shot 2015-05-30 at 01 29 32](https://cloud.githubusercontent.com/assets/4121898/7895555/90dad1ec-066b-11e5-967c-0061ed9e6ddf.png)

**Comment by kbwatts** [comment]
Same here (out of the box). Doesn't seem to affect anything, but probably might...

**Comment by addyosmani** [comment]
cc @wibblymat who works on sw-toolbox

**Comment by addyosmani** [comment]
We have an upstream patch that should solve this and will aim to get it nailed down shortly.

**Comment by Angarsk8** [comment]
I've been getting the same error! what is this?

**Comment by vl4dt** [comment]
Same error here, no idea what triggers it but once it happens it becomes a recurrent error.
Only once without touching anything unusual it started all clean, after a while I closed the browser, stopped 'gulp serve' and started it again and the error showed up again.
It breaks the execution and not even the toast message shows up.

**Comment by addyosmani** [comment]
This issue was fixed in https://github.com/GoogleChrome/sw-toolbox/pull/11 and once we land https://github.com/PolymerElements/platinum-sw/pull/36, we'll update Starter Kit to include it. Hang in there, folks!

**Comment by ValueBC** [comment]
I had this same issue, then read the docs and it mentioned adjusting the path in sw-import.js:

```
importScripts('../bower_components/platinum-sw/service-worker.js');

```
For PSK, we need to go up one level. Or maybe it just decided to work this time ;)

**Comment by addyosmani** [comment]
As of https://github.com/PolymerElements/polymer-starter-kit/commit/b4b6b7fbc40b3c732123243d0e4ce2c6ed5acf66 this issue should now be fixed. You may need to unregister any local Service Workers that were previously setup via `chrome://serviceworker-internals/` and refresh before the old 'Request method POST' messages disappear.

![screen shot 2015-06-05 at 15 28 59](https://cloud.githubusercontent.com/assets/110953/8008066/9f14dd80-0b97-11e5-96db-ff2322ff5a46.png)

**Comment by calbertts** [comment]
I've installed the Polymer Starter Kit but at the same time I've been working in other web project, every time that I tried to do a request I got this error **despite of that it doesn't have nothing to do with Polymer.**

**I'm afraid about the Polymer instalation is affecting some global things affecting other projects created with NPM, because this problem started just after installed Polymer.**

Is it possible?

**Comment by addyosmani** [comment]
@calbertts could you go to about:serviceworker-internals and unregister/stop any active service workers on the page? (in particular any tied to the local server you initially ran for Polymer Starter Kit). After that refresh. Could you let me know if that fixes things?

**Comment by robdodson** [comment]
@calbertts you might also try testing your projects on a different port. A service worker will latch on to the domain `localhost:3000` and try to proxy it until you explicitly unregister it. It's actually pretty annoying when you accidentally install a service worker on the port you usually dev on and don't know it. Probably another reason to do #80

**Comment by calbertts** [comment]
@addyosmani  your workaround worked well, Thank you.
@robdodson This worked also, but you're right, this is pretty annoying, it should be optional or the developer should be aware about what it's gonna happen when you install the Polymer Start Kit.

Thanks guys.

**Comment by addyosmani** [comment]
@calbertts could you add a vote for making SW optional to that issue? I think we should definitely consider a clean way of achieving this if sufficient numbers of users are finding the debugging workflow for disabling painful. cc @jeffposnick as an fyi

**Comment by jeffposnick** [comment]
The persistence of service workers and the host + port based scoping really is a pain for `localhost:####` scenarios. I've mostly internalized that pain at this point, and tend to heavily use Incognito windows, but I see how it could be very confusing for folks not aware of what's going on under the hood.

I'll add some thoughts to https://github.com/PolymerElements/polymer-starter-kit/issues/80
