### ISSUE TITLE
Add <span id="browser-sync-binding"></span> only in development

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/polymer-starter-kit#649]
Maybe we can remove the `<span id="browser-sync-binding"></span>`from the index.html and the `gulp serve` task add this tag?

**Comment by addyosmani** [comment]
Is this appearing during production builds as well? I'm fine with us injecting this in during development rather than it being a static part of the index.

**Comment by abdonrd** [comment]
@addyosmani yes. For example, you can find it in the official demo:

view-source:https://polymerelements.github.io/polymer-starter-kit/

**Comment by abdonrd** [comment]
Closed with https://github.com/PolymerElements/polymer-starter-kit/issues/649 :)
