### ISSUE TITLE
track down node-gyp dependency...

### ISSUE THREAD

**Issue by samccone** [PolymerElements/polymer-starter-kit#652]
Who needs this... and how can we remove this.. it is a non-stop source of issues for people just starting out

**Comment by robdodson** [comment]
I was wondering if it was coming from the imagemin task

**Comment by addyosmani** [comment]
Looking at past issues, I also think this might be down to the imagemin task. If that is the case, it might be tricky for us to drop imagemin or find a suitable replacement that works as well cross-platform. Image optimisation (as we know) is the biggest issue slowing down pages at load time these days so it's somewhat necessary for us to try helping there imo.

**Comment by robdodson** [comment]
*sigh* yeah I really don't want to remove image minification, at the same time I bet it causes all kinds of havoc for folks because of the compilation it does. Right now we're seeing issues from folks who cared enough to file them. I bet there are an equal number of people who tried PSK, it blew up in their terminal, and they just gave up and moved on :\

I think we should update the README to include the suggested change here: https://github.com/PolymerElements/polymer-starter-kit/pull/637#issuecomment-170396704 at least.

**Comment by samccone** [comment]
or or or, we only install imagemin on deploy :) 

And we lead off the deploy task with a super clear and easy to understand message, and a failure message about ways to debug.

Thoughts?

**Comment by robdodson** [comment]
hm how do you install only on deploy?

**Comment by samccone** [comment]
npm scripts are just random bits of code, so we can do _anything_ we want there :bug:

**Comment by addyosmani** [comment]
install on deploy vs. install on production build? Hard part with deploy is they may want to deploy to something beyond what our deployment tooling supports and our hooks might not get triggered.

**Comment by samccone** [comment]
oh sorry, I meant install on production build :)

**Comment by addyosmani** [comment]
I'd be down with install on prod build :)

**Comment by samccone** [comment]
```
info wct-local@2.0.0: The lifecycle hook postinstall isn't supported.
info wct-sauce@1.8.3: The lifecycle hook postinstall isn't supported.
info fsevents@1.0.6: The lifecycle hook install isn't supported.
info sauce-connect-launcher@0.14.0: The lifecycle hook postinstall isn't supported.
info gifsicle@3.0.3: The lifecycle hook postinstall isn't supported.
info jpegtran-bin@3.0.6: The lifecycle hook postinstall isn't supported.
info optipng-bin@3.0.4: The lifecycle hook postinstall isn't supported.
info dtrace-provider@0.6.0: The lifecycle hook install isn't supported.
```

here are the packages that have hooks...

Looks like WCT + image opt

(thanks @kittens for this)

**Comment by sindresorhus** [comment]
Imagemin author here. It doesn't use node-gyp, but:

> Imagemin also requires compiling if the pre-built binaries doesn't work, which happens a lot on Linux where it's close to impossible to make an universally usable pre-compiled binary. That's the main reason for it failing. - https://github.com/google/web-starter-kit/issues/660#issuecomment-85317612

Dealing with native code is messy. I'm actually surprised we managed to make it as convenient as it is. Although, my hope is that one day we can compile all of the image optimization binaries into WebAssembly and run them natively in Node.js or using asm.js (or even in the browser!). Meaning no postinstall script.

-

Installing it only on production build sounds like a good compromise.

**Comment by robdodson** [comment]
imagemin is now no longer included with PSK and is instead part of https://github.com/PolymerElements/generator-polymer-init-custom-build.
