### ISSUE TITLE
Add PR#650 to the deploy_ghpages() function in travis-runner.sh

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/polymer-starter-kit#654]
Add https://github.com/PolymerElements/polymer-starter-kit/pull/650 to the `deploy_ghpages()` function in `travis-runner.sh`.

**Comment by robdodson** [comment]
@chuckh do you think we could add the change from #650 to the deploy script? The change would be to include `<script>'https:'!==window.location.protocol&&(window.location.protocol='https')</script>` in the `<head>` somewhere.

**Comment by chuckh** [comment]
We should be able to. I will give it a try later today.

**Comment by chuckh** [comment]
I created PR #667 to do this. @robdodson PTAL.

**Comment by abdonrd** [comment]
Nice work @chuckh!
