### ISSUE TITLE
Request for more clear onboarding learning path

### ISSUE THREAD

**Issue by salamanders** [PolymerElements/polymer-starter-kit#655]
I'm trying to put together a prototype mockup of an ecommerce site.  I'd like it to be responsive.  In researching the first steps, I've encountered:

polymer-project.org

1. Polymer instructions on building my own elements (Do I want to do this?  I just want to duct-tape together existing elements, right?)
2. Bower (the "suggested" route)
3. Zip files of polymer (what I'm used to in the past with things like jquery mobile)
4. Polymer starter kit (not the suggested route?  Directory structure is all different)
5. Polymer starter kit lite (Now I'm getting a bit lost)
6. grunt, gulp (Don't know if I need this yet?)
7. I want to build a single web page app, but the only thing I found was a polymer 0.5 tutorial articles on "scaffold" still linked from a easy to reach flow.  Is this at all usable?  Over a year old, I'm guessing no, will be hard to retrofit for 1.x.
8. Gold elements that have a CC / phone / email validator, but not the rest of a shipping/billing form, so am I supposed to think of them as examples or starters or "we hope the community writes the rest"? 
9. Or should I use iron forms?
10. More than a bit intimidated by the first page, things like "Polymer 1.0 replaces the shadow DOM polyfill with a lightweight shim, uses a new, faster data-binding system" - do I need to know what these are to use polymer?
11. Polyfill Web Components support for older browsers - so I always need this?  What if I'm just demoing on latest non-alpha chrome?  Better to always have it and ignore it?
12. getmdl.io - Not sure if there is an upgrade route from here to polymer, or if that even makes sense

You get the idea.  I'm not looking for answers to the above list (even though they would be great!)  I'm more concerned about a new user that has some of the same questions, and is having a hard time building out a reasonable prototype of a site using polymer, gets confused, and bails to bootstrap, angular2, etc.

**Comment by salamanders** [comment]
@robdodson and @samccone gave me some great pointers.  Paraphrasing: 

1. Cobble together >80% of your stuff from existing https://elements.polymer-project.org/
2. Learn Bower, it is worth it.
3. Zip file bad.  Ecosystem good.  https://customelements.io/
4. PSK is a good "starter app".  The tutorials are for a "starter element."  That is why directories are all different.
5. PSK lite - TBD.
6. Grunt/Gulp/etc.  Bit the bullet and learn it.  Needed for any "real" site deployment eg. Vulcanize
7. PSK is a better single page demo than the "single page app" Article.  Also TBD.
8. Combine Paper inputs, Iron-form, and Gold.
9. yes.
10. nope.
11. Doesn't hurt to keep it.
12. TBD with PSK, but likely continues to be it's own thing.

**Comment by samccone** [comment]
xref #653

**Comment by robdodson** [comment]
Hopefully the process is now greatly simplified.

Use Polymer CLI to scaffold out starter-kit
Run `polymer build` to generate a productionized build.
Docs are now official too https://www.polymer-project.org/1.0/start/toolbox/set-up

**Comment by salamanders** [comment]
Very cool, looking forward to it!
