### ISSUE TITLE
Vulcanize in dist/ doesn't seem to work

### ISSUE THREAD

**Issue by alexkolson** [PolymerElements/polymer-starter-kit#656]
When I run `gulp`, the vulcanize task can't find some things in `dist/bower_components/`:

```bash
ERROR finding /project/dist/bower_components/iron-flex-layout/classes/iron-flex-layout.html
ERROR finding /project/dist/bower_components/paper-item/paper-item.html
ERROR finding /project/dist/bower_components/paper-material/paper-material.html
ERROR finding /project/dist/bower_components/paper-menu/paper-menu.html
ERROR finding /project/dist/bower_components/paper-scroll-header-panel/paper-scroll-header-panel.html
ERROR finding /project/dist/bower_components/paper-styles/paper-styles-classes.html
ERROR finding /project/dist/bower_components/paper-toast/paper-toast.html
ERROR finding /project/dist/bower_components/paper-toolbar/paper-toolbar.html
ERROR finding /project/dist/bower_components/polymer/polymer.html
ERROR finding /project/dist/bower_components/paper-styles/default-theme.html
ERROR finding /project/dist/bower_components/paper-ripple/paper-ripple.html
ERROR finding /project/dist/bower_components/page/page.js
```

I believe I'm using the vanilla `gulpfile.js` as provided by PSK. Have I messed up my build somehow?

**Comment by samccone** [comment]
@alexkolson did you run `bower i` ?

**Comment by alexkolson** [comment]
@samccone Yeah. Running it again produces no output.

**Comment by samccone** [comment]
hmm fascinating, are you on the latest PSK?

**Comment by alexkolson** [comment]
Used the latest generator-polymer version as of today via `npm install -g generator-polymer`

**Comment by samccone** [comment]
@alexkolson what version of node are you on?

**Comment by alexkolson** [comment]
I've changed my `bower_components/` location via `.bowerrc` and it looks like the vanilla gulpfile expects it to be at the root of the directory:

```js
  var bower = gulp.src([
    'bower_components/**/*'
  ]).pipe(gulp.dest(dist('bower_components')));
```

Changing that to the new location of `bower_components/` solved the issue. Should've just looked at the gulpfile before bothering you guys.

**Comment by samccone** [comment]
no worries, thanks for the info @alexkolson
