### ISSUE TITLE
The set up tutorial on PSK1.2.2 leads to errors on build

### ISSUE THREAD

**Issue by ebidel** [PolymerElements/polymer-starter-kit#659]
_From @greenido on January 17, 2016 16:58_

How to reproduce:
1. Install [PSK1.2.2](https://github.com/PolymerElements/polymer-starter-kit/releases/download/v1.2.2/polymer-starter-kit-light-1.2.2.zip)
2. Follow the steps: https://www.polymer-project.org/1.0/docs/start/psk/set-up.html
3. When you reach the 'gulp' phase you should get:
```
idog (master) poly-news-1 $ gulp
module.js:339
    throw err;
    ^

Error: Cannot find module 'readable-stream/transform'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/gulp-util/node_modules/through2/through2.js:1:79)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)

idog (master) poly-news-1 $ node -v
v5.0.0
idog (master) poly-news-1 $ npm -v
3.5.3
```

Thanks!

_Copied from original issue: Polymer/polymer#3306_

**Comment by robdodson** [comment]
@greenido can you delete the `node_modules` directory, run `npm cache clean`, then run `npm install` again and try running gulp. This looks like it may be a missing deep dependency.

**Comment by greenido** [comment]
I did all the steps - but got the same error :(

**Comment by robdodson** [comment]
hmmmm calling in the npm expert: @samccone 💪

It really looks like maybe `through2` is missing a dependency, but we don't directly depend on `through2`, `gulp` does. Maybe it's related to using Node 5...?

**Comment by robdodson** [comment]
Btw @kaycebasques I noticed the demo reports using node `0.12` but that's an old version now. I think maybe it should be revved to either `4.x` which is the long term release or `5.x` which is currently stable. Similarly npm should be revved to `3.x`.

**Comment by robdodson** [comment]
<img width="827" alt="screen shot 2016-01-17 at 11 15 41 pm" src="https://cloud.githubusercontent.com/assets/1066253/12385363/44f2868c-bd70-11e5-8d1b-2483b1860ced.png">

**Comment by samccone** [comment]
@greenido if I had to guess it looks like you had a bad / partial install somewhere. 
Try running `npm cache clean` `rm -rf node_modules` and install everything again.

I am going to close for now since I can not reproduce however if you are still hitting this we can reopen and continue the investigation.
