### ISSUE TITLE
BrowserSync: routes break on synchronized browsers

### ISSUE THREAD

**Issue by samsabra** [PolymerElements/polymer-starter-kit#66]
When using BrowserSync, synchronized browsers don't navigate to the correct route when clicking on Users or Contact in the navigation drawer

Click Users link from Chrome on Android, and Chrome on OS X and Window 8.1 displays "Cannot GET /users"
![image](https://cloud.githubusercontent.com/assets/2354574/7895909/92a6e328-0673-11e5-97d2-c6f5046a787f.png)

Click Contact link from Chrome on OS X, and Chrome on Android and Windows 8.1 displays  displays "Cannot GET /contact"
![image](https://cloud.githubusercontent.com/assets/2354574/7895949/cd8e90fc-0674-11e5-839e-f48b78720116.png)

Chrome - (43.0.2357.81) on OS X 10.7.4 
Chrome - (42.0.2311.111) on Android 5.01
Chrome - (43.0.2357.81) on Windows 8.1

**Comment by addyosmani** [comment]
I think what's happening here is BrowserSync is attempting to update before the page has a chance to re-register routes. We'll look into it.

**Comment by addyosmani** [comment]
I started experimenting with https://github.com/bripkens/connect-history-api-fallback as a solution for this based on https://github.com/BrowserSync/browser-sync/issues/204. It works a little better than our current setup, but requires some further work to get sub-views (e.g /users/Rob) working. I'll continue looking into this.

**Comment by fones** [comment]
Same problem here. Testing on mobile safari and chrome on iOS.

**Comment by bppffnn** [comment]
Also doesn't work on IE8 on windows.

**Comment by arthurvr** [comment]
Polymer itself doesn't support IE8.

**Comment by addyosmani** [comment]
This should be resolved as of https://github.com/PolymerElements/polymer-starter-kit/commit/ee1b0c5ac5dd26e3ac56b12ec36d607ff02dced4
