### ISSUE TITLE
Should iron-pages use one way binding

### ISSUE THREAD

**Issue by robdodson** [PolymerElements/polymer-starter-kit#662]
Uses a two way binding here: https://github.com/PolymerElements/polymer-starter-kit/blob/master/app/index.html#L119

But really you probably only want the router to change `app.route`, so this should be one way I think. It's one way in the menu, for instance.

**Comment by abdonrd** [comment]
:+1:

**Comment by addyosmani** [comment]
I think it's worth us getting in a PR to switch over to one-way binding. Anyone interested in taking a stab at it and we can do some testing to measure impact after? :hear_no_evil:

**Comment by robdodson** [comment]
PSK2 uses one way bindings here
