### ISSUE TITLE
elements.html confuses folks so... so much...

### ISSUE THREAD

**Issue by robdodson** [PolymerElements/polymer-starter-kit#663]
If you create a new element, you should put the imports that element depends on inside of its definition. But everyone just sticks them in `elements.html` because that's where all the other imports are...

At the least we need a comment that says "These are just the imports that index.html depends on, don't put yr stuff in here!" But maybe there's just a fundamentally better structure that we should explore...

**Comment by chuckh** [comment]
Don't you need to put new elements you want vulcanized in `elements.html` too besides those required by index.html?

:+1:  for: 
>But maybe there's just a fundamentally better structure that we should explore...

**Comment by robdodson** [comment]
> Don't you need to put new elements you want vulcanized in elements.html too besides those required by index.html?

Yes and no. If you're using those elements in `index.html` then yes. But let's say you create `x-foo` which depends on `x-bar`. If `x-foo` is used in `index.html` then it should go in `elements.html`. But the import for `x-bar` should only be inside of `x-foo`.

**Comment by chuckh** [comment]
I see. So `x-foo` will still be vulcanized since the import is in `x-bar` and since `x-bar` is in `elements.html`.

**Comment by robdodson** [comment]
@chuckh kinda, it's the other way around. `x-foo` is in `elements.html` and since `x-foo` contains `x-bar`, then `x-bar` gets vulcanized.

**Comment by TimvdLippe** [comment]
Yes it was very confusing for me. I did not know about this until @robdodson told me about it.

:+1: for exploring a better structure

**Comment by David-Mulder** [comment]
Just my 2ct: Wouldn't it maybe be a better idea to put the `index.html` imports in `index.html` and make the *default* that `elements.html` will be automatically generated importing all elements in the `elements` folder? Of course once you start doing stuff like lazy loading and all those things you will have to turn off that automatic generation and for users of the 'light' version they would simply have to edit the default automatically generated `elements.html`, but I think it would be quite neat for the large majority of users and take away this confusion entirely.

**Comment by addyosmani** [comment]
Let's explore if there's a better way to tackle this for V2. We may end up requiring less of an elements.html file if we adopt the `<x-app>` strategy.

**Comment by David-Mulder** [comment]
Been thinking a bit about this, but why not just put them straight in `index.html`? Seems a lot more sensible as that's the generic rule: you define your dependencies at the top of the file where you use them.

**Comment by TimvdLippe** [comment]
The elements.html file is used in the vulcanize task. Therefore the output of vulcanize is elements.build.html which is imported by index.html

**Comment by David-Mulder** [comment]
@TimvdLippe The vulcanization step should be able to parse `index.html` just as easily as `elements.html` for its dependencies, rip them out and inject it's own vulcanized version.

And regardless, moving to HTTP/2 structures might be worth it either way sometime very very soon. From experience I can say it makes a lot of stuff a lot easier (once you get through all the troubles).

**Comment by robdodson** [comment]
@David-Mulder what're you using for http2? One question I've had is whether a large non-vulcanized polymer app served over h2 with lots of dependencies will be faster or at least the same speed as a vulcanized one. Testing with app engine's (very limited support for h2) made it appear that it was slower to just send everything over the wire but I am looking for another good h2 implementation to test this on.

As Tim pointed out, it previously made the vulcanize process easier to separate everything out into its own file. Also, I personally hate having my index file crowded with imports, it just becomes harder to read :\

**Comment by chuckh** [comment]
Below is more info on using http2 with Polymer on GAE.  See this discussion at: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/firebase-talk/DjMoVvhVANw/QMEjApmtDAAJ

> 	Ian MacLeod 	
One alternative until/if Firebase Hosting gets support for HTTP/2 (+ push), you might want to take a look at https://github.com/GoogleChrome/http2push-gae and https://github.com/GoogleChrome/http2-push-manifest - well geared toward Polymer projects

> Though, definitely would be a fan of HTTP/2 support via Firebase Hosting - GAE is still pretty high friction :(

**Comment by mkazlauskas** [comment]
`elements.html` concerns me as well. I realise it's convenient for build/vulcanize, but it's really awful for maintainability. It's not clear **where** the imports are used, therefore it's very hard to do clean-up and you end up importing stuff that is not used at all.

**Comment by jsilvermist** [comment]
Though it may not affect many people, one problem is that if you are using multiple pages with the current implementation it can be unclear if you should add all imports in a single elements.html page to enable it to be cached and not download the same dependencies multiple times, but add initial overhead, or add a different elements.html for each page which uses different dependencies.

At the moment it's just a matter of balancing depending on how many dependencies are shared, how many are different, and how likely the pages are to be used together.

**Comment by TimvdLippe** [comment]
@jsilvermist Since HTML imports are deduplicated and only downloaded once, every element should declare its dependencies in the file where the element is defined. This is a common misunderstanding and one of the reasons is currently elements.html confusing people.

Another note about elements.html and vulcanize: If the elements.html is vulcanized and loaded async, the other structure of the page inside index.html can still be loaded while loading all elements, improving the first paint time.

**Comment by robdodson** [comment]
This may become more sensible if we move away from the current `dom-bind` approach to using something like `x-app`. Frankly, even though developers might get a little freaked out by the idea of an `x-app` element, `dom-bind` is essentially the same thing. It's a template that obscures the markup from the rest of the page and doesn't stamp until Polymer has loaded. It shouldn't, as I understand it, grant any special SEO benefits (which is the reason we initially thought we should use it). The [Element's Catalog](https://elements.polymer-project.org/) uses an x-app style approach and indexes just fine.

<img width="686" alt="screen shot 2016-02-22 at 7 13 10 am" src="https://cloud.githubusercontent.com/assets/1066253/13222203/c57152dc-d933-11e5-8f76-7fc53581ed3b.png">

**Comment by jsilvermist** [comment]
@TimvdLippe Yes, that's true for HTML Imports, but when we are vulcanizing it and only importing elements.html, everything is the file MUST be downloaded regardless of the contents, deduplication would only affect the import if we tried to import elements.html twice.

**Comment by ryantheleach** [comment]
The best way to fix this I think, is to have the build process alert you that there are imports that may not be in use (if possible) that way it also catches the case where people have removed things they were previously using and forgotten to remove them from elements.html

**Comment by MaKleSoft** [comment]
The entire structure of the starter kit appears extremely convoluted and confusing to me and the way imports are used seems like an antipattern. One of the key selling points of Polymer is that **everything** is an element, even the app itself, so why is such a big part of the app implemented in `index.html` directly? Imo, apart from the usual boilerplate like the webcomponents script and meta tags and such `index.html` should only contain one element, `<my-app>`, and a single import for just that element. Also, it was my impression that the idea of vulcanize was to compress the entire code into one single file to eliminate the use of html imports in production. The way that it is used here still requires an import in `index.html`. Overall, this project seems to be doing a bad job at illustrating the key techniques and concepts of a Polymer app.

**Comment by robdodson** [comment]
@MaKleSoft Take a look at the work-in-progress psk2 branch. I think it addresses your concerns.

**Comment by MaKleSoft** [comment]
@robdodson Yeah, you're right. Thanks!

**Comment by robdodson** [comment]
We got rid of elements.html and greatly simplified the structure of PSK. Hope this setup is better for folks.
