### ISSUE TITLE
Paper-scroll-header-panel prevents iOS Safari from collapsing header

### ISSUE THREAD

**Issue by vinerz** [PolymerElements/polymer-starter-kit#664]
Hello everyone! I am really sorry that I created this issue here, is that because I don't really know which component is creating this.

I just noticed that a fresh install of the current PSK somehow prevents the iOS Safari from achieving the minimal-ui effect. The expected effect would be like this screenshot:

![image](https://cloud.githubusercontent.com/assets/1482034/12383315/c89c6a0a-bd8b-11e5-998a-337880d15904.png)

But I couldn't achieve this on my iPhone:

![image](https://cloud.githubusercontent.com/assets/1482034/12383325/e51e4b8a-bd8b-11e5-928b-d4f43d3cc625.png)

This way we lose some precious screen pixels.
What can we do to fix this issue?

**Comment by robdodson** [comment]
Pretty sure this is fixed by using https://github.com/PolymerLabs/app-layout

We're planning to switch Polymer over to app-layout when they're released.

**Comment by vinerz** [comment]
Hey Rob! I didn't know about app-playout. I'm already checking it out. Thank you!

**Comment by BartKoppelmans** [comment]
Will this have any effect on the code that we currently have? And do you know if there is a solution to do this with paper-scroll-header-panel?

**Comment by robdodson** [comment]
@BartKoppelmans In the future we'll probably need to swap out paper-scroll-header-panel for the app-layout elements. I don't think this is currently possible with paper-scroll-header-panel because of the way it is structured. I think the app-layout elements were built in a way to work around this issue

**Comment by BartKoppelmans** [comment]
That would be great, looking forward to any progress on this. :blush:

**Comment by vinerz** [comment]
@BartKoppelmans I've migrated to app-layout elements very easily, you don't need to worry about that. It is almost a drop-in replacement (if you didn't do many customizations)

**Comment by BartKoppelmans** [comment]
Unfortunately, I did. I have a variable headerHeight and condensedHeaderHeight, which are not supported (as far as I can see). Perhaps in the future. Thanks anyway!

**Comment by addyosmani** [comment]
@robdodson Are `app-layout` issues like this ones we want to keep open and label accordingly until we make the switch or do we want to close them knowing we're going to have to make the transition anyway?

**Comment by robdodson** [comment]
@addyosmani I'm kind of in favor of closing them. I think we had another header-panel related issue and @chuckh was thinking it may be good to leave them open till the switch over... I could go either way really.

**Comment by chuckh** [comment]
@addyosmani @robdodson I would like to keep open until we switch over to app-layout. This way it reminds us to test for this case. I flagged this and #274 as `waiting-on-upstream-fix` to help track issues that hopefully will be fixed with v2 of PSK.

See:
https://github.com/PolymerElements/polymer-starter-kit/labels/waiting-on-upstream-fix

**Comment by addyosmani** [comment]
sgtm

**Comment by robdodson** [comment]
We've switched over to app-layout for PSK2 and we're no longer using a scrolling header panel. I feel like any issues related to header panels should go in the [app-layout](https://github.com/PolymerElements/app-layout) repo. Closing this but happy to reopen if folks disagree.
