### ISSUE TITLE
Why PSK uses vulcanize instead of polybuild?

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/polymer-starter-kit#665]
Why PSK uses `vulcanize` instead of `polybuild`? :)

**Comment by robdodson** [comment]
We trying using polybuild at one point and it broke PSK so we reverted back https://github.com/PolymerElements/polymer-starter-kit/pull/421

**Comment by abdonrd** [comment]
Okey! :(

Thanks @robdodson!
