### ISSUE TITLE
scriptInHead: false in js task results in import js executed before js from index

### ISSUE THREAD

**Issue by bushuyev** [PolymerElements/polymer-starter-kit#669]
Why is it neccessary to set scriptInHead to the false? It results in javascripts from the imported files executed before javascript in the index no matter how high it is. Quite confusing.

See the full funny story
http://stackoverflow.com/questions/34857939/order-of-javascript-execution-when-loading-html-import

**Comment by robdodson** [comment]
Related https://github.com/PolymerElements/polymer-starter-kit/issues/605

**Comment by addyosmani** [comment]
@robdodson From the sounds of it this is an issue with Crisper setup in the ES2015 recipe. The default option for `scriptInHead` is set to true in Crisper 1.x. This apparently gives you:

* This improves load performance by parallelizing HTML and script parsing
* This will break document.write calls
* If you experience problems, you can use --script-in-head=false argument or scriptInHead: false in library usage.

Is there a reason for us to not be `scriptInHead: true` here? (I'm probably missing some context here) :question:

**Comment by robdodson** [comment]
@addyosmani using script in head breaks the app but I could never figure out why

**Comment by robdodson** [comment]
Going to close this as we're no longer directly involved with the build (that's handled by Polymer CLI now). Polymer is moving toward better ES2015 support in the very near future so I think this point will resolve itself when those updates land.
