### ISSUE TITLE
Suggestion: improve doc about Firebase Pretty URLs

### ISSUE THREAD

**Issue by felipecesar00** [PolymerElements/polymer-starter-kit#670]
I had a lot of problems when using Pretty URLs in Firebase, even following the guide: https://github.com/PolymerElements/polymer-starter-kit/blob/master/docs/deploy-to-firebase-pretty-urls.md

I discovered that the tag `<base href="/">` should come first in the `index.html`. When this tag was the last line of the `<head>` tag the browser had a lot of problems when finding the elements. But, if you put this tag just after the starting of the `<head>` and before any kind of import it works perfectly.

So, I would like to suggest changing the step text
`"Add <base href="/"> to head in index.html"`
to
`"Add <base href="/"> in the beggining of the head in index.html"`

**Comment by samccone** [comment]
:+1: this seems like a reasonable change to me, good idea @felipecesar00 
Any interest in opening up a PR?

**Comment by felipecesar00** [comment]
I don't. Fell free to change :). I believe this detail will help many devs spend less time on solving routing problems :)

**Comment by chuckh** [comment]
I created pr #671 with this change.
