### ISSUE TITLE
errors installing dependencies, debug log below

### ISSUE THREAD

**Issue by atomikolex** [PolymerElements/polymer-starter-kit#68]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'deps' ]
2 info using npm@2.10.1
3 info using node@v0.12.4
4 verbose node symlink /usr/bin/node
5 verbose run-script [ 'predeps', 'deps', 'postdeps' ]
6 info predeps polymer-starter-kit@0.0.0
7 info deps polymer-starter-kit@0.0.0
8 verbose unsafe-perm in lifecycle true
9 info polymer-starter-kit@0.0.0 Failed to exec deps script
10 verbose stack Error: polymer-starter-kit@0.0.0 deps: `npm install -g gulp && npm install -g bower && npm install && bower install`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1015:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
11 verbose pkgid polymer-starter-kit@0.0.0
12 verbose cwd /home/atomikolex/public_html/polymer/polymer-starter-kit-1.0.0
13 error Linux 3.19.0-9-generic
14 error argv "/usr/bin/node" "/usr/bin/npm" "run" "deps"
15 error node v0.12.4
16 error npm  v2.10.1
17 error code ELIFECYCLE
18 error polymer-starter-kit@0.0.0 deps: `npm install -g gulp && npm install -g bower && npm install && bower install`
18 error Exit status 1
19 error Failed at the polymer-starter-kit@0.0.0 deps script 'npm install -g gulp && npm install -g bower && npm install && bower install'.
19 error This is most likely a problem with the polymer-starter-kit package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     npm install -g gulp && npm install -g bower && npm install && bower install
19 error You can get their info via:
19 error     npm owner ls polymer-starter-kit
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]

**Comment by iacopodeenosee** [comment]
the same error for me: 
http://pastebin.com/33d61Hxx

**Comment by addyosmani** [comment]
Can you try `npm install && bower install` from the roof of your download and let me know if the same messages show up?

**Comment by addyosmani** [comment]
I've investigated this further and I'm almost certain the issue is npm doesn't have consistent support for `npm run` scripts on Windows.

I believe this one liner will work instead, when run from inside the Polymer Starter Kit directory: `npm install --global gulp && npm install && bower install`. Could you try that?

**Comment by atomikolex** [comment]
Success with sudo npm install && bower install, thank you!

**Comment by atomikolex** [comment]
Successfull install! Thank you!!
Great presentation, btw!
Alex


Am 30.05.2015 um 16:23 schrieb Addy Osmani:

**Comment by addyosmani** [comment]
Awesome!

**Comment by sajjadmurtaza49** [comment]
➜  my-project  sudo npm install npm@2.11.0 && npm install -g gulp && npm install -g bower && npm install && bower install
npm@2.11.0 node_modules/npm
npm ERR! Linux 3.13.0-24-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "gulp"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! path /usr/bin/gulp
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, unlink '/usr/bin/gulp'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, unlink '/usr/bin/gulp'] errno: -13, code: 'EACCES', path: '/usr/bin/gulp' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
npm ERR! error rolling back Error: EACCES, unlink '/usr/bin/gulp'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EACCES, unlink '/usr/bin/gulp'] errno: -13, code: 'EACCES', path: '/usr/bin/gulp' }

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sajad/p_projects/my-project/npm-debug.log
