### ISSUE TITLE
gulp serve leads to a blank page in browser

### ISSUE THREAD

**Issue by kevinpmbudd** [PolymerElements/polymer-starter-kit#680]
No errors with npm or bower installs, gulp serve shows no errors either. From devtools the console shows: 
Our app is ready to rock!
app.js:78 Uncaught TypeError: app.$.paperDrawerPanel.closeDrawer is not a function(anonymous function) @ webcomponents-lite.js:2409

The page appears blank. Thanks

**Comment by samccone** [comment]
@kevinpmbudd can you delete your bower_components folder and run bower i again?

**Comment by kevinpmbudd** [comment]
@samccone thanks for help. deleting bower_components and running bower i did not fix. seeing the same result in the browser.

**Comment by samccone** [comment]
what version are you on? and what platform (windows/mac/linux)?

**Comment by kevinpmbudd** [comment]
mac
polymer 1.2.2
node 5.5.0
npm 3.3.12
bower 1.7.4

**Comment by samccone** [comment]
Which release of PSK are you using?

**Comment by kevinpmbudd** [comment]
believe its the latest release, getting it from here on the github, polymer-starter-kit-1.2.2.zip

**Comment by joryphillips** [comment]
I've had the blank screen and a few different things have fixed it, depending on the circumstance: 

1. My HTML had some errors.
2. With devtools open, I held down a mouse click (or left click) on the 'reload' button and clicked 'empty cache and reload'
3. I deleted my bower_components, used `bower cache clean` and then reinstalled the components.

**Comment by kevinpmbudd** [comment]
miracles do happen. thanks @joryphillips, third one was a charm, bower cache clean and then bower i did the trick. thanks @samccone for working on this as well.

**Comment by samccone** [comment]
:boom: good call on the cache clean @joryphillips 

:+1:

**Comment by preetcam** [comment]
For me cleaning the bower cache dint work. Is there any other trick I can try.
There are no errors in console.
