### ISSUE TITLE
WATCH HTML - node.exe high CPU consumption on gulp serve

### ISSUE THREAD

**Issue by vitoexe** [PolymerElements/polymer-starter-kit#681]
Compare to all previous version of PSK including 1.2.0rc,
in 1.2.2 when __gulp serve__ is running CPU consumption (on Windows 7) increase:
from __0%__-__1%__ to __20%__-__27%__

seems to be because this line:
gulp.watch(['app/**/*.html'], reload);

**Comment by samccone** [comment]
@vitoexe what node version are you on?

**Comment by vitoexe** [comment]
v4.2.6

**Comment by vitoexe** [comment]
on version 1.2.0rc and all before, CPU consumption was minimal __0%-1%__
on 1.2.2 - __20%-27%__ (node 4.2.6), __38%-50%__ node (node 5.5.0)
on 1.2.3 - __10%-13%__ (node 4.2.6 & 5.5.0)

CPU Intel Core 2 Duo P8700  (2.53 GHz)

**Comment by vitoexe** [comment]
I'm pretty sure, problem is __bower_component folder__ in app directory.
__gulp.watch(['app/&ast;&ast;/&ast;.html',...__ observe also this folder, which is quite big.

my solution ...
__gulp.watch(['app/&ast;&ast;/&ast;.html', '!app/bower_components/&ast;&ast;/&ast;.html'], reload);__

I understand benefits of observe changes in components but, no every one has new iMac PRO :P

**Comment by cvanleeuwen** [comment]
@vitoexe is right, watching changes on bower_components affects performance significantly.

**Comment by samccone** [comment]
:+1: seems like a super reasonable fix @vitoexe 

It would be awesome if you wanted to open a PR to add your fix here: https://github.com/PolymerElements/polymer-starter-kit/blob/master/gulpfile.js#L241

Thanks a ton for tracking this down @vitoexe and @cvanleeuwen :clap:

**Comment by samccone** [comment]
@vitoexe thanks again for spotting this, @e111077 swooped in and fixed this up for us, this should go out in the next release.

Thanks :sparkles:

**Comment by abdonrd** [comment]
@vitoexe thanks for catch it! :smiley:
