### ISSUE TITLE
Browser sync binding and CSP

### ISSUE THREAD

**Issue by zboralski** [PolymerElements/polymer-starter-kit#687]
After watching @robdodson's last polycast, I decided to enable CSP and use crisper to separate html and javascript code and the last road block is the browser-sync-binding snippet : 

```html
  //<![CDATA[
  document.write(
    "<script async src='/browser-sync/browser-sync-client.2.11.0.js'><\/script>"
    .replace("HOST", location.hostname));
  //]]>
```

I am not sure how I should go around to fix it.

**Comment by robdodson** [comment]
Is that line of code coming out of the browser sync task itself?

**Comment by addyosmani** [comment]
We have static browser-sync markup in PSK's index over at https://github.com/PolymerElements/polymer-starter-kit/blob/master/app/index.html#L63 and I believe that's used for injection over in places like https://github.com/PolymerElements/polymer-starter-kit/blob/5929c0b16c170f6d8d5ac115167458652ac24161/gulpfile.js#L218. 

@zboralski If you drop https://github.com/PolymerElements/polymer-starter-kit/blob/master/app/index.html#L63 entirely from your setup, do you run into any issues with crisper at all?

**Comment by zboralski** [comment]
@addyosmani I removed the span which gets replaced by some inline code. It would help if the injection is done before vulcanise. Although I think vulcanize is only ran on elements.html.

**Comment by zboralski** [comment]
@addyosmani if I remove https://github.com/PolymerElements/polymer-starter-kit/blob/master/app/index.html#L63 I have no issues.

**Comment by samccone** [comment]
:+1: @zboralski seems like the correct resolution. I am glad you got it worked out. Hopefully this issue will act as a good reference if someone finds themselves in a similar situation. Thanks for digging in on this one.

**Comment by zboralski** [comment]
@samccone why should the snippet be injected for the dist version ?  I don't think this is resolved correctly. I'd like to be able to use browser sync during development but it shouldn't interfere with the dist version.

**Comment by samccone** [comment]
> I'd like to be able to use browser sync during development but it shouldn't interfere with the dist version.

^ This is an issue that you should only hit when using CSP

+1 to this goal however, this would be ideal, we would need to inject the browser-sync code dynamically during dev or just dynamically remove the chunk when building the final dist.

---

The reason I closed this is because at a certain point of customization of the PSK you will hit these kind of issues, and making a change to the code is to be expected, since this is just a starter kit :)

That said, I would be +1 to landing a change that makes the browser sync logic a bit smarter between dev mode and production mode.


Thoughts?

**Comment by vguillou** [comment]
We could simply use `gulp-useref` to remove the browser-sync span, since it has already been made available to inject minified version of the webcomponent polyfill.

Like this :

    
    <span id="browser-sync-binding"></span>

**Comment by samccone** [comment]
:+1: I love that idea @vguillou :) 

Any interest in opening a PR?

**Comment by vguillou** [comment]
Will do shortly :+1:
