### ISSUE TITLE
Make <platinum-bluetooth> elements optional

### ISSUE THREAD

**Issue by beaufortfrancois** [PolymerElements/polymer-starter-kit#689]
According to https://github.com/PolymerElements/polymer-starter-kit/blob/5929c0b16c170f6d8d5ac115167458652ac24161/bower.json#L9 all `<platinum-elements>` are mandatory. As it's not only about SW stuff, it might be good to select the elements we want to be present in the starter kit.

I'm not sure `<platinum-bluetooth>` elements for instance will be of interest for everyone ;)

**Comment by addyosmani** [comment]
Although we include the Platinum elements by default, they are referenced in PSK until you explicitly decide to do this: https://github.com/PolymerElements/polymer-starter-kit/blob/master/app/elements/elements.html#L28

I'm :+1: on us trimming down the deps pulled in by default so perhaps we either:

1) Trim `bower.json` to only include the SW elements
2) Trim `bower.json` to exclude all Platinum elements and add an extra step to `bower install` them if you decide to follow the optional SW add-on instructions

@robdodson @samccone @chuckh thoughts?

**Comment by chuckh** [comment]
I agree with @addyosmani and prefer option 2.

On Thu, Feb 4, 2016 at 10:36 AM Addy Osmani <notifications@github.com>
wrote:

> Although we include the Platinum elements by default, they are referenced
> in PSK until you explicitly decide to do this:
> https://github.com/PolymerElements/polymer-starter-kit/blob/master/app/elements/elements.html#L28
>
> I'm [image: :+1:] on us trimming down the deps pulled in by default so
> perhaps we either:
>
> 1) Trim bower.json to only include the SW elements
> 2) Trim bower.json to exclude all Platinum elements and add an extra step
> to bower install them if you decide to follow the optional SW add-on
> instructions
>
> @robdodson <https://github.com/robdodson> @samccone
> <https://github.com/samccone> @chuckh <https://github.com/chuckh>
> thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PolymerElements/polymer-starter-kit/issues/689#issuecomment-179989691>
> .
>
-- 
Chuck Horton
proplanr.com
www.hware.com
chuck@hware.com
530.268.5840

Let us create a world that works for all.

**Comment by robdodson** [comment]
+1 for 2 :+1:

**Comment by abdonrd** [comment]
+1 por option 2!

**Comment by beaufortfrancois** [comment]
Who should be assigned to that issue?

**Comment by robdodson** [comment]
Good question... maybe @azakus?

**Comment by samccone** [comment]
I can just do this... would only take a moment right?

**Comment by robdodson** [comment]
yeah i wasn't sure if it needed to be part of the tedium release process

**Comment by robdodson** [comment]
We're no longer using platinum elements in PSK2. Instead we rely on CLI and sw-precache to generate our service workers.
