### ISSUE TITLE
Windows not supported?

### ISSUE THREAD

**Issue by IntranetFactory** [PolymerElements/polymer-starter-kit#69]
Maybe you should provide some information about the supported platforms. It seems that Windows is not supported - which surprises as Polymer itself supports Windows.

**Comment by addyosmani** [comment]
Could you provide some more information on what is failing for you on Windows?

**Comment by addyosmani** [comment]
Rolling into #68. I believe I've discovered a common paths issue on Windows that prevents the current approach we use for npm `run` scripts from consistently working. We're going to expand the install instructions soon to address this.

**Comment by IntranetFactory** [comment]
I'm not sure that #68 is the the same problem I still have.

`npm install` 

fails. I've VS2013 and VS2015RC installed. But I don't understand why VS needs to be installed at all? 


![2015-05-30_1101](https://cloud.githubusercontent.com/assets/7462342/7897866/74a0f150-06bb-11e5-8413-a6cc996c29c8.png)

**Comment by addyosmani** [comment]
That's really weird. The only thing I can think of is that there's a dependency being pulled in which requires recompilation on your version of Windows. I'm guessing it's trying to do this using VS. 

Could you try this for a sec? 

1. Delete node_modules
2. Run `npm install npm@2.11.0 && npm install -g gulp && npm install -g bower && npm install && bower install` (You can drop the bower portions if you already have those deps installed).

I'll try to dig into why web-component-tester needs dep recompilation there.

**Comment by IntranetFactory** [comment]
Still same problem, node_modules\socket.io fails several times to compile.

**Comment by IntranetFactory** [comment]
Found some information on http://stackoverflow.com/questions/16469086/npm-cant-install-socket-io and https://github.com/joyent/node/blob/v0.10.29/tools/gyp/pylib/gyp/MSVSVersion.py#L209-294 so for me 

`set GYP_MSVS_VERSION=2013`

seem to help.

IMHO a "Starter Kit" should be self-contained and not require an obviously fragile build process.

**Comment by addyosmani** [comment]
Thanks for the feedback. I've updated our releases page to highlight that we do offer a simpler starting point without any build process for anyone that prefers or has issues getting the tools working correctly (obviously not their fault, Node tooling can be tricky cross-platform).
