### ISSUE TITLE
Feature: Chrome App Shell with Polymer.

### ISSUE THREAD

**Issue by myuseringithub** [PolymerElements/polymer-starter-kit#692]
Will you add App Shell in future Polymer kit releases ? 
https://github.com/GoogleChrome/application-shell

**Comment by robdodson** [comment]
Yeah, probably not that specific example, but our plan is to roll our PSK templates that meet the progressive web app, app-shell model

**Comment by myuseringithub** [comment]
Thanks ! Great job.
