### ISSUE TITLE
Babel 6.5 with es2015 preset leads to 'undefined' errors in third-party scripts

### ISSUE THREAD

**Issue by ankon** [PolymerElements/polymer-starter-kit#694]
Sorry for the vague title, hard to describe the problem exactly in a single line :)

What we did/tried to accomplish is to use components with ES2015 syntax, and in our main app follow https://github.com/PolymerElements/polymer-starter-kit/blob/master/docs/add-es2015-support-babel.md to transpile the vulcanized & crisped JS file using the `es2015` preset. When running the resulting application on Chrome in Android 5.1.1 we received errors such as this one:
~~~~
I/chromium(22794): [INFO:CONSOLE(15703)] "Uncaught TypeError: Cannot set property 'moment' of undefined", source: file:///android_asset/www/elements/elements-c8cf783c6f.js (15703)
~~~~

I tracked this line down to the `moment.js` script used by one of our components:
~~~~
!function (a, b) {
  "object" == (typeof exports === 'undefined' ? 'undefined' : _typeof(exports)) && "undefined" != typeof module ? module.exports = b() : "function" == typeof define && define.amd ? define(b) : a.moment = b();
}(undefined, function () {
~~~~

Before babel this looks like this:
~~~~
!function(a,b){"object"==typeof exports&&"undefined"!=typeof module?module.exports=b():"function"==typeof define&&define.amd?define(b):a.moment=b()}(this,function(){
~~~~

Note how babel replaced `this` with `undefined` here. This is seemingly intentional behavior: https://github.com/babel/babelify/issues/37#issuecomment-160041164 / https://phabricator.babeljs.io/T3055 -- except that in the case of a polymer app the script we're running through babel is not a module!

A similar situation also happens when you use neon-animation and its imported `web-animations-next-lite.min.js`.

I fixed this by using a different preset (https://github.com/Collaborne/babel-preset-es2015-script). I think it would be good to adjust the documentation to warn about that, or even better let you take that preset over and use it instead of the default `es2015` :)

**Comment by sandrina-p** [comment]
Thank you! It worked es-2015-script. Could you explain what are the other differences between es-2015 and es-2015-script?

**Comment by ankon** [comment]
@sandrina-p the only difference is that the babel-plugin-transform-es2015-modules-* plugins are removed, other than that it aims to be identical. Thanks for the reminder though to check for updates: es2015 now includes babel-plugin-transform-es2015-duplicate-keys, so I added that one as well: https://github.com/Collaborne/babel-preset-es2015-script/commit/9314f0aee1b64ba16af9e8275c4f0fe8ae570609

**Comment by robdodson** [comment]
This is good to know. We've removed the ES2015 recipe as Polymer is moving toward ES2015 support soon and our hacky gulp workaround was honestly causing more problems than it was worth. For folks who want to experiment with Babel and ES2015 support they can still use https://github.com/PolymerElements/generator-polymer-init-custom-build and add in their own call to babel
