### ISSUE TITLE
Duplicate "mainContainer" ID in PSK

### ISSUE THREAD

**Issue by landmaxcanada** [PolymerElements/polymer-starter-kit#697]
Hi, I just noticed that document.querySelectorAll('#mainContainer') will return two elements with the same  ID, which I thought ID's were suppose to be unique.

**Comment by robdodson** [comment]
You want to use Polymer's DOM API to simulate Shadow DOM. https://www.polymer-project.org/1.0/docs/devguide/local-dom.html#dom-api
