### ISSUE TITLE
node 0.10 support

### ISSUE THREAD

**Issue by samccone** [PolymerElements/polymer-starter-kit#699]
Let's investigate the work needed to get everything working on node 0.10

not supporting it is kinda rough for us atm

xref #696

**Comment by addyosmani** [comment]
I know that we're going to need to support 0.12 for a while. Do we have any insight into how widespread 0.10 usage is atm? I really wish we could get more folks using the latest Node stable, but :crying_cat_face:

**Comment by samccone** [comment]
Let me ask @seldo for the latest stats :)
