### ISSUE TITLE
Incorrect GitHub link on homepage

### ISSUE THREAD

**Issue by CodinCat** [PolymerElements/polymer-starter-kit#70]
Not sure where should I report

https://developers.google.com/web/tools/polymer-starter-kit/

The GitHub link on the menu bar is incorrect,
it links to https://github.com/google/polymer-starter-kit

**Comment by addyosmani** [comment]
Thanks for letting us know. This is actually fixed upstream now and we're waiting for a deploy for it to go live. Should hopefully be addressed soon.
