### ISSUE TITLE
Inform the user when navigate with the menu

### ISSUE THREAD

**Issue by felixzapata** [PolymerElements/polymer-starter-kit#704]
Hi, this issue is related with the accessibility. If a user clicks on the menu, the application should inform him that the page has changed maybe sending the focus, plus using the aria live regions.

I've made some tests but i am not sure which is the best approach to fix this. I mean, maybe this issue is more related with the iron-selectable behavior when it sets the "iron-selected" class. 

But maybe can this fix can be more related with the application itself, and when you uses the routing set the focus and the regions.  Or maybe it is necessary to add the iron-a11y-announcer in the starter.

Regards.

**Comment by felixzapata** [comment]
I think that the solution can be like this way:

```javascript
    page('/users', function() {
      app.route = 'users';
      app.fire('iron-announce', { text: 'This is an announcement!' }, { bubbles: true });
    });
```

Maybe I will send a pull request.

**Comment by robdodson** [comment]
I think the usual approach for managing focus in a situation like this is to set tabindex=-1 on one of the heading or section elements, then call focus on it after the page has transitioned

**Comment by felixzapata** [comment]
yes, in the pull request I use the iron-a11y-announcer component to listen the event and to set the focus and the tabindex attribute.
