### ISSUE TITLE
app-theme colors with paper-styles/color

### ISSUE THREAD

**Issue by peter-mueller** [PolymerElements/polymer-starter-kit#709]
The primary-color and accent colors could be set by css variables from paper-styles/color.html

**Who will use the feature?**
Everyone that wants to change to a different, but material style conform color theme.

**What is the user’s goal?**
Change the theme quick, without needing to look at the Material Palette or the Material Design Color guidelines.

Given this style: 
```
:root {
    --primary-text-color: #212121;
    --primary-background-color: #ffffff;
    --secondary-text-color: #737373;
    --disabled-text-color: #9b9b9b;
    --divider-color: #b6b6b6;
    --primary-color: var(--paper-blue-500);
    --light-primary-color: var(--paper-blue-300);
    --dark-primary-color: var(--paper-blue-700);
    --accent-color: var(--paper-lime-a200);
    --light-accent-color: var(--paper-lime-a100);
    --dark-accent-color: var(--paper-lime-a400);
  }
```
A User can change to a red primary color and green accent color without much effort or any external sources.

**Downsides:**
Very new Users could be confused.

**Comment by robdodson** [comment]
I'm a little confused. We already provide theme colors here: https://github.com/PolymerElements/polymer-starter-kit/blob/master/app/styles/app-theme.html#L28-L38

Is there something you think we should do differently?

**Comment by peter-mueller** [comment]
I suggested replacing the hex values in  `app-theme` with **vars** from `paper-styles/color.html` to make switching colors easy. Excuse me if that was unclear.

**Comment by robdodson** [comment]
Ah I see! Would you be interested in putting together a pull request for this?

**Comment by peter-mueller** [comment]
ofc
