### ISSUE TITLE
Polymer Starter Kit Title Flickers When Tap Home Menu Item

### ISSUE THREAD

**Issue by chuckh** [PolymerElements/polymer-starter-kit#717]
Current PSK Polymer Starter Kit Title Flickers when tapping on User or Contact menu item and then tapping on Home menu item? Happens on Mac Chrome and Safari, and not Firefox. 

You can test it at: https://polymerelements.github.io/polymer-starter-kit/

**Comment by samccone** [comment]
+1 profiled this and I know why... (detailed writeup pending)

**Comment by addyosmani** [comment]
Thanks for taking the time to dive into the cause of this Sam 🙋
