### ISSUE TITLE
Fixup ES2015 recipe

### ISSUE THREAD

**Issue by robdodson** [PolymerElements/polymer-starter-kit#718]
Currently the ES2015 recipe doesn't work for `gulp serve:dist`. Also related https://github.com/PolymerElements/polymer-starter-kit/issues/625

**Comment by robdodson** [comment]
cc @nevraeka

**Comment by Nevraeka** [comment]
thanks @robdodson . I'm looking into this tonight

**Comment by buele** [comment]
1. Following the recipe: [Add ES2015 support through Babel](https://github.com/PolymerElements/polymer-starter-kit/blob/master/docs/add-es2015-support-babel.md)
 2. Running ```gulp serve:dist``` this error appears: 

```
$ gulp serve:dist
[15:32:42] Using gulpfile /data/buele/git/polymer-starter-kit/gulpfile.js
[15:32:42] Starting 'clean'...
[15:32:42] Finished 'clean' after 69 ms
[15:32:42] Starting 'default'...
[15:32:42] Starting 'ensureFiles'...
[15:32:42] Finished 'ensureFiles' after 419 μs
[15:32:42] Starting 'copy'...
[15:32:42] Starting 'styles'...
[15:32:43] styles all files 98 B
[15:32:43] Finished 'styles' after 755 ms
[15:32:43] copy all files 1.05 MB
[15:32:43] Finished 'copy' after 925 ms
[15:32:43] Starting 'elements'...
[15:32:43] Starting 'js'...
[15:32:43] 'js' errored after 1.45 ms
[15:32:43] TypeError: Cannot read property 'init' of undefined
    at Gulp.<anonymous> (/data/buele/git/polymer-starter-kit/gulpfile.js:124:23)
    at module.exports (/data/buele/git/polymer-starter-kit/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/data/buele/git/polymer-starter-kit/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/data/buele/git/polymer-starter-kit/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/data/buele/git/polymer-starter-kit/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/data/buele/git/polymer-starter-kit/node_modules/run-sequence/index.js:88:16)
    at Gulp.onTaskEnd (/data/buele/git/polymer-starter-kit/node_modules/run-sequence/index.js:77:5)
    at emitOne (events.js:95:20)
    at Gulp.emit (events.js:182:7)
    at Gulp.Orchestrator._emitTaskDone (/data/buele/git/polymer-starter-kit/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
[15:32:43] 'default' errored after 939 ms
[15:32:43] Error in plugin 'run-sequence'
Message:
    An error occured in task 'js'.
[15:32:43] Finished 'elements' after 41 ms
```

Do you get the same error?

**Comment by bradjohnwoods** [comment]
i get the same error, when running 'gulp serve', is there a fix for this?

**Comment by robdodson** [comment]
@bradjohnwoods that's what @Nevraeka is working on :)

**Comment by bradjohnwoods** [comment]
Thanks for the reply! love your work @ polymer, best thing since sliced
bread..

**Comment by alexpaluzzi** [comment]
Well that was fast. Great work @abdonrd. #730

**Comment by abdonrd** [comment]
Your welcome @alexpaluzzi!

**Comment by samccone** [comment]
resolved!

**Comment by alexpaluzzi** [comment]
Hey @samccone! Are you talking about #677? I don't see any actual fixes in there and it still seems like a bunch of old tasks being referenced. Maybe I'm missing the fix for this?

**Comment by samccone** [comment]
hmm i followed it and was able to make it work.... can you post your errors once more and let me see if i can reproduce 

thanks @alexpaluzzi

**Comment by alexpaluzzi** [comment]
I can try tomorrow. I don't have errors. 

But just looking at it, there's old stuff in there. `elements` task doesn't exist anymore. It may be working but I still think it really needs cleaned up. I can do it tomorrow.

**Comment by JustinXinLiu** [comment]
Yeah same I still can see a lot of old stuff there too...

**Comment by samccone** [comment]
any help welcome here, thanks @alexpaluzzi and @JustinXinLiu

**Comment by robdodson** [comment]
@samccone I think the issues with the ES2015 codelab were around gulp serve:dist not working. Did you try that? If not we may want to reopen this issue. I think @Nevraeka is working on improving the doc

**Comment by samccone** [comment]
yeah I did not try dist ... lemme reopen until we can verify :)

**Comment by Nevraeka** [comment]
I got it all working ( w/ help from @belcherj as far as I can tell @samccone . I'll post a PR. Please take a look and let me know what you think.

cc @alexpaluzzi @robdodson  @JustinXinLiu

**Comment by JustinXinLiu** [comment]
Thanks @Nevraeka for doing this!! Please correct me if I am wrong but I thought we should update the [ES6 recipe](https://github.com/PolymerElements/polymer-starter-kit/blob/master/docs/add-es2015-support-babel.md) based on the latest version of *gulpfile.js* instead of modifying the file itself?

**Comment by alexpaluzzi** [comment]
Looks like the errors are resolved, @Nevraeka! +1 But like @JustinXinLiu mentioned, it's still using outdated tasks (`elements`) which is guaranteed to confuse any newcomers.

**Comment by Nevraeka** [comment]
@JustinXinLiu @alexpaluzzi Cool. I closed the PR and I'm adding to the recipe instead. Additionally I'll remoe the noted deprecated tasks. Thanks for the follow up. cc @robdodson

**Comment by alexpaluzzi** [comment]
Thanks @Nevraeka! Happy to run through them from scratch when you open the PR. I got a Windows machine as well that I can test with. Just ping.

**Comment by addyosmani** [comment]
Similarly happy to assist with Windows testing as needed.

**Comment by nibuen** [comment]
@Nevraeka Looks like already close to done.

But encase you need, I have a working version from when i added the fix for vulcanize with gulp serve:dist from #672

using the old elements task setup though.

**Comment by robdodson** [comment]
I noticed that `gulp serve:dist` didn't seem to be working in this update. I think we may need to run `vulcanize` from the `.tmp` dir to make it happy. We're doing a codelab this coming week and I thought maybe I could take a stab at tuning up some of the work in this PR so here's the crazy big patch to the current ES2015 codelab https://github.com/googlecodelabs/psk-es2015/pull/12

I'm wondering if it would make sense for us to remove this recipe and just use that codelab as the canonical source for how you roll in ES2015 support? At least until we rev for PSK2

**Comment by peterblazejewicz** [comment]
@robdodson 
I had a problem compiling  ES6 recipes - both from Codelab and PSK, but the version from googlecodelabs/psk-es2015#12 works for me.

**Comment by robdodson** [comment]
@peterblazejewicz good to hear! I'm updating the code lab documentation as we speak. Hope to get that published soon

**Comment by ZergMark** [comment]
One issue I can see with dropping the "patch" docs here and just using the Codelab repo is that the gulpfile for the PSK gets changed (or at least PRed) very frequently. Are you going to be syncing the Codelab repo on a regular basis? If there is a desire to not make devs go around patching the existing `gulpfile.js`, perhaps a separate `gulpfile.es2015.js` in this repo to keep everything together? JM2C.

**Comment by robdodson** [comment]
> Are you going to be syncing the Codelab repo on a regular basis?

In the near term I think so. We're kicking off a rewrite of PSK to make this more modular and make ES2015 a first class citizen so ideally none of this stuff will be needed in a few months

**Comment by robdodson** [comment]
We ended up going with a simplified approach to PSK as the Polymer team is working on rolling ES2015 support into the library itself. We should have updates to show in this area very soon. I'm going to close this issue as PSK now relies on Polymer CLI to generate its build. If you want to experiment with adding ES2015 support you can do so using https://github.com/PolymerElements/generator-polymer-init-custom-build
