### ISSUE TITLE
Fixup Perf Patterns recipe

### ISSUE THREAD

**Issue by robdodson** [PolymerElements/polymer-starter-kit#719]
Self assigning this.

**Comment by addyosmani** [comment]
When we were planning PSK 2 we talked about trying to reduce our reliance on recipes for certain workflows. Is perf pattern integration something you see still existing as a guide or something we should try adding to Polytool as a plugin/flag?

**Comment by robdodson** [comment]
It's probably deeper than polytool. This has to come from the polymer team itself I think. What their final strategy around h2 and the like looks like. I'd prefer to not have to do too much hackery to just get decent perf out of the box

**Comment by robdodson** [comment]
Most of the perf pattern recipe is just built into PSK now thanks to [PRPL](https://www.polymer-project.org/1.0/toolbox/server)
