### ISSUE TITLE
When deploying to App Engine are HashBangs Necessary?

### ISSUE THREAD

**Issue by johnwhitton** [PolymerElements/polymer-starter-kit#723]
Hi, 
I was following the [App Engine deploy recipe](https://github.com/PolymerElements/polymer-starter-kit/blob/master/docs/deploy-to-google-app-engine.md) and I remembered that in the [firebase deploy recipe](https://github.com/PolymerElements/polymer-starter-kit/blob/master/docs/deploy-to-firebase-pretty-urls.md) it recommended removing hashbangs
So I followed steps 7 and 8 in the firebase recipe and the deploy seems to be working fine
You can see the the deployed version at www.jincubator.com and here is the [github repository](https://github.com/johnwhitton/jincubator).
My question is are hashbangs just  a matter of preference or is there a reason why they're required when deploying to app engine?

Thanks in advance.

Regards,

John

**Comment by abdonrd** [comment]
Because if you go, for example to http://www.jincubator.com/contact directly, the server try to resolve the route, and break. :sweat_smile:

**Comment by johnwhitton** [comment]
Ok so I've placed the hashbangs back in and that has resolved the issue.

**Comment by johnwhitton** [comment]
I'll leave this open so other people can add their thoughts.
Thanks @abdonrd for all your help on this.

**Comment by samccone** [comment]
:+1: glad you got this resolved @johnwhitton :) Thanks for the help and advice @abdonrd :clap:
