### ISSUE TITLE
Router

### ISSUE THREAD

**Issue by hourliert** [PolymerElements/polymer-starter-kit#73]
Hi,

This is more a question than an issue. But why does the starter-kit use https://github.com/visionmedia/page.js rather than https://github.com/PolymerLabs/more-routing or https://github.com/erikringsmuth/app-router (polymer 0.5) ?

Thanks in advance,
Thomas

**Comment by addyosmani** [comment]
The current element based approaches to app routing don't provide sufficient imperative hooks for giving you full control over the router. We did initially support more-routing here, but took it out after realising this wasn't quite what we needed. For the time being, we find that just using a JS router actually gets you pretty far, but we'll continue to experiment with what a better routing solution might look like for Polymer.

**Comment by devAtPolydeals** [comment]
@hourliert I agree with you, i love app-router, they are not planning to upgrade to 1.0 polymer, but it will work with new version since its js based (except core-animation-pages integration). See https://github.com/erikringsmuth/app-router/issues/111, i m sure someone will eventually fork it to be fully compatible with 1.0.0.

BTW page.js out of box is giving me problems after i click any link once, it then starts expecting my app is root of localhost instead being nested. I am planning on switching to app-router or may read page.js don't know yet.

**Comment by addyosmani** [comment]
> BTW page.js out of box is giving me problems after i click any link once, it then starts showing on URL that my app is in root of localhost instead being nested. May be i need to read about page.js. I am planning on switching to app-router or may read page.js don't know yet.

Is this occurring for you in the current window or only if you're using BrowserSync and testing this across multiple windows? There's a known bug in #66 related to the latter. The former shouldn't however have this issue. If it does more info would be hugely appreciated.

**Comment by devAtPolydeals** [comment]
I am not using BrowserSync, i deployed on my wamp server and running it directly on my browser with the URL.  What more info do you need? I don't mind helping..

**Comment by devAtPolydeals** [comment]
This is initial state:
![image](https://cloud.githubusercontent.com/assets/12582040/7904297/726be51c-07aa-11e5-8271-888240985ebf.png)

This is state 2 on clicking users:
![image](https://cloud.githubusercontent.com/assets/12582040/7904299/877a19e2-07aa-11e5-9d21-8058de1c23cb.png)

This is state 3 on clicking home
![image](https://cloud.githubusercontent.com/assets/12582040/7904302/97eb8e32-07aa-11e5-812f-f11b46aff80c.png)

As you can see after the 2nd click the url has issues. Navigation works though. See below
![image](https://cloud.githubusercontent.com/assets/12582040/7904304/bd45182e-07aa-11e5-822d-40d45e13afca.png)

**Comment by addyosmani** [comment]
Thanks for the screenshots! I'll investigate further and see if I can come up with a fix.
