### ISSUE TITLE
Switch to Polymer Team's labeling approach

### ISSUE THREAD

**Issue by robdodson** [PolymerElements/polymer-starter-kit#736]
Outlined here: https://gist.github.com/justinfagnani/bcd0af53a325986ddc8f this should help us work better with Polymer team's dashboard tool http://meowni.ca/frankly/

**Comment by robdodson** [comment]
Maybe using https://www.npmjs.com/package/git-labelmaker

**Comment by justinfagnani** [comment]
Note that the tools team is using a different labeling scheme than elements. `frankly` should be usable with any set of labels, but I think one dashbard needs one set of labels to work right. It'd be nice to have devrel projects on the tools dashboard.

**Comment by samccone** [comment]
down for whatever, process has never been a huge issue on this repo so adding more may not be much of a win imho

**Comment by addyosmani** [comment]
Similarly flexible with whatever labelling approach adds value here.

**Comment by addyosmani** [comment]
@robdodson sounds like we're chill with doing this :cake:

**Comment by robdodson** [comment]
it doesn't seem like those labels listed include the cla labels. Do we need to add those manually?

**Comment by robdodson** [comment]
I'm going to close this. The system we have in place now seems to work fine for us so let's just stick with it
