### ISSUE TITLE
Polymer Starter Kit for Dart

### ISSUE THREAD

**Issue by gbr** [PolymerElements/polymer-starter-kit#738]
Currently, there is no official starter kit for a Dart app. As a Polymer.dart user, I would like to take advantage of the included Page.js, and perhaps the Web Component Tester. There are unofficial versions floating out there but nothing that is maintained like this one. The WebStorm sample project is a helpful start but it is not as useful as this kit.

**Comment by robdodson** [comment]
Hey @gbr thanks for the issue.

IMO this would be better served as a separate project, possibly maintained by the Dart team. I don't think any of the maintainers of PSK are currently well versed in Dart so it would be very difficult for us to attempt to build and maintain a version of this. I'm going to close the issue for now but happy to continue the discussion and answer any questions you have.
