### ISSUE TITLE
Problem with example template autobinding snippets

### ISSUE THREAD

**Issue by peterblazejewicz** [PolymerElements/polymer-starter-kit#74]
I've a problem with template auto-binding event not being fired in kit:
https://github.com/PolymerElements/polymer-starter-kit/blob/master/app/scripts/app.js#L24-L26
The same code in generator-polymer fires just fine:
https://github.com/yeoman/generator-polymer/blob/master/app/templates/app/app.js#L12-L14
```
'Our app is ready to rock!'
```
Can someone confirm this? 

OS X/Chrome/Safari
PSK:  v1.0.0

**Comment by addyosmani** [comment]
@arthurevans do you know if `template-bound` is still available in 1.0? I haven't been able to locate references to whether we dropped it, but..just checking :)

**Comment by arthurevans** [comment]
I think the 1.0 equivalent is `dom-change`. See the API Docs for `dom-bind` here:

http://polymer.github.io/polymer/

We should add a note about this to the migration guide.

**Comment by peterblazejewicz** [comment]
```
app.addEventListener('dom-change', function() {
  console.log('Our app is ready to rock!');
});
```
Yes, this works with the kit current code. Thanks for checking this.

**Comment by addyosmani** [comment]
Thanks @arthurevans! A note would be fantastic. I'll update kit to use `dom-change` instead.
