### ISSUE TITLE
Using marked-element

### ISSUE THREAD

**Issue by oopg** [PolymerElements/polymer-starter-kit#740]
Using PSK 1.2.3, during gulp, at vulcanize task marked-element is looked at /app/elements/bower_components rather than /app/bower_components. Gives the following error: ERROR finding /app/elements/bower_components/marked-element/marked-element.html. The marked-element version is 1.1.3.

**Comment by felixzapata** [comment]
hi @oopg, after install the component with `bower install --save PolymerElements/marked-element` inside your project folder, have you added it to the `elements.html` file like this way?:

`<link rel="import" href="../bower_components/marked-element/marked-element.html">`

Regards.

**Comment by oopg** [comment]
Yes, it is added as import and polylint is confirming it in Atom. However, vulcanize is having issues.

**Comment by oopg** [comment]
Fixed. One wrong reference to marked-element in one file. 
Thanks.

**Comment by felixzapata** [comment]
you`re welcome @oopg
