### ISSUE TITLE
Add Nginx Recipe for Pretty URLs

### ISSUE THREAD

**Issue by landmaxcanada** [PolymerElements/polymer-starter-kit#741]
Hi, can you add Nginx recipe to the list? Very similar to Firebase Pretty URLs, but I got stuck missing the forward slash on "index.html" in the "try_files" statement. This seems to work. There may be other optimizations for Nginx as well. Firebase suggests a "rewrites" statement, not sure if that is needed with Nginx?

```
index.html
<base href="/">

routing.html
page({hashbang: false})

nginx
location / { try_files $uri $uri/ /index.html }
```

**Comment by robdodson** [comment]
Yeah would you be interested in putting together a pull request for it?

**Comment by motss** [comment]
@landmaxcanada Unless you don't mind having the hashbang in your URL, then `location / { try_file $uri $uri/ /index.html` can be omitted as that is equivalent to Firebase's "rewrites" statement. This looks good to me.

**Comment by robdodson** [comment]
We're no longer doing recipes on this repo because they became impossible to maintain. Every time we changed PSK we had to go through and audit all of the recipes manually.

I think this may be better served as a blog post by those who are interested in the topic.
