### ISSUE TITLE
focus null in neon-animated-pages recipe

### ISSUE THREAD

**Issue by lucasfrib** [PolymerElements/polymer-starter-kit#742]
"focus null" error after following the neon-animated-pages recipe in the /docs

i think is the "section" in the routing.html file:
document.querySelector('section[data-route="' + selected + '"]').focus();

it´s ok to replace section to "neon-animated" too? (#newbie)
document.querySelector('neon-animatable[data-route="' + selected + '"]').focus();

**Comment by vguillou** [comment]
Yes you are right, I forgot to add this in the current recipe.
Do you want to create the PR ? :+1:

**Comment by motss** [comment]
@lucasfrib @vguillou @samccone Created a PR to fix issue.
