### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by camerongreen** [PolymerElements/polymer-starter-kit#747]
First download link on

https://github.com/polymerelements/polymer-starter-kit/releases

Points to what seems like the right URL

https://github.com/PolymerElements/polymer-starter-kit/releases/download/v1.3.0/polymer-starter-kit-light-1.3.0.zip

But seems the file might have been misnamed, or rounded by a calculator :)

https://github.com/PolymerElements/polymer-starter-kit/releases/download/v1.3.0/polymer-starter-kit-light-1.3.zip

**Comment by addyosmani** [comment]
Fixed. cc @samccone as an fyi :)

**Comment by samccone** [comment]
Ah drat my bad!
