### ISSUE TITLE
#mainToolbar text placement prevents hamburger menu from working on scroll

### ISSUE THREAD

**Issue by kbwatts** [PolymerElements/polymer-starter-kit#75]
Once you add enough content to scroll the default waterfall-tall toolbar, the hamburger menu button seems to stop working - see screenshot (you can click but no effect - also affects mobile-sized/ios simulator):

![hamburger-no-effect-wide](https://cloud.githubusercontent.com/assets/961706/7899478/81875934-0767-11e5-8f0f-45784caf3d26.png)
![hamburger-no-effect-narrow](https://cloud.githubusercontent.com/assets/961706/7899479/86f5ccfc-0767-11e5-9536-32410ba20225.png)
![hamburger-no-effect-ios](https://cloud.githubusercontent.com/assets/961706/7899483/b3595df4-0767-11e5-92ea-3142180e3666.png)

**Comment by kbwatts** [comment]
When you `display: none` on the mainToolbar text ("Polymer Starter Kit") then the hamburger button works again, so it looks like a problem with that text more than the button - will rename this issue.

**Comment by addyosmani** [comment]
I think you're right that the issue is with the text rather than the button. I'll try to dig into the cause.
