### ISSUE TITLE
Index.html  file display blank (local && on gulp)

### ISSUE THREAD

**Issue by Ahtesham1234** [PolymerElements/polymer-starter-kit#751]
Done every step .npm bower,gulp install and rest but still getting the blank page on local hosting and on gulp serve.
How to fix it .

**Comment by robdodson** [comment]
If you open the DevTools do you see any errors in the JavaScript console?

**Comment by Ahtesham1234** [comment]
@robdodson Below are my Errors in console:


1-Failed to load resource: net::ERR_FILE_NOT_FOUND
2-Imported resource from origin 'file://' has been blocked from loading by Cross-Origin Resource Sharing policy: Invalid response. Origin 'null' is therefore not allowed access.

**Comment by robdodson** [comment]
It looks like you're not running the local server, that's why you have a blank page. When you run `gulp serve` it should open a window for you, otherwise navigate to http://localhost:5000

**Comment by Ahtesham1234** [comment]
@robdodson yup finally working, thx Rob.
