### ISSUE TITLE
Improve precache file generation gulp task using http2-push-manifest

### ISSUE THREAD

**Issue by kenchris** [PolymerElements/polymer-starter-kit#752]
When using HTTP2 you usually don't vulcanize your files but might use a push manifest instead.

The current task it kind of depends on the vulcanizing step, but with HTTP2 you need a way to track all files (through imports etc) to gather a list of files to cache. This turns out to be what http2-push-manifest does and it can easily be reused in PSK:

```
20 let Manifest = require('http2-push-manifest/lib/manifest');
21 
22 var DIST = '.';
23 
24 var dist = function(subpath) {
25   return !subpath ? DIST : path.join(DIST, subpath);
26 };
27 
28 gulp.task('cache-config', function(callback) {
29   var dir = dist();
30   var config = {
31     cacheId: packageJson.name || path.basename(__dirname),
32     disabled: false
33   };
34 
35   let f = 'index.html';
36 
37   // Make a path if one wasn't given. e.g. basic.html -> ./basic.html
38   if (f.indexOf(path.sep) === -1) {
39     f = `.${path.sep}${f}`;
40   }
41 
42   let basePath = f.slice(0, f.lastIndexOf(path.sep))
43   let inputPath = f.slice(f.lastIndexOf(path.sep) + 1);
44 
45   let manifest = new Manifest({basePath, inputPath, name: 'cache-config.json'}); 
46   manifest.generate().then(output => {
47     config.precache = output.urls.map((url) => {
48       return url.startsWith('/') ? url.slice(1) : url;
49     });
50     config.precache.push('./');
51 
52     let md5 = crypto.createHash('md5');
53     md5.update(JSON.stringify(config.precache));
54     config.precacheFingerprint = md5.digest('hex');
55 
56     var configPath = path.join(dir, 'cache-config.json');
57     fs.writeFile(configPath, JSON.stringify(config), callback);
58   })
59 });
```

There is a small difference that http2-push-manifest adds / to the start of the urls which platinum-sw doesn't like so I had to map those away.

More info here: https://github.com/GoogleChrome/http2-push-manifest/issues/5

**Comment by addyosmani** [comment]
My take on H2 is that we could have s guide on specifics for how to cater for it but not yet bake in assumptions for H2 push as a default just yet. It's possible we could automate some of this setup using a --http2 flag or similar in Polytool. Interested on thoughts around this from Rob, Sam and co.

**Comment by robdodson** [comment]
Yeah I don't think we should bake in any h2 stuff yet. Polymer team is actively working on guidance but running into a number of quirks with different browser implementations. I wouldn't want us to have to try to stay on top of all that ourselves. It should come from the Polymer team in the form of official guidance on h2

**Comment by robdodson** [comment]
I'm going to suggest we close this issue and move it to https://github.com/Polymer/polymer-build
