### ISSUE TITLE
Failed to parse web animations sourcemap

### ISSUE THREAD

**Issue by motss** [PolymerElements/polymer-starter-kit#754]
Anyone come across this issue while deploying your app to Firebase? Is it only me?
Thinking of sending in a PR to fix this.

![capture](https://cloud.githubusercontent.com/assets/10607759/13840058/dfb25206-ec5a-11e5-979e-974ee49a8652.PNG)

## Expected outcome
Open webpage after running `gulp && firebase deploy` and the page loads successfully without any issue and no error message is thrown at the Dev Tools' console.

## Actual outcome
Vulcanized `elements.html`, `app.js`, etc are successfully downloaded and the page loads without any issue but the error message `Failed to parse SourceMap` appears at the Dev Tools' console.

## Steps to reproduce the issue
- Run `gulp && firebase deploy`
- Open webpage after deploy is done.
- Open Dev Tools' console and you can find the error message `Failed to parse SourceMap` as shown in the image above.

## Additional info
- Only vulcanizing all files will cause this issue on Firebase. 
- However, running `gulp` or `gulp serve:dist` locally will not see this issue.
- This ONLY happens to Web Animations.

**Comment by robdodson** [comment]
Haven't seen that one before. Seems like a firebase bug

**Comment by motss** [comment]
@robdodson Oh really? I've been seeing this error for quite a long time and always thought that I messed up something in the build process.

**Comment by robdodson** [comment]
maybe? i thought that output was something you saw while deploying to firebase. Do you see the same error while running the local server with `gulp serve`?

**Comment by motss** [comment]
@robdodson Sorry my bad. I've updated a much clearer description of the issue.

**Comment by robdodson** [comment]
@davideast does firebase hosting support serving sourcemaps?

**Comment by MrBrightside29** [comment]
Same problem here after deploying to Firebase hosting

**Comment by lucasfrib** [comment]
Same problem, Firebase hosting to.

**Comment by robdodson** [comment]
Hm @mbleigh or @davideast have either of you seen problems with deploying sourcemaps to firebase hosting?

**Comment by mbleigh** [comment]
I haven't seen this one before. Can someone give me a public URL or minimum repro of the problem? May be a missing mime type.

**Comment by motss** [comment]
@mbleigh @robdodson @MrBrightside29 @lucasfrib 

Here's the link just down below where you can see the repro I created and deployed to Firebase:
https://polymerimation.firebaseapp.com/

Just in case, here's the steps if a link is not enough.
### Steps:
1. `git clone git@github.com:PolymerElements/polymer-starter-kit.git` to download `polymer-starter-kit`.
2. `cd` to the `polymer-starter-kit` directory and run `npm install && bower install` in the terminal to install all the dependencies.
3. Add web animations by following this [adding page transition recipe](https://github.com/PolymerElements/polymer-starter-kit/blob/master/docs/neon-animated-pages.md).
4. After that is to deploy the webapp to Firebase by just following this [deploy to Firebase recipe](https://github.com/PolymerElements/polymer-starter-kit/blob/master/docs/deploy-to-firebase-pretty-urls.md).
5. At this step, the webapp should be successfully deployed to Firebase. Visit the site and open the Chrome Dev Tool if you're using Chrome. From there you can find the `Failed to parse sourcemap` error message.

Hope these explained everything you need for this problem.

**Comment by mbleigh** [comment]
"Failing to parse" in this case is a bit of a misnomer - the file just isn't there there. The content at https://polymerimation.firebaseapp.com/elements/web-animations-next-lite.min.js.map is the `index.html` content of the app (as caused by the `**` rewrite).

My guess is that the source map isn't being created, isn't being copied to the right directory in `dist`, or isn't being deployed to Firebase. You might try updating your `rewrites` in `firebase.json` to:

```
"rewrites": [
  {
    "source": "!{/bower_components,/elements}/**",
    "destination": "/index.html"
  }
]
```

This will prevent weird 404-as-200 confusing errors.

**Comment by motss** [comment]
@mbleigh Thanks for the clarification. It did work after changing the `rewrites`.
@robdodson How about updating the current `Deploy to Firebase recipe` with this new configuration?

**Comment by robdodson** [comment]
@motss Would you be interested in throwing together a PR for it?

**Comment by motss** [comment]
@robdodson Sure.

**Comment by motss** [comment]
@robdodson Made changes to affected files. #768

**Comment by lucasfrib** [comment]
hey @motss ,
did you changed something in the step 3 (animateio recipe) of the repro that you created?
looks like that is a change in the height of papper-material... tks.

**Comment by motss** [comment]
@lucasfrib Hope that helped. [Here's the diff.](https://github.com/PolymerElements/polymer-starter-kit/commit/c3e22698476ef2e8b6e2254788debf013eca040d#diff-f054aaffec64c24ea16c8c634b8c0360R72)

**Comment by MrBrightside29** [comment]
After resolving this error in Chrome updating my firebase.json to what @mbleigh said, Safari still won't load the page with a 404. 
![img_20160408_130011](https://cloud.githubusercontent.com/assets/6217462/14382261/b2d2eed8-fd8c-11e5-9ac6-7577dfd14e19.jpg)

Any help would be appreciated. Thanks.
