### ISSUE TITLE
Toolbar gets stuck when scrolling up and down back and forth on Chrome Android

### ISSUE THREAD

**Issue by NicolasRannou** [PolymerElements/polymer-starter-kit#759]
Toolbar gets stuck when scrolling up and down back and forth on Chrome Android.

## Expected outcome

The toolbar should never get stuck.

## Actual outcome

The toolbar gets stuck when minimize the second time.

## Steps to reproduce
Android 6.0
Chrome
(It works on Firefox)

You can reproduce it with: https://polymerelements.github.io/polymer-starter-kit/

1- Scroll down the page slowly to minimize the toolbar.
2- Scroll up slowly to maximize it
3- Scroll down again slowly to minimize it.
The toolbar gets stuck at some point and doesn't fully minimize.
No errors in the console... I couldn't reproduce with the paper toolbar element.

![screen shot 2016-03-18 at 9 20 22 am](https://cloud.githubusercontent.com/assets/214063/13872390/b304efee-ecea-11e5-8873-2ab634d9f26a.png)

**Comment by robdodson** [comment]
Seems related to https://github.com/PolymerElements/polymer-starter-kit/issues/756

**Comment by robdodson** [comment]
Closing. See #756
