### ISSUE TITLE
Error Installing Deps Linux

### ISSUE THREAD

**Issue by danielhickman** [PolymerElements/polymer-starter-kit#76]
I run `sudo npm run deps` and I get a bunch of warns in the process including 5 optional deps failed and 
```
npm WARN package.json polymer-starter-kit@0.0.0 No repository field.
npm WARN engine imagemin@3.2.0: wanted: {"node":">=0.10.0","npm":">=2.1.5"} (current: {"node":"0.10.38","npm":"1.4.28"})
```

**Debug Log:**
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'deps' ]
2 info using npm@1.4.28
3 info using node@v0.10.38
4 verbose node symlink /usr/bin/node
5 verbose run-script [ 'predeps', 'deps', 'postdeps' ]
6 info predeps polymer-starter-kit@0.0.0
7 info deps polymer-starter-kit@0.0.0
8 verbose unsafe-perm in lifecycle true
9 info polymer-starter-kit@0.0.0 Failed to exec deps script
10 error polymer-starter-kit@0.0.0 deps: `npm install -g gulp && npm install -g bower && npm install && bower install`
10 error Exit status 47
11 error Failed at the polymer-starter-kit@0.0.0 deps script.
11 error This is most likely a problem with the polymer-starter-kit package,
11 error not with npm itself.
11 error Tell the author that this fails on your system:
11 error     npm install -g gulp && npm install -g bower && npm install && bower install
11 error You can get their info via:
11 error     npm owner ls polymer-starter-kit
11 error There is likely additional logging output above.
12 error System Linux 3.18.5-x86_64-linode52
13 error command "/usr/bin/node" "/usr/bin/npm" "run" "deps"
14 error cwd /var/www/materialcolorize.com/public_html
15 error node -v v0.10.38
16 error npm -v 1.4.28
17 error code ELIFECYCLE
18 verbose exit [ 1, true ]
```

I run a Ubuntu 14.04.2 VPN server with no updates needing to be made. I extracted the polymer-starter-kit-1.0.0 into /var/www/materialcolorize.com/public_html/ (where the virtual host has document root listed) Plain HTML files work fine in that folder, but after the errors, it just shows me the Index Of: apache2 default.

**Comment by addyosmani** [comment]
Could you do me a favour? Can you try running `npm install -g gulp && npm install -g bower && npm install && bower install` directly inside the root folder and see if that works? I've seen a number of people run into issues with the npm deps script, so I've updated master to drop using it.

**Comment by danielhickman** [comment]
Document root or server root (`/var/www/[website]/public_html/` or `/`)

**Comment by addyosmani** [comment]
Sorry for not being clear. I meant the root of your Polymer Starter Kit download (so, cd `polymer-starter-kit` or the extracted directory where you put the project).

**Comment by danielhickman** [comment]
Ah okay, thought so. I got this instead. I assume I ave to login as root instead of using sudo. I'll try that too.

```
npm ERR! Error: EACCES, unlink '/usr/bin/bower'
npm ERR!  { [Error: EACCES, unlink '/usr/bin/bower'] errno: 3, code: 'EACCES', path: '/usr/bin/bower' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 4.0.4-x86_64-linode57
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "-g" "bower"
npm ERR! cwd /var/www/materialcolorize.com/public_html
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! path /usr/bin/bower
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, unlink '/usr/bin/bower'
npm ERR! error rolling back Error: EACCES, unlink '/usr/bin/bower'
npm ERR! error rolling back  { [Error: EACCES, unlink '/usr/bin/bower'] errno: 3, code: 'EACCES', path: '/usr/bin/bower' }
npm ERR! not ok code 0
```

**Comment by danielhickman** [comment]
In root:
Five optional deps failed
```
ERR! EEXIST, open '/root/.npm/f24fb369-adable-stream-1-0-33-package-tgz.lock'
File exists: /root/.npm/f24fb369-adable-stream-1-0-33-package-tgz.lock
Move it away, and try again.

npm ERR! System Linux 4.0.4-x86_64-linode57
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /var/www/materialcolorize.com/public_html
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! path /root/.npm/f24fb369-adable-stream-1-0-33-package-tgz.lock
npm ERR! code EEXIST
npm ERR! errno 47
npm ERR! not ok code 0
```

There is no file or dir at `/root/.npm/f24fb369-adable-stream-1-0-33-package-tgz.lock`

**Comment by samcarecho** [comment]
@addyosmani  @danielhickman I also run into deps install problem on ubuntu 14.04, but telated to bower execution using sudo.

I solved it by modifying the following code on package.json:
from:
```
"scripts": {
    "deps": "npm install -g gulp && npm install -g bower && npm install && bower install"
  }
```

to:
```
"scripts": {
    "deps": "npm install gulp && npm install bower && npm install && bower install"
  }
```

And then running "npm run deps" (without sudo). it worked for me. Every deps were installed and I'm running the project without a single problem. Although I'm not sure if there are bad consequences on not installing gulp and bower globally.

**Comment by danielhickman** [comment]
@samcarecho Were you root when you executed it without sudo?

**Comment by samcarecho** [comment]
@danielhickman 

it seems as it's not a good idea to run deps install as root, as by default Bower won't run as root or sudoer.


Try installing the deps using o common user and read the note that I added to my last post.

**Comment by danielhickman** [comment]
@samcarecho 
Hmm I don't think I can run it in that directory. Is there any issues if I run it in /home/daniel and cp it to /var/www/[website] without any issues?

**Comment by samcarecho** [comment]
@danielhickman  Develop on /home/daniel, always.

Then build your project and copy what's inside /dist to /www.

**Comment by samcarecho** [comment]
If I'm not wrong, you can also set the server raised by gulp (gulp serve) to be reachable from outside, so you will not have to build and publish to apache's www to be able to preview.

**Comment by danielhickman** [comment]
`npm install -g gulp && npm install -g bower && npm install && bower install` Won't run without sudo or root
`npm install gulp && npm install bower && npm install && bower install` Won't work.

I've tried both in `/home/daniel` and `/var/www`

They both result in the same (or similar in case of being root) as https://github.com/PolymerElements/polymer-starter-kit/issues/76#issuecomment-107122478

I'm going to try to do the chown but I don't think that will help with the issues

**Comment by samcarecho** [comment]
Try chown on the .npm directory that lives on the root of your normal user
home directory and then run "npm install gulp && npm install bower && npm
install && bower install"  (without the -g). It worked for me. ;)

**Comment by danielhickman** [comment]
mdc = the test dir
Chowned the .npm dir, chwoned and removed write protection on mdc

Ran without sudo or the `-g`s `npm install gulp && npm install bower && npm install && bower install`
It warned about Polymer, not using `-g`, and a bunch of deps.

**Warns:**
```
npm WARN package.json polymer-starter-kit@0.0.0 No repository field.

npm WARN package.json polymer-starter-kit@0.0.0 No repository field.
npm WARN prefer global bower@1.4.1 should be installed with -g

npm WARN package.json polymer-starter-kit@0.0.0 No repository field.
npm WARN engine imagemin@3.2.0: wanted: {"node":">=0.10.0","npm":">=2.1.5"} (current: {"node":"0.10.38","npm":"1.4.28"})

npm WARN optional dep failed, continuing fsevents@0.3.6

npm WARN optional dep failed, continuing imagemin-gifsicle@4.1.0
npm WARN optional dep failed, continuing imagemin-optipng@4.2.0
npm WARN optional dep failed, continuing imagemin-jpegtran@4.1.0
```

**Error:**
```
File exists: /home/daniel/.npm/9dc86f75-adable-stream-1-0-33-package-tgz.lock
Move it away, and try again.

npm ERR! System Linux 4.0.4-x86_64-linode57
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/daniel/mdc
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! path /home/daniel/.npm/9dc86f75-adable-stream-1-0-33-package-tgz.lock
npm ERR! code EEXIST
npm ERR! errno 47
npm ERR! not ok code 0
```

**Full output:**
```
daniel@beth:~/mdc$ npm install gulp && npm install bower && npm install && bower install
npm WARN package.json polymer-starter-kit@0.0.0 No repository field.
gulp@3.8.11 node_modules/gulp
├── pretty-hrtime@0.2.2
├── interpret@0.3.10
├── deprecated@0.0.1
├── archy@1.0.0
├── tildify@1.0.0 (user-home@1.1.1)
├── minimist@1.1.1
├── v8flags@2.0.5 (user-home@1.1.1)
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)
├── orchestrator@0.3.7 (stream-consume@0.1.0, sequencify@0.0.7, end-of-stream@0.1.5)
├── liftoff@2.1.0 (extend@2.0.1, rechoir@0.6.1, flagged-respawn@0.3.1, resolve@1.1.6, findup-sync@0.2.1)
├── gulp-util@3.0.5 (beeper@1.0.0, array-differ@1.0.0, array-uniq@1.0.2, object-assign@2.0.0, lodash._reescape@3.0.0, lodash._reevaluate@3.0.0, lodash._reinterpolate@3.0.0, replace-ext@0.0.1, chalk@1.0.0, vinyl@0.4.6, lodash.template@3.6.1, multipipe@0.1.2, through2@0.6.5, dateformat@1.0.11)
├── vinyl-fs@0.3.13 (graceful-fs@3.0.7, strip-bom@1.0.0, defaults@1.0.2, vinyl@0.4.6, mkdirp@0.5.1, through2@0.6.5, glob-stream@3.1.18, glob-watcher@0.0.6)
└── semver@4.3.5
npm WARN package.json polymer-starter-kit@0.0.0 No repository field.
npm WARN prefer global bower@1.4.1 should be installed with -g
bower@1.4.1 node_modules/bower
├── is-root@1.0.0
├── junk@1.0.1
├── stringify-object@1.0.1
├── user-home@1.1.1
├── chmodr@0.1.0
├── rimraf@2.3.4
├── abbrev@1.0.7
├── archy@1.0.0
├── opn@1.0.2
├── bower-logger@0.2.2
├── bower-endpoint-parser@0.2.2
├── graceful-fs@3.0.7
├── lru-cache@2.6.4
├── lockfile@1.0.1
├── nopt@3.0.2
├── retry@0.6.1
├── tmp@0.0.24
├── request-progress@0.3.1 (throttleit@0.0.2)
├── q@1.4.1
├── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.0.1, supports-color@1.3.1, strip-ansi@2.0.1, has-ansi@1.0.3)
├── which@1.1.1 (is-absolute@0.1.7)
├── shell-quote@1.4.3 (array-filter@0.0.1, array-reduce@0.0.0, array-map@0.0.0, jsonify@0.0.0)
├── semver@2.3.2
├── p-throttler@0.1.1 (q@0.9.7)
├── fstream@1.0.6 (inherits@2.0.1)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── bower-json@0.4.0 (intersect@0.0.3, deep-extend@0.2.11, graceful-fs@2.0.3)
├── promptly@0.2.0 (read@1.0.6)
├── fstream-ignore@1.0.2 (inherits@2.0.1, minimatch@2.0.8)
├── tar-fs@1.5.1 (pump@1.0.0, tar-stream@1.1.5)
├── glob@4.5.3 (inherits@2.0.1, once@1.3.2, inflight@1.0.4, minimatch@2.0.8)
├── insight@0.5.3 (object-assign@2.0.0, lodash.debounce@3.1.0, async@0.9.2, os-name@1.0.3, tough-cookie@0.12.1)
├── decompress-zip@0.1.0 (mkpath@0.1.0, touch@0.0.3, readable-stream@1.1.13, binary@0.3.0)
├── request@2.53.0 (caseless@0.9.0, aws-sign2@0.5.0, forever-agent@0.5.2, stringstream@0.0.4, oauth-sign@0.6.0, tunnel-agent@0.4.0, isstream@0.1.2, json-stringify-safe@5.0.1, node-uuid@1.4.3, qs@2.3.3, combined-stream@0.0.7, form-data@0.2.0, mime-types@2.0.12, http-signature@0.10.1, bl@0.9.4, tough-cookie@1.2.0, hawk@2.3.1)
├── github@0.2.4 (mime@1.3.4)
├── cardinal@0.4.4 (ansicolors@0.2.1, redeyed@0.4.4)
├── bower-registry-client@0.3.0 (request-replay@0.2.0, graceful-fs@2.0.3, rimraf@2.2.8, lru-cache@2.3.1, async@0.2.10, mkdirp@0.3.5, request@2.51.0)
├── update-notifier@0.3.2 (is-npm@1.0.0, string-length@1.0.0, latest-version@1.0.0, semver-diff@2.0.0)
├── mout@0.11.0
├── bower-config@0.6.1 (osenv@0.0.3, graceful-fs@2.0.3, optimist@0.6.1, mout@0.9.1)
├── configstore@0.3.2 (object-assign@2.0.0, xdg-basedir@1.0.1, osenv@0.1.1, uuid@2.0.1, js-yaml@3.3.1)
├── handlebars@2.0.0 (optimist@0.3.7, uglify-js@2.3.6)
└── inquirer@0.8.0 (figures@1.3.5, mute-stream@0.0.4, ansi-regex@1.1.1, through@2.3.7, readline2@0.1.1, chalk@0.5.1, lodash@2.4.2, cli-color@0.3.3, rx@2.5.2)
npm WARN package.json polymer-starter-kit@0.0.0 No repository field.
npm WARN engine imagemin@3.2.0: wanted: {"node":">=0.10.0","npm":">=2.1.5"} (current: {"node":"0.10.38","npm":"1.4.28"})

> spawn-sync@1.0.11 postinstall /home/daniel/mdc/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-wrapper/node_modules/bin-check/node_modules/spawn-sync
> node postinstall

npm WARN optional dep failed, continuing fsevents@0.3.6

> spawn-sync@1.0.11 postinstall /home/daniel/mdc/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-wrapper/node_modules/bin-check/node_modules/spawn-sync
> node postinstall


> spawn-sync@1.0.11 postinstall /home/daniel/mdc/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-wrapper/node_modules/bin-check/node_modules/spawn-sync
> node postinstall


> ws@0.5.0 install /home/daniel/mdc/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)


> ws@0.5.0 install /home/daniel/mdc/node_modules/web-component-tester/node_modules/socket.io/node_modules/engine.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)


> ws@0.4.31 install /home/daniel/mdc/node_modules/browser-sync/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

|
> sauce-connect-launcher@0.9.3 postinstall /home/daniel/mdc/node_modules/web-component-tester/node_modules/wct-sauce/node_modules/sauce-connect-launcher
> node scripts/install.js


> ws@0.4.31 install /home/daniel/mdc/node_modules/web-component-tester/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)


> phantomjs@1.9.17 install /home/daniel/mdc/node_modules/gulp-uncss/node_modules/uncss/node_modules/phridge/node_modules/phantomjs
> node install.js

Download already available at /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
Extracting tar contents (via spawned process)
Removing /home/daniel/mdc/node_modules/gulp-uncss/node_modules/uncss/node_modules/phridge/node_modules/phantomjs/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2-extract-1433047490712/phantomjs-1.9.8-linux-x86_64 -> /home/daniel/mdc/node_modules/gulp-uncss/node_modules/uncss/node_modules/phridge/node_modules/phantomjs/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /home/daniel/mdc/node_modules/gulp-uncss/node_modules/uncss/node_modules/phridge/node_modules/phantomjs/lib/phantom/bin/phantomjs
npm WARN optional dep failed, continuing imagemin-gifsicle@4.1.0
npm WARN optional dep failed, continuing imagemin-optipng@4.2.0
npm WARN optional dep failed, continuing imagemin-jpegtran@4.1.0

> wct-sauce@1.6.0 postinstall /home/daniel/mdc/node_modules/web-component-tester/node_modules/wct-sauce
> node scripts/postinstall.js

Prefetching the Sauce Connect binary.
Missing Sauce Connect local proxy, downloading dependency
This will only happen once.
Downloading 3.42MB
Unzipping sc-4.3.5-linux.tar.gz
Removing sc-4.3.5-linux.tar.gz
Sauce Connect downloaded correctly
Removing /home/daniel/mdc/node_modules/web-component-tester/node_modules/wct-sauce/node_modules/sauce-connect-launcher/sc/sc-4.3.5-linux.tar.gz
\
> wct-local@1.4.1 postinstall /home/daniel/mdc/node_modules/web-component-tester/node_modules/wct-local
> node scripts/postinstall.js

----------
selenium-standalone installation starting
----------

---
selenium install:
from: http://selenium-release.storage.googleapis.com/2.45/selenium-server-standalone-2.45.0.jar
to: /home/daniel/mdc/node_modules/web-component-tester/node_modules/wct-local/node_modules/selenium-standalone/.selenium/selenium-server/2.45.0-server.jar
---
chrome install:
from: http://chromedriver.storage.googleapis.com/2.15/chromedriver_linux64.zip
to: /home/daniel/mdc/node_modules/web-component-tester/node_modules/wct-local/node_modules/selenium-standalone/.selenium/chromedriver/2.15-x64-chromedriver
---
File from http://chromedriver.storage.googleapis.com/2.15/chromedriver_linux64.zip has already been downloaded
---
File from http://selenium-release.storage.googleapis.com/2.45/selenium-server-standalone-2.45.0.jar has already been downloaded


-----
selenium-standalone installation finished
-----

> web-component-tester@3.1.3 postinstall /home/daniel/mdc/node_modules/web-component-tester
> node scripts/postinstall.js

Fetching bower dependencies for the WCT client to /home/daniel/mdc/node_modules/web-component-tester/bower_components
Fetched bower packages: stacky, chai, sinonjs, async, mocha, lodash, sinon-chai
npm ERR! EEXIST, open '/home/daniel/.npm/9dc86f75-adable-stream-1-0-33-package-tgz.lock'
File exists: /home/daniel/.npm/9dc86f75-adable-stream-1-0-33-package-tgz.lock
Move it away, and try again.

npm ERR! System Linux 4.0.4-x86_64-linode57
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/daniel/mdc
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! path /home/daniel/.npm/9dc86f75-adable-stream-1-0-33-package-tgz.lock
npm ERR! code EEXIST
npm ERR! errno 47
npm ERR! not ok code 0
```

**Comment by samcarecho** [comment]
Try removing the file "/home/daniel/.npm/9dc86f75-
adable-stream-1-0-33-package-tgz.lock" and running "npm install gulp && npm
install bower && npm install && bower install" again.


I was also asked to remove a similar lock file.

**Comment by danielhickman** [comment]
I tried, but it's not there. `find` spit out a bunch of lines and said not found (I don't know if I did that right) and  I tried manually too

**Comment by samcarecho** [comment]
if it's not there, then try running

"npm install gulp && npm install bower && npm install && bower install"

again to see if the lock file error happens again.

**Comment by danielhickman** [comment]
Alphabetically there is only:
`9ca3684e--download-node-modules-url-regex.lock`
`9df42353-er-sync-node-modules-serve-index.lock`

It skips right over.

Also, that's been the error for all like 10 times I've executed it with the right permissions, I think something's wrong with the script. My buddy @crutchcorn can't do it either, locally or on his server.

**Comment by addyosmani** [comment]
Can you try (if not already) running `npm cache clean` before running "npm install gulp && npm install bower && npm install && bower install"?

**Comment by danielhickman** [comment]
Same error @addyosmani

**Comment by arthurvr** [comment]
> Note: don't use sudo.

+1. It's never a good idea [and Bower even explicitly blocks it.](https://github.com/bower/bower/blob/58a7de3136e32cebd1d7ecdc37c7eefcaaadab2d/lib/util/rootCheck.js) Instead, fix your local setup :)

**Comment by danielhickman** [comment]
@arthurevans I've tried with and without many times. The `-g` seems to force me, but I didn't use them the last time.

**Comment by danielhickman** [comment]
Can confirm, that lock file is from that script, sudo, root, or not. It's not working for my buddies because of a similar issue. I've asked around to a few other professional linux programmers and they suggested that the script or NPM is to blame. I'm stuck on this if I am to use this version of the kit.

If this can't be resolved, is there any downsides to the no tools version?

**Comment by arthurvr** [comment]
> I've tried with and without many times. The -g seems to force me, but I didn't use them the last time.

I know, I read your comments too :) The thing is just that the only fact that you have to use `sudo` (or similar tweaking) indicates potential problems with your local setup. 

> If this can't be resolved, is there any downsides to the no tools version?

Yes, that you've got no tools then :)

**Comment by BigDataPop** [comment]
@arthurvr is right, it seems to be a problem with your local setup. I was having the same issue and ran the following commands:

sudo chown -R $USER ~/.npm
sudo chown -R $USER /usr/local/lib/node_modules

and all went well. Also, ensure NPM is updated to latest version.

Cheers!

**Comment by kraz** [comment]
This guide might be in help: 

[Install npm packages globally without sudo on OS X and Linux](https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md)

**Comment by arthurvr** [comment]
Yup. That's the right way to fix these kind of errors. I would love anyone to confirm but I think this is just an issue with your local setup.

**Comment by danielhickman** [comment]
*sigh*
I followed the guide, reuploaded the package, chowned everything in my home dir, and there wasn't anything in `/usr/local/lib/node_modules`.

I can't find out what's wrong with my setup.

**Comment by danielhickman** [comment]
https://github.com/npm/npm/issues/6309 shows others are having this issue left right and center. I'll look into what they are suggesting there.

**Comment by samcarecho** [comment]
@BigDataPop,

Are you sure that "sudo chown -R $USER /usr/local/lib/node_modules" is a good practice?

**Comment by samcarecho** [comment]
@danielhickman 

Try this: 
[NodeJS on Ubuntu](https://github.com/PolymerElements/polymer-starter-kit/wiki/NodeJS-Installation-on-Ubuntu)

After reinstalling NodeJS, go to the starter-kit root and delete "bower_components" and "node_modules".

After deleting both directories, run the following commands inside the starter-kit root, one per time:

```sh
npm install gulp && npm install bower && npm install
```

```sh
bower install
```

I hope this helps you.

**Comment by zmoshansky** [comment]
@danielhickman  

I also had this issue (Fedora 22), the best solution seemed to be option 2 in this guide (from npm). I also think that it's weird (hacky?) to change permissions on a /usr/local/* directory. 

https://docs.npmjs.com/getting-started/fixing-npm-permissions#option-2-change-npm-s-default-directory-to-another-directory

**Comment by samcarecho** [comment]
@zmoshansky 

Hacky ([source](http://en.wiktionary.org/wiki/hacky)):
(computing, informal) Using, or characterised by, hacks: poorly designed workarounds.


I don't feel comfortable messing with the /usr/local/* permissions.
If nothing else works, I would also take approach 2 of creating a node-global directory under $HOME.

**Comment by addyosmani** [comment]
Has anyone had any better luck using `npm@next` (per the linked to npm thread) to workaround these issues? Once we've got a solution that a few folks find works here, we'll make sure to link to it from the readme. I'm sorry you've had to deal with any frustrating setup issues to get through this.

**Comment by danielhickman** [comment]
Sorry I've not been able to do this just yet because of my computer needing
some TLC.

**Comment by steinhoff1989** [comment]
Had the same error with "file exists". Looks like a npm bug.

Please check the npm Version you are on. (npm -v)
I have been on 1.4.28 like @danielhickman, This version has a bug you are fighting with discribed here:
https://github.com/npm/npm/issues/6309

After updating npm to 2.11.1 "npm run deps" finished without errors.

Be carefull if you are on Windows and installed npm via node in "C:\Program Files\". Updating npm by calling "npm install npm@2.11.0". This will install npm in "%AppData%\npm", but your cmd will still use the old npm version, as long as you delete it from "C:\Program Files\nodejs" like described here:
https://github.com/npm/npm/issues/6309#issuecomment-67549380

So please chekc you npm version, before running "npm run deps"!

**Comment by addyosmani** [comment]
I think we've reached a point where the advice offered by @steinhoff1989 above should be the go-to for solving this. Would anyone be able to confirm following this (updating to 2.11.1) resolves the issue for them before we close this and link to a reliable answer?

**Comment by addyosmani** [comment]
We've since documented the workarounds required here in the README. I've also verified running through a fresh install and following the guidance in the FAQ that this is sufficient to get setup so closing this issue. If the notes provided aren't able to get someone up and running, let us know and we'll explore what other advice needs to be added.

**Comment by danielhickman** [comment]
Thank you guys very much! I've been able to get this working. Sorry about not being able to check for a while.

**Comment by sajjadmurtaza49** [comment]
➜  my-project  sudo npm install npm@2.11.0 && npm install -g gulp && npm install -g bower && npm install && bower install
npm@2.11.0 node_modules/npm
npm ERR! Linux 3.13.0-24-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "gulp"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! path /usr/bin/gulp
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, unlink '/usr/bin/gulp'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, unlink '/usr/bin/gulp'] errno: -13, code: 'EACCES', path: '/usr/bin/gulp' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
npm ERR! error rolling back Error: EACCES, unlink '/usr/bin/gulp'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EACCES, unlink '/usr/bin/gulp'] errno: -13, code: 'EACCES', path: '/usr/bin/gulp' }

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sajad/p_projects/my-project/npm-debug.log
