### ISSUE TITLE
ERR_FILE_EXISTS - Reload Error

### ISSUE THREAD

**Issue by bkawk** [PolymerElements/polymer-starter-kit#760]
After finding errors when reloading, even when hard refresh  and clearing the cache on this page https://polymerstartkithb.firebaseapp.com/users/Addy  

I made a number of tests, with hash bangs on and off, service workers on and off, with firebase hosting redirects. Each test was uploaded with a fresh download of the starter kit.

What combinations of service workers and hashbangs should work? 

- I'm using NPM version 3.3.9
- Chrome Version 49.0.2623.87 (64-bit)

Does this relate to: https://bugs.chromium.org/p/chromium/issues/detail?id=541797

TEST 1
=============================================
https://polymerstartkit.firebaseapp.com/
- hash bangs true
- service workers disabled

NO ERROR - IM HAPPY

TEST 2
=============================================
https://polymerstartkithb.firebaseapp.com
hashbang: false
- service workers disabled

- base href="/" added to header of index

- added to firebase.json :
  "rewrites": [ {
    "source": "**",
    "destination": "/index.html"
  } ]

NO ERROR - IM HAPPY

TEST 3
=============================================
https://polymerstartkit-sw.firebaseapp.com/
hashbang: true
- service workers enabled
- 'vulcanize', 'cache-config', uncommented in gulp,
- Uncomment Service Worker code in index.html
- Uncomment Service Worker code in elements.html

ERORR ON RELOAD : https://polymerstartkit-sw.firebaseapp.com/#!/users/Addy

/sw-import.js?baseURI=https%3A%2F%2Fpolymerstartkit-sw.firebaseapp.com%2Fbo…ingerprint=c546b3ce132d015b719d026ed69466c1&skipWaiting=true&version=1.0:1 GET https://polymerstartkit-sw.firebaseapp.com/sw-import.js?baseURI=https%3A%2F…eFingerprint=c546b3ce132d015b719d026ed69466c1&skipWaiting=true&version=1.0 net::ERR_FILE_EXISTS

TEST 4
=============================================
https://polymerstartkit-swhb.firebaseapp.com/
hashbang: false
- service workers enabled

- 'vulcanize', 'cache-config', uncommented in gulp,
- Uncomment Service Worker code in index.html
- Uncomment Service Worker code in elements.html

- base href="/" added to header of index
- added to firebase.json: 
  "rewrites": [ {
    "source": "**",
    "destination": "/index.html"
  } ]

ERROR ON RELOAD : GET https://polymerstartkit-swhb.firebaseapp.com/sw-import.js?baseURI=https%3A%…w%2Fbootstrap%2Fsw-toolbox-setup.js&precache=&skipWaiting=true&version=1.0 net::ERR_FILE_EXISTS

**Comment by robdodson** [comment]
> ERROR ON RELOAD : GET https://polymerstartkit-swhb.firebaseapp.com/sw-import.js?baseURI=https%3A%…w%2Fbootstrap%2Fsw-toolbox-setup.js&precache=&skipWaiting=true&version=1.0 net::ERR_FILE_EXISTS

This is a quirk of service worker. Bug has been filed in Chrome. Nothing is actually wrong, it's just over reporting https://bugs.chromium.org/p/chromium/issues/detail?id=541797

**Comment by dandv** [comment]
I think I see the same behavior exactly after git clone and following the instructions on enabling service worker.

@bkawk - can you reproduce that?

**Comment by robdodson** [comment]
@dandv This always occurs, it's just service worker reporting that the exact same service worker was already in place
