### ISSUE TITLE
gulp-minify-css is deprecated in favor of gulp-clean-css

### ISSUE THREAD

**Issue by targeter21** [PolymerElements/polymer-starter-kit#761]
While running npm install on the latest PSK for master, I noticed the following message:

`npm WARN deprecated gulp-minify-css@1.2.4: Please use gulp-clean-css`

I saw that there were several issues related to deprecated npm components, but the ones I found all seem to be closed without fixing this issue.

**Comment by targeter21** [comment]
I created PR #762 to address this.

**Comment by robdodson** [comment]
Closing. See https://github.com/PolymerElements/polymer-starter-kit/pull/762
