### ISSUE TITLE
In firefox javascript error when using webcomponents.min.js instead of lite version

### ISSUE THREAD

**Issue by isdmac** [PolymerElements/polymer-starter-kit#763]
### Description
i am using the latest release version 1.3 . this works ok in chrome but not in firefox

in the debug console i can see the error as 

TypeError: str is undefined
if (index < str.length) {

this error occurred in  bower_components/page/page.js on line 800 

### Expected outcome

page should load fully .

### Actual outcome

page loads stops unexpectedly 

### Browsers Affected

- [ ] Chrome
- [* ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by robdodson** [comment]
yeah page.js has problems with shadow dom (in particular, if you have links in shadow dom it won't be able to delegate their click events). Not sure if that's the specific problem here and we have a new router coming out soon which will hopefully replace page.js.

**Comment by addyosmani** [comment]
I haven't been able to reproduce this but Rob's take on it sounds about right. It's likely an SD issue. PSK2 will use carbon-route and we should be able to avoid issues like this there.

@robdodson does it make sense to keep issues like this around or close in favor of addressing in V2 in your opinion?

**Comment by robdodson** [comment]
i'm in favor of closing and addressing in v2
