### ISSUE TITLE
Automatic element import/inject?

### ISSUE THREAD

**Issue by phonicdespot** [PolymerElements/polymer-starter-kit#764]
### Automatic element import/inject?
It would be great if installing an element using Bower also dealt with adding the import into elements.html. Having to manually manage a load of HTML imports doesn't seem very sensible.

Not entirely sure how; wiredep? webpack?

Very happy to try and help if anyone thinks this is worth pursuing :)

**Comment by abdonrd** [comment]
The elements.html isn't the right place. And we can't guess where import. :confused: 

Reference: https://github.com/PolymerElements/polymer-starter-kit/issues/663

**Comment by addyosmani** [comment]
@robdodson my take on scaffolding is we should get these added as feature requests for Polytool. In this case there's always a risk of us adding too much magic. I do wonder how deterministic we could really be given elements.html doesn't jive well for errbody.

**Comment by robdodson** [comment]
elements.html is going away in psk2. And yeah this should move to polytool feature request.
