### ISSUE TITLE
Use carbon-route instead of page.js

### ISSUE THREAD

**Issue by davidwittenbrink** [PolymerElements/polymer-starter-kit#767]
Hi!

Now that `<carbon-route>` is officially in the element catalog I was wondering if there are plans to replace the current routing with it? Imo the the current page.js solution feels a bit out of place since everything else is so beautifully encapsulated into elements.
I replaced the element manually for a project and it worked like a charm.

What do you guys think?

**Comment by robdodson** [comment]
Hey David. Yeah this is being discussed over here https://github.com/PolymerElements/polymer-starter-kit/issues/653

We definitely plan to swap in carbon-route. Just haven't had a chance to get to it yet :)

**Comment by davidwittenbrink** [comment]
Sorry, didn't see this.
