### ISSUE TITLE
Can't vulcanize when iron-ajax or paper-dropdown-menu are imported

### ISSUE THREAD

**Issue by bobobo1618** [PolymerElements/polymer-starter-kit#770]
### Description
When `iron-ajax` or `paper-dropdown-menu` are imported from an import of `elements.html`, Vulcanize fails.

### Expected outcome

Gulp builds succeed and loading `index.html` from the `dist` directory results in a working page.

### Actual outcome

Gulp fails with the following errors:
```
ERROR finding /private/tmp/test/polymer-starter-kit-1.3.0/app/elements/bower_components/bower_components/promise-polyfill/Promise.js
ERROR finding /private/tmp/test/polymer-starter-kit-1.3.0/app/elements/bower_components/bower_components/bower_components/bower_components/bower_components/bower_components/web-animations-js/web-animations-next-lite.min.js
```

I've reproduced this on both a Mac (OS X 10.11.3) and a Linux server (Fedora 23).

### Steps to reproduce

```bash
#!/bin/bash
wget "https://github.com/PolymerElements/polymer-starter-kit/releases/download/v1.3.0/polymer-starter-kit-1.3.0.zip"
unzip polymer-starter-kit-1.3.0.zip
cd polymer-starter-kit-1.3.0
npm install
bower install
mkdir app/elements/test-element
cat > app/elements/test-element/test-element.html <<EOF
<link rel="import" href="../../bower_components/polymer/polymer.html">
<link rel="import" href="../../bower_components/iron-ajax/iron-ajax.html">
<link rel="import" href="../../bower_components/paper-dropdown-menu/paper-dropdown-menu.html">

<dom-module is="test-element">
    <template>
    </template>
    <script>
        Polymer({
            is: "test-element"
        });
    </script>
</dom-module>
EOF
echo '<link rel="import" href="test-element/test-element.html">' >> app/elements/elements.html
gulp
```

**Comment by bobobo1618** [comment]
I'll add that this is reproducible with Git master as well and that running `bower install --save PolymerElements/iron-ajax` before building makes no difference.

**Comment by bobobo1618** [comment]
And in honor of https://github.com/PolymerElements/polymer-starter-kit/issues/621 I'll also add that `bower cache clean` makes no difference either. Nor does upgrading to Node v4.

**Comment by robdodson** [comment]
@bobobo1618 apparently this is a recent bug in vulcanize. Team is working on a fix as we speak

**Comment by robdodson** [comment]
Temporary fix `npm uninstall -g vulcanize && npm cache clean vulcanize && npm install -g vulcanize`. We've unshipped the busted version

**Comment by bobobo1618** [comment]
Yep, that worked, thanks!
