### ISSUE TITLE
Delete old branches

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/polymer-starter-kit#773]
The PSK has very old [branches](https://github.com/PolymerElements/polymer-starter-kit/branches/all). We can delete all of them, right?

<img width="1002" alt="screen shot 2016-04-10 at 14 59 44" src="https://cloud.githubusercontent.com/assets/1007051/14410319/2f22a932-ff2d-11e5-8bb9-9dfb536b7cf0.png">

**Comment by robdodson** [comment]
yep you can delete them

**Comment by abdonrd** [comment]
Cleaned! :shower:
