### ISSUE TITLE
Problems with bower on ubuntu 15.04 (64bit)

### ISSUE THREAD

**Issue by macbroadcast** [PolymerElements/polymer-starter-kit#78]
After i cloned the starterkit from github and tweaked the package.json , i was able to install without errors, but even when i install bower manually ,  i got this error when run :

~/development/polymer-starter-kit$ gulp test:local
[06:26:48] Using gulpfile ~/development/polymer-starter-kit/gulpfile.js
[06:26:48] Starting 'wct:local'...
Starting Selenium server for local browsers
Selenium server running on port 43653
Web server running on port 38957 and serving from /home/macbroadcast/development/polymer-starter-kit/app
chrome 43                Beginning tests via http://localhost:38957/components/app/generated-index.html?cli_browser_id=0
404 GET /components/bower_components/webcomponentsjs/webcomponents.min.js
404 GET /components/bower_components/test-fixture/test-fixture-mocha.js
404 GET /components/bower_components/webcomponentsjs/webcomponents.min.js
404 GET /components/bower_components/polymer/polymer.html
404 GET /components/bower_components/test-fixture/test-fixture.html
chrome 43                ✖ Test Suite Initialization

  Polymer is not defined
    <unknown> at   <unknown> at /components/app/elements/my-greeting/my-greeting.html:32:0
    <unknown> at   <unknown> at /components/app/elements/my-greeting/my-greeting.html:43:0

chrome 43                ✖ test/my-greeting-basic.html » my-greeting tests » "before each" hook

  fixture is not defined

404 GET /components/bower_components/webcomponentsjs/webcomponents.min.js
404 GET /components/bower_components/test-fixture/test-fixture-mocha.js
404 GET /components/bower_components/polymer/polymer.html
404 GET /components/bower_components/test-fixture/test-fixture.html
chrome 43                ✖ Test Suite Initialization

  Polymer is not defined
    <unknown> at   <unknown> at /components/app/elements/my-list/my-list.html:28:0
    <unknown> at   <unknown> at /components/app/elements/my-list/my-list.html:47:0

chrome 43                ✖ test/my-list-basic.html » my-list tests » "before each" hook

  fixture is not defined

chrome 43                Tests failed: 4 failed tests

**Comment by addyosmani** [comment]
Is it possible to share a list of what got installed in your bower_components directory? `cd bower_components && ls`

**Comment by macbroadcast** [comment]
No bower_components directory in node_modules or in polymer-starter-kit root  folder :open_mouth:

**Comment by addyosmani** [comment]
It looks like there may be a step you missed during installation :) Can you `bower install` in your root folder of polymer-starter-kit and try again? That would explain some of the WCT errors.

**Comment by macbroadcast** [comment]
:laughing: thanks @addyosmani everything works as expected now
gulp test:local
[07:36:43] Using gulpfile ~/development/polymer-starter-kit/gulpfile.js
[07:36:43] Starting 'wct:local'...
Starting Selenium server for local browsers
Selenium server running on port 57343
Web server running on port 55275 and serving from /home/macbroadcast/development/polymer-starter-kit/app
chrome 43                Beginning tests via http://localhost:55275/components/app/generated-index.html?cli_browser_id=0
chrome 43                Tests passed
firefox 38               Beginning tests via http://localhost:55275/components/app/generated-index.html?cli_browser_id=1
firefox 38               Tests passed
Test run ended with great success

chrome 43 (2/0/0)                       firefox 38 (2/0/0)                    
[07:37:12] Finished 'wct:local' after 29 s
[07:37:12] Starting 'test:local'...
[07:37:12] Finished 'test:local' after 13 μs

**Comment by addyosmani** [comment]
:tada: :balloon: :star: yay!
