### ISSUE TITLE
Add polylint task to PSK2

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/polymer-starter-kit#784]
I think it would be interesting to add `polylint` as gulp task.

Opinions?

cc @robdodson @chuckh @samccone

**Comment by chuckh** [comment]
@abdonrd I agree.  It would be nice to have another tasks to run both `polylint` and the `lint` task.

Also note with polytool you can run `polylint` by doing `polytool lint ...`.

**Comment by abdonrd** [comment]
Sure! Maybe the `lint` task can run a new `eslint` (actual `lint`) and `polylint` tasks. :grin:

**Comment by addyosmani** [comment]
I agree. We're going to be delegating a lot of PSK2's tooling to Polytool most likely and it should come with a gulpfule setup that makes good use of polylint we can piggy back off :)

**Comment by robdodson** [comment]
Good news! You can just run `polymer lint` using Polymer CLI and it'll lint your project for you.
Bad news: It doesn't work well with PRPL and logs all sorts of issues right now. I don't think there's anyplace where we are actually doing anything wrong, but the linter has a bunch of false positives it logs. I'm going to close this and encourage folks to open lint issues on the [polylint repo](https://github.com/PolymerLabs/polylint)
