### ISSUE TITLE
Elements.html gets loaded twice

### ISSUE THREAD

**Issue by markovuksanovic** [PolymerElements/polymer-starter-kit#791]
### Description
Elements.html is fetched (downloaded) twice.

![image](https://cloud.githubusercontent.com/assets/52777/14494371/f79e3f96-01cd-11e6-83b4-a126666761ce.png)

### Expected outcome

Elements.html is loaded only once.

### Actual outcome

Elements.html is fetched twice!

### Live Demo
https://polymerelements.github.io/polymer-starter-kit/

### Browsers Affected
- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by samccone** [comment]
Pretty sure this is a bug in devtools right now, and things are actually not downloading twice....

cc @paulirish

**Comment by paulirish** [comment]
nope. it's a bug in Chrome.


Chrome issue. Verified with clean profile and net-internals:

![image](https://cloud.githubusercontent.com/assets/39191/14498608/03c9f720-0169-11e6-8af7-8d4c5c8b6ac1.png)


Doesn't appear to happen on first load, but does on subsequent ones. Might have something to do with the service worker

**Comment by samccone** [comment]
:+1: thx @paulirish

**Comment by ebidel** [comment]
Is there a number for the chrome bug?
