### ISSUE TITLE
The Travis build is failing during the addons stage.

### ISSUE THREAD

**Issue by fluky** [PolymerElements/polymer-starter-kit#796]
### Description
The Travis build is failing during the addons stage.  This is with an unmodified .travis.yml file.

### Expected outcome
The Travis build should pass.

### Actual outcome
The Travis build fails.

2.48s$ sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install google-chrome-stable g++-4.8
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 google-chrome-stable : Depends: lsb-base (>= 4.1) but 4.0-0ubuntu20.3 is to be installed
E: Unable to correct problems, you have held broken packages.
...
The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install google-chrome-stable g++-4.8" failed and exited with 100 during .`

### Live Demo
https://travis-ci.org/scaffold-js/scaffold-ja-website/jobs/123643507

### Steps to reproduce
1. Create a project with the polymer-starter-kit
2. Push to GitHub
3. Link Travis
4. Build

### Browsers Affected
N/A

**Comment by abdonrd** [comment]
There are already an issue (https://github.com/PolymerElements/polymer-starter-kit/issues/794) and PR (https://github.com/PolymerElements/polymer-starter-kit/pull/795) about this. :)
