### ISSUE TITLE
Make it easier for service workers to be optional

### ISSUE THREAD

**Issue by pdf** [PolymerElements/polymer-starter-kit#80]
For applications where it may not be possible to enforce the end-user (where the end-user is deploying the application) requirement of SSL deployment, or simply for those who don't want/need the extra complexity, it'd be nice if there was an easier way to disable service workers yet still sync the project (even if you're not syncing with this repo, removing chunks in half a dozen files is tedious).  This might possibly be handled by adding gulp tasks, and using gulp pre-processing to inject the SW stuff depending on which task is called, though the markup wouldn't be as clean.  Personally, I think I would prefer SW to be opt-in rather than opt-out, considering spotty browser support and added complexity.

**Comment by arthurvr** [comment]
Well, I guess if we would ever base `generator-polymer` (the yeoman generator for polymer) on PSK, that would be something to consider. It would be as easy as a checkbox, then :)

**Comment by addyosmani** [comment]
@pdf thanks for the feedback. The light version of Starter Kit (in the releaes page) doesn't include SW by default. 

I'd considered making it opt in in Starter Kit proper, but this would involve commenting out/in lines in about 4 different files (I've tried the code injection way before and it's far too fragile unfortunately) Side: I was hoping we could get more people doing offline-first by it being the default :)

Let us have a think more about how we can strike a balance between this being available without being too hard to either opt in or out. I'm not opposed to it being commented out.

@robdodson I agree that it might be useful to consider making SW support optional in the generator version of this project.

**Comment by robdodson** [comment]
re: the generator. The plan at the moment is to base it on PSK by pulling in PSK through a git submodule and using that as the template. This is so PSK can be the canonical source. If it's easy to strip out the SW bits I'm happy to add it in, maybe they could have comments around them or something to make it easier to rip them out? I'm heading out for a week on vacation but happy to take a look when I get back

**Comment by addyosmani** [comment]
I think for the V1 on the new generator, your plan sounds absolutely fine :) We may end up choosing to comment out SW support (would love it if it was still the default personally) but let's keep this issue open and see what folks think.

(also, thanks for updating the generator once again!)

**Comment by calbertts** [comment]
:+1:

**Comment by chuckh** [comment]
@robdodson regarding adding comments, would this make sense?

### index.html
```
    <!-- Service Workers -->
    <paper-toast id="caching-complete"
                 duration="6000"
                 text="Caching complete! This app will work offline.">
    </paper-toast>

    <platinum-sw-register auto-register
                          clients-claim
                          skip-waiting
                          on-service-worker-installed="displayInstalledToast">
      <platinum-sw-cache default-cache-strategy="networkFirst"
                         precache-file="precache.json">
      </platinum-sw-cache>
    </platinum-sw-register>
    <!-- endserviceworkers-->
```


### elements.html
```
<!-- Platinum elements Service Workers -->
<link rel="import" href="../bower_components/platinum-sw/platinum-sw-cache.html">
<link rel="import" href="../bower_components/platinum-sw/platinum-sw-register.html">
<!-- Platinum elements Service Workers end -->
```

**Comment by robdodson** [comment]
it may be better to use the same comments throughout:

```
<!-- begin serviceworkers -->
<!-- end serviceworkers -->
```

something like that, just so we can look for the same pattern everywhere

**Comment by arthurvr** [comment]
> `<!-- begin serviceworkers -->`

Just because we want to make it optional in the generator? That might confuse people and is honestly ugly, definitely because they don't add value for the people just using PSK without generator-polymer.

**Comment by chuckh** [comment]
How about something like this @arthurvr and @robdodson. It is consistent and provides value to PSK only users. Could reference in readme for disabling service workers.

### index.html
```
    <!-- Begin Service Workers -->
    <paper-toast id="caching-complete"
                 duration="6000"
                 text="Caching complete! This app will work offline.">
    </paper-toast>

    <platinum-sw-register auto-register
                          clients-claim
                          skip-waiting
                          on-service-worker-installed="displayInstalledToast">
      <platinum-sw-cache default-cache-strategy="networkFirst"
                         precache-file="precache.json">
      </platinum-sw-cache>
    </platinum-sw-register>
    <!-- End Service Workers -->
```

### elements.html
```
<!-- Begin Service Workers -->
<link rel="import" href="../bower_components/platinum-sw/platinum-sw-cache.html">
<link rel="import" href="../bower_components/platinum-sw/platinum-sw-register.html">
<!-- End Service Workers -->
```

**Comment by arthurvr** [comment]
> It is consistent and provides value to PSK only users.

How does that add value? It are two comments that totally make no sense if you're just an all day PSK user.

**Comment by chuckh** [comment]
I think it adds value by letting PSK only users known where in the code Service Workers code is so it is easier to fine if they want to disable it.

**Comment by arthurvr** [comment]
Does that add real value? When a file is called `platinum-sw` people know that. Also I think the `<!-- End` comment will look strange to people anyways.

**Comment by chuckh** [comment]
I don't think people who are new Polymer will know what `platinum-sw` is. As far as `<!-- End` might look a little strange to some people but is a trade-off. We already have comments with `<!- end...`.

```
<!-- build:js bower_components/webcomponentsjs/webcomponents.min.js -->
  <script src="bower_components/webcomponentsjs/webcomponents-lite.js"></script>
<!-- endbuild -->
```

**Comment by arthurvr** [comment]
> We already have comments with <!- end....

Yes, because the build process requires those. That's the main reason I think people are going to confuse this.

**Comment by art0001** [comment]
@chuckh ignore @arthurvr  because he only like to comment to feel important about himself but in reality he doesn't know anything :)

**Comment by robdodson** [comment]
This may not end up being a generator specific thing, it seems like a handful of folks have run into issues with service worker so the starter kit itself may need to make it optional, perhaps the lite version would strip it out (if it doesn't already).

I think since @addyosmani has the most experience in this realm it's probably best to let him weigh in on which approach he would prefer.

**Comment by addyosmani** [comment]
I think that if we're adding in comments here, they should first and foremost provide value to the end user and be clear about their intentions. There may well be a simpler way to achieve this, but heres another option:

If we decide to disable Service Workers by default we can comment out the implementation and do something like this..

### index.html

```
    <!-- Uncomment next block to enable Service Worker support (1/2) -->
    <!--
    <paper-toast id="caching-complete"
                 duration="6000"
                 text="Caching complete! This app will work offline.">
    </paper-toast>

    <platinum-sw-register auto-register
                          clients-claim
                          skip-waiting
                          on-service-worker-installed="displayInstalledToast">
      <platinum-sw-cache default-cache-strategy="networkFirst"
                         precache-file="precache.json">
      </platinum-sw-cache>
    </platinum-sw-register>
   -->
```

### elements.html

```
<!-- Uncomment next block to enable Service Worker Support (2/2) -->
<!-- 
<link rel="import" href="../bower_components/platinum-sw/platinum-sw-cache.html">
<link rel="import" href="../bower_components/platinum-sw/platinum-sw-register.html">
-->
```

This makes it clear that:

1. They're disabled by default
2. There are two blocks that need uncommenting in order to get this working

(We can play around with variations of the above comments if this doesn't make sense)

For the Yeoman generator to offer this up as an option, it could search for the two `..Uncomment to enable..` lines and regex parse/remove the `<!--` and `-->` for the proceeding comment blocks found.

Does this make sense? Too complicated? The start/end approach could work too, but I tend to agree with the comments that this could confuse users.

**Comment by robdodson** [comment]
I quite like that approach

**Comment by chuckh** [comment]
Makes sense to me. :+1:

**Comment by pdf** [comment]
Looks fair to me @addyosmani, not sure how easy that will be to match in the generator though.

**Comment by addyosmani** [comment]
Service Workers are now commented out (and optional) in PSK as of the version in master.
