### ISSUE TITLE
Polymer 1.4 ?

### ISSUE THREAD

**Issue by gpoulet** [PolymerElements/polymer-starter-kit#800]
Hello,

Polymer 1.4 is out, and Polymer Kit Starter still use Polymer 1.2

( bower.json's Polymer Starter Kit )
```
{
  "name": "polymer-starter-kit",
  "private": true,
  "dependencies": {
    "iron-elements": "PolymerElements/iron-elements#^1.0.0",
    "neon-elements": "PolymerElements/neon-elements#^1.0.0",
    "page": "visionmedia/page.js#~1.6.4",
    "paper-elements": "PolymerElements/paper-elements#^1.0.1",
    "platinum-elements": "PolymerElements/platinum-elements#^1.1.0",
    "polymer": "Polymer/polymer#^**1.2.0**"
  },
  "devDependencies": {
    "web-component-tester": "^4.0.0"
  },
  "ignore": []
}
```

Is it normal ?

**Comment by robdodson** [comment]
@gpoulet we can update the bower.json but when you run `bower install` it will pull down 1.4. The `^` in the version range tells it to pull down any new package except for a major version change.

![screen shot 2016-04-19 at 7 46 31 am](https://cloud.githubusercontent.com/assets/1066253/14643352/f156455a-0602-11e6-939d-79c6b504ccef.png)

If I'd like to submit a pull request to update the bower.json I'd be happy to merge it in though :)

**Comment by abdonrd** [comment]
Closed by https://github.com/PolymerElements/polymer-starter-kit/pull/815
