### ISSUE TITLE
Dynamically loaded js files?

### ISSUE THREAD

**Issue by davidmaxwaterman** [PolymerElements/polymer-starter-kit#803]
Instructions: https://github.com/PolymerElements/polymer-starter-kit/CONTRIBUTING.md#filing-issues 

^^^ this file 404s ^^^

### Description
Gulpfile only copies script files that have script tags in html files (using gulp-useref). My app is a progressive web app and doesn't load any files via tags that are in the source html in stages so that the user gets changes in stages and in a more controller manner.

The app is here, if it helps :

https://github.com/01org/webapps-scientific-calculator

I'm trying to switch from that grunt-based build system to the gulp one in PSK. There's not really much in there to do with Polymer, apart from the SW elements. I hope to change that over time and port it to use Polymer elements.

**Comment by robdodson** [comment]
I think this should be resolved by our new dependency on Polymer CLI. If you want to specifically tell it to copy files to your build directory use the [includeDependencies array](https://github.com/PolymerElements/polymer-starter-kit/blob/master/polymer.json#L15)
