### ISSUE TITLE
I need relative links in index.html that go straight to the server and not through the page.js routing logic

### ISSUE THREAD

**Issue by brancoliticus** [PolymerElements/polymer-starter-kit#804]
I am trying to develop a demo app for google appengine go that mixes static and dynamic pages. The plan is to have static stuff with PSK accesible only by logged in users and dynamic stuff for login, logout and xmlhttp requests. Having to put absolute paths to access the dynamic pages from the server when the absolute path is changing from localhost on the local development environment and something else with the deployed app is just unwieldy.

The best thing would be if the following link added to index.html  would go straight to '/logout' on tge server, but it goes in the page.js routing logic instead: '<a href="/logout">Logout</a>'. Can someone suggest me a way to get around this issue?

**Comment by robdodson** [comment]
Hm, looks like there's a PR for this in page.js but hasn't been merged yet. https://github.com/visionmedia/page.js/pull/361

Looking at the code though, it seems like if you add `rel=external` it may bypass page.js
https://github.com/visionmedia/page.js/pull/361/files#diff-168726dbe96b3ce427e7fedce31bb0bcR565

So maybe give that a shot and let us know if you still have issues

**Comment by samccone** [comment]
I am working on getting access to page.js to help 

https://twitter.com/samccone/status/722910316678373376

**Comment by brancoliticus** [comment]
Adding rel="external" to the link seems to do the trick. I was expecting it to open a new tab for that link so I didn't check that option.
