### ISSUE TITLE
Gulp serve:dist does not watch for changes

### ISSUE THREAD

**Issue by TimvdLippe** [PolymerElements/polymer-starter-kit#811]
### Description
Running `gulp serve` includes livereloading whenever a change is observed in `app/`. It would be nice if this is also possible in `gulp serve:dist`. This means that we can test our production build more easily, as it syncs with multiple browsers.

### Expected outcome
Whenever I change a file in `app/` the build is rerun and refreshes the page in the browser.

### Actual outcome
I need to manually restart the terminal task every time I make a change.

This might be an issue for the new polytool or the PSKv2 itself, currently in PSKv1 it does not work.

**Comment by robdodson** [comment]
Closing this as we're no longer using gulp in our build. I think watch support is a requested feature on Polymer CLI and there are workarounds listed in [this issue](https://github.com/Polymer/polymer-cli/issues/230)
