### ISSUE TITLE
psk should be dropped from psk-element-name for psk2

### ISSUE THREAD

**Issue by atishpatel** [PolymerElements/polymer-starter-kit#817]
I was considering starting an app with psk2, and I noticed I'll have to change all the psk-element names. For example, I'll have to change `psk-page-404` to `page-404`. If this project is suppose to be a starting point or template for projects, I think it'd be good if psk was dropped from the element names by default. It would make it easier to start new projects from this project.

Thoughts?

**Comment by robdodson** [comment]
We're using the `my-` prefix for now. Invariable folks are going to rename the elements anyway (or just delete them). For the sake of keeping things simple we're going to stick with `my-` for now and we can explore maybe turning PSK into a real yeoman generator with templating options down the line
