### ISSUE TITLE
Creating app based on PSK: which version? Cloning or unzipping? How do you derive the "light" version?

### ISSUE THREAD

**Issue by mercmobily** [PolymerElements/polymer-starter-kit#818]
I would like to create a "starter kit" for my fancy store-oriented framework: something that includes login, a form, a table, etc. I obviously want to derive it from PSK, but I have a few questions... sorry if some of them are silly.

* PSK1 or PSK2, considering that I want to release in a couple of months? I would _love_ to pick PSK2, to be honest, especially because after installing both, I can see that it's a full revolution. However, there is no fancy theming, no swipe to get the menu out, no resizing of header, etc... Do you have a vague ETA for PSK2?

* git clone (with constant up pulling/merging from upstream) or release? This is a very important one... my aim is to base my app on the PSK. If I use the zipped releases, I will basically have to diff/apply all of the improvements. cloning seems like a good idea, but the project doesn't seem to be geared up for people cloning.... which brings me to my next question

* What's the process to go from a git branch to a release? By "diffing", it looks like the "normal" version is just a git checkout, whereas the "light" version is the normal one, plus bower install plus a few changes here and there... do you use a script? If so, is it available?

**Comment by mercmobily** [comment]
Just for the record:

* PSK2 all the way. It's 10000000 times better. I sent some PRs
* git clone works best. I am changing as little as possible and find it easy to sync up. LOVE the fact that there is no huge GULP file anymore, but recipes.

* Still curious about what you do to go from "normal" to "light", but it has absolutely no priority

Thank you!

**Comment by robdodson** [comment]
We're still figuring out our strategy with PSK2 but likely it will get subsumed by our CLI tool and become one of many template projects

**Comment by mercmobily** [comment]
Oh OK. Can you give me a link to the current CLI tool on Github? Plus, shall I not bother with pull requests for PSK2 then? Thank you!

**Comment by TimvdLippe** [comment]
@mercmobily You can find the tool here: https://github.com/polymer/polytool. It is still under development though.

**Comment by mercmobily** [comment]
@TimvdLippe  Thank you Tim! Closing this, it has zero priority and likely zero relevance in les than 2 months.

**Comment by robdodson** [comment]
@mercmobily yeah the development of psk2 is in a lot of flux right now and is mostly dictated by the direction the team is going with their CLI. I would say hold off on pull request for the time being because we may pivot around a lot or even move the repo entirely to a new home to live with other templates. I need to do some catch up with the team this week (just got back from vacation) to see what our next move is. Given that Google I/O is the week after next there may be a lot of activity or absolutely none, it depends on what we decide we want to try to ship by then :D

**Comment by mercmobily** [comment]
@robdodson  OK thanks a million for answering!

**Comment by mercmobily** [comment]
Well, since I did it, I think #823 is a good idea. It's a tiny change, and it gives users the ability to theme it. Plus, like this is looks more like PSK1! It's there if you want it, I promise I won't make any more PRs against it!
