### ISSUE TITLE
Script src to page.js in routing fails in windows

### ISSUE THREAD

**Issue by devAtPolydeals** [PolymerElements/polymer-starter-kit#82]
In app/elements/routing.html page.js is referred relatively as 

```<script src="../../bower_components/page/page.js"></script>```

however bower_components is only 1 level up. Changing it to
 ```javascript 
<script src="../bower_components/page/page.js"></script> 
``` 
fixes the issue else i was getting 
"Uncaught ReferenceError: page is not defined"

**Comment by addyosmani** [comment]
Could you confirm which version of the kit this is failing on? My guess is the light one as our paths are slightly different there (but can be fixed).

**Comment by devAtPolydeals** [comment]
download page has changed since i installed, but i used the one which is now polymer-starter-kit-1.0.0.zip

**Comment by devAtPolydeals** [comment]
Let me download and run the latest one...may be its fixed now.

**Comment by addyosmani** [comment]
This may be related to a Windows paths issue. On OSX/Unix, the path resolves correctly in polymer-starter-kit-1.0.0.zip, but I'll also test on Windows to see if I can repro.

**Comment by devAtPolydeals** [comment]
same issue with new zip file as well, script src tag is same. Yes,i am guessing its because how windows or rather apache on windows resolves relative paths. elements.html is on the same level and it works good as it has ../bower-components.

**Comment by devAtPolydeals** [comment]
The issue is a little different now, I totally forgot that after initial install I had manually moved bower_components directory manually inside app/. to temporarily fix not found errors. This caused issue for page.js.

However after new install it is still required to change the path to bower_components in elements.html to ../../bower_components from ../bower_components and in Index.html from bower_components to ../bower_components.

**Comment by devAtPolydeals** [comment]
am closing this issue.

For future reference:

After install in windows : Change the path to bower_components in elements.html to ../../bower_components from ../bower_components and in Index.html from bower_components to ../bower_components.
