### ISSUE TITLE
iron-ajax seems to send requests to the wrong url or something

### ISSUE THREAD

**Issue by brancoliticus** [PolymerElements/polymer-starter-kit#826]
Please see http://stackoverflow.com/questions/37101221/iron-ajax-in-tandem-with-polymer-starter-kit-misbehaves-or-something-it-sends-r for a detailed description of the problem and the source code that I created.

**Comment by moderndeveloperllc** [comment]
I posted on SO, but I'll post it here too:

A couple of things. You are missing the slashes in "http:localhost:8080/journal_tag" It should be http://localhost:8080/journal_tag. Also, you can use the Developer tools for the browser you are in to see all the XHR requests that you are sending. Check there to see what the request headers being sent are. If they are not what you are expecting, post them here.

**Comment by brancoliticus** [comment]
Just a small change and everything works fine now. See my stackoverflow answer for details.
