### ISSUE TITLE
Chrome on Android doesn't hide address bar on scrolling down

### ISSUE THREAD

**Issue by jsilvermist** [PolymerElements/polymer-starter-kit#827]
When scrolling in the PSK in Chrome on Android, the address bar will remain stuck to the top and doesn't auto hide.

Similar to (google/material-design-lite#1072).

**Comment by abdonrd** [comment]
Already fixed in [PSK2](https://github.com/PolymerElements/polymer-starter-kit/tree/psk2) with the `app-elements`. :)
