### ISSUE TITLE
PSK should include Babel.

### ISSUE THREAD

**Issue by iugo** [PolymerElements/polymer-starter-kit#829]
### Description

If the app.js include `for ... of`, then `gulp`.

### Actual outcome

trigger an error:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error
at JS_Parse_Error .../gulp-uglify/...
```

### Live Demo

PSK should include Babel.

**Comment by robdodson** [comment]
Hi @iugo I'm planning to add support for Babel in the pks2 branch. Until then you can follow this guide to add it yourself.

https://github.com/PolymerElements/polymer-starter-kit/blob/master/docs/add-es2015-support-babel.md
