### ISSUE TITLE
Polymer starter kit with cca 

### ISSUE THREAD

**Issue by eljazouli** [PolymerElements/polymer-starter-kit#83]
how to use this starter template with cca (https://github.com/MobileChromeApps/mobile-chrome-apps) ?
Thanks

**Comment by addyosmani** [comment]
Thanks for asking. We don't currently have plans to officially support CCA out of the box, however, it should be possible to use PSK and CCA together using Vulcanize as long as you opt for using https://github.com/PolymerLabs/crisper. My hope is that we'll soon have a community-driven repo showing how to do this that we can link up to.
