### ISSUE TITLE
How to add files to-be cached?

### ISSUE THREAD

**Issue by abhisheksoni27** [PolymerElements/polymer-starter-kit#831]
Where should I add files that I want to be cached?

**Comment by robdodson** [comment]
I believe if you uncomment this line in the gulpfile (https://github.com/PolymerElements/polymer-starter-kit/blob/master/gulpfile.js#L256) that it will generate that cache-config.json for you in your dist directory.

**Comment by robdodson** [comment]
Sorry, to continue on a bit...

This task specifies which files will be included in the cache-config. You can either add directories to the `glob` or push your own individual files into the `files` array.
