### ISSUE TITLE
Moving PSK2 to Master

### ISSUE THREAD

**Issue by robdodson** [PolymerElements/polymer-starter-kit#833]
Hey folks,

I think the CLI is lagging a little and it'll take some time for them to get us the hooks we want for things like image optimization and ES2015. Having said that, the site does currently work with the CLI (though I think there may be some [small bugs](https://github.com/Polymer/polymer-cli/issues/226)). A number of folks have pinged me saying they're confused if they should use the CLI or PSK so I think it'd be good to move forward with a PSK2 pre-release. This would entail switching PSK2 over to master, creating a pre-release tag, and updating our README. @samccone @addyosmani @abdonrd @chuckh @justinfagnani wdyt?

**Comment by addyosmani** [comment]
With respect to feature parity with master (CLI and known issues aside) what are we still missing in your opinion in PSK2?

**Comment by robdodson** [comment]
@addyosmani I think we would need to do a pass to update the recipes and remove any that seem outdated. Also rewriting the README. Note that this version doesn't include the platinum-* elements so we'd want to clear out that section. The CLI generates a `service-worker.js` for you so we may want to do a bit of a write up explaining how that works and how to modify it.

I think the upside is we probably don't need to produce two versions anymore since we're ditching the build process entirely in favor of the CLI.

**Comment by oneezy** [comment]
@robdodson The CLI tool is great, but one thing I've been missing is BrowserSync. Is there any plans to integrate something like this into the CLI? Or is it possible to use both Polymer CLI + BrowserSync together?

**Comment by robdodson** [comment]
@oneezy I'm not sure if it's currently on their roadmap but [I've opened an issue](https://github.com/Polymer/polymer-cli/issues/230). I agree it would be nice :)

**Comment by joryphillips** [comment]
@robdodson At least initially, there should be a basic step-by-step comparison of the PSK1 and PSK2 build processes to help make this a smoother transition. The CLI's Typescript roots makes for a steep climb for those who want to understand how it works & what we're gaining from it (or... contribute). 

I'm happy to help with the crafting of the comparison, but need to get up to speed on the CLI to be of much help.

**Comment by chuckh** [comment]
This is done as part of PSK2 release.
