### ISSUE TITLE
Remove bower_components from dist after vulcanization has finished

### ISSUE THREAD

**Issue by rubenstolk** [PolymerElements/polymer-starter-kit#84]
Easier if `dist` is entirely to be deployed into production...?

**Comment by ValueBC** [comment]
I agree. "Dist" should be clean and minified for easy deployment into production. Why are redundant files included? Or can you give an easy way to modify the gulpfile.js to accomplish this?

**Comment by addyosmani** [comment]
Pre 1.0.0, I was running into issues with not all elements in the Kit being fully Vulcanized. This required the bower_components directory to stick around in dist, even if it was being partially used. This is of course not ideal and we should fix it.

@rubenstolk when you're deleting `bower_components` from `dist`, are you seeing any runtime errors in your builds? I'll test this back out on our supported platforms and see if it's safe to just drop it from dist from our gulpfile.

**Comment by rubenstolk** [comment]
Hi Addy,

I tested it briefly without `bower_components` and it was all working, but
it would have to be tested once more properly.

--

Ruben Stolk

http://changer.nl, "Raising the bar in online experience"
+91 95 6105 0034   /  +31 6 46 11 80 37

**Comment by devAtPolydeals** [comment]
@rubenstolk  won't this line break it?
https://github.com/PolymerElements/polymer-starter-kit/blob/master/app/index.html#L50

**Comment by moeric** [comment]
Without 'bower_components' in dist I'm getting 404s in this files:

bower_components/webcomponentsjs/webcomponents.min.js
bower_components/promise-polyfill/Promise.js
bower_components/page/page.js
bower_components/paper-drawer-panel/paper-drawer-panel.css
bower_components/paper-item/paper-item-shared.css
bower_components/google-signin/google-signin.css

**Comment by hourliert** [comment]
@devAtPolydeals you are right. This line break the build. This is the only file needed from `dist/bower_components`.

**Comment by devAtPolydeals** [comment]
@hourliert , Vulcanize is too buggy btw for windows, so for windows users dist needs to have bower_components. I would advice not to vulcanize at all because the results are very unpredictable

**Comment by rubenstolk** [comment]
What do you mean windows users dist? Dist is meant to put something in production. If vulcanize itself doesn't run on Windows that's too bad but the output of vulcanize should still not have bower_components

**Comment by addyosmani** [comment]
> won't this line break it?
https://github.com/PolymerElements/polymer-starter-kit/blob/master/app/index.html#L50

@devAtPolydeals Is that the only file you're seeing requested from the bower_components directory post Vulcanization at the moment?

**Comment by devAtPolydeals** [comment]
@addyosmani no actually there are some arbitrary css files that are also requested post vulcanization from the bower_components directory. See the screenshot for what files get requested post vulcanization.

BTW vulcanization on windows works intermittently, i have had times when the styles won't get applied or it will throw file not found errors for promise.js even when i didn't change anything. I did raise an issue with Vulcanize team and they seem to have given it high priority.  BTW i would add in FAQ that if your app works fine in the app directory and doesn't in dist directory && you are on windows then maybe its vulcanization. I had to fight for long to end up with that conclusion

![polydeals](https://cloud.githubusercontent.com/assets/12582040/8214451/32fb07f0-14de-11e5-8abc-a67790c4e7eb.png)

See https://github.com/Polymer/vulcanize/issues/205 and https://github.com/Polymer/vulcanize/issues/202

**Comment by notwaldorf** [comment]
@azakus Would you mind taking a look at this, please? Thanks! 💝

**Comment by rubenstolk** [comment]
@notwaldorf @azakus I think this would be a good and simple starting point:

https://github.com/PolymerElements/polymer-starter-kit/pull/203

We can then decide to even remove the `bower_components` folder.

**Comment by wintersandroid** [comment]
I implemented for a couple of projects some modifications to the gulpfile.js which start by changing the directory "dist" into "dist.temp" and then adding a copy to copy only what is needed after vulcanize into the "dist" directory.

I have posted my altered file into the gist https://gist.github.com/wintersandroid/1ee1d38059a86d3f721a

What I do is run the original gulp file and note in the browser dev tools which files are being loaded and then use that list in the copy.

**Comment by pantaluna** [comment]
I  would like to add that in my environment (1.3.0 Windows) I had to change line 97 and change `'bower_components/**/*'` to `'app/bower_components/**/*'`

https://github.com/PolymerElements/polymer-starter-kit/blob/master/gulpfile.js#L97

**Comment by michelecos** [comment]
By the way, I get an error building a Cordova application, related to bower_components:

      Unable to add '/Users/michele/Src/MyApp/platforms/android/build/intermediates/assets/debug/www/bower_components/web-animations-js/web-animations.min.js.gz': file already in archive (try '-u'?)

**Comment by ragingwind** [comment]
@michelecos Cordova(Android) doesn't allow any gz files in the package. Update gruntfile to avoid gz file  copy, see https://github.com/ragingwind/polymer-starter-kit/commit/f77c8010ac21607d23c195eb10bacfe390aa71ba#diff-66febfab889f33c11e360c2f526061e6R79

**Comment by robdodson** [comment]
This should be addressed by https://github.com/PolymerElements/polymer-starter-kit/pull/568

The only files being moved over with bower_components now are ones that we can't vulcanize into a bundle (such as those required by service worker and the web components polyfills). This should bring the size of dist down significantly.
