### ISSUE TITLE
gulp default task fails with Error: EISDIR

### ISSUE THREAD

**Issue by IchordeDionysos** [PolymerElements/polymer-starter-kit#841]
When running `gulp` at the root of the Polymer Starter Kit I'll get an error in the `build` gulp task which says: 

    'build' errored after 2.33 s 
    Error: EISDIR: illegal operation on a directory, open '[...]\dist\scripts' at Error (native) 
    'default' errored after 5.61 s Error in plugin 'run-sequence'
    Message:
      An error occurred in task 'build'.

I made some research and I think, it should do some operations on a file, not on a folder

**Comment by IchordeDionysos** [comment]
I've although tried to reinstall the node_modules, didn't work :/

**Comment by robdodson** [comment]
@IchordeDionysos I think EISDIR means the directory might not exist. Just curious did it generate a `dist` directory? cc @felixzapata

**Comment by felixzapata** [comment]
@robdodson I will take a look

**Comment by felixzapata** [comment]
@IchordeDionysos I can't reproduce the error. This issue happen to you every time you run the `gulp` task in the root folder?

Which operating system are you using? When you reinstalled the modules, did you delete the `node_modules` folder first?

**Comment by IchordeDionysos** [comment]
Yeah the folder `dist` exists! 
Yep, then it occurs
I'm using Windows, but same error occurred on Ubuntu
I did delete `node_modules` before

**Comment by robdodson** [comment]
@IchordeDionysos Is this happening with a fresh checkout of PSK or have you modified it any?

**Comment by felixzapata** [comment]
@IchordeDionysos which version of Node are you using? Are you trying the version from master branch or the current release?

I´ve test the PSK (master version) in a fresh install in Xubuntu and in OS X but I still can´t reproduce the issue :S

**Comment by felixzapata** [comment]
@IchordeDionysos I´ve tested the PSK (master version) in a fresh install in Ubuntu too, and neither can reproduce the issue :(

**Comment by IchordeDionysos** [comment]
@robdodson @felixzapata I changed files inside the app directory!
Node version is: v4.2.1
I've tried it again with master branch and changed the files step by step to evaluate when it occurs, and it happened when I changed the index.html to my current version.
Switching back to PSK version resolved the error.

Does it make a change if you change this:

    

to this:

    

Because with the first comment it works and the second not!

I renamed the comment when I added other `.js` files than `app.js`

**Comment by IchordeDionysos** [comment]
Okay, I now understand the annotation: `build:js scripts/app.js`
It's the file to create out of all scripts between that two comments right?

**Comment by felixzapata** [comment]
@IchordeDionysos affirmative.. one of the goal of the `build` task is create the file you indicate with the comment

**Comment by IchordeDionysos** [comment]
Okay, thank you very much. Helped me a lot!

**Comment by felixzapata** [comment]
you're welcome @IchordeDionysos

**Comment by felixzapata** [comment]
can we close this issue @IchordeDionysos ?

**Comment by IchordeDionysos** [comment]
Yes
