### ISSUE TITLE
PSK2: Reorganizing Elements by Functionality and Relationship

### ISSUE THREAD

**Issue by LoveAndHappiness** [PolymerElements/polymer-starter-kit#847]
### Situation
Right now every element, regardless of function, is placed inside the src directory.

    src/psk-app/psk-app.html
    src/psk-page-home/psk-page-home.html
    src/psk-page-about/psk-page-about.html
    src/psk-page-404/psk-page-404.html

### Problem
The problem with this approach is, that though the elements belong together in a hierarchical way (f.e. psk-page-home is inside psk-app), this hierarchical structure is not reflected in the structure of the app, thus the connection between elements has to be understood by the "name" of each element.

This leads to the elements needing a descriptive and thus longer name, which leads to "three-word-elements". In our case "psk-page-about" or "psk-page-404".

### Implication
The implicated results are, that as the app grows, the list of elements that are placed inside the src becomes longer. Thus making it more difficult to understand the relationship between the elements, by looking into the directory. This might even make "four-word-element-names" necessary. Who knows...

### Suggestion
By structuring the psk-app, by adding a views directory to it and moving the "pages" inside this views directory, like this:

    src/psk-app/psk-app.html
    src/psk-app/views/psk-home/psk-home.html
    src/psk-app/views/psk-about/psk-about.html

#### Benefits of this approach is: 
- Function and relationship between the elements become more intuitive, because of separation
- The two-word naming convention for custom elements can be kept, because of directory name, thus also solving Issue [#817](https://github.com/PolymerElements/polymer-starter-kit/issues/817)
- Increased clarity, maintainability and intuitiveness.

**Comment by LoveAndHappiness** [comment]
Added a pull request just for reference.

**Comment by oneezy** [comment]
I second that. 

A good article I always like to refer to for `folder / file` hierarchy is:
http://cliffmeyers.com/blog/2013/4/21/code-organization-angularjs-javascript

**Comment by addyosmani** [comment]
Given that we've been leaning on @justinfagnani for some thoughts on structure, interested in his take on this problem.

**Comment by robdodson** [comment]
I still lean toward the original structure because it doesn't attempt to ingrain any pattern. Folks are free to organize their elements however they want without wondering if the views directory is special. But that's just 1 opinion :). I'm also curious what other folks on team Polymer feel.

**Comment by jsilvermist** [comment]
The only problem with purely using folder structure to add context to elements and simplifying names by removing things such as `page` is namespacing.

Even if it's clear that it's a page by folder structure, you still can't have 2 elements named the same thing. Naming everything psk-oneword with no other context could get more complicated with many elements, not less.

**Comment by LoveAndHappiness** [comment]
As @robdodson correctly pointed out, this issue might be a question about leaving developers the freedom to structure the app the way they want, without attempting to ingrain particular patterns. As this might give the false impression that the views folder is somehow special and thus unnecessarily adding false contraints.

On the other hand, if particular **expert** recommendations about structure exist in regard to building successful Polymer apps, then I believe that they should be ingrained in the PSK, because conventnions are usually beneficial.

Since I myself am no expert on this subject, I lean with @addyosmani to wait on the take of @justinfagnani, since he seems to be experienced on this subject.

**Comment by robdodson** [comment]
I spoke with the team, here's their feedback:

Justin:
> organization of `src/` should be completely up to the project. Big projects probably benefit from some hierarchical organization, but we don't have any requirements on it.

Scott Miles:
> Fwiw, I tend to go back and forth on the folder hierarchy thing, I tend to agree with you that not cementing a pattern is valuable. I think the answer varies by complexity of the project. Maybe we should also make it clearer that there are options? If it's true that it  "leads to the elements needing a descriptive and thus longer name" that would be objectively bad, although I'm not sure that's true (because the elements have to live in a single namespace an runtime anyway).

**Comment by robdodson** [comment]
Scott also mentioned that requiring a directory for each element may not be necessary as the elements don't tend to require support files (ex: https://github.com/Polymer/shop/tree/master/src)

Obviously that would change if you were doing something like pairing SASS with a component but that's not something that we're currently trying to support with this one example.

**Comment by oneezy** [comment]
I agree that the `folder` hierarchy should be left up to the project and not try to sway a particular `style`. 

On the other hand, having a structure you're accustomed to created "out of the box" would be nice.

One approach would be adding this as an extra to the [Polymer CLI](https://github.com/Polymer/polymer-cli) `init template` command.

Using [Cliff Meyer's code organizing blog](http://cliffmeyers.com/blog/2013/4/21/code-organization-angularjs-javascript) as reference,

**The commands might look something like:**
```
$ polymer init application:default      (in it's current state)
$ polymer init application:piles        (piles on the floor)
$ polymer init application:sock         (the sock drawer)
$ polymer init application:modular      (modularity)
```
**Using the `application:modular` might produce something like:**
```
src/
├── psk-app/
├───── psk-components/
│           ├─── component-header/
│           ├─── component-main/
│           └─── component-footer/
│
├───── psk-pages/
│           ├─── page-404/
│           ├─── page-about/
│           └─── page-home/
│                   ├─── page-home.html
│                   ├─── page-home.js
│                   └─── page-home.css
│
├───── psk-app.html
├───── psk-app.js
└───── psk-app.css
```

Just an idea... I think it would be pretty cool though!

**Comment by robdodson** [comment]
I don't think we'll be going in this direction for PSK2 based on feedback from the eng team. Having said that, the CLI is designed so anyone can [create their own template project](https://github.com/Polymer/polymer-cli#templates-and-generators) which uses the approach they prefer.
