### ISSUE TITLE
How to disable scroll to top for specific div?

### ISSUE THREAD

**Issue by dadatawajue** [PolymerElements/polymer-starter-kit#849]
I'm trying to integrate photoswipe into a Polymer project (similar to http://stackoverflow.com/questions/32934724/photoswipe-with-polymer-misalignment which is working) using the polymer-starter-kit

The problem is that when you exit the full screen of an image then it automatically scrolls to the top, which I assume is intended behavior for navigating between the different pages.. so my question is, is there a way that I can easily disable the effect from affecting the photoswipe fullscreen without affecting the sidebar navigation?

Any help would be greatly appreciated ;3

**Comment by robdodson** [comment]
This is the function doing the scroll top work: https://github.com/PolymerElements/polymer-starter-kit/blob/master/app/elements/routing.html#L25 which is called on every route change https://github.com/PolymerElements/polymer-starter-kit/blob/master/app/elements/routing.html#L42

You could remove `scrollToTop` from that route and only add it to the routes that you actually want it to affect.

**Comment by dadatawajue** [comment]
Thanks a lot, it works <3

I'm still a little confused about the best way to deal with it through.. because the routes that use photoswipe are the same as those from the `<paper-scroll-header-panel drawer fixed>`.

e.g. the route pics (http://localhost:5000/#!/pics) contain the photoswipe gallery, and the route pics is also available through the side navigation.. so I figured if I made a new route for the side navigation which would scrollToTop and then redirect to the pics route then the problem would be solved, but it doesn't seem to be working

```
page('picstotop', scrollToTop, function() {
      page.redirect('/pics');
});

page('/pics', function() {
      app.route = 'pics';
      setFocus(app.route);
});
```

I don't understand why this isn't working, because when you close the photoswipe fullscreen view then it would just return to the route pics which does not use the scrollToTop function, and if I didn't do the picstotop route trick then photoswipe wouldn't scroll to top when closing the fullscreen view of an image.

(Alternatively I figured could add # to the url when closing photoswipe, but even if that worked then I'd have to give up on the 404 function (and I think the solution above would be more neat if it worked))

**Comment by robdodson** [comment]
Sorry I don't understand. Are you saying that /pics is still scrolling to the top? You may want to remove that call to `setFocus`

**Comment by dadatawajue** [comment]
I decided to do:

```
<script>
  app.scrollToTop = function() {
    app.scrollPageToTop();
  };
</script>
```
and call it with
`<paper-menu class="app-menu" attr-for-selected="data-route" selected="[[route]]" on-iron-activate="scrollToTop">`

This seems to be working great and I hope/assume it's the right/a good way to do it?

Before it still didn't work with photoswipe, but after I removed `setFocus` as you suggested then it works! Thanks a lot <3
