### ISSUE TITLE
Duplicated lower bound for desktop x-large media query in the application theme

### ISSUE THREAD

**Issue by peterblazejewicz** [PolymerElements/polymer-starter-kit#85]
The media query breakpoints in application theme seems to be not very clear for x-large desktop breakpoint:
https://github.com/PolymerElements/polymer-starter-kit/commit/a8e5560c524a46201368d4efd944b2ecce807111#diff-a49e3b55ce6c03ad8616b1b64d5b5d1bR215
```
/* desktop-xlarge */
@media all and (min-width: 1601px) and (min-width: 1920px) { }
```
They are in line with material design but use doubled lower bound. I'm not sure if the intent is clear here.
Thanks!

**Comment by addyosmani** [comment]
It should be min `1601` and max `1920` with an option to specify larger than that. I'll fix that up.
