### ISSUE TITLE
Remove the  paper scroll header panel and minimize left pane for one routes

### ISSUE THREAD

**Issue by MacTheZazou** [PolymerElements/polymer-starter-kit#850]
I have an element who need to be full screen with the less possible superfluous elements...

Is there an easy way to hide/minimze the fat header menu bar and minimize the left pane? from an element or from a routes?

the best would be this layout: 

![Layout](http://puu.sh/pmdxQ/1229e2a9a0.png)

Thank you!

**Comment by PChild** [comment]
Adding the `force-narrow` attribute to your paper-drawer-panel should achieve this. Here's what I use: `<paper-drawer-panel force-narrow id="paperDrawerPanel">`.

**Comment by robdodson** [comment]
Yep @PChild nailed it. Closing but let me know if you still have issues.
