### ISSUE TITLE
PSK2 - Polymerfire integration?

### ISSUE THREAD

**Issue by maria-le** [PolymerElements/polymer-starter-kit#852]
Would it be possible to see an integration with [Polymerfire](https://github.com/firebase/polymerfire) at some point during the PSK2 lifecycle?

The need to authenticate users and save and modify user data is ubiquitous in apps. So, if the PSK2 could model how that is best done, I think it would be a huge time saver for developers who use Polymer and Firebase.

**Comment by robdodson** [comment]
I think the plan for PSK2 is just build a stripped down app template that uses ES2015. Because the CLI supports as many templates as you can build, I think it would be good to create a separate template that's basically a Firebase focused project.
