### ISSUE TITLE
Polymer Starter Kit v2.0

### ISSUE THREAD

**Issue by AliMD** [PolymerElements/polymer-starter-kit#853]
Hi Everyone
After release polymer app toolbox I refactor my codes (even structure)
And maybe it's time to update this awesome project too
For example
* change routing
* change app layout
* More progressive web app
* fix issue with new structure (for example new addressing for new routing)
* use polymer cli
* ...

Could you please add new branch and milestone for next release and more describe on it.
I will be happy to contribute, please tell me the plan and priority.
Thank you in advance.

**Comment by robdodson** [comment]
Hi Ali, there's already a psk2 branch that does a lot of what you mention. We're waiting on the CLI to provide gulp hooks which should land this week or next
