### ISSUE TITLE
effects="waterfall" does not work

### ISSUE THREAD

**Issue by akshaymarkande** [PolymerElements/polymer-starter-kit#855]
### Description

the shadow effect is not visible when we apply waterfall effect.
### Expected outcome

there should have been a shadow applied to the header when we scroll 

### Actual outcome

there is no shadow effect
### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by robdodson** [comment]
Are you using the psk2 branch that uses app-layout elements or the current release of psk which uses paper-drawer-panel?

**Comment by akshaymarkande** [comment]
Paper drawer panel

**Comment by robdodson** [comment]
The paper-scroll-header-panel in the current PSK doesn't support effects=waterfall. I believe that is only supported in the app-layout elements. We're working on switching to the app-layout elements in the psk2 branch. https://github.com/PolymerElements/polymer-starter-kit/tree/psk2

**Comment by akshaymarkande** [comment]
Ok great.
So we can use version 2 right now or there is still time for our being
production grade ready?

**Comment by robdodson** [comment]
@akshaymarkande I'd recommend using the Polymer CLI and using app-drawer-template
