### ISSUE TITLE
Service worker functionality does not work when 'gulp serve' is run

### ISSUE THREAD

**Issue by TheoMer** [PolymerElements/polymer-starter-kit#859]
OS: Windows 10 Pro
Browser; Chrome Version 51.0.2704.106 m (64-bit)
Yo: version 1.8.4
Polymer generator: 1.3.0

### Description
Service worker is non functioning when 'gulp serve' is run.

### Expected outcome

As I have amended both index.html and elements.html, as well as gulpfile.js, to allow for service worker functionality, I expected, on initial page load, that a 'caching activated for offline usage' type message would appear in Chrome browser, and if taken offline in developer tools > network, that the app would still load.

### Actual outcome

What actually happens is that service worker functionality is not enabled if I run 'gulp serve'. I verified this by going to developer tools > network > offline, then reloading the page (f5), which renders the dinosaur offline/no network page. 

But If I run 'gulp server:dist', then service worker functionality works as expected.

### Live Demo
Using the latest polymer-starter kit

### Steps to reproduce

1. yo polymer
2. gulp serve
3. gulp serve:dist

### Browsers Affected

- [ x] Chrome

What is the issue here? Why is service worker functionality not available when running 'gulp serve', even though I have un-commented the service worker sections in index.html and elements.html?

**Comment by robdodson** [comment]
`gulp serve` doesn't run the `cache-config` task. This is because you typically don't want to develop with a service worker turned on (you'll have to keep deleting and renaming the cache every time you change any file).

If you find this confusing we could update the README to mention this. Would you be interested in filing a PR for that?
