### ISSUE TITLE
Service worker doesn't work if https: true  is enabled in gulpfile.js, when 'gulp serve:dist' is run

### ISSUE THREAD

**Issue by TheoMer** [PolymerElements/polymer-starter-kit#860]
OS: Windows 10 Pro
Browser; Chrome Version 51.0.2704.106 m (64-bit)
Yo: version 1.8.4
Polymer generator: 1.3.0

### Description
Service worker doesn't work if https: true  is enabled in gulpfile.js, when 'gulp serve:dist' is run

### Expected outcome

Expected the site to work when developer tools > network was set to offline

### Live Demo
polymer starter kit

### Steps to reproduce

1. yo polymer
2. uncomment service worker sections in index.html, elements.html, an gulpfile.js
3. uncomment https: true in gulpfile.js
4. gulp serve:dist

### Browsers Affected

- [x ] Chrome

**Comment by robdodson** [comment]
I believe to do this you'll have to create a self signed certificate for localhost. Probably easier to not have to do this for local development.
