### ISSUE TITLE
Adding async to <link rel="import" href="elements/elements.html"> messes up menu list

### ISSUE THREAD

**Issue by TheoMer** [PolymerElements/polymer-starter-kit#863]
OS: Windows Pro 10
Browser: Chrome version 52.0.2743.60 beta-m (64-bit)
Yo: version 1.8.4
Polymer version: latest (installed today: 13/07/2016)

### Description
Adding the value async to `<link rel="import" href="elements/elements.html">`, in index.html, messes up the menu option list 

### Expected outcome

Expected the elements.html to be lazy-loaded without any issues

### Actual outcome

1. 'Home' option from the menu list disappears, 
2. A 'Could not find style data in module named shared-styles' warning is thrown at (polymer.html : 2662)

### Live Demo
Vanilla polymer-starter project

### Steps to reproduce

1. yo polymer
2. Add async as follows `<link rel="import" href="elements/elements.html" async>`
3. gulp serve

### Browsers Affected

- [x] Chrome

**Comment by robdodson** [comment]
@TheoMer  can you try this with the PSK2 version?
https://github.com/PolymerElements/polymer-starter-kit/tree/psk2

**Comment by TheoMer** [comment]
@robdodson so I ran:

1. git clone https://github.com/PolymerElements/polymer-starter-kit.git
2. python -m http.server 8080

but nothing is served up at 0.0.0.0:8080. 

What am I overlooking?

**Comment by robdodson** [comment]
@TheoMer did you checkout the psk2 branch?

**Comment by TheoMer** [comment]
@robdodson So I:

1. downloaded polymer-starter-kit-psk2.zip
2. cd into directory
3. npm install & bower install
4. python -m http.server 8080

Still nothing.

**Comment by robdodson** [comment]
@TheoMer oh I would recommend cloning the repo and checking out the `psk2` branch. Then using [the Polymer CLI server](https://www.polymer-project.org/1.0/docs/tools/polymer-cli).

`polymer serve --open`

**Comment by TheoMer** [comment]
@robdodson Just to confirm, I'm doing:

1. git clone https://github.com/PolymerElements/polymer-starter-kit.git
2. git checkout -t origin/PSK2

correct?

**Comment by TheoMer** [comment]
@robdodson Apologies for going off-topic, but in relation to point 5 of my previous post, either way, I'm getting the following error message:

> fatal: Cannot update paths and switch to branch 'PSK2' at the same time.
Did you intend to checkout 'origin/PSK2' which can not be resolved as commit?

**Comment by robdodson** [comment]
you want to do `git checkout psk2`

**Comment by robdodson** [comment]
and you would want to npm/bower install _after_ you checkout the new branch.

**Comment by TheoMer** [comment]
@robdodson Many thanks for the update. 

I did notice that the node_modules folder is empty after running npm install. Should this be the caase?

**Comment by robdodson** [comment]
yep right now it looks like the psk2 branch doesn't have any npm
dependencies.
https://github.com/PolymerElements/polymer-starter-kit/blob/psk2/package.json

We're offloading much of what we would put in there to the CLI.

**Comment by TheoMer** [comment]
@robdodson Ok. In relation to your original question relating to relating to the menu structure after applying async to a `<link />`, doing so to `<link rel="import" href="/src/psk-app.html" async>` has no adverse effect on the menu structure.

Even though Chromes dev tools (Application/Service Worker) shows that a service worker is activated, disabling internet (Network\offline) renders a 'There is no internet connection' message. But then, and after doing a global search, I couldn't find any sign of 'paper-toast id="caching-complete"', platinum-sw-register, or platinum-sw-cache.

**Comment by robdodson** [comment]
The service worker in PSK2 doesn't do anything in development mode (check out service-worker.js). We also haven't configured what it will do in production mode. We'll likely actually remove it and let Polymer CLI generate a service worker for us.

**Comment by robdodson** [comment]
I'm going to close this as fixed in PSK2 branch if that's ok.

**Comment by TheoMer** [comment]
@robdodson Is there a roadmap (timetable) for PSK2, and Polymer in general?

**Comment by robdodson** [comment]
@TheoMer working on PSK2 as we speak.

Polymer: https://github.com/polymer/project
