### ISSUE TITLE
Bring back <body is="polymer-body"> for fast rendering apps

### ISSUE THREAD

**Issue by TheoMer** [PolymerElements/polymer-starter-kit#864]
Why are none of the issues raised in the 'rendering bottlenecks' section of this polymer github issue, not adhered to in the polymer-starter-kit?:

https://github.com/Polymer/polymer/issues/2654

Surely the starter kit should come out of the blocks showcasing best practices, right?

**Comment by robdodson** [comment]
Lazy loading polyfills is being addressed in psk2.

As for using a single element to render the entire app (which is what psk2 does and which eric lists as a bottleneck), we're aligning ourselves with the PRPL performance pattern outlined here https://www.youtube.com/watch?v=J4i0xJnQUzU.

Async loading elements the Polymer team has produced tends to have mixed results so we're not doing it for now. If you find issues with specific elements please file them on the element's repo, not here.
