### ISSUE TITLE
spelling error in docs/neon-animated-pages.md

### ISSUE THREAD

**Issue by LogoiLab** [PolymerElements/polymer-starter-kit#873]
### Description

Spelling error in docs/neon-animated-pages.md

```
## Update your dependencies

- First thing first, we need to replace the `iron-pages` import in `app/elements/elements.html` with a set of components from the `neon-animation` librairy, including `neon-animated-pages`:
```

note `librairy`

This is considered low priority.

**Comment by robdodson** [comment]
Any interest in opening a PR to help us fix it?

**Comment by LogoiLab** [comment]
I see it as a waste of GitHub resources to do that

**Comment by robdodson** [comment]
@LogoiLab hah um ok.. the reason we ask for folks to help with PRs, even for low priority stuff or easy fixes, is just to encourage folks to have a sense of ownership over the project. Everyone who works on it contributes part time so it's always great to have as many developers contributing pull requests to help patch things up.

**Comment by motss** [comment]
This can be closed anytime soon as this has been fixed in https://github.com/PolymerElements/polymer-starter-kit/commit/db06e2aa416cd5acc8212d80e258bf6ccfbd24a0.

**Comment by robdodson** [comment]
thanks @motss :)
