### ISSUE TITLE
bower install error

### ISSUE THREAD

**Issue by thomasgcompany** [PolymerElements/polymer-starter-kit#882]
bower install results in this error:

bower validate      4.3.1 against https://github.com/Polymer/web-component-tester.git#^4.0.0
bower ECMDERR       Failed to execute "git ls-remote --tags --heads git://github.com/PolymerElements/iron-elements.git", exit code of #128 fatal: unable to connect to github.com: github.com[0: 192.30.253.113]: errno=Operation timed out

Additional error details:
fatal: unable to connect to github.com:
github.com[0: 192.30.253.113]: errno=Operation timed out

**Comment by robdodson** [comment]
Could you try again? The error states your attempt to reach GitHub timed
out. If that doesn't work you want to verify you're not behind a corporate
firewall of some kind

**Comment by rishirD** [comment]
bower ECMDERR       Failed to execute "git ls-remote --tags --heads git://github.com/polymerelements/iron-flex-layout.git", exit code of #128 fatal: unable to connect to github.com: github.com[0: 192.30.253.113]: errno=Connection refused

**Comment by robdodson** [comment]
Similar comment as above. The error code says that your connection was refused. I can verify that the repo does exist https://github.com/polymerelements/iron-flex-layout so this sounds like it may be an issue with how you're connecting to github. Can you try to just run `bower install PolymerElements/iron-flex-layout` and see if you get a similar error?

**Comment by alex-ene** [comment]
Turns out some corporate firewalls are filtering out the protocol part, which, in this case is git://
A possible workaround is either to adapt the bower.json file to point explicitly to the https:// version of the repository.

**Comment by framled** [comment]
you can use this line on code, write at your terminal:

git config --global url.https://github.com/.insteadOf git://github.com/

this gonna use https: instead of git

**Comment by mayeedwin** [comment]
Check that you are connected to internet by the way
