### ISSUE TITLE
PSK2: Page not rendered as expected if route is updated by an external script on refresh

### ISSUE THREAD

**Issue by johnlim** [PolymerElements/polymer-starter-kit#888]
### Description
About page not rendered if ```window.location.href = '#/about' ``` called in `ready()` . Calling `window.location.href` in `ready` is not an actual use case but simulates the scenario where the route is updated by an external script (i.e login script with a 3rd party provider) during first load.

### Expected outcome
About page should be rendered

### Actual outcome
Blank screen is shown instead

### Live Demo
https://github.com/johnlim/polymer-starter-kit/tree/race-condition

### Steps to reproduce
1. Checkout the branch `race-condition`.
2. Run polymer serve.
3. Url in address bar shows localhost:8080/#/about but page isn't rendered

### Browsers Affected

- [* ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by johnlim** [comment]
This seems to be related to https://github.com/PolymerElements/app-route/issues/112.

**Comment by TimvdLippe** [comment]
This should probably be changed to
```js
window.history.pushState({}, null, '/#/about');
window.dispatchEvent(new CustomEvent('location-changed'));
```

see https://github.com/PolymerElements/app-route/issues/131#issuecomment-240698867

**Comment by robdodson** [comment]
Closing in favor of the app-route issue.
