### ISSUE TITLE
After build, don't load manifest.json in PSK2

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/polymer-starter-kit#891]
<img width="601" alt="screen shot 2016-08-04 at 21 18 15" src="https://cloud.githubusercontent.com/assets/1007051/17415214/1a0d68ae-5a89-11e6-9c3a-130994e1f0ca.png">

@robdodson @chuckh

**Comment by abdonrd** [comment]
https://github.com/Polymer/polymer-cli/issues/344

**Comment by robdodson** [comment]
I think we should still load it, it sounds like it needs to be in the `includeDependencies` property of polymer.json?

**Comment by abdonrd** [comment]
Right. We need to add it in the `includeDependencies`. And should works because we use `polymer-build`.
