### ISSUE TITLE
PSK2: Async build pipeline could resolve after task completion

### ISSUE THREAD

**Issue by 43081j** [PolymerElements/polymer-starter-kit#896]
Regarding [this](https://github.com/PolymerElements/polymer-starter-kit/blob/psk2/gulpfile.js#L38) gulp task.

imagemin (and likely most other gulp tasks) will be executed asynchronously, so it can complete _after_ the `cb()` call further down. This means if we depend on the `build` task to complete before our task, it could actually finish later on rather than when the done callback is executed.

To fix this, you can do something along the lines of (and remove the `cb` parameter):

```
	return Promise.all([
		new Promise(function(resolve) {
			// this fork will vulcanize the project
			fork(mergedFiles)
				.pipe(project.bundler)
				// write to the bundled folder
				.pipe(gulp.dest('build/bundled'))
				.on('end', resolve);
		}),
		new Promise(function(resolve) {
			fork(mergedFiles)
				// write to the unbundled folder
				.pipe(gulp.dest('build/unbundled'))
				.on('end', resolve);
		})
	]);
```

Although, maybe you know a better way. Maybe just `mergeStream`?

**Comment by abdonrd** [comment]
Thanks @43081j! Fixed!

Closed in favor to [PolymerElements/generator-polymer-init-custom-build](https://github.com/PolymerElements/generator-polymer-init-custom-build).
