### ISSUE TITLE
PSK2 images dir not copied on polymer build

### ISSUE THREAD

**Issue by robdodson** [PolymerElements/polymer-starter-kit#903]
### Expected outcome

Running `polymer build` should copy over the images dir. It's already in `sourceGlobs` in `polymer.json`.

### Actual outcome

images dir is not copied over

### Steps to reproduce

1. `polymer init starter-kit`
2. `polymer build`
3. `cd build/bundled`

no images dir 😰

**Comment by robdodson** [comment]
cc @justinfagnani @FredKSchott

**Comment by FredKSchott** [comment]
@robdodson We've been tracking this in a few other polymer-cli issues, but the problem is that the CLI was never updated to map these new `polymer.json` properties to be passed into `polymer-build`. 

I'll be adding a fix this afternoon and hopefully getting a new version out by EOD.

**Comment by robdodson** [comment]
This is fixed in the latest CLI

**Comment by oneezy** [comment]
I'm having this issue in a **Polymer Shop** app.

Cross referencing the **Polymer-CLI** issue I created: 
https://github.com/Polymer/polymer-cli/issues/386

It seems that the newest release (0.16.0) broke my image links as well.

**Comment by FredKSchott** [comment]
@oneezy see fix here: https://github.com/Polymer/shop/pull/77
