### ISSUE TITLE
polymer-cli generating psk1 project

### ISSUE THREAD

**Issue by jakecoffman** [PolymerElements/polymer-starter-kit#907]
### Description

Running `polymer init` and choosing starter-kit generates a PSK1 project.
### Expected outcome

PSK2 project is generated.

### Actual outcome

PSK1 project is generated.

### Live Demo

![capture](https://cloud.githubusercontent.com/assets/886768/18027754/e64c5b64-6c31-11e6-8512-c81104f5ee3a.PNG)

### Steps to reproduce

I am using Windows Subsystem for Linux. 

### Browsers Affected

n/a

**Comment by robdodson** [comment]
ack! I think Polymer CLI is using the latest release created for a project and ignoring the version numbers on those releases. I wrote release notes for PSK v1.4 yesterday and I guess it's counting it as a "new" release. That's annoying. I removed that release and I think things are fixed now.

**Comment by robdodson** [comment]
@FredKSchott @justinfagnani I deleted the release to fix this issue but do you know if there's anyway to sort by tag version in the releases that Polymer CLI pulls down?

**Comment by FredKSchott** [comment]
Can you create a new issue in the CLI? Right now we just take the latest release by date. It'll take some additional work to get a list of all release and then compare them all to find the one with the highest version. 

If we only title our releases as version numbers we can get away with just comparing them alphabetically.
