### ISSUE TITLE
Polymer init starter-kit throwing error

### ISSUE THREAD

**Issue by prithviraju1369** [PolymerElements/polymer-starter-kit#909]
F:\polymerp>polymer init starter-kit
error:   Uncaught exception: SyntaxError: Unexpected token ILLEGAL
error:   SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\prith_000\AppData\Roaming\npm\node_modules\p
olymer-cli\node_modules\yeoman-environment\lib\environment.js:7:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by jsilvermist** [comment]
When you type: `polymer --version`
Does it say: `0.16.0`?
If not, run: `npm cache clean && npm install -g polymer-cli`

If it's still not working, try update your Node install.

**Comment by prithviraju1369** [comment]
version is 0.16.0 only. still i am getting the error ....

**Comment by robdodson** [comment]
@prithviraju1369 I'm assuming you're on Windows right? Can you run `node --version` and tell us what you're on?

**Comment by prithviraju1369** [comment]
yes i am on windows @rob v4.1.0

**Comment by robdodson** [comment]
@chuckh Have you had a chance to try the CLI on windows?

**Comment by chuckh** [comment]
@chuckh have not had a chance yet to try CLI on windows.  Maybe next week.

**Comment by prithviraju1369** [comment]
@robdodson @chuckh i have just upgraded my node version from v4.1.0 to v4.5.0, maybe its just old version issue. its solved now. thanks
Offtopic: @robdodson clarification regarding polymer. if i am using angular 2 and polymer in my app, which is better
**routing** : app-router or angular router ? 
and 
whats the best way to integrate PolymerLibrary into angular 2, as angular 2 is a framework.

**Comment by robdodson** [comment]
@prithviraju1369 if you're using angular2 for your app then you probably want to rely on their router and just use the custom elements as leaf nodes. You can read up on using Angular2 and Custom Elements (not specific to Polymer) here https://medium.com/@dee_bloo/custom-element-inter-op-with-angular-2-ed75f013a9ba#.gunbxhjdg or look at an example of using them together here https://twitter.com/manekinekko/status/735220896835731456
