### ISSUE TITLE
Lots of errors from polymer lint

### ISSUE THREAD

**Issue by vdhpieter** [PolymerElements/polymer-starter-kit#911]
### Description

On a fresh project the polymer lint command wil give a lot of errors
### Expected outcome

no errors

### Actual outcome

lots of errors

### Steps to reproduce

1. init a fresh starter-kit project
2. run polymer lint

**Comment by chuckh** [comment]
This is a problem with `polylint`, see polylint fails for PRPL apps and with scope variables not present in properties obj:  https://github.com/PolymerLabs/polylint/issues/144.

**Comment by abdonrd** [comment]
Close in favor to the new [Polymer Linter](https://github.com/Polymer/polymer-linter).
