### ISSUE TITLE
Event listeners in new starter kit 2

### ISSUE THREAD

**Issue by jakelodowitz** [PolymerElements/polymer-starter-kit#914]
I installed new starter kit and wanted to do some neon-animations. But somehow when i use the basic example of Events found on polymer site i cant select the element i want (span, div) inside my custom element, instead i select the whole element. Basicaly what i did was i created a simple dom-repeat template inside the default my-view1.html and added the listeners { 'click': 'onClick' } but when i click on anything inside i only select the my-view1 element, event.target is alwys the my-view1 element (parent element). 

I know this worked in the old polymer starter kit so i want to know if im doing something wrong .

**Comment by robdodson** [comment]
It's not clear what your setup is from the explanation. Can you share a snippet of code?

**Comment by jakelodowitz** [comment]
Sure mate.
 When i use this code: https://github.com/PolymerElements/neon-animation/blob/master/demo/tiles/circles-page.html in the starter kit 1.3 without the app-layout,
this code:
 _onClick: function(event) {
      var target = event.target;
      if (target.classList.contains('circle')) {
        // configure the page animation
        this.sharedElements = {
          'hero': target
        };
event.target returns precisely the element i clickes on, the one containing .circle class. And it works fine.
But in the new 2.0 version of the polymer-cli it always returns the parent element.

You can use the polymer-cli, add an listener on an entire element but when you click on the "circle" it selects the whole "animated-page" or the custom-element i created.

I hope it makes more sense now.

**Comment by robdodson** [comment]
Are you adding the listeners from outside of the element? I believe the difference you're seeing is that with native Shadow DOM events are retargeted. [This line](https://github.com/PolymerElements/polymer-starter-kit/blob/master/index.html#L52) is what opts you in to native Shadow DOM.

Example:

```
x-foo
  #shadow-root
    .circle
```

If I listened to click events on x-foo, even if someone clicked the circle, it would be retargeted to x-foo to preserve encapsulation. So only x-foo itself would be able to add listeners for .circle.

Are your event listeners being setup inside of the element that contains .circle. Or are your listeners outside of that element?

**Comment by jakelodowitz** [comment]
Thanks alot my dear ser, removing that line makes it work as i need.

**Comment by robdodson** [comment]
@jakelodowitz yes but now you're relying on polyfill behavior which will possibly break sometime in the future. It would be good to make sure you're working with native Shadow DOM correctly. Can you share the code where you setup your event handler? Maybe a github gist of the file itself?

**Comment by jakelodowitz** [comment]
Ofcourse my Dear sir.

Basicaly i used the Starter kit 2 and the Tiles demo neon animated pages.

//--- my-app.html ---//

<neon-animated-pages id="pages" selected="0">          
          <circles-page on-circle-click="_onCircleClick"></circles-page>
          <squares-page on-click="_onSquaresClick"></squares-page>          
 </neon-animated-pages>

<script>
    Polymer({
      is: 'my-app',
      
      _onCircleClick:function(event) {
        this.$.pages.selected = 1;
      },
      _onSquaresClick:function(event) {
        this.$.pages.selected = 0;
      }
    });
  </script>

I copied entire circles-page.html and the squares-page.html from the Tiles demo. So when i use the "dom: 'shadow"' nothing happens and circles-page line 77 "var target = event.target" returns : circles-page.iron-selected.

Without the "dom: 'shadow"' everything works like in the demo. 
var target returns : "circles-page.style-scope.my-app.x-scope.circles-page-0.iron-selected".

Probably im doing something wrong and i hope this kinda explains whats my problem.

**Comment by jakelodowitz** [comment]
Dear sir,

I read a little about shadow dom and i found that if i replace 

`var target = event.target;` with `Polymer.dom(event).rootTarget;` inside the circles-page.html everything works with:

```
window.Polymer = {
        dom: 'shadow',        
        lazyRegister: true
      };
```

Is this the right way to go?

**Comment by robdodson** [comment]
OK, moved over to this pull request that also contains an explanation. Going to close the issue here and suggest folks file future bugs against neon-animated-pages against that repo. @jakelodowitz I think your fix of using `rootTarget` is a good one. Another option would be to add the listeners directly to each circle element, then they wouldn't get retargeted.
https://github.com/PolymerElements/neon-animation/pull/204
