### ISSUE TITLE
Blank page on Firefox with build/bundled version from cache

### ISSUE THREAD

**Issue by davideicardi** [PolymerElements/polymer-starter-kit#915]
### Description

When I run `polymer serve build/bundled` and open it with Firefox (version 48.0) I get a blank page.
It works perfectly on Chrome and on Firefox with just `polymer serve`.

It also works the first time I load the page but if I hit `F5` I get the blank page.

I suspect it is something related to the Service Worker, because if I hit `Ctrl+F5` it works again, but then if I close and reopen the page (or hit `F5`) it show me again the blank page.

I'm using `Polymer CLI` v. 0.16. I have just modified some page name and titles. It can be some of my changes but I really don't understand.

### Live Demo

https://amp-on-fire.firebaseapp.com/

### Steps to reproduce

- Open https://amp-on-fire.firebaseapp.com/dashboard on Firefox
- Hit `F5`

### Browsers Affected

- [X] Firefox

**Comment by robdodson** [comment]
Opening the network panel it looks like maybe the service worker is infinitely requesting app.html and webcomponents-lite.js

My short term suggestion would be to try commenting out the line in index.html that registers the service worker https://github.com/PolymerElements/polymer-starter-kit/blob/master/index.html#L87-L92

Also, can you share the contents of your `polymer.json` file?

cc @FredKSchott @justinfagnani

**Comment by davideicardi** [comment]
Oh sorry my fault!
I have renamed `my-app.html` to `app.html` without changing `polymer.json` file:

`  "shell": "src/my-app.html",`

Sorry again and thank your for your quick response!

**Comment by robdodson** [comment]
No worries.

@FredKSchott @justinfagnani do you think it would be possible for the CLI to check for the existence of the files listed in polymer.json at build time and fail if it can't find them? I've made similar mistakes before where I forgot to update something in polymer.json

**Comment by FredKSchott** [comment]
This should have failed during build because it couldn't find the file, but maybe that's regressed.

These kinds of bugs & improvements are at the top of our list now that analyzer work is humming along, I'll create an issue to track this specific feature request

**Comment by equinusocio** [comment]
I have the same issue, but when i run the build command no `service-worker.js` is generated. The console show no errors.

**Comment by FredKSchott** [comment]
We've had some trouble with hanging and silently failing builds in the past, we're about to merge a PR to fix this and emit proper error messages. In the mean time, make sure you're seeing "Build Complete" in your console logs. If you are not, the build did not complete. 

This is almost always caused because an import path is pointing to a file that doesn't exist.

**Comment by equinusocio** [comment]
@FredKSchott The error message will be always emitted or only under the `-v` flag?

**Comment by FredKSchott** [comment]
@equinusocio currently some builds fail silently, without emitting any error message

**Comment by equinusocio** [comment]
There is a way to ignore files from build optimization? I get this error on a dependency:
```
Unable to optimize .html file /Users/*******/******/****/***/pro-marketing-automation/bower_components/clab-ui-components/clab-ui-components-no-polymer.html 
{ err: {} }
```

**Comment by FredKSchott** [comment]
The next version of the CLI will have controls for which optimizations you'd like to run. But the CLI won't support including/excluding specific files. You'll need to use polymer-build to do that.

Fwiw, an "unable to optimize" warning won't break the build. The build will continue, but that file will not have been optimized, which it sounds like is what you want.

**Comment by equinusocio** [comment]
I don't know if the error {{}} is related to this file... Anyway thank you.

Il lun 30 gen 2017, 19:27 Fred K. Schott <notifications@github.com> ha
scritto:

**Comment by FredKSchott** [comment]
Yea, it looks like html-minifier is returning an empty object for an error. That might be a bug though, we should look into that.

**Comment by equinusocio** [comment]
👍

Il lun 30 gen 2017, 20:50 Fred K. Schott <notifications@github.com> ha
scritto:
