### ISSUE TITLE
404 not working polymer/build/bundled

### ISSUE THREAD

**Issue by vdhpieter** [PolymerElements/polymer-starter-kit#917]
### Description

The 404-redirect doesn't work in the bundled version if you go to a wrong URL.
### Expected outcome
Sended to the 404 page

### Actual outcome
Site hangs and navigation doesn't work

### Steps to reproduce
1. run the bundled version of the app
2. go to a wrong URL

### Browsers Affected

only tested in chrome
- [ x] Chrome

**Comment by robdodson** [comment]
It's not clear from your description which version you're having issues with. You mentioned:

> The 404-redirect doesn't work in **de bundled** version if you go to a wrong URL.

But you also said:

> run the **bundled** version of the app

Either way I wasn't able to reproduce the issue.

How are you serving the project? Typically I do `polymer serve build/bundled`. If you're doing this on your own server you'll want to make sure that the server is always serving `index.html` for every request.

**Comment by vdhpieter** [comment]
I updated my issue, it meant "the" bundled issue but I am from Belgium and a the Dutch word for "the" is "de". It was a typo.

**Comment by vdhpieter** [comment]
It tried it again and it is working locally but not on my server though it redirects all the requests to index.html

**Comment by robdodson** [comment]
do you have a liver version hosted somewhere?

**Comment by vdhpieter** [comment]
![image](https://cloud.githubusercontent.com/assets/12659249/18332281/9a667990-7565-11e6-8bf3-01d358fe0d32.png)
I get these errors...

**Comment by vdhpieter** [comment]
I have a live version hosted somewhere, but I rather not share the link in public if I could PM it you somehow...

**Comment by robdodson** [comment]
sure you can email it to me. robdodson at google dot com

**Comment by daniel-tabarcea** [comment]
Does anyone remember how this was fixed? I'm having the exact same issue and I can't figure out what the problem is.

**Comment by keanulee** [comment]
Are you sure that the network request for my-invalidpath.html fails/404's? That needs to be the case for the 404 fragment to be loaded https://github.com/PolymerElements/polymer-starter-kit/blob/master/src/my-app.html#L164

**Comment by daniel-tabarcea** [comment]
Yes, the callback was there. But i eventually found out that the problem was with a custom express server that was being used; the routing was such that requests for non-existent static files would redirect to index and that would return 200, so importHref wasn't triggering the error callback. Anyway, thank you for taking the time to answer my question, i really appreciate it!
