### ISSUE TITLE
Gulp serve doesn't properly watch changes to .css files

### ISSUE THREAD

**Issue by adamaviner** [PolymerElements/polymer-starter-kit#92]
When running with gulp serve, changes to .html files are watched and the browser auto reloads to reflect them, however when making changes to .css files, gulp serve doesn't seem to be watching them and nothing happens.

Seems to be fixed by removing curly braces around .css in lines 198 199 of gulpfile.js like so:
 gulp.watch(['app/styles/**/*.{css}'], ['styles', reload]); ->  gulp.watch(['app/styles/**/*.css'], ['styles', reload]); 
  gulp.watch(['app/elements/**/*.{css}'], ['elements', reload]);  ->   gulp.watch(['app/elements/**/*.css'], ['elements', reload]);

**Comment by moneal** [comment]
Noticed the same problem and removed the braces to fix. I was wondering if it was intentional for some reason.

**Comment by addyosmani** [comment]
Oversight on my part. Would either of you like to PR back this change? If not, I'll land it tomorrow. Thanks for pointing it out.
