### ISSUE TITLE
NGINX Server Config Errors

### ISSUE THREAD

**Issue by haydenbjyoung** [PolymerElements/polymer-starter-kit#921]
### Description
I am unable to properly serve "pretty URLs" through NGINX with the `try_files` config line in the virtual server settings.

### Expected outcome

I should be able to manually browse to http://example.com/home or http://example.com/about.

### Actual outcome

I get an NGINX 404 message, unless I navigate from http://example.com/, but only from that root page.

### Live Demo

[MirukaiYT](http://mirukai.uk.to/)

### Steps to reproduce

Create a generic page/set of pages and try to navigate to each individual page through the address bar.

### Browsers Affected

- [*] Chrome
- [*] Firefox
- [*] Safari 9
- [*] Safari 8
- [*] Safari 7
- [*] Edge
- [*] IE 11
- [*] IE 10

**Comment by robdodson** [comment]
This sounds like an NGINX issue, not PSK

**Comment by sjcalamia** [comment]
"This is not our problem" is essentially what you said, which is tantamount to, "RTFM", which is a terrible response if you're trying to teach people Polymer, which I'm pretty sure what the PSK is specifically _for_.

It may be an NGINX issue, but it would be wonderful if someone, anyone really, could post a sample vhost server config that is designed to serve a polymer app with routing. Try searching for `nginx polymer server config` and you'll see that you get this bug report and a whole lot of other people asking for this, but literally no one replying or being helpful. Either Polymer is not catching on, or people aren't using it with nginx, or all the devs working with Polymer are a**holes, in which case, I'm starting to question why I should... is this even worth the time?

**Comment by robdodson** [comment]
We provide instructions for [deploying to App Engine and Firebase](https://www.polymer-project.org/2.0/start/toolbox/deploy#deploy-to-a-server). Those are the two technologies our team is most familiar with and what we recommend when using PSK.

> It may be an NGINX issue, but it would be wonderful if someone, anyone really, could post a sample vhost server config that is designed to serve a polymer app with routing. Try searching for nginx polymer server config and you'll see that you get this bug report and a whole lot of other people asking for this, but literally no one replying or being helpful.

I googled `nginx polymer server config` and [the first result was a StackOverflow suggestion](https://stackoverflow.com/questions/34713474/polymer-starter-kit-pretty-urls-on-nginx-server). Does this fix your issue? I think the main point is to make sure any request (minus those for .css, .js, and images) always returns index.html, that way manually navigating to `example.com/about` would send index.html, the client side router would start, it would look at the url, and show the about page. I _think_ that's what that NGINX config is doing but again, I'm not an NGINX expert :)

> Either Polymer is not catching on, or people aren't using it with nginx, or all the devs working with Polymer are a**holes, in which case, I'm starting to question why I should... is this even worth the time?

Please refer to [the code of conduct](https://github.com/Polymer/project/blob/master/Code_of_Conduct.md) when engaging with this community.

**Comment by kaseyhinton** [comment]
I think I was able to get a polymer app to work with nginx. Let me check on my server when I get home and I will share my config!
