### ISSUE TITLE
Feedback requested - App template

### ISSUE THREAD

**Issue by bwh-rl** [PolymerElements/polymer-starter-kit#924]
Hi all.

Based on the starter-kit, i've created an app template for our app, capable of hosting an bigger app.
Live Demo: https://bwh-rl.github.io/
Repo: https://github.com/bwh-rl/bwh-rl.github.io

All feedback or suggestions are appreciated.

**Comment by robdodson** [comment]
Hi @bwh-rl,

I'm going to close this so it doesn't look like an open bug on Starter Kit. We're working on creating a better space for folks to share their templates and should have more to show around that in October
