### ISSUE TITLE
Check Polymer.isInstance() before importHref?

### ISSUE THREAD

**Issue by stramel** [PolymerElements/polymer-starter-kit#930]
### Description
I noticed that @robdodson in one of the PolyCasts recommended doing a `Polymer.isInstance()` (or `instanceOf` in Polymer 2.0) check before doing a `this.importHref()`.

### Expected outcome
Expected `Polymer.isInstance()` check before doing a `this.importHref()`

### Actual outcome
No `Polymer.isInstance()` check
https://github.com/PolymerElements/polymer-starter-kit/blob/master/src/my-app.html#L131

If this is not the route to go, can you explain why to help me better understand?

**Comment by robdodson** [comment]
I think we're making the assumption that none of these elements have already been imported. If they have, (I think) importHref won't try to load them again (@sorvell is that accurate?). In Polymer 2.0, `.isInstance` has been removed, as you can instead use the native `instanceof`. From the [docs](https://github.com/polymer/polymer/tree/2.0-preview#removed-api):

> Polymer.instanceof and Polymer.isInstance: no longer needed, use instanceof and instanceof Polymer.Element instead.

**Comment by stramel** [comment]
@robdodson I was just basing it off of a previous polycast that you had done. If this has been baked into the `importHref` that's awesome! I did notice that the method was dropped in 2.0, thanks!

**Comment by robdodson** [comment]
yeah it appears that it does. Look at the `<head>` in a PSK app. As you click the menu items you'll see it adds each one using importHref but if you go to a previous item it won't add it
