### ISSUE TITLE
Polymer endless resource request 

### ISSUE THREAD

**Issue by nigeltiany** [PolymerElements/polymer-starter-kit#931]
Polymer endless resource request when serving the bundled project in firebase.

Viewing the network tab on chrome, the response GET request that has this error is a request to the paper-dialog element.
### Live Demo

Go to https://envoy-app.firebaseapp.com
Login with email:newuser@mailer.com password:password

Result,
The dashboard will not load, observe the network.
### Browsers Affected (Confirmed,  others may face the same issue.)
- [x] Chrome
- [x] Firefox
  Confirmed,  others may face the same issue.

**Comment by robdodson** [comment]
Hard to say what's up without seeing the source

**Comment by robdodson** [comment]
@nigeltiany are you able to share the source in some fashion?

**Comment by nigeltiany** [comment]
I found the problem, it wasn't with the source
Running `polymer build` doesn't copy all the bower dependencies in bower components

**Comment by robdodson** [comment]
@nigeltiany it should, so that may be a bug. What dependencies weren't copied over? /cc @FredKSchott

**Comment by FredKSchott** [comment]
@nigeltiany you can include undetected dependencies using the `includeDependencies` flag/polymer.json property. Would love to hear which were missing if you can respond, so that we can look into helping others with documentation.

**Comment by motss** [comment]
@nigeltiany Do you lazy load your `paper-dialog` using `importHref` or something like that in your app?

**Comment by robdodson** [comment]
I'm going to close this as we're not getting a response but happy to open it again if others hit a similar issue and can provide feedback.
