### ISSUE TITLE
Add style guide/beautifier 

### ISSUE THREAD

**Issue by robdodson** [PolymerElements/polymer-starter-kit#933]
Need to add a link to a style guide and some eslint rules so PRs can have a consistent look and feel

**Comment by abdonrd** [comment]
Yes, please!

**Comment by robdodson** [comment]
@abdonrd I don't have a strong opinion here, do you want to take this on?

**Comment by abdonrd** [comment]
Ok! I think we should use [ESLint](https://github.com/eslint/eslint) to lint Javascript.
And maybe [StyleLint](https://github.com/stylelint/stylelint) for CSS.

**Comment by robdodson** [comment]
ok. i'm doing this today. it's happening. for reals.

**Comment by robdodson** [comment]
We may have to hold off on Stylelint. It doesn't seem to process the line numbers correctly. Added a +1 to this issue https://github.com/ccbikai/stylelint-processor-html/issues/1

**Comment by abdonrd** [comment]
Ok, thanks @robdodson!

**Comment by abdonrd** [comment]
@robdodson could you integrate it with VSCode? I can't: https://github.com/shinnn/vscode-stylelint/issues/52

**Comment by TimvdLippe** [comment]
ESLint was introduced in #951 but this issue was not closed. @robdodson I think we can close it now or do you explicitly want to mention `eslint` in the README?
