### ISSUE TITLE
polymer build copy all the files

### ISSUE THREAD

**Issue by samuelcardillo** [PolymerElements/polymer-starter-kit#939]
Hi, 

I have two folders inside `src`, one being `elements` which contain one custom element (lets call it `custom-elements.html`) and the other one being `fragments` which contain one view.

I am importing, inside my fragment (the view), the custom element that is in `elements` then I run `polymer build` which does vulcanization. So the code of the custom elements is copied & pasted in my fragment, making the file `custom-elements.html` useless as it is no longer called anyway but still, `polymer build` copy the folder `elements` with the file inside in the `bundled` folder. 

I have been trying multiple solutions in the `polymer.json` and nothing worked. Still, when I don't import `custom-elements.html` in my view, `polymer build` is able to exclude it from `bundled`. 

So I am not sure if the problem comes from me or if its Polymer CLI that is having a problem.

Thanks in advance

**Comment by robdodson** [comment]
@samuelcardillo I think, rather than try to filter out a bunch of files, polymer build just does the easiest thing possible which is to copy everything over. @FredKSchott can correct me if i'm totally wrong about this (I probably am :P)

**Comment by motss** [comment]
@samuelcardillo @robdodson Suprising enough, you can do filtering at `sourceGlobs`.

```json
"sourceGlobs": [
  "src/**/*",
  "!src/dont_copy_this_folder/**',
  "images/**/*",
  "bower.json"
],
```

**Comment by samuelcardillo** [comment]
@motss We already spoke about that on Slack, it doesn't work as my folder `elements` contain a file imported by a fragment but vulcanized during the `polymer build` process making the folder `elements` useless as the code of the file is now vulcanized in the fragment.

**Comment by FredKSchott** [comment]
Great question, I think we've seen this reported before. The analysis step that detects and adds your `elements/` folder is the first thing to happen in the build process. It doesn't know whether or not bundling (vulcanize) will be called later in the process.

We could look into fixing this by having the "bundle" step remove files that it bundles from the build stream. I don't believe it is currently doing this. Adding an issue to polymer-build to track this.

**Comment by samuelcardillo** [comment]
Gotcha. So it is not implemented (yet?) and the only way to do it for now is manually at the end of the `polymer build` process. I might write a temporary gulp workflow on the custom build with the hope of seeing that feature natively working in the polymer cli. Thanks @FredKSchott!

**Comment by FredKSchott** [comment]
np! Thanks for reporting @samuelcardillo
