### ISSUE TITLE
Questions about @media queries

### ISSUE THREAD

**Issue by kaelig** [PolymerElements/polymer-starter-kit#94]
## Double min-width and naming

Seen in [app-theme.html#L224](https://github.com/PolymerElements/polymer-starter-kit/blob/master/app/elements/app-theme.html#L224):

```css
/* desktop-xlarge */
@media all and (min-width: 1601px) and (min-width: 1920px) { }
```

- `desktop-xlarge` is for 1920dp and up, according to the spec (not 1601px)
- This code contains `min-width` twice, is it normal?

## Breakpoint values

The Material spec is ambiguous about the value at which breakpoints start and end (599, 600, 601?) but having a breakpoint starting at 481dp seems strange since 480dp is a common screen width. It would probably make more sense to have `(min-width: 480px)` instead of `(min-width: 481px)`.

## Encourage a mobile-first approach

As per @petele's [guidelines](https://developers.google.com/web/fundamentals/layouts/rwd-fundamentals/how-to-choose-breakpoints?hl=en): 

> Design for the smallest mobile device first, then progressively enhance the experience as more screen real estate becomes available.

There are multiple ways to encourage a mobile-first thinking, here is one:

```css
/* Default styles go here (explain the mobile-first approach) */
…

/**
 * [Description of the grid system]
 * Note: you may use max-width queries when necessary
 */

/* handset-medium */
@media (min-width: 360px) { }
…

/**
 * Layouts over 1600dp wide may let the layout grow until it 
 * hits a max width. At this point, the grid may do one of the 
 * following:
 *
 * - Become center aligned with increased margins
 * - Remain left aligned while the right margin grows
 * - Continue to grow while revealing additional content
 */
@media (min-width: 1600px) { }
/* x-large */
@media (min-width: 1920px) { }
```

**Comment by addyosmani** [comment]
Good questions!

> This code contains min-width twice, is it normal?

Was fixed in master over the weekend. This was a typo. 

> desktop-xlarge is for 1920dp and up, according to the spec (not 1601px)

We began implementing this a little while before the public version of the adaptive spec got updated. Now that 1920dp is the baseline for xlarge, I agree we should update to match for sure.

> It would probably make more sense to have (min-width: 480px) instead of (min-width: 481px).

As you mentioned, the spec was ambiguous about this so I made a call. I'm personally fine with us starting with `480px` rather than 481 given we have some flexibility here. Are there other related changes here you had in mind for the breakpoints in app-theme? I'd like to land them sooner rather than later so, early feedback is definitely welcome :)

> Encourage a mobile-first approach

For the first version of the kit, the Material team didn't really have strong opinions about how we should tackle the mobile first approach to layout beyond defining breakpoints. I'm happy to have a chat with them about your proposal, but if you're interested / have time to flesh it out in a PR that would accelerate us switching approaches. If not, no worries! I might prototype what your version would look like over the weekend.

**Comment by kaelig** [comment]
It would be interesting to understand the thought process behind the grid a bit better because there are a few ambiguous things in the spec (about the number of columns and the min-max width values).

I took a fresh look at it and I interpreted it as a hierarchy of breakpoints (major vs minor).

Here's my interpretation (not sure how it would look like in code yet):

```css
/* Major breakpoints */

/* 0-599       xsmall   */
/* 600-1023    small    */
/* 1024-1439   medium   */
/* 1440-1919   large    */
/* 1920+       xlarge   */


/* Minor breakpoints (tweakpoints) */

/* 0-359      small handset (portrait)                            xsmall */
/* 360-399    medium handset (portrait)                           xsmall */
/* 400-479    large handset (portrait)                            xsmall */
/* 480-599    large handset (portrait) small handset (landscape)  xsmall */
/* 600-719    small tablet (portrait) medium handset (landscape)  small  */
/* 720-839    large tablet (portrait) large handset (landscape)   small  */
/* 840-959    large tablet (portrait) large handset (landscape)   small  */
/* 960-1023   small tablet (landscape)                            small  */
/* 1024-1279  large tablet (landscape)                            medium */
/* 1280-1439  large tablet (landscape)                            medium */
/* 1440-1599                                                      large  */
/* 1600-1919                                                      large  */
```

Putting it like this before coding it is interesting because it raises a few more questions:
- what to do when 2 ranges have the same names (such as "large tablet")?
- one range is very small (the 360-399px minor breakpoint), what are the use cases for this one?
- the `#overlay` is given a min-width of 360px (to match the first breakpoint) on small screens but actually it probably should be full width and flexible until a certain range
- Where should most important layout changes happen?

Thoughts?

It'd be great if we could write [custom media queries](http://dev.w3.org/csswg/mediaqueries-4/#custom-mq). Any idea when a polyfill might be coming?

**Comment by addyosmani** [comment]
> It would be interesting to understand the thought process behind the grid a bit better because there are a few ambiguous things in the spec (about the number of columns and the min-max width values).

Happy to loop in members of the design team on questions you may have regarding the grid. We've implemented a version of it in MDL in case you're curious how far it was possible to get with the current spec. 

> what to do when 2 ranges have the same names (such as "large tablet")?

My best intelligent guess is that either one of the two are meant to be targeted or there's another factor the design team intended to be taken into account to avoid these two named breakpoints being the same. 

> one range is very small (the 360-399px minor breakpoint), what are the use cases for this one?

I believe these came from a study of the device metric tool over at https://www.google.com/design/tool/devices/. There are smaller handsets the spec attempts to provide some guidance around.

> the #overlay is given a min-width of 360px (to match the first breakpoint) on small screens but actually it probably should be full width and flexible until a certain range

I agree.

> Where should most important layout changes happen?

Could you expand on what you mean here? One interpretation is which breakpoint should most layout changes occur in. I assume this would be per Pete's other responsive guidance on Web Fundamentals. 

> It'd be great if we could write custom media queries. Any idea when a polyfill might be coming?

We actually tried exploring a grid + breakpoint system using named media queries before switching back to standard mqs before launch. I'd say "soon" but it requires some further thought :)

**Comment by kaelig** [comment]
Cheers,

> Happy to loop in members of the design team on questions you may have regarding the grid. We've implemented a version of it in MDL in case you're curious how far it was possible to get with the current spec.

Very interested indeed!

> My best intelligent guess is that either one of the two are meant to be targeted or there's another factor the design team intended to be taken into account to avoid these two named breakpoints being the same.

Ok, would be great to clarify so that implementation and guidelines match the same rationale.

> > Where should most important layout changes happen?
>
> Could you expand on what you mean here?

MD guidelines could recommend authors to make macro-layout changes in the major breakpoints and then use tweakpoints to… tweak things that break and/or improve the experience.

So the question is: what are these major breakpoints at which macro-layout changes should happen?

> We actually tried exploring a grid + breakpoint system using named media queries before switching back to standard mqs before launch. I'd say "soon" but it requires some further thought :)

That sounds really cool. Looking forward to seeing what that looks like.

**Comment by robdodson** [comment]
I think I'm going to close this as it seems mostly related to material design breakpoints and PSK has been greatly simplified now to act as more of a basic getting started template. This feels like it falls more into the wheelhosue of the Material Design/Material Design Lite team.
