### ISSUE TITLE
App not working with 404 route when deployed to Firebase

### ISSUE THREAD

**Issue by motss** [PolymerElements/polymer-starter-kit#941]
### Expected outcome

Display 404 page when route is not found.

### Actual outcome

1. App not working properly when hitting 404.
2. No 404 page displays.
3. Errors in Dev Tools like `instanceCount of undefined, _flushNextRender of undefined`, etc.

### Steps to reproduce
1. Clone `polymer-starter-kit`.
2. Run `firebase init` and enable url rewrite in Firebase.
3. Run `firebase deploy` to deploy the app.
4. Open the URL and route to an undefined route.
5. Route not working, no 404 page displays and errors in the Dev Tools.

### Browsers Affected
- [x] Chrome
- [x] Firefox
- [x] Safari 10
- [x] Edge
- [x] IE 11

**Comment by motss** [comment]
Just found the cause of this matter. It's basically a routing issue with Firebase Hosting when rewriting the URL for SPA and it's again related to #754.

Solution (kind of but it works):

```json
"rewrites": [
  {
    "source": "!{/bower_components,/src}/**",
    "destination": "/index.html"
  }
],
```

**Comment by robdodson** [comment]
@motss can you give the source suggestion in this comment a shot:
https://github.com/Polymer/docs/issues/1755#issuecomment-249678734

**Comment by motss** [comment]
@robdodson This works as well~ Like a charm! 😸

**Comment by robdodson** [comment]
nice! ok i'll add it to the polymer docs

**Comment by luizaugustoventura** [comment]
> Just found the cause of this matter. It's basically a routing issue with Firebase Hosting when rewriting the URL for SPA and it's again related to #754.
> 
> Solution (kind of but it works):
> 
> ```json
> "rewrites": [
>   {
>     "source": "!{/bower_components,/src}/**",
>     "destination": "/index.html"
>   }
> ],
> ```

Worked perfectly here. But now I have a '#' in between my domain and the actual page, just like 'https://mydomain.com/#/homepage'. Do you know a way to remove that '#' ?

**Comment by IsaacEduardo** [comment]
Olá pessoal. Tentei as sugestões aqui apresentadas infelizmente o erro continua
