### ISSUE TITLE
Vulcanize: How to?

### ISSUE THREAD

**Issue by mbana** [PolymerElements/polymer-starter-kit#945]
Is it possible to make a completely static build, say, something like vulcanize?

Effectively, I want to inline all deps into just a single file for all the HTML imports.
Not too worried about the CSS/JS.

Cheers,

**Comment by robdodson** [comment]
Polymer CLI runs vulcanize when you do `polymer build`. I believe right now it looks at the fragments in your `polymer.json` to created sharded bundles that you can lazy load. I guess you could create an import that imports all of your other imports and just list that as your only fragment, maybe that'd work

**Comment by abdonrd** [comment]
Closed in favor to the [Polymer CLI](https://github.com/Polymer/polymer-cli) with [Polymer Build](https://github.com/Polymer/polymer-build).
