### ISSUE TITLE
service-worker.js still uses absolute paths

### ISSUE THREAD

**Issue by pomber** [PolymerElements/polymer-starter-kit#947]
### Description
[`build/bundled/service-worker.js`](https://github.com/PolymerElements/polymer-starter-kit/blob/gh-pages/service-worker.js#L32) still uses absolute paths: 
```
/* eslint-disable quotes, comma-spacing */
var PrecacheConfig = [["/bower_components/webcomponentsjs/webcomponents-lite.min.js","02395895d5d08242c6ba93518a6da2c5"],["/index.html","c11c33a4a1e4e98d807ecb780291f663"], ...];
```

### Expected outcome
After #940 paths should be relative

### Actual outcome
[service-worker](https://github.com/PolymerElements/polymer-starter-kit/blob/gh-pages/service-worker.js) still uses absolute paths, generating 404s when deployed in gh-pages.

### Live Demo
https://polymerelements.github.io/polymer-starter-kit/

### Steps to reproduce

1. clone repo
2. bower i
3. polymer build

**Comment by robdodson** [comment]
We're backing out the relative path change. See comment here: https://github.com/PolymerElements/polymer-starter-kit/pull/940#issuecomment-261645920
