### ISSUE TITLE
Migration problem from PSK1 to PSK2

### ISSUE THREAD

**Issue by MacTheZazou** [PolymerElements/polymer-starter-kit#949]
### Description

Hi, I'm actually migrating my dev project from PSK1 to PSK2, and I'm having major problem with the migration of a custom element.

I use a custom element to crop image in the browser. The element was working well with PSK1, but with PSK2, there is some heavy bug I don't understand...

My first problem is: CSS don't apply to the element.

Here is the element:

http://pastebin.com/zSEKD7NQ

If I remove all the ::content in the CSS, the style is working again (only on chrome), but it is impossible to drag the cropper. 

I think I just miss some important details, but after 4 hours debugging, I just can't see it. And the migration guide don't help..

Thank you in advance,

Mac

Expected: 
<img width="587" alt="cropexpected" src="https://cloud.githubusercontent.com/assets/1732909/20469140/f7f1188a-afe0-11e6-8924-629a34f88745.png">

**Comment by robdodson** [comment]
Any luck finding a solution?

The main differences with PSK 1 and PSK2 are mainly around layout and folder structure. If something was working in CSS in PSK1 and stopped working in PSK2 I would first try to test the element in isolation. Does it work if you just create a basic page and only load polymer, the element, and the things it depends on?
