### ISSUE TITLE
Where's "Web App Install Banner"?

### ISSUE THREAD

**Issue by shawnExplore** [PolymerElements/polymer-starter-kit#95]
This was presented as a "feature" of the starter kit, but no such install banner pops up on my android device, nor can I find any code for this banner while browsing through this repo.

Do I need some specific version of browser for this to work, or is it not actually implemented? Also, I notice the app he's actually showing is IOWA, which also doesn't pop up any such banner when I navigate to the url from my Android Lollipop phone..

[video showing "web app install banner"](https://youtu.be/fD2As5RmM8Q?t=2210)

I'd love to know how to display such a banner  - it is an install experience almost as easy (easier) as the native play store.

**Comment by deearcodes** [comment]
@shawnExplore There's no "Install Banner". Using a supported browser (I'm using Chrome) go to browser menu while browsing the Polymer Starter Kit web-app. If your ´manifest.json´ and ´<meta>´ tags are fine tap "Request desktop version". Search for the Polymer Starter Kit logo in your home screen.

**Comment by shawnExplore** [comment]
With further investigation it appears this feature has nothing to do with Polymer at all, and in fact isn't __directly__ controllable by the developer. It's something [introduced in Chrome 42](https://developers.google.com/web/updates/2015/03/increasing-engagement-with-app-install-banners-in-chrome-for-android?hl=en).  Please correct me if I'm wrong, but highlighting this "feature" (see video link) in a Polymer talk was a bit of false advertising :-1:  Feel free to reopen this ticket if it is supposed to be a feature of this repository.

**Comment by addyosmani** [comment]
@shawnExplore It's absolutely not false advertising. The native UI for the feature is exposed in Chrome 42, but requires several prerequisites normally manually setup by a developer in order to be enabled. This includes the web app manifest being required (we provide this), Service Worker setup (non trivial, and we provide this) and sufficient favicons setup. We also, provide this. Any normal website or webapp without these setup is not going to get access to the functionality.

**Comment by dandv** [comment]
The requirements for the app install banner to show have fluctuated over time, which might explain why the feature hasn't worked for @shawnExplore.

I've updated our [docs](https://github.com/google/WebFundamentals/pull/2617) to mention the requirement for defining a `start_url` in `manifest.json`, and PR #733 adds a section about adding the setting.

**Comment by addyosmani** [comment]
Thanks so much for updating the docs and landing this change for PSK, @dandv! We really appreciate it :)
