### ISSUE TITLE
default manifest.json should include description

### ISSUE THREAD

**Issue by raydaly** [PolymerElements/polymer-starter-kit#953]
Simple request. When submitting a web app to https://outweb.io and for other uses, a description is required. It would be useful to have "description" : "" in manifest.json so authors are reminded that while it is optional, it is required for outweb.io and other uses.

**Comment by robdodson** [comment]
Sure we can do that. Would you be interested in submitting a PR to add this feature?

**Comment by raydaly** [comment]
I'll do that.
