### ISSUE TITLE
 Modify starter kit to allow deploying to server subfolder out of the box

### ISSUE THREAD

**Issue by brancoliticus** [PolymerElements/polymer-starter-kit#959]
Please have a look at https://github.com/Polymer/polymer-cli/issues/442 for the reason that the current way of doing things doesn't satisfy my requirements. I would have opened an issue at this repository, but I thought it was abandoned and on it's way to being deleted.

Basically all link imports should be modified to point to the subfolder instead of the root url on project creation. Also the routing code has to be modified to take into account the subfolder.

**Comment by robdodson** [comment]
Thank you for the issue but I don't think is something we'll do with the starter kit. It doesn't do any code generation, so that kind of work would need to either be handled by polymer-cli or you could create a custom yeoman generator.
