### ISSUE TITLE
Starter kit should display app like behaviour in addition to the blog like behaviour it currently displays

### ISSUE THREAD

**Issue by brancoliticus** [PolymerElements/polymer-starter-kit#960]
In the app I have described at https://github.com/Polymer/polymer-cli/issues/442 I have the top component, that serves as starter kit 1 top level layout, also act as mediator between the page view components. So for example enter data in one page component and have it added to an array displayed in another page component with data binding via the top level layout component. I believe that this kind of a setup can't be mixed with the PRPL design pattern of loading stuff from the server on demand. Therefore I propose that an example of this kind of app functionality be added to the starter kit.

**Comment by robdodson** [comment]
I don't think we'll change the basic structure of PSK. It's meant to be a very simple starting point so folks can see how to put together a basic app. It's not meant to be a "do all the things" example. The 1.0 version was very much along those lines and it became very difficult to maintain.
