### ISSUE TITLE
[ Introductory video/presentation/Screenshot needed]

### ISSUE THREAD

**Issue by vikaskyadav** [PolymerElements/polymer-starter-kit#964]
Can somebody include an introductory video or presentation or screenshots related with usage of polymer-starter-kit for beginners?

**Comment by web-padawan** [comment]
@vikaskyadav there is a [polycast](https://www.youtube.com/watch?v=HgJ0XCyBwzY) about current PSK version.

**Comment by vikaskyadav** [comment]
@web-padawan , then I request you to place a link on the front. It would be easy for newcomers on your repo for better understanding I guess.

**Comment by web-padawan** [comment]
I'm not a maintainer of PSK, but adding that video to the readme is a good idea. @robdodson WDYT?

**Comment by robdodson** [comment]
Sure
