### ISSUE TITLE
How to modify PSK service worker?

### ISSUE THREAD

**Issue by 8ctopotamus** [PolymerElements/polymer-starter-kit#966]
The service-worker.js file is generated after running ```polymer build```. How do I modify the SW code that is generated in PSK before build time?

I'd rather make some tweaks to the existing SW code vs integrating platinum-sw.

**Comment by robdodson** [comment]
The service worker that's generated doesn't use platinum-sw, it uses [sw-precache](https://github.com/GoogleChrome/sw-precache). You can provide configuration to the sw-preachce-config.js file. Otherwise you may prefer to just write your own service worker

**Comment by 8ctopotamus** [comment]
Yep, I was just wondering if you could modify the generated SW. I guess writing your own is essentially the same thing.

Thanks!
