### ISSUE TITLE
Is `routeData` a missing property on `my-app`?

### ISSUE THREAD

**Issue by FredKSchott** [PolymerElements/polymer-starter-kit#971]
The new linter is warning that:

```
warn:    /src/my-app.html:107:3
    Property routeData not found in 'properties' for element 'my-app'
```

I believe this is because we've added an observer on my-app that uses it as if it is a property:

```
      observers: [
        '_routePageChanged(routeData.page)',
      ],
```

Should routeData be listed as a property on my-app? Or is the linter warning incorrect here?

/cc @robdodson @abdonrd @chuckh & @rictic for the linting angle

**Comment by FredKSchott** [comment]
I believe the old linter was warning incorrectly here and that it is okay to define variables like `routeData` that aren't described/exposed properties. The new linter doesn't warn.

Can someone comment to confirm just in case I'm wrong?

**Comment by rictic** [comment]
The old linter is pretty sensitive about use of undeclared properties, as it's hard to tell the difference between a typo and a legit property that's just not declared anywhere.

**Comment by robdodson** [comment]
For something like JSHint you usually add a comment. Something like `/* globals Foo */` or whatever. Maybe we could have stuff like that for the linter as well?

**Comment by rictic** [comment]
I definitely agree that we need pragmas in comments to communicate with the linter. For this case though, if you're adding a line to your source to tell the linter about a property, why not add it in the properties block?

```javascript
Foo: {}
```

It seems just as easy and doesn't introduce a new syntax for the user to learn or for us to maintain.

**Comment by robdodson** [comment]
I agree with that. OK I guess you could just complain for anything that isn't in the properties block and maybe folks could have a pragma to turn that off if they prefer the implicit prop creation?

**Comment by rictic** [comment]
:+1:

**Comment by abdonrd** [comment]
But the undeclared/"internal" properties (like `routeData`) should not be declared in the `properties` object, right? We only declare the "exposed" properties.

**Comment by rictic** [comment]
There are times when you need to use features of the `properties` object for internal properties, so it cannot be limited only to an element's public API. The best way to indicate that a property isn't part of an element's public API is to prefix it with an underscore.

**Comment by stramel** [comment]
so `routeData` and `subroute` should both be internal only?

**Comment by stramel** [comment]
I believe this has been addressed in the `2.0-preview`/`3.0.0` code by @justinfagnani

**Comment by FredKSchott** [comment]
@stramel link to fix? Want to confirm before closing

**Comment by stramel** [comment]
@FredKSchott Here ya go

https://github.com/PolymerElements/polymer-starter-kit/blob/2.0-preview/src/my-app.html#L126-L127

https://github.com/PolymerElements/polymer-starter-kit/pull/1014

**Comment by FredKSchott** [comment]
woot! Thanks for the link @stramel
