### ISSUE TITLE
polymer.json

### ISSUE THREAD

**Issue by jay8t6** [PolymerElements/polymer-starter-kit#975]
Rename sourceGlobs and includeDependencies to sources and extraDependencies.

**Comment by abdonrd** [comment]
Right now, the last Polymer CLI version hasn't this properties:

https://github.com/Polymer/polymer-cli/blob/master/CHANGELOG.md

I will create a PR for when the new version comes out.

**Comment by jay8t6** [comment]
sounds good. generator-polymer-init-custom-build is linking to PSK and it requires these properties since the generator is using 0.8.1 version of polymer-build.

**Comment by abdonrd** [comment]
Exactly! :) The Custom Build uses the last `polymer-build` version. :)
