### ISSUE TITLE
Test Case Error

### ISSUE THREAD

**Issue by Aadriya** [PolymerElements/polymer-starter-kit#977]
"before each" hook for "has the correct class":      TypeError: Cannot convert undefined or null to object       at Function.from (native)       at _toConsumableArray (src/reducers/country_reducer.js:22:182)       at exports.default (src/reducers/country_reducer.js:8:7)       at combination (node_modules/redux/lib/combineReducers.js:132:29)       at dispatch ---------------------------etc

----------------------------------------------------
  Error Shows When Run Test cases of sign up page (npm run test -- --watch
)

**Comment by robdodson** [comment]
It looks like you have an error in your src/reducers/country_reducer code at line 22

**Comment by Aadriya** [comment]
there is no error in src/reducers/country_reducer.it work properly

**Comment by robdodson** [comment]
can you share a gist of the file?

**Comment by Aadriya** [comment]
import {
  FETCH_COUNTRIES
} from '../actions/types';

export default function(state = [], action) {
  switch(action.type) {
    case FETCH_COUNTRIES:state = [];
    
      return [ ...state, ...action.payload.data ];
  }

  return state;
}

**Comment by robdodson** [comment]
We don't have module support in HTML Imports so I suspect that's the issue
