### ISSUE TITLE
Deploy PSK with nginx

### ISSUE THREAD

**Issue by pite3517** [PolymerElements/polymer-starter-kit#978]
I just tried to deploy PSK on ubuntu with nginx but it's no worked.
I always get error 500 when I called URL.

**Steps to reproduce**
1. run 

> polymer build
2. copy bundled folder to ubuntu
3. set up nginx config like this
```
server {
     listen 8080;
     listen [::] 8080;
     root /polymer-web-portal/bundled;
     location / {
          try_files $uri $uri/ /index.html;
     }
}
```
Does anyone know how to fix this ?

Thanks,

**Comment by moderndeveloperllc** [comment]
This would seem to be an issue with nginx configuration as opposed to Polymer as all it's work is done in the browser - not server. Have you checked the nginx logs to see what the 500 error actually is?

**Comment by moderndeveloperllc** [comment]
@abdonrd I'm guessing this can be closed out as no response in 6 months from user.
