### ISSUE TITLE
Absolute paths on index.html

### ISSUE THREAD

**Issue by LostInBrittany** [PolymerElements/polymer-starter-kit#981]
### Description

In ` index.html`  all the paths used are absolute ones, either for image resources of for the polyfill or for the main component, ` my-app` .

But in many cases, specially when doing code labs, people don't launch the server with the polymer app at its root, they deploy the app in a subfolder. Or they are simply using static webservers. And then all the links are broken.

I understand that it would also need to add `useHashAsPath` to `app-location`, but I see that like something good, as you already need to do it if using, for example a static web server.

### Expected outcome

I would like to have a `index.html` file with relative paths and hash as a stand-in alternative to path for navigation, that would work in any folder structure of the server.

### Actual outcome

Well, the current absolute path `index.html`

### Live Demo

See `index.html`

### Steps to reproduce

See `index.html`

### Browsers Affected
- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [x] Safari 8
- [x] Safari 7
- [x] Edge
- [x] IE 11
- [x] IE 10

**Comment by robdodson** [comment]
I've wanted to do this for a long time but Polymer used to rewrite relative anchor's to be relative to the import path, not the main document. Please see: https://github.com/Polymer/polymer/issues/4213

The team recently fixed this but it requires a binding to `[[rootPath]]` now. If you're interested in sending a PR on this that'd be awesome :D

**Comment by LostInBrittany** [comment]
Oh, that's a nice way to do things, I'm going to try it and put a PR :)

Thanks, Rob!

**Comment by jsilvermist** [comment]
### [2.0-preview/PSK3.0]
I'm not sure if this is the best way to do it, but it worked in all scenarios I tested.
Without the `<base>` tag, I couldn't get nested paths to work. (eg. /view1/subpage)

https://github.com/jsilvermist/polymer-starter-kit/commit/2134b719201d983ee3523c6ff46874b1af030039

**Comment by abdonrd** [comment]
Fixed in https://github.com/PolymerElements/polymer-starter-kit/pull/995
