### ISSUE TITLE
Display 404 page for valid routes on load - 2.0-preview

### ISSUE THREAD

**Issue by davidcv5** [PolymerElements/polymer-starter-kit#991]
### Description
Display 404 page for valid routes on load.

### Expected outcome

Display the actual page if it exists, otherwise show 404 page.

### Actual outcome

1. App shows 404 view on page load for any of the valid routes (/, /view1, /view2, /view3).
2. When navigating to a different view through the drawer it works, but on refresh, 404 is shown again.
3. There are no errors in Dev Tools, is like `Polymer.importHref` fails the first time then it works afterwards, maybe some dependencies are missing at that point.

### Steps to reproduce

1. Clone polymer-starter-kit.
2. Run firebase init and enable url rewrite in Firebase.
3. `$ polymer build --add-service-workers`
3. `$ firebase deploy`
4. Open the URL and route to a valid route.
5. Route not working, shows 404 view and no error in the Dev Tools.
6. Click on a menu item in the drawer, it should show the corresponding view.
7. Refresh the page, it show the 404 view again.

**Firebase routing:**
```json
"rewrites": [
      {
        "source": "!{/bower_components,/src}/**",
        "destination": "/index.html"
      }
    ]
```

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10
- [x] Safari on iOS 10.3
- [x] Chrome 57.0.2987.100 on iOS 10.3

**Comment by JonathanSidego** [comment]
Is this still happening in 2.0 final?

**Comment by tgensol** [comment]
I don't see it anymore on the final version (Safari 10.1)

**Comment by abdonrd** [comment]
I think it's fixed in master. Let me know if the problem persists!

**Comment by zhen1991** [comment]
Hi!
I am facing the same issue??
how i can fix it??
please help me!
thnx:)
